// Generators for English Games 21 to 30 (50 questions each = 500 questions)

export function getGames21to30() {
  const games = {};

  // 21. المشاعر والأحاسيس بالإنجليزية
  const feelingsList = [
    { name: 'Happy', ar: 'سعيد ومسرور', img: '😊', o: ['Happy', 'Sad', 'Angry', 'Tired'] },
    { name: 'Sad', ar: 'حزين وكئيب', img: '😢', o: ['Sad', 'Happy', 'Excited', 'Brave'] },
    { name: 'Angry', ar: 'غاضب ومنفعل', img: '😡', o: ['Angry', 'Calm', 'Proud', 'Shy'] },
    { name: 'Excited', ar: 'متحمس ومتشوق', img: '🤩', o: ['Excited', 'Bored', 'Sleepy', 'Sad'] },
    { name: 'Surprised', ar: 'متفاجئ ومندهش', img: '😲', o: ['Surprised', 'Angry', 'Tired', 'Hungry'] },
    { name: 'Scared', ar: 'خائف ومذعور', img: '😨', o: ['Scared', 'Brave', 'Proud', 'Glad'] },
    { name: 'Tired', ar: 'تعبان ومرهق', img: '🥱', o: ['Tired', 'Energetic', 'Excited', 'Happy'] },
    { name: 'Sleepy', ar: 'نعسان يريد النوم', img: '😴', o: ['Sleepy', 'Awake', 'Active', 'Hungry'] },
    { name: 'Hungry', ar: 'جائع يشتهي الطعام', img: '🤤', o: ['Hungry', 'Thirsty', 'Full', 'Tired'] },
    { name: 'Thirsty', ar: 'عطشان يريد شرب الماء', img: '🥤', o: ['Thirsty', 'Hungry', 'Cold', 'Hot'] },
    { name: 'Bored', ar: 'شديد الملل والضجر', img: '😑', o: ['Bored', 'Excited', 'Busy', 'Happy'] },
    { name: 'Confused', ar: 'محتار ومرتبك في أمره', img: '😕', o: ['Confused', 'Certain', 'Sure', 'Calm'] },
    { name: 'Proud', ar: 'فخور بإنجازه العظيم', img: '🦚', o: ['Proud', 'Shy', 'Sad', 'Afraid'] },
    { name: 'Shy', ar: 'خجول ومتردد', img: '🫣', o: ['Shy', 'Bold', 'Proud', 'Angry'] },
    { name: 'Nervous', ar: 'متوتر وقلق', img: '😬', o: ['Nervous', 'Calm', 'Relaxed', 'Brave'] },
    { name: 'Calm', ar: 'هادئ ومطمئن البال', img: '😌', o: ['Calm', 'Angry', 'Nervous', 'Loud'] },
    { name: 'Grateful', ar: 'شاكر وممتن للمعروف', img: '🙏', o: ['Grateful', 'Greedy', 'Angry', 'Rude'] },
    { name: 'Loved', ar: 'محبوب ويشعر بالحنان', img: '🥰', o: ['Loved', 'Lonely', 'Hated', 'Sad'] },
    { name: 'Disgusted', ar: 'مشمئز ومنزعج من شيء', img: '🤢', o: ['Disgusted', 'Delighted', 'Happy', 'Hungry'] },
    { name: 'Curious', ar: 'فضولي يحب الاستكشاف', img: '🧐', o: ['Curious', 'Bored', 'Lazy', 'Sleepy'] },
    { name: 'Cheerful', ar: 'بشوش ومبتهج دائماً', img: '😄', o: ['Cheerful', 'Sad', 'Gloomy', 'Grumpy'] },
    { name: 'Jealous', ar: 'غيور ويشعر بالحسد', img: '😒', o: ['Jealous', 'Kind', 'Loving', 'Generous'] },
    { name: 'Silly', ar: 'مرح وعفوي يحب الضحك', img: '😜', o: ['Silly', 'Serious', 'Angry', 'Sad'] },
    { name: 'Brave', ar: 'شجاع وجريء لا يخاف', img: '🦁', o: ['Brave', 'Scared', 'Timid', 'Weak'] },
    { name: 'Energetic', ar: 'مفعم بالطاقة والنشاط', img: '⚡', o: ['Energetic', 'Lazy', 'Tired', 'Weak'] },
    { name: 'Lonely', ar: 'وحيد ويشعر بالوحدة', img: '🥺', o: ['Lonely', 'Crowded', 'Friendly', 'Joyful'] },
    { name: 'Anxious', ar: 'قلق ومهموم البال', img: '😟', o: ['Anxious', 'Relaxed', 'Carefree', 'Glad'] },
    { name: 'Relaxed', ar: 'مسترخٍ ومستجم', img: '🧘', o: ['Relaxed', 'Stressed', 'Busy', 'Nervous'] },
    { name: 'Friendly', ar: 'ودود ومحب للجميع', img: '🤗', o: ['Friendly', 'Mean', 'Rude', 'Fierce'] },
    { name: 'Amused', ar: 'مستمتع ومسلور بشيء مضحك', img: '🤭', o: ['Amused', 'Annoyed', 'Bored', 'Tired'] },
    { name: 'Delighted', ar: 'مغتبط وفرحان جداً', img: '😁', o: ['Delighted', 'Disappointed', 'Sad', 'Angry'] },
    { name: 'Worried', ar: 'قلق على شخص أو أمر', img: '😟', o: ['Worried', 'Safe', 'Happy', 'Confident'] },
    { name: 'Upset', ar: 'منزعج ومتضايق', img: '😣', o: ['Upset', 'Joyful', 'Excited', 'Peaceful'] },
    { name: 'Confident', ar: 'واثق من نفسه وقدراته', img: '😎', o: ['Confident', 'Doubtful', 'Afraid', 'Shy'] },
    { name: 'Shocked', ar: 'مصدوم من المفاجأة', img: '😱', o: ['Shocked', 'Prepared', 'Calm', 'Bored'] },
    { name: 'Hopeful', ar: 'مفعم بالأمل والتفاؤل', img: '🤞', o: ['Hopeful', 'Hopeless', 'Sad', 'Tired'] },
    { name: 'Joyful', ar: 'ممتلئ بالبهجة والسرور', img: '🥳', o: ['Joyful', 'Miserable', 'Sad', 'Angry'] },
    { name: 'Peaceful', ar: 'يعيش بسلام وسكينة', img: '🕊️', o: ['Peaceful', 'Violent', 'Angry', 'Noisy'] },
    { name: 'Kind', ar: 'حنون ولطيف المعاملة', img: '❤️', o: ['Kind', 'Cruel', 'Mean', 'Rough'] },
    { name: 'Impatient', ar: 'غير صبور ومتعجل', img: '⏳', o: ['Impatient', 'Patient', 'Calm', 'Slow'] },
    { name: 'Glad', ar: 'مسرور بلقائك', img: '😊', o: ['Glad', 'Sorry', 'Unhappy', 'Mad'] },
    { name: 'Enthusiastic', ar: 'حماسي وشديد الاندفاع للعمل', img: '🌟', o: ['Enthusiastic', 'Bored', 'Lazy', 'Quiet'] },
    { name: 'Content', ar: 'قانع وراضٍ بما لديه', img: '😌', o: ['Content', 'Greedy', 'Jealous', 'Angry'] },
    { name: 'Sleepyhead', ar: 'كثير النعاس', img: '😴', o: ['Sleepyhead', 'Athlete', 'Runner', 'Leader'] },
    { name: 'Weeping', ar: 'منهمر في البكاء', img: '😭', o: ['Weeping', 'Laughing', 'Singing', 'Cheering'] },
    { name: 'Smiling', ar: 'مبتسم الوجه والمحيا', img: '😄', o: ['Smiling', 'Frowning', 'Crying', 'Screaming'] },
    { name: 'Laughing', ar: 'ضاحك بصوت مسموع', img: '😂', o: ['Laughing', 'Crying', 'Whispering', 'Sleeping'] },
    { name: 'Caring', ar: 'مهتم وراعٍ للآخرين', img: '🤲', o: ['Caring', 'Selfish', 'Ignorant', 'Rude'] },
    { name: 'Loving', ar: 'محب ومخلص الود', img: '💖', o: ['Loving', 'Hating', 'Cold', 'Cruel'] },
    { name: 'Wondering', ar: 'متسائل ومستغرب في فكره', img: '🤔', o: ['Wondering', 'Knowing', 'Sure', 'Bored'] }
  ];
  games['المشاعر والأحاسيس بالإنجليزية'] = feelingsList.map((d, i) => ({
    id: 21001 + i,
    question: `ما هو الشعور بالإنجليزية الذي يعبر عن الشخص (${d.ar})؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `الشعور الذي يعني ${d.ar} هو '${d.name}'.`
  }));

  // 22. الملابس والأزياء بالإنجليزية
  const clothesList = [
    { name: 'Shirt', ar: 'القميص ذو الأزرار والياقة', img: '👕', o: ['Shirt', 'Pants', 'Shoes', 'Hat'] },
    { name: 'T-shirt', ar: 'التي شيرت القطني المريح', img: '👕', o: ['T-shirt', 'Coat', 'Dress', 'Skirt'] },
    { name: 'Pants', ar: 'البنطال الطويل', img: '👖', o: ['Pants', 'Shirt', 'Hat', 'Gloves'] },
    { name: 'Jeans', ar: 'بنطال الجينز الأزرق', img: '👖', o: ['Jeans', 'Sweater', 'Socks', 'Cap'] },
    { name: 'Shorts', ar: 'الشورت القصير للصيف', img: '🩳', o: ['Shorts', 'Pants', 'Jacket', 'Coat'] },
    { name: 'Dress', ar: 'الفستان الأنيق للبنات', img: '👗', o: ['Dress', 'Shirt', 'T-shirt', 'Suit'] },
    { name: 'Skirt', ar: 'التنورة الجميلة', img: '👗', o: ['Skirt', 'Dress', 'Jeans', 'Coat'] },
    { name: 'Jacket', ar: 'الجاكيت الخفيف الأنيق', img: '🧥', o: ['Jacket', 'Shirt', 'Vest', 'Tie'] },
    { name: 'Coat', ar: 'المعطف الشتوي الثقيل', img: '🧥', o: ['Coat', 'T-shirt', 'Shorts', 'Skirt'] },
    { name: 'Sweater', ar: 'كنزة الصوف الدافئة', img: '🧶', o: ['Sweater', 'Shirt', 'Dress', 'Pajamas'] },
    { name: 'Hoodie', ar: 'الهودي ذو غطاء الرأس', img: '🧥', o: ['Hoodie', 'Hat', 'Scarf', 'Belt'] },
    { name: 'Pajamas', ar: 'بيجامة النوم المريحة', img: '🩱', o: ['Pajamas', 'Suit', 'Uniform', 'Jeans'] },
    { name: 'Socks', ar: 'الجوارب القطنية للقدمين', img: '🧦', o: ['Socks', 'Shoes', 'Gloves', 'Pants'] },
    { name: 'Shoes', ar: 'الأحذية المريحة للمشي', img: '👟', o: ['Shoes', 'Socks', 'Hat', 'Glasses'] },
    { name: 'Sneakers', ar: 'الحذاء الرياضي للجري', img: '👟', o: ['Sneakers', 'Boots', 'Slippers', 'Sandals'] },
    { name: 'Boots', ar: 'حذاء البوت الشتوي الطويل', img: '👢', o: ['Boots', 'Sneakers', 'Socks', 'Sandals'] },
    { name: 'Sandals', ar: 'الصندل الصيفي المفتوح', img: '🩴', o: ['Sandals', 'Boots', 'Shoes', 'Gloves'] },
    { name: 'Slippers', ar: 'خف أو شبشب المنزل المنزلي', img: '🥿', o: ['Slippers', 'Sneakers', 'Boots', 'Socks'] },
    { name: 'Hat', ar: 'القبعة العريضة للحماية من الشمس', img: '🧢', o: ['Hat', 'Belt', 'Tie', 'Watch'] },
    { name: 'Cap', ar: 'قبعة الكاب الرياضية ذات الحافة', img: '🧢', o: ['Cap', 'Scarf', 'Gloves', 'Coat'] },
    { name: 'Scarf', ar: 'الوشاح الصوفي الملفوف حول العنق', img: '🧣', o: ['Scarf', 'Belt', 'Tie', 'Hat'] },
    { name: 'Gloves', ar: 'القفازات ذات الأصابع لتدفئة اليدين', img: '🧤', o: ['Gloves', 'Socks', 'Shoes', 'Sleeves'] },
    { name: 'Mittens', ar: 'قفازات الشتاء المتصلة الأصابع', img: '🧤', o: ['Mittens', 'Gloves', 'Socks', 'Shoes'] },
    { name: 'Belt', ar: 'حزام الخصر الجلدي', img: '🥋', o: ['Belt', 'Tie', 'Scarf', 'Ribbon'] },
    { name: 'Tie', ar: 'ربطة العنق الرسمية (الكرافتة)', img: '👔', o: ['Tie', 'Belt', 'Bowtie', 'Scarf'] },
    { name: 'Bowtie', ar: 'ربطة الفراشة الأنيقة للبدلة', img: '👔', o: ['Bowtie', 'Tie', 'Collar', 'Belt'] },
    { name: 'Raincoat', ar: 'معطف المطر الواقي من البلل', img: '🧥', o: ['Raincoat', 'Sweater', 'T-shirt', 'Suit'] },
    { name: 'Swimsuit', ar: 'لباس ومريول السباحة', img: '🩱', o: ['Swimsuit', 'Coat', 'Jeans', 'Pajamas'] },
    { name: 'Uniform', ar: 'الزي الموحد الرسمي للمدرسة', img: '🥋', o: ['Uniform', 'Pajamas', 'Costume', 'Sweater'] },
    { name: 'Glasses', ar: 'النظارات الطبية للقراءة', img: '👓', o: ['Glasses', 'Sunglasses', 'Watch', 'Ring'] },
    { name: 'Sunglasses', ar: 'النظارات الشمسية لحماية العيون', img: '🕶️', o: ['Sunglasses', 'Glasses', 'Hat', 'Mask'] },
    { name: 'Watch', ar: 'ساعة اليد المعصمية لمعرفة الوقت', img: '⌚', o: ['Watch', 'Bracelet', 'Ring', 'Belt'] },
    { name: 'Ring', ar: 'الخاتم الذهبي في الإصبع', img: '💍', o: ['Ring', 'Watch', 'Necklace', 'Earrings'] },
    { name: 'Necklace', ar: 'العقد والقلادة حول العنق', img: '📿', o: ['Necklace', 'Bracelet', 'Ring', 'Tie'] },
    { name: 'Bracelet', ar: 'السوار الملتف حول المعصم', img: '📿', o: ['Bracelet', 'Necklace', 'Ring', 'Watch'] },
    { name: 'Earrings', ar: 'الأقراط المتدلية في الأذن', img: '🪞', o: ['Earrings', 'Necklace', 'Ring', 'Glasses'] },
    { name: 'Backpack', ar: 'حقيبة الظهر المدرسية', img: '🎒', o: ['Backpack', 'Suitcase', 'Handbag', 'Pouch'] },
    { name: 'Handbag', ar: 'حقيبة اليد النسائية', img: '👜', o: ['Handbag', 'Backpack', 'Box', 'Pocket'] },
    { name: 'Suitcase', ar: 'حقيبة السفر الكبيرة بالدولاب', img: '🧳', o: ['Suitcase', 'Backpack', 'Handbag', 'Trunk'] },
    { name: 'Umbrella', ar: 'المظلة المطرية للحماية', img: '☂️', o: ['Umbrella', 'Coat', 'Hat', 'Tent'] },
    { name: 'Beanie', ar: 'قبعة الصوف الدافئة بدون حافة', img: '🧶', o: ['Beanie', 'Cap', 'Helmet', 'Crown'] },
    { name: 'High Heels', ar: 'حذاء الكعب العالي الأنيق', img: '👠', o: ['High Heels', 'Sneakers', 'Boots', 'Slippers'] },
    { name: 'Hiking Boots', ar: 'أحذية تسلق الجبال القوية', img: '🥾', o: ['Hiking Boots', 'Sandals', 'Slippers', 'Socks'] },
    { name: 'Baby Onesie', ar: 'لباس الرضيع المتصل المريح', img: '👶', o: ['Baby Onesie', 'Coat', 'Dress', 'Skirt'] },
    { name: 'Apron', ar: 'مريلة المطبخ الواقية من البقع', img: '🧑‍🍳', o: ['Apron', 'Shirt', 'Coat', 'Vest'] },
    { name: 'Bathrobe', ar: 'روب الحمام بعد الاستحمام', img: '👘', o: ['Bathrobe', 'Towel', 'Pajamas', 'Coat'] },
    { name: 'Vest', ar: 'الصدرية (الجيليه) بدون أكمام', img: '🦺', o: ['Vest', 'Jacket', 'Coat', 'Shirt'] },
    { name: 'Cardigan', ar: 'كارديجان سترة صوفية بأزرار', img: '🧥', o: ['Cardigan', 'T-shirt', 'Shorts', 'Skirt'] },
    { name: 'Headband', ar: 'طوق الشعر التجميلي للبنات', img: '🎀', o: ['Headband', 'Hat', 'Cap', 'Ribbon'] },
    { name: 'Ribbon', ar: 'شريط تزيين الشعر الملون', img: '🎀', o: ['Ribbon', 'Belt', 'Tie', 'Scarf'] }
  ];
  games['الملابس والأزياء بالإنجليزية'] = clothesList.map((d, i) => ({
    id: 22001 + i,
    question: `ما اسم قطعة الملابس أو الزينة (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية تُسمى '${d.name}'.`
  }));

  // 23. الكلمات المتشابهة في النطق بالإنجليزية
  const homophonesQuestions = [
    { q: 'أي كلمة تعني شمس بالسماء وتتشابه نطقاً مع Son (ابن)؟', img: '☀️', correct: 'Sun', opts: ['Sun', 'Soon', 'San', 'Sin'], exp: 'Sun (شمس) و Son (ابن) ينطقان بنفس الصوت.' },
    { q: 'أي كلمة تعني بحر مالح وتتشابه نطقاً مع See (يرى)؟', img: '🌊', correct: 'Sea', opts: ['Sea', 'She', 'Saw', 'Say'], exp: 'Sea (بحر) و See (يرى) لهما نفس النطق تماماً.' },
    { q: 'أي كلمة تعني الرقم اثنان وتتشابه نطقاً مع To و Too؟', img: '2️⃣', correct: 'Two', opts: ['Two', 'Toe', 'Ten', 'Tie'], exp: 'Two (اثنان) تنطق مثل To و Too.' },
    { q: 'أي كلمة تعني الرقم واحد وتتشابه نطقاً مع Won (فاز)؟', img: '1️⃣', correct: 'One', opts: ['One', 'Own', 'Win', 'On'], exp: 'One (واحد) و Won (فاز بالماضي) ينطقان بالصوت نفسه.' },
    { q: 'أي كلمة تعني زهرة جميلة وتتشابه نطقاً مع Flour (دقيق الطحين)؟', img: '🌸', correct: 'Flower', opts: ['Flower', 'Floor', 'Flock', 'Flyer'], exp: 'Flower (زهرة) و Flour (طحين) لهما نفس النطق.' },
    { q: 'أي كلمة تعني اللون الأزرق وتتشابه نطقاً مع Blew (هبّت الرياح)؟', img: '🔵', correct: 'Blue', opts: ['Blue', 'Blow', 'Glow', 'Clue'], exp: 'Blue (أزرق) و Blew (نفخ/هبّ) هما هوموفون متطابق الصوت.' },
    { q: 'أي كلمة تعني يكتب بالقلم وتتشابه نطقاً مع Right (صحيح أو يمين)؟', img: '✍️', correct: 'Write', opts: ['Write', 'Rate', 'Rope', 'Ride'], exp: 'Write (يكتب) و Right (صحيح/يمين) نفس النطق.' },
    { q: 'أي كلمة تعني وقت الليل وتتشابه نطقاً مع Knight (الفارس الشجاع)؟', img: '🌙', correct: 'Night', opts: ['Night', 'Net', 'Note', 'Nut'], exp: 'Night (ليل) و Knight (فارس بحرف K صامت) متطابقان في النطق.' },
    { q: 'أي كلمة تعني يسمع بالأذن وتتشابه نطقاً مع Here (هنا)؟', img: '👂', correct: 'Hear', opts: ['Hear', 'Hair', 'Her', 'Hare'], exp: 'Hear (يسمع) و Here (هنا) ينطقان بنفس الطريقة.' },
    { q: 'أي كلمة تعني لحم يؤكل وتتشابه نطقاً مع Meet (يقابل)؟', img: '🥩', correct: 'Meat', opts: ['Meat', 'Mat', 'Metal', 'Melt'], exp: 'Meat (لحم) و Meet (يلتقي) لهما ذات النطق.' },
    { q: 'أي كلمة تعني فاكهة الكمثرى وتتشابه نطقاً مع Pair (زوج من الأشياء)؟', img: '🍐', correct: 'Pear', opts: ['Pear', 'Peer', 'Poor', 'Pure'], exp: 'Pear (كمثرى) و Pair (زوج مثل حذاء) متطابقان.' },
    { q: 'أي كلمة تعني عين الإنسان وتتشابه نطقاً مع الضمير I (أنا)؟', img: '👁️', correct: 'Eye', opts: ['Eye', 'Ear', 'Ice', 'Egg'], exp: 'Eye (عين) تنطق كحرف I (أنا).' },
    { q: 'أي كلمة تعني وداعاً وتتشابه نطقاً مع Buy (يشتري)؟', img: '👋', correct: 'Bye', opts: ['Bye', 'Bay', 'Bee', 'Bow'], exp: 'Bye (مع السلامة) و Buy (يشتري) نفس الصوت.' },
    { q: 'أي كلمة تعني ساعة زمنية (60 دقيقة) وتتشابه نطقاً مع Our (لنا)؟', img: '⏰', correct: 'Hour', opts: ['Hour', 'Hair', 'Hear', 'Her'], exp: 'Hour (ساعة زمنية) بحرف H صامت، تنطق مثل Our.' },
    { q: 'أي كلمة تعني الرقم ثمانية وتتشابه نطقاً مع Ate (أكل بالماضي)؟', img: '8️⃣', correct: 'Eight', opts: ['Eight', 'Late', 'Gate', 'Bite'], exp: 'Eight (ثمانية) و Ate (أكل) متطابقان في النطق.' },
    { q: 'أي كلمة تعني دب بري وتتشابه نطقاً مع Bare (عارٍ/مكشوف)؟', img: '🐻', correct: 'Bear', opts: ['Bear', 'Beer', 'Bar', 'Boar'], exp: 'Bear (دب) و Bare (مكشوف القدمين مثلاً) متطابقان.' },
    { q: 'أي كلمة تعني غزال رشيق وتتشابه نطقاً مع Dear (عزيزي/حبيبي)؟', img: '🦌', correct: 'Deer', opts: ['Deer', 'Door', 'Dare', 'Dire'], exp: 'Deer (غزال) و Dear (عزيزي) ينطقان بنفس النمط.' },
    { q: 'أي كلمة تعني أرنب بري سريع وتتشابه نطقاً مع Hair (شعر الرأس)؟', img: '🐰', correct: 'Hare', opts: ['Hare', 'Hear', 'Here', 'Hate'], exp: 'Hare (أرنب بري) و Hair (شعر) لهما نفس الصوت.' },
    { q: 'أي كلمة تعني كرة للعب وتتشابه نطقاً مع Bawl (يبكي وينتحب)؟', img: '⚽', correct: 'Ball', opts: ['Ball', 'Bell', 'Bill', 'Bull'], exp: 'Ball (كرة) و Bawl (يبكي بصوت) ينطقان Ball.' },
    { q: 'أي كلمة تعني بريد ورسائل وتتشابه نطقاً مع Male (ذكر)؟', img: '📬', correct: 'Mail', opts: ['Mail', 'Mile', 'Mole', 'Meal'], exp: 'Mail (بريد) و Male (ذكر) نفس النطق.' },
    { q: 'أي كلمة تعني قصة وحكاية وتتشابه نطقاً مع Tail (ذيل الحيوان)؟', img: '📖', correct: 'Tale', opts: ['Tale', 'Tile', 'Toll', 'Tall'], exp: 'Tale (حكاية) و Tail (ذيل) نفس الصوت تماماً.' },
    { q: 'أي كلمة تعني طائرة وتتشابه نطقاً مع Plain (بسيط أو سهل)؟', img: '✈️', correct: 'Plane', opts: ['Plane', 'Plan', 'Pain', 'Pan'], exp: 'Plane (طائرة) و Plain (بسيط) متماثلان في النطق.' },
    { q: 'أي كلمة تعني شراع السفينة وتتشابه نطقاً مع Sale (تخفيضات/بيع)؟', img: '⛵', correct: 'Sail', opts: ['Sail', 'Seal', 'Soul', 'Soil'], exp: 'Sail (يبحر/شراع) و Sale (تخفيض/بيع) لهما نفس النطق.' },
    { q: 'أي كلمة تعني ضعيف القوة وتتشابه نطقاً مع Week (أسبوع)؟', img: '🪶', correct: 'Weak', opts: ['Weak', 'Walk', 'Wake', 'Work'], exp: 'Weak (ضعيف) و Week (أسبوع) ينطقان Week.' },
    { q: 'أي كلمة تعني سلام وأمان وتتشابه نطقاً مع Piece (قطعة كيك)؟', img: '🕊️', correct: 'Peace', opts: ['Peace', 'Pace', 'Price', 'Peas'], exp: 'Peace (سلام) و Piece (قطعة) متطابقان.' },
    { q: 'أي كلمة تعني حفرة في الأرض وتتشابه نطقاً مع Whole (كامل/بأكمله)؟', img: '🕳️', correct: 'Hole', opts: ['Hole', 'Hall', 'Hill', 'Hold'], exp: 'Hole (حفرة) و Whole (بأكمله) ينطقان بنفس الصوت.' },
    { q: 'أي كلمة تعني يعلم ويعرف وتتشابه نطقاً مع No (كلا/لا)؟', img: '🧠', correct: 'Know', opts: ['Know', 'Now', 'New', 'Knew'], exp: 'Know (يعرف) بحرف K صامت تنطق مثل No.' },
    { q: 'أي كلمة تعني طريق للسيارات وتتشابه نطقاً مع Rode (ركب بالماضي)؟', img: '🛣️', correct: 'Road', opts: ['Road', 'Read', 'Red', 'Raid'], exp: 'Road (طريق) و Rode (ركب الدراجة) نفس الصوت.' },
    { q: 'أي كلمة تعني وردة حمراء وتتشابه نطقاً مع Rows (صفوف أو يجدف)؟', img: '🌹', correct: 'Rose', opts: ['Rose', 'Rice', 'Rise', 'Rope'], exp: 'Rose (وردة) و Rows (صفوف) متقاربان جداً بالنطق.' },
    { q: 'أي كلمة تعني خشب الأشجار وتتشابه نطقاً مع Would (يرغب أو يفعل)؟', img: '🪵', correct: 'Wood', opts: ['Wood', 'Word', 'Ward', 'Wild'], exp: 'Wood (خشب) و Would (فعل مساعد) ينطقان بنفس الشكل.' },
    { q: 'أي كلمة تعني فرامل السيارة للتوقف وتتشابه نطقاً مع Break (يكسر)؟', img: '🛑', correct: 'Brake', opts: ['Brake', 'Bake', 'Bark', 'Brick'], exp: 'Brake (مكابح فرامل) و Break (يكسر/استراحة) متطابقان.' },
    { q: 'أي كلمة تعني خصر الجسم وتتشابه نطقاً مع Waste (يهدر/مهملات)؟', img: '👤', correct: 'Waist', opts: ['Waist', 'Wait', 'West', 'Water'], exp: 'Waist (خصر) و Waste (نفاية/إهدار) نفس النطق.' },
    { q: 'أي كلمة تعني كعب القدم وتتشابه نطقاً مع Heal (يشفي ويتعافى)؟', img: '🦶', correct: 'Heel', opts: ['Heel', 'Hole', 'Hill', 'Hall'], exp: 'Heel (كعب) و Heal (يشفى) ينطقان Heel.' },
    { q: 'أي كلمة تعني نملة صغيرة وتتشابه نطقاً مع Aunt (العمة أو الخالة)؟', img: '🐜', correct: 'Ant', opts: ['Ant', 'Art', 'Arm', 'Act'], exp: 'Ant (نملة) تنطق مثل كلمة Aunt في كثير من اللهجات.' },
    { q: 'أي كلمة تعني نحلة عسل وتتشابه نطقاً مع فعل Be (يكون)؟', img: '🐝', correct: 'Bee', opts: ['Bee', 'Bay', 'Bow', 'Boy'], exp: 'Bee (نحلة) و Be (فعل يكون) لهما نفس الصوت تماماً.' },
    { q: 'أي كلمة تعني عقدة في الحبل وتتشابه نطقاً مع Not (أداة النفي)؟', img: '🪢', correct: 'Knot', opts: ['Knot', 'Nut', 'Net', 'Note'], exp: 'Knot (عقدة) بحرف K صامت تنطق مثل Not.' },
    { q: 'أي كلمة تعني دقيق الطحين وتتشابه نطقاً مع Flower (زهرة)؟', img: '🌾', correct: 'Flour', opts: ['Flour', 'Floor', 'Flap', 'Float'], exp: 'Flour (طحين) و Flower (زهرة) نفس النطق.' },
    { q: 'أي كلمة تعني درج أو سلم للصعود وتتشابه نطقاً مع Stare (يحدق)؟', img: '🪜', correct: 'Stair', opts: ['Stair', 'Star', 'Store', 'Steer'], exp: 'Stair (درجة سلم) و Stare (يحدق بالعين) متطابقان.' },
    { q: 'أي كلمة تعني صوت الرياح بالماضي (Blew) وتشبه اللون Blue؟', img: '💨', correct: 'Blew', opts: ['Blew', 'Blow', 'Glow', 'Bow'], exp: 'Blew (هبت الرياح) تنطق تماماً مثل Blue.' },
    { q: 'أي كلمة تعني لوح خشبي للتزلج وتتشابه نطقاً مع Bored (يشعر بالملل)؟', img: '🛹', correct: 'Board', opts: ['Board', 'Bird', 'Beard', 'Broad'], exp: 'Board (لوح) و Bored (ضجران) لهما نفس النطق.' },
    { q: 'أي كلمة تعني رقائق حبوب الإفطار وتشبه لفظاً Serial (مسلسل)؟', img: '🥣', correct: 'Cereal', opts: ['Cereal', 'Circle', 'Coral', 'Curtain'], exp: 'Cereal (حبوب الإفطار) و Serial متطابقان.' },
    { q: 'أي كلمة تعني مسموح ومصرح به وتتشابه نطقاً مع Aloud (بصوت مسموع)؟', img: '🗣️', correct: 'Allowed', opts: ['Allowed', 'Aloud', 'Along', 'Alone'], exp: 'Allowed (مسموح) و Aloud (بصوت عالٍ) نفس النطق.' },
    { q: 'أي كلمة تعني طقس ومناخ وتتشابه نطقاً مع Whether (سواء/فيما إذا)؟', img: '⛅', correct: 'Weather', opts: ['Weather', 'Leather', 'Feather', 'Gather'], exp: 'Weather (طقس) و Whether نفس النطق.' },
    { q: 'أي كلمة تعني يدقق ويفحص (Check) وتتشابه مع Cheque (شيك بنكي)؟', img: '✅', correct: 'Check', opts: ['Check', 'Chick', 'Choke', 'Clock'], exp: 'Check (يفحص/علامة صح) و Cheque نفس الصوت.' },
    { q: 'أي كلمة تعني ذيل قطة أو كلب وتشبه كلمة Tale (قصة)؟', img: '🐈', correct: 'Tail', opts: ['Tail', 'Tale', 'Tall', 'Toll'], exp: 'Tail (ذيل) تنطق مثل Tale.' },
    { q: 'أي كلمة تعني زوج من الأحذية المتطابقة وتشبه Pear (كمثرى)؟', img: '👟👟', correct: 'Pair', opts: ['Pair', 'Pear', 'Pier', 'Pour'], exp: 'Pair (زوج من شيئين) تنطق Pear.' },
    { q: 'أي كلمة تعني حافر حيوان أو يتعافى (Heal) وتشبه كعب القدم Heel؟', img: '❤️', correct: 'Heal', opts: ['Heal', 'Heel', 'Hole', 'Hall'], exp: 'Heal (يتعافى) تنطق Heel.' },
    { q: 'أي كلمة تعني خادمة منزلية وتشبه كلمة Made (صنع في الماضي)؟', img: '🧹', correct: 'Maid', opts: ['Maid', 'Made', 'Mood', 'Mad'], exp: 'Maid (عاملة منزلية) و Made (صُنع) نفس النطق.' },
    { q: 'أي كلمة تعني يخيط بالإبرة والخيط وتتشابه نطقاً مع So (لذلك/جداً)؟', img: '🧵', correct: 'Sew', opts: ['Sew', 'Saw', 'See', 'Sue'], exp: 'Sew (يخيط) و So (لذلك) ينطقان بنفس الطريقة.' },
    { q: 'أي كلمة تعني فارس شجاع يمتطي حصاناً وتشبه Night (ليل)؟', img: '🤺', correct: 'Knight', opts: ['Knight', 'Night', 'Kite', 'Knife'], exp: 'Knight (فارس) تبدأ بحرف K صامت وتنطق Night.' }
  ];
  games['الكلمات المتشابهة في النطق بالإنجليزية'] = homophonesQuestions.map((d, i) => ({
    id: 23001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  // 24. أدوات الرسم والفنون بالإنجليزية
  const artList = [
    { name: 'Paint', ar: 'الألوان المائية والزيتية', img: '🎨', o: ['Paint', 'Brush', 'Pencil', 'Eraser'] },
    { name: 'Paintbrush', ar: 'فرشاة التلوين الناعمة', img: '🖌️', o: ['Paintbrush', 'Pencil', 'Pen', 'Scissors'] },
    { name: 'Palette', ar: 'لوحة وباليتة مزج الألوان', img: '🎨', o: ['Palette', 'Canvas', 'Easel', 'Paper'] },
    { name: 'Canvas', ar: 'قماش الكانفاس المخصص للرسم الزيتي', img: '🖼️', o: ['Canvas', 'Book', 'Mirror', 'Cloth'] },
    { name: 'Pencil', ar: 'قلم الرصاص للتخطيط والرسم', img: '✏️', o: ['Pencil', 'Pen', 'Crayon', 'Marker'] },
    { name: 'Colored Pencils', ar: 'أقلام التلوين الخشبية الملونة', img: '✏️', o: ['Colored Pencils', 'Crayons', 'Paints', 'Chalk'] },
    { name: 'Eraser', ar: 'الممحاة لإزالة الخطأ في الرسم', img: '🧼', o: ['Eraser', 'Ruler', 'Sharpener', 'Glue'] },
    { name: 'Sharpener', ar: 'المبراة لبري أقلام الرصاص', img: '🪒', o: ['Sharpener', 'Scissors', 'Eraser', 'Compass'] },
    { name: 'Ruler', ar: 'المسطرة لتسطير الخطوط المستقيمة', img: '📏', o: ['Ruler', 'Tape', 'Scissors', 'Compass'] },
    { name: 'Scissors', ar: 'المقص المخصص لقص الأوراق الفنية', img: '✂️', o: ['Scissors', 'Knife', 'Ruler', 'Stapler'] },
    { name: 'Glue', ar: 'الصمغ والغراء للصق الأعمال الفنية', img: '🧴', o: ['Glue', 'Paint', 'Water', 'Oil'] },
    { name: 'Glue Stick', ar: 'أنبوب الصمغ الجاف الدوار', img: '🧴', o: ['Glue Stick', 'Crayon', 'Tape', 'Chalk'] },
    { name: 'Tape', ar: 'الشريط اللاصق الشفاف', img: '📼', o: ['Tape', 'Glue', 'Ruler', 'Paper'] },
    { name: 'Paper', ar: 'ورقة الرسم البيضاء النقية', img: '📄', o: ['Paper', 'Canvas', 'Cardboard', 'Cloth'] },
    { name: 'Sketchbook', ar: 'دفتر كراسة الرسم والاسكتشات', img: '📓', o: ['Sketchbook', 'Notebook', 'Book', 'Folder'] },
    { name: 'Crayons', ar: 'ألوان الباستيل والشمع الزاهية', img: '🖍️', o: ['Crayons', 'Pencils', 'Markers', 'Paints'] },
    { name: 'Markers', ar: 'أقلام الفلوماستر للتحديد والتلوين', img: '🖊️', o: ['Markers', 'Crayons', 'Pencils', 'Chalk'] },
    { name: 'Watercolors', ar: 'الألوان المائية الشفافة الرائعة', img: '🎨', o: ['Watercolors', 'Oil Paints', 'Pastels', 'Ink'] },
    { name: 'Oil Pastels', ar: 'ألوان الباستيل الزيتية الغنية', img: '🖍️', o: ['Oil Pastels', 'Chalk', 'Pencils', 'Markers'] },
    { name: 'Clay', ar: 'الصلصال والطين لتشكيل المجسمات', img: '🧱', o: ['Clay', 'Playdough', 'Sand', 'Wax'] },
    { name: 'Glitter', ar: 'البريق واللميع المضيء اللامع', img: '✨', o: ['Glitter', 'Paint', 'Sand', 'Stars'] },
    { name: 'Stickers', ar: 'الملصقات الملونة للزينة', img: '⭐', o: ['Stickers', 'Cards', 'Stamps', 'Pictures'] },
    { name: 'Easel', ar: 'حامل لوحة الرسم الخشبي', img: '🪵', o: ['Easel', 'Desk', 'Chair', 'Table'] },
    { name: 'Chalk', ar: 'الطبشور الأبيض والملون للكتابة', img: '🖍️', o: ['Chalk', 'Pencil', 'Pen', 'Marker'] },
    { name: 'Chalkboard', ar: 'السبورة السوداء للكتابة بالطبشور', img: '⬛', o: ['Chalkboard', 'Whiteboard', 'Screen', 'Paper'] },
    { name: 'Stencil', ar: 'مسطرة وقوالب الأشكال المفرغة', img: '📐', o: ['Stencil', 'Ruler', 'Stamp', 'Sticker'] },
    { name: 'Stamp', ar: 'ختم الحبر لطباعة الأشكال الجاهزة', img: '📮', o: ['Stamp', 'Sticker', 'Coin', 'Card'] },
    { name: 'Sponge', ar: 'الإسفنجة المخصصة لتأثيرات الطلاء', img: '🧽', o: ['Sponge', 'Brush', 'Cloth', 'Paper'] },
    { name: 'Apron', ar: 'مريلة الفنون لحماية الملابس من الدهان', img: '🧑‍🎨', o: ['Apron', 'Coat', 'Shirt', 'Hat'] },
    { name: 'Sculpture', ar: 'التمثال والمنحوتة الفنية ثلاثية الأبعاد', img: '🗿', o: ['Sculpture', 'Painting', 'Drawing', 'Photo'] },
    { name: 'Drawing', ar: 'رسمة وتخطيط بالرصاص أو القلم', img: '🖼️', o: ['Drawing', 'Sculpture', 'Photo', 'Music'] },
    { name: 'Painting', ar: 'لوحة ملونة بالألوان الزيتية أو المائية', img: '🎨', o: ['Painting', 'Drawing', 'Book', 'Letter'] },
    { name: 'Portrait', ar: 'لوحة البورتريه التي ترسم وجه شخص', img: '🖼️', o: ['Portrait', 'Landscape', 'Still Life', 'Map'] },
    { name: 'Landscape', ar: 'رسمة المنظر الطبيعي للجبال والأشجار', img: '🏞️', o: ['Landscape', 'Portrait', 'Cityscape', 'Seascape'] },
    { name: 'Collage', ar: 'لوحة الكولاج بقصاصات الورق المختلفة', img: '📑', o: ['Collage', 'Painting', 'Sculpture', 'Origami'] },
    { name: 'Craft', ar: 'الأشغال اليدوية والحرف الإبداعية', img: '✂️', o: ['Craft', 'Drawing', 'Music', 'Sport'] },
    { name: 'Origami', ar: 'فن طي الورق الياباني المتقن', img: '🦢', o: ['Origami', 'Clay', 'Pottery', 'Knitting'] },
    { name: 'Ceramic Pot', ar: 'الإناء الفخاري الخزفي المصنوع من الطين', img: '🏺', o: ['Ceramic Pot', 'Glass', 'Cup', 'Bowl'] },
    { name: 'Beads', ar: 'الخرز الملون لصنع الأساور والعقود', img: '📿', o: ['Beads', 'Buttons', 'Coins', 'Stones'] },
    { name: 'Yarn', ar: 'كرة خيوط الصوف للحياكة والنسيج', img: '🧶', o: ['Yarn', 'Rope', 'Wire', 'Ribbon'] },
    { name: 'Ribbon', ar: 'شريط الساتان الملون للزينة واللف', img: '🎀', o: ['Ribbon', 'Tape', 'Ruler', 'String'] },
    { name: 'Felt', ar: 'قماش الجوخ الملون للأشغال اليدوية', img: '🧶', o: ['Felt', 'Paper', 'Silk', 'Leather'] },
    { name: 'Color Wheel', ar: 'دائرة الألوان لاختيار التناسق اللوني', img: '🎡', o: ['Color Wheel', 'Clock', 'Compass', 'Wheel'] },
    { name: 'Art Class', ar: 'حصة الفنون والرسم في المدرسة', img: '🏫', o: ['Art Class', 'Math Class', 'Music Room', 'Lab'] },
    { name: 'Gallery', ar: 'معرض وصالة عرض اللوحات الفنية', img: '🏛️', o: ['Gallery', 'Library', 'Shop', 'Theater'] },
    { name: 'Masterpiece', ar: 'التحفة الفنية الرائعة الفريدة', img: '🏆', o: ['Masterpiece', 'Draft', 'Copy', 'Sketch'] },
    { name: 'Shading', ar: 'التظليل بالقلم لإعطاء عمق وواقعية', img: '✏️', o: ['Shading', 'Coloring', 'Cutting', 'Erasing'] },
    { name: 'Highlight', ar: 'نقطة الضوء واللمعان بالرسم', img: '💡', o: ['Highlight', 'Shadow', 'Darkness', 'Edge'] },
    { name: 'Primary Colors', ar: 'الألوان الأساسية (الأحمر والأزرق والأصفر)', img: '🔴', o: ['Primary Colors', 'Dark Colors', 'Pastels', 'Shades'] },
    { name: 'Creativity', ar: 'الإبداع والابتكار الفني الباهر', img: '💡', o: ['Creativity', 'Copying', 'Routine', 'Silence'] }
  ];
  games['أدوات الرسم والفنون بالإنجليزية'] = artList.map((d, i) => ({
    id: 24001 + i,
    question: `ما اسم أداة الرسم أو المصطلح الفني (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} يُسمى بالإنجليزية '${d.name}'.`
  }));

  // 25. الطقس والمواسم بالإنجليزية
  const weatherList = [
    { name: 'Sunny', ar: 'مشمس وساطع الأشعة', img: '☀️', o: ['Sunny', 'Rainy', 'Cloudy', 'Snowy'] },
    { name: 'Rainy', ar: 'ممطر وتهطل فيه الأمطار', img: '🌧️', o: ['Rainy', 'Sunny', 'Windy', 'Dry'] },
    { name: 'Cloudy', ar: 'غائم ومغطى بالسحب', img: '☁️', o: ['Cloudy', 'Clear', 'Sunny', 'Hot'] },
    { name: 'Windy', ar: 'عاصف وشديد الرياح الهابة', img: '💨', o: ['Windy', 'Calm', 'Rainy', 'Warm'] },
    { name: 'Snowy', ar: 'مثلج وتتساقط فيه حبات الثلج', img: '❄️', o: ['Snowy', 'Hot', 'Sunny', 'Desert'] },
    { name: 'Stormy', ar: 'عاصف برعد وبرق وأمطار', img: '⛈️', o: ['Stormy', 'Pleasant', 'Clear', 'Sunny'] },
    { name: 'Foggy', ar: 'ضبابي ويحجب الرؤية في الصباح', img: '🌫️', o: ['Foggy', 'Clear', 'Bright', 'Sunny'] },
    { name: 'Rainbow', ar: 'قوس قزح البديع سباعي الألوان', img: '🌈', o: ['Rainbow', 'Cloud', 'Lightning', 'Sun'] },
    { name: 'Hot', ar: 'طقس حار مرتفع الحرارة', img: '☀️', o: ['Hot', 'Freezing', 'Cold', 'Cool'] },
    { name: 'Cold', ar: 'طقس بارد ومنخفض الحرارة', img: '❄️', o: ['Cold', 'Hot', 'Boiling', 'Warm'] },
    { name: 'Warm', ar: 'طقس دافئ ومعتدل وممتع', img: '🌤️', o: ['Warm', 'Freezing', 'Icy', 'Cold'] },
    { name: 'Cool', ar: 'طقس لطيف البرودة منعش', img: '🍃', o: ['Cool', 'Hot', 'Burning', 'Dusty'] },
    { name: 'Rain', ar: 'المطر وقطرات الماء الهاطلة', img: '🌧️', o: ['Rain', 'Snow', 'Hail', 'Dust'] },
    { name: 'Snow', ar: 'الثلج الأبيض النقي المنهمر', img: '❄️', o: ['Snow', 'Rain', 'Sand', 'Fog'] },
    { name: 'Hail', ar: 'البَرَد وحبات الجليد المتساقطة', img: '🧊', o: ['Hail', 'Rain', 'Mist', 'Dew'] },
    { name: 'Thunder', ar: 'صوت الرعد القوي في السماء', img: '⚡', o: ['Thunder', 'Lightning', 'Wind', 'Rain'] },
    { name: 'Lightning', ar: 'وميض البرق اللامع المضيء', img: '⚡', o: ['Lightning', 'Thunder', 'Cloud', 'Rain'] },
    { name: 'Breeze', ar: 'النسيم العليل اللطيف الهادئ', img: '🍃', o: ['Breeze', 'Hurricane', 'Tornado', 'Gale'] },
    { name: 'Tornado', ar: 'الإعصار القمعي الدوار العنيف', img: '🌪️', o: ['Tornado', 'Breeze', 'Rain', 'Cloud'] },
    { name: 'Hurricane', ar: 'الإعصار المداري البحري الهائل', img: '🌀', o: ['Hurricane', 'Shower', 'Drizzle', 'Mist'] },
    { name: 'Sun', ar: 'الشمس المضيئة مصدر الدفء', img: '☀️', o: ['Sun', 'Moon', 'Star', 'Planet'] },
    { name: 'Cloud', ar: 'السحابة والغيوم البيضاء والرمادية', img: '☁️', o: ['Cloud', 'Sun', 'Rainbow', 'Sky'] },
    { name: 'Sky', ar: 'السماء الزرقاء الواسعة', img: '🌌', o: ['Sky', 'Earth', 'Sea', 'Ground'] },
    { name: 'Temperature', ar: 'درجة الحرارة المقاسة', img: '🌡️', o: ['Temperature', 'Pressure', 'Speed', 'Distance'] },
    { name: 'Thermometer', ar: 'ميزان ومقياس الحرارة (الترمومتر)', img: '🌡️', o: ['Thermometer', 'Barometer', 'Clock', 'Ruler'] },
    { name: 'Weather Forecast', ar: 'النشرة الجوية وتوقعات الطقس', img: '📺', o: ['Weather Forecast', 'News', 'Movie', 'Music'] },
    { name: 'Spring', ar: 'فصل الربيع المزهر بالورود', img: '🌸', o: ['Spring', 'Summer', 'Autumn', 'Winter'] },
    { name: 'Summer', ar: 'فصل الصيف الحار المشمس والشاطئ', img: '☀️', o: ['Summer', 'Winter', 'Spring', 'Fall'] },
    { name: 'Autumn', ar: 'فصل الخريف المتساقط الأوراق', img: '🍂', o: ['Autumn', 'Spring', 'Summer', 'Winter'] },
    { name: 'Winter', ar: 'فصل الشتاء المثلج البارد', img: '⛄', o: ['Winter', 'Summer', 'Spring', 'Autumn'] },
    { name: 'Snowflake', ar: 'ندفة وبلورة الثلج الهندسية الجميلة', img: '❄️', o: ['Snowflake', 'Hailstone', 'Raindrop', 'Iceberg'] },
    { name: 'Frost', ar: 'الصقيع الأبيض المتجمد على النباتات', img: '🧊', o: ['Frost', 'Dew', 'Rain', 'Steam'] },
    { name: 'Dew', ar: 'قطرات الندى الصباحية على الزهور', img: '💧', o: ['Dew', 'Frost', 'Hail', 'Snow'] },
    { name: 'Puddle', ar: 'بركة ماء المطر الصغيرة في الشارع', img: '🌧️', o: ['Puddle', 'Lake', 'Ocean', 'River'] },
    { name: 'Sunbeam', ar: 'شعاع الشمس الذهبي المنبثق', img: '☀️', o: ['Sunbeam', 'Shadow', 'Cloud', 'Wind'] },
    { name: 'Umbrella', ar: 'المظلة الواقية من المطر والشمس', img: '☂️', o: ['Umbrella', 'Coat', 'Hat', 'Glove'] },
    { name: 'Raincoat', ar: 'معطف المطر الأصفر المقاوم للماء', img: '🧥', o: ['Raincoat', 'T-shirt', 'Sweater', 'Pants'] },
    { name: 'Sunglasses', ar: 'النظارات الشمسية لحماية العين', img: '🕶️', o: ['Sunglasses', 'Glasses', 'Mask', 'Cap'] },
    { name: 'Sunscreen', ar: 'كريم واقي الشمس للبشرة', img: '🧴', o: ['Sunscreen', 'Soap', 'Shampoo', 'Lotion'] },
    { name: 'Snowman', ar: 'رجل الجليد ذو الأنف الجزري', img: '⛄', o: ['Snowman', 'Statue', 'Scarecrow', 'Doll'] },
    { name: 'Ice', ar: 'الجليد المتجمد الصلب', img: '🧊', o: ['Ice', 'Water', 'Steam', 'Fire'] },
    { name: 'Melt', ar: 'يذوب بفعل الحرارة والدفء', img: '💧', o: ['Melt', 'Freeze', 'Burn', 'Break'] },
    { name: 'Freeze', ar: 'يتجمد ويتحول لثلج بالبرودة', img: '🧊', o: ['Freeze', 'Boil', 'Melt', 'Warm'] },
    { name: 'Humidity', ar: 'الرطوبة ونسبة بخار الماء في الجو', img: '💧', o: ['Humidity', 'Wind', 'Heat', 'Cold'] },
    { name: 'Clear Sky', ar: 'سماء صافية نقية لا غيوم فيها', img: '☀️', o: ['Clear Sky', 'Overcast', 'Storm', 'Fog'] },
    { name: 'Overcast', ar: 'سماء ملبدة كلياً بالغيوم الداكنة', img: '☁️', o: ['Overcast', 'Sunny', 'Clear', 'Bright'] },
    { name: 'Drizzle', ar: 'الرذاذ والأمطار الخفيفة الناعمة', img: '🌦️', o: ['Drizzle', 'Downpour', 'Flood', 'Hail'] },
    { name: 'Seasons', ar: 'فصول السنة الأربعة المتعاقبة', img: '🗓️', o: ['Seasons', 'Months', 'Days', 'Years'] },
    { name: 'Climate', ar: 'المناخ العام للمنطقة والبلاد', img: '🌍', o: ['Climate', 'Weather', 'Season', 'Temp'] },
    { name: 'Nature', ar: 'الطبيعة الساحرة الخلابة', img: '🌿', o: ['Nature', 'City', 'Space', 'Room'] }
  ];
  games['الطقس والمواسم بالإنجليزية'] = weatherList.map((d, i) => ({
    id: 25001 + i,
    question: `ما هو المصطلح بالإنجليزية الذي يعبر عن (${d.ar})؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية هو '${d.name}'.`
  }));

  // 26. أدوات المدرسة والكتابة بالإنجليزية
  const schoolList = [
    { name: 'Backpack', ar: 'حقيبة الظهر المدرسية', img: '🎒', o: ['Backpack', 'Pencil Case', 'Lunchbox', 'Book'] },
    { name: 'Pencil', ar: 'قلم الرصاص للكتابة والرسم', img: '✏️', o: ['Pencil', 'Pen', 'Crayon', 'Marker'] },
    { name: 'Pen', ar: 'قلم الحبر الأزرق', img: '🖊️', o: ['Pen', 'Pencil', 'Chalk', 'Brush'] },
    { name: 'Eraser', ar: 'الممحاة لإزالة كتابة الرصاص', img: '🧼', o: ['Eraser', 'Ruler', 'Sharpener', 'Glue'] },
    { name: 'Sharpener', ar: 'المبراة لبري القلم الرصاص', img: '🪒', o: ['Sharpener', 'Eraser', 'Scissors', 'Compass'] },
    { name: 'Ruler', ar: 'المسطرة لقياس ورسم الخطوط', img: '📏', o: ['Ruler', 'Tape', 'Scissors', 'Pen'] },
    { name: 'Notebook', ar: 'دفتر الكشكول لكتابة الدروس', img: '📓', o: ['Notebook', 'Textbook', 'Storybook', 'Folder'] },
    { name: 'Book', ar: 'الكتاب المدرسي المفيد', img: '📖', o: ['Book', 'Notebook', 'Paper', 'Slate'] },
    { name: 'Textbook', ar: 'الكتاب التعليمي المقرر للمادة', img: '📚', o: ['Textbook', 'Magazine', 'Comic', 'Newspaper'] },
    { name: 'Pencil Case', ar: 'المقلمة الحافظة للأقلام', img: '👝', o: ['Pencil Case', 'Backpack', 'Box', 'Bag'] },
    { name: 'Scissors', ar: 'المقص المدرسي ذو الرأس الآمن', img: '✂️', o: ['Scissors', 'Knife', 'Ruler', 'Stapler'] },
    { name: 'Glue', ar: 'الصمغ المدرسي للأشغال الورقية', img: '🧴', o: ['Glue', 'Tape', 'Ink', 'Paint'] },
    { name: 'Crayons', ar: 'ألوان الشمع المبهجة للتلوين', img: '🖍️', o: ['Crayons', 'Pencils', 'Markers', 'Chalk'] },
    { name: 'Markers', ar: 'أقلام التلوين العريضة الفلوماستر', img: '🖊️', o: ['Markers', 'Pens', 'Pencils', 'Paints'] },
    { name: 'Highlighter', ar: 'قلم التحديد الفسفوري للعبارات المهمة', img: '🖊️', o: ['Highlighter', 'Marker', 'Pen', 'Pencil'] },
    { name: 'Paper', ar: 'ورقة الدفتر المسطرة', img: '📄', o: ['Paper', 'Cardboard', 'Board', 'Cover'] },
    { name: 'Folder', ar: 'الملف الحافظ للأوراق والواجبات', img: '📁', o: ['Folder', 'Notebook', 'Book', 'Pocket'] },
    { name: 'Binder', ar: 'المجلد الحلقي لحفظ الملخصات', img: '📂', o: ['Binder', 'Folder', 'Box', 'Case'] },
    { name: 'Desk', ar: 'مقعد ومكتب الطالب الصفي', img: '🪑', o: ['Desk', 'Chair', 'Table', 'Bench'] },
    { name: 'Chair', ar: 'كرسي الجلوس داخل الصف', img: '🪑', o: ['Chair', 'Desk', 'Floor', 'Sofa'] },
    { name: 'Whiteboard', ar: 'اللوح الأبيض المدرسي للشرح', img: '📋', o: ['Whiteboard', 'Blackboard', 'Screen', 'Wall'] },
    { name: 'Blackboard', ar: 'السبورة السوداء القديمة', img: '⬛', o: ['Blackboard', 'Whiteboard', 'Desk', 'Door'] },
    { name: 'Chalk', ar: 'الطبشور الأبيض المخصص للسبورة', img: '🖍️', o: ['Chalk', 'Marker', 'Pen', 'Pencil'] },
    { name: 'Whiteboard Marker', ar: 'قلم السبورة البيضاء القابل للمسح', img: '🖊️', o: ['Whiteboard Marker', 'Permanent Marker', 'Pen', 'Crayon'] },
    { name: 'Duster', ar: 'مساحة وممحاة لوح الصف', img: '🧽', o: ['Duster', 'Eraser', 'Sponge', 'Towel'] },
    { name: 'Calculator', ar: 'الآلة الحاسبة لحل العمليات الحسابية', img: '🔢', o: ['Calculator', 'Clock', 'Phone', 'Computer'] },
    { name: 'Globe', ar: 'مجسم الكرة الأرضية الجغرافي', img: '🌍', o: ['Globe', 'Map', 'Ball', 'Compass'] },
    { name: 'Map', ar: 'خريطة العالم الجغرافية الملونة', img: '🗺️', o: ['Map', 'Globe', 'Chart', 'Picture'] },
    { name: 'Clock', ar: 'ساعة الحائط المدرسية لمعرفة الوقت', img: '⏰', o: ['Clock', 'Watch', 'Bell', 'Calendar'] },
    { name: 'School Bell', ar: 'جرس المدرسة معلن الحصص والفسحة', img: '🔔', o: ['School Bell', 'Alarm', 'Siren', 'Horn'] },
    { name: 'Computer', ar: 'جهاز الحاسوب في معمل التكنولوجيا', img: '💻', o: ['Computer', 'Tablet', 'TV', 'Radio'] },
    { name: 'Tablet', ar: 'الجهاز اللوحي الذكي للتعلم', img: '📱', o: ['Tablet', 'Phone', 'Laptop', 'Screen'] },
    { name: 'Compass', ar: 'الفرجار الهندسي لرسم الدوائر', img: '📐', o: ['Compass', 'Protractor', 'Ruler', 'Square'] },
    { name: 'Protractor', ar: 'المنقلة الهندسية لقياس الزوايا', img: '📐', o: ['Protractor', 'Compass', 'Ruler', 'Triangle'] },
    { name: 'Set Square', ar: 'مثلث الرسم الهندسي القائم', img: '📐', o: ['Set Square', 'Ruler', 'Compass', 'Protractor'] },
    { name: 'Stapler', ar: 'الدباسة لتجميع الأوراق معاً', img: '📎', o: ['Stapler', 'Puncher', 'Clip', 'Tape'] },
    { name: 'Paperclip', ar: 'مشبك الورق المعدني الصغير', img: '📎', o: ['Paperclip', 'Stapler', 'Pin', 'Clamp'] },
    { name: 'Sticky Notes', ar: 'الأوراق اللاصقة الصغيرة للتذكير', img: '🟨', o: ['Sticky Notes', 'Paper', 'Card', 'Label'] },
    { name: 'Lunchbox', ar: 'صندوق حفظ وجبة الغداء المدرسية', img: '🍱', o: ['Lunchbox', 'Water Bottle', 'Backpack', 'Tray'] },
    { name: 'Water Bottle', ar: 'قارورة وزمزمية مياه الشرب', img: '🍶', o: ['Water Bottle', 'Cup', 'Glass', 'Thermos'] },
    { name: 'School Badge', ar: 'شارة وشعار المدرسة على الزي', img: '🏷️', o: ['School Badge', 'Pin', 'Medal', 'Sticker'] },
    { name: 'Locker', ar: 'الخزانة الخاصة بالطالب لحفظ الكتب', img: '🗄️', o: ['Locker', 'Closet', 'Drawer', 'Desk'] },
    { name: 'Classroom', ar: 'غرفة الفصل الدراسي للتعلم', img: '🏫', o: ['Classroom', 'Library', 'Gym', 'Lab'] },
    { name: 'Library', ar: 'المكتبة المدرسية العامرة بالكتب', img: '📚', o: ['Library', 'Classroom', 'Canteen', 'Playground'] },
    { name: 'Science Lab', ar: 'مختبر ومعمل العلوم للتجارب', img: '🔬', o: ['Science Lab', 'Kitchen', 'Gym', 'Art Room'] },
    { name: 'Playground', ar: 'فناء وساحة المدرسة للعب والفسحة', img: '🛝', o: ['Playground', 'Classroom', 'Hall', 'Stairs'] },
    { name: 'Homework', ar: 'الواجب المنزلي المطلوب حله', img: '📝', o: ['Homework', 'Exam', 'Lesson', 'Project'] },
    { name: 'Exam', ar: 'الاختبار والامتحان الدراسي', img: '📄', o: ['Exam', 'Homework', 'Book', 'Game'] },
    { name: 'Student ID', ar: 'بطاقة وهوية الطالب التعريفية', img: '🪪', o: ['Student ID', 'Passport', 'Ticket', 'Badge'] },
    { name: 'Certificate', ar: 'شهادة التفوق والنجاح الدراسية', img: '📜', o: ['Certificate', 'Letter', 'Book', 'Diploma'] }
  ];
  games['أدوات المدرسة والكتابة بالإنجليزية'] = schoolList.map((d, i) => ({
    id: 26001 + i,
    question: `ما اسم الأداة المدرسية (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} بالإنجليزية تُسمى '${d.name}'.`
  }));

  // 27. الأدوات الهندسية والأشكال بالإنجليزية
  const shapesList = [
    { name: 'Circle', ar: 'الدائرة المستديرة تماماً', img: '⚪', o: ['Circle', 'Square', 'Triangle', 'Oval'] },
    { name: 'Square', ar: 'المربع متساوي الأضلاع الأربعة', img: '⬛', o: ['Square', 'Rectangle', 'Circle', 'Rhombus'] },
    { name: 'Triangle', ar: 'المثلث ذو الأضلاع الثلاثة', img: '🔺', o: ['Triangle', 'Square', 'Circle', 'Pentagon'] },
    { name: 'Rectangle', ar: 'المستطيل ذو الطول والعرض', img: '▭', o: ['Rectangle', 'Square', 'Oval', 'Circle'] },
    { name: 'Oval', ar: 'الشكل البيضاوي الشبيه بالبيضة', img: '🥚', o: ['Oval', 'Circle', 'Round', 'Sphere'] },
    { name: 'Star', ar: 'شكل النجمة الخماسية البراقة', img: '⭐', o: ['Star', 'Heart', 'Moon', 'Sun'] },
    { name: 'Heart', ar: 'شكل القلب رمز المحبة', img: '❤️', o: ['Heart', 'Star', 'Diamond', 'Circle'] },
    { name: 'Diamond', ar: 'شكل المعين الماسي الرائع', img: '🔷', o: ['Diamond', 'Square', 'Triangle', 'Star'] },
    { name: 'Pentagon', ar: 'الشكل الخماسي ذو 5 أضلاع', img: '⬟', o: ['Pentagon', 'Hexagon', 'Octagon', 'Square'] },
    { name: 'Hexagon', ar: 'الشكل السداسي ذو 6 أضلاع كخلية النحل', img: '🛑', o: ['Hexagon', 'Pentagon', 'Heptagon', 'Octagon'] },
    { name: 'Octagon', ar: 'الشكل الثماني ذو 8 أضلاع كإشارة قف', img: '🛑', o: ['Octagon', 'Hexagon', 'Decagon', 'Circle'] },
    { name: 'Cube', ar: 'المكعب ثلاثي الأبعاد ذو 6 أوجه مربعة', img: '🧊', o: ['Cube', 'Sphere', 'Cone', 'Pyramid'] },
    { name: 'Sphere', ar: 'الكرة المجسمة التامة الاستدارة', img: '⚽', o: ['Sphere', 'Circle', 'Cylinder', 'Cube'] },
    { name: 'Cylinder', ar: 'الأسطوانة ذات القاعدتين الدائريتين', img: '🥫', o: ['Cylinder', 'Cone', 'Prism', 'Cube'] },
    { name: 'Cone', ar: 'المخروط الشبيه بقبعة الحفلات والآيس كريم', img: '🍦', o: ['Cone', 'Pyramid', 'Cylinder', 'Sphere'] },
    { name: 'Pyramid', ar: 'الهرم ذو القمة المدببة والأوجه المثلثة', img: '🔺', o: ['Pyramid', 'Cone', 'Cube', 'Prism'] },
    { name: 'Semi-circle', ar: 'نصف الدائرة المقوس', img: '🌓', o: ['Semi-circle', 'Crescent', 'Circle', 'Oval'] },
    { name: 'Crescent', ar: 'الهلال الشبيه بالقمر في أول الشهر', img: '🌙', o: ['Crescent', 'Semi-circle', 'Star', 'Ring'] },
    { name: 'Arrow', ar: 'السهم المشير للاتجاه', img: '➡️', o: ['Arrow', 'Line', 'Cross', 'Dot'] },
    { name: 'Cross', ar: 'شكل علامة الزائد المتقاطعة (+)', img: '➕', o: ['Cross', 'Star', 'Square', 'Box'] },
    { name: 'Trapezoid', ar: 'شبه المنحرف الهندسي', img: '⏢', o: ['Trapezoid', 'Rectangle', 'Rhombus', 'Kite'] },
    { name: 'Parallelogram', ar: 'متوازي الأضلاع الهندسي', img: '▱', o: ['Parallelogram', 'Rectangle', 'Square', 'Trapezoid'] },
    { name: 'Rhombus', ar: 'المعين متساوي الأضلاع الأربعة', img: '🔶', o: ['Rhombus', 'Square', 'Rectangle', 'Pentagon'] },
    { name: 'Ring', ar: 'الحلقة الدائرية المفرغة من الوسط', img: '⭕', o: ['Ring', 'Circle', 'Dot', 'Wheel'] },
    { name: 'Dot', ar: 'النقطة الهندسية الصغيرة', img: '⏺️', o: ['Dot', 'Line', 'Circle', 'Point'] },
    { name: 'Line', ar: 'الخط المستقيم الممتد', img: '➖', o: ['Line', 'Dot', 'Ray', 'Angle'] },
    { name: 'Straight Line', ar: 'الخط المستقيم غير المنحني', img: '📏', o: ['Straight Line', 'Curved Line', 'Zigzag', 'Wave'] },
    { name: 'Curved Line', ar: 'الخط المنحني المقوس بانسيابية', img: '〰️', o: ['Curved Line', 'Straight Line', 'Parallel', 'Ray'] },
    { name: 'Zigzag Line', ar: 'الخط المتعرج المنكسر الزوايا', img: '⚡', o: ['Zigzag Line', 'Straight Line', 'Circle', 'Loop'] },
    { name: 'Angle', ar: 'الزاوية الناتجة عن التقاء شعاعين', img: '📐', o: ['Angle', 'Side', 'Corner', 'Vertex'] },
    { name: 'Right Angle', ar: 'الزاوية القائمة قياسها 90 درجة', img: '📐', o: ['Right Angle', 'Acute Angle', 'Obtuse Angle', 'Straight Angle'] },
    { name: 'Acute Angle', ar: 'الزاوية الحادة أصغر من 90 درجة', img: '📐', o: ['Acute Angle', 'Right Angle', 'Obtuse Angle', 'Reflex Angle'] },
    { name: 'Obtuse Angle', ar: 'الزاوية المنفرجة أكبر من 90 درجة', img: '📐', o: ['Obtuse Angle', 'Acute Angle', 'Right Angle', 'Zero Angle'] },
    { name: 'Ruler', ar: 'مسطرة القياس الهندسية بالسنتيمتر', img: '📏', o: ['Ruler', 'Compass', 'Protractor', 'Square'] },
    { name: 'Compass', ar: 'فرجار الهندسة لرسم الدوائر والأقواس', img: '📐', o: ['Compass', 'Protractor', 'Ruler', 'Divider'] },
    { name: 'Protractor', ar: 'المنقلة الهندسية الشفافة لقياس الدرجات', img: '📐', o: ['Protractor', 'Compass', 'Ruler', 'Scale'] },
    { name: 'Set Square', ar: 'المثلث الهندسي القائم الزاوية', img: '📐', o: ['Set Square', 'Ruler', 'Protractor', 'Compass'] },
    { name: 'Tape Measure', ar: 'شريط القياس المتري المرن', img: '📏', o: ['Tape Measure', 'Ruler', 'Stick', 'Rope'] },
    { name: 'Grid', ar: 'الشبكة التربيعية الهندسية', img: '▦', o: ['Grid', 'Plane', 'Chart', 'Table'] },
    { name: 'Side', ar: 'الضلع في الشكل الهندسي', img: '⬛', o: ['Side', 'Corner', 'Angle', 'Center'] },
    { name: 'Corner', ar: 'الرأس والزاوية الحادة للشكل', img: '📐', o: ['Corner', 'Side', 'Edge', 'Face'] },
    { name: 'Diameter', ar: 'قطر الدائرة المار بمركزها', img: '⭕', o: ['Diameter', 'Radius', 'Chord', 'Arc'] },
    { name: 'Radius', ar: 'نصف قطر الدائرة من المركز للمحيط', img: '⭕', o: ['Radius', 'Diameter', 'Circumference', 'Area'] },
    { name: 'Perimeter', ar: 'محيط الشكل الهندسي الخارجي', img: '🔲', o: ['Perimeter', 'Area', 'Volume', 'Height'] },
    { name: 'Area', ar: 'المساحة الداخلية المحصورة للشكل', img: '🟩', o: ['Area', 'Perimeter', 'Volume', 'Length'] },
    { name: 'Geometry', ar: 'علم الهندسة الرياضية والأشكال', img: '📐', o: ['Geometry', 'Algebra', 'Science', 'Art'] },
    { name: 'Symmetry', ar: 'التماثل والتناظر الهندسي المتطابق', img: '🦋', o: ['Symmetry', 'Rotation', 'Reflection', 'Shift'] },
    { name: 'Pattern', ar: 'النمط والتكرار الهندسي المنتظم', img: '💠', o: ['Pattern', 'Chaos', 'Line', 'Color'] },
    { name: '2D Shapes', ar: 'الأشكال ثنائية الأبعاد (طول وعرض)', img: '📄', o: ['2D Shapes', '3D Shapes', 'Solids', 'Points'] },
    { name: '3D Shapes', ar: 'المجسمات ثلاثية الأبعاد (طول وعرض وارتفاع)', img: '🧊', o: ['3D Shapes', '2D Shapes', 'Flats', 'Lines'] }
  ];
  games['الأدوات الهندسية والأشكال بالإنجليزية'] = shapesList.map((d, i) => ({
    id: 27001 + i,
    question: `ما اسم الشكل الهندسي أو الأداة (${d.ar}) بالإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية هو '${d.name}'.`
  }));

  // 28. مفردات الحديقة والمزرعة بالإنجليزية
  const gardenFarmList = [
    { name: 'Flower', ar: 'الزهرة الفواحة البديعة', img: '🌸', o: ['Flower', 'Tree', 'Grass', 'Leaf'] },
    { name: 'Rose', ar: 'الوردة الجورية العطرة', img: '🌹', o: ['Rose', 'Tulip', 'Daisy', 'Lily'] },
    { name: 'Tulip', ar: 'زهرة التوليب ذات الكأس الأنيق', img: '🌷', o: ['Tulip', 'Rose', 'Sunflower', 'Orchid'] },
    { name: 'Sunflower', ar: 'دوار الشمس الأصفر المتتبع للنور', img: '🌻', o: ['Sunflower', 'Daisy', 'Rose', 'Tulip'] },
    { name: 'Daisy', ar: 'زهرة الأقحوان البيضاء الناعمة', img: '🌼', o: ['Daisy', 'Rose', 'Sunflower', 'Tulip'] },
    { name: 'Tree', ar: 'الشجرة الكبيرة ذات الظل الوارف', img: '🌳', o: ['Tree', 'Bush', 'Flower', 'Grass'] },
    { name: 'Oak Tree', ar: 'شجرة البلوط المعمرة القوية', img: '🌳', o: ['Oak Tree', 'Palm Tree', 'Pine Tree', 'Willow'] },
    { name: 'Palm Tree', ar: 'شجرة النخيل الباسقة بالتمور', img: '🌴', o: ['Palm Tree', 'Pine Tree', 'Apple Tree', 'Oak'] },
    { name: 'Pine Tree', ar: 'شجرة الصنوبر دائمة الخضرة', img: '🌲', o: ['Pine Tree', 'Palm Tree', 'Cactus', 'Bush'] },
    { name: 'Bush', ar: 'الشجيرة الصغيرة الكثيفة', img: '🌳', o: ['Bush', 'Tree', 'Flower', 'Vine'] },
    { name: 'Grass', ar: 'العشب الأخضر الناعم الممتد', img: '🌱', o: ['Grass', 'Tree', 'Moss', 'Dirt'] },
    { name: 'Lawn', ar: 'مسطح المروج الخضراء المشذبة', img: '🌱', o: ['Lawn', 'Garden', 'Field', 'Yard'] },
    { name: 'Soil', ar: 'التربة الخصبة الصالحة للزراعة', img: '🪴', o: ['Soil', 'Sand', 'Stone', 'Water'] },
    { name: 'Seed', ar: 'البذرة الصغيرة التي نغرسها بالأرض', img: '🌱', o: ['Seed', 'Leaf', 'Fruit', 'Stem'] },
    { name: 'Sprout', ar: 'البرعم الصغير النابت من البذرة', img: '🌱', o: ['Sprout', 'Root', 'Branch', 'Flower'] },
    { name: 'Plant', ar: 'النبتة الخضراء في الحديقة', img: '🪴', o: ['Plant', 'Tree', 'Stone', 'Seed'] },
    { name: 'Leaf', ar: 'ورقة الشجر الخضراء', img: '🍃', o: ['Leaf', 'Flower', 'Branch', 'Root'] },
    { name: 'Branch', ar: 'غصن الشجرة الممتد في الهواء', img: '🪵', o: ['Branch', 'Trunk', 'Leaf', 'Root'] },
    { name: 'Trunk', ar: 'جذع الشجرة الخشبي السميك القوي', img: '🪵', o: ['Trunk', 'Branch', 'Leaf', 'Twig'] },
    { name: 'Root', ar: 'جذر النبتة الممتد تحت الأرض لامتصاص الماء', img: '🥕', o: ['Root', 'Stem', 'Leaf', 'Flower'] },
    { name: 'Weed', ar: 'الأعشاب الضارة التي يجب إزالتها', img: '🌿', o: ['Weed', 'Flower', 'Crop', 'Tree'] },
    { name: 'Watering Can', ar: 'مرش ورشاش سقاية النباتات اليدوي', img: '🚿', o: ['Watering Can', 'Bucket', 'Hose', 'Shovel'] },
    { name: 'Garden Hose', ar: 'خرطوم مياه ري الحديقة الطويل', img: '🪠', o: ['Garden Hose', 'Rope', 'Pipe', 'Wire'] },
    { name: 'Shovel', ar: 'المجرفة لحفر وتقليب التربة', img: '⛏️', o: ['Shovel', 'Rake', 'Hoe', 'Fork'] },
    { name: 'Rake', ar: 'المعزقة والمشط لجمع الأوراق الجافة', img: '🧹', o: ['Rake', 'Broom', 'Shovel', 'Mop'] },
    { name: 'Wheelbarrow', ar: 'عربة الحديقة اليدوية ذات العجلة الواحدة', img: '🛒', o: ['Wheelbarrow', 'Cart', 'Wagon', 'Tractor'] },
    { name: 'Flower Pot', ar: 'أصيص وزهرية زرع النباتات', img: '🪴', o: ['Flower Pot', 'Vase', 'Bucket', 'Jar'] },
    { name: 'Greenhouse', ar: 'البيت الزجاجي المحمي لنمو الشتلات', img: '🏡', o: ['Greenhouse', 'Barn', 'Shed', 'House'] },
    { name: 'Fence', ar: 'سياج وسور الحديقة الخشبي', img: '🪵', o: ['Fence', 'Wall', 'Gate', 'Door'] },
    { name: 'Gate', ar: 'بوابة مدخل الحديقة والمزرعة', img: '🚪', o: ['Gate', 'Door', 'Fence', 'Window'] },
    { name: 'Barn', ar: 'الحظيرة الكبيرة لحفظ الحيوانات والمحصول', img: '🏚️', o: ['Barn', 'House', 'Stable', 'Shed'] },
    { name: 'Silo', ar: 'صومعة تخزين وتبريد الحبوب والغلال', img: '🏢', o: ['Silo', 'Tower', 'Barn', 'Mill'] },
    { name: 'Tractor', ar: 'جرار المزرعة القوي لحرث الحقول', img: '🚜', o: ['Tractor', 'Truck', 'Car', 'Combine'] },
    { name: 'Scarecrow', ar: 'فزاعة الطيور لحماية المحصول', img: '🌾', o: ['Scarecrow', 'Statue', 'Doll', 'Man'] },
    { name: 'Windmill', ar: 'طاحونة الهواء لضخ المياه أو طحن الحبوب', img: '💨', o: ['Windmill', 'Turbine', 'Tower', 'Barn'] },
    { name: 'Hay', ar: 'القش والتبن غذاء المواشي بالمزرعة', img: '🌾', o: ['Hay', 'Grass', 'Wheat', 'Corn'] },
    { name: 'Meadow', ar: 'المرج الأخضر الفسيح لرعي الأبقار', img: '🏞️', o: ['Meadow', 'Forest', 'Desert', 'Mountain'] },
    { name: 'Orchard', ar: 'بستان أشجار الفواكه المثمرة', img: '🍎', o: ['Orchard', 'Garden', 'Farm', 'Field'] },
    { name: 'Vegetable Patch', ar: 'حوض ومشتل زراعة الخضروات الطازجة', img: '🥕', o: ['Vegetable Patch', 'Lawn', 'Park', 'Yard'] },
    { name: 'Compost', ar: 'السماد العضوي الطبيعي المفيد للنبات', img: '🪱', o: ['Compost', 'Soil', 'Mud', 'Clay'] },
    { name: 'Earthworm', ar: 'دودة الأرض الصديقة للمزارع التي تهوي التربة', img: '🪱', o: ['Earthworm', 'Caterpillar', 'Snake', 'Centipede'] },
    { name: 'Ladybug', ar: 'الدعسوقة المنقطة صديقة النباتات', img: '🐞', o: ['Ladybug', 'Beetle', 'Fly', 'Bee'] },
    { name: 'Beehive', ar: 'خلية النحل منتجة العسل الذهبي', img: '🐝', o: ['Beehive', 'Nest', 'Anthill', 'Hole'] },
    { name: 'Honeycomb', ar: 'قرص شمع العسل سداسي العيون', img: '🍯', o: ['Honeycomb', 'Beehive', 'Wax', 'Honey'] },
    { name: 'Butterfly', ar: 'الفراشة الملونة الرفافة بين الزهور', img: '🦋', o: ['Butterfly', 'Moth', 'Bee', 'Bird'] },
    { name: 'Caterpillar', ar: 'اليرقة الخضراء الصغيرة التي تتحول لفراشة', img: '🐛', o: ['Caterpillar', 'Worm', 'Snail', 'Beetle'] },
    { name: 'Garden Bench', ar: 'مقعد الحديقة الخشبي للاستراحة', img: '🪑', o: ['Garden Bench', 'Chair', 'Table', 'Sofa'] },
    { name: 'Fountain', ar: 'نافورة المياه المترقرقة بالحديقة', img: '⛲', o: ['Fountain', 'Pond', 'Pool', 'Well'] },
    { name: 'Bird Feeder', ar: 'معلفة ومطعم العصافير المعلق', img: '🐦', o: ['Bird Feeder', 'Nest', 'Birdcage', 'House'] },
    { name: 'Harvest', ar: 'موسم الحصاد وجني المحاصيل الطيبة', img: '🌾', o: ['Harvest', 'Planting', 'Watering', 'Ploughing'] }
  ];
  games['مفردات الحديقة والمزرعة بالإنجليزية'] = gardenFarmList.map((d, i) => ({
    id: 28001 + i,
    question: `ما اسم (${d.ar}) باللغة الإنجليزية في سياق الحديقة والمزرعة؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 29. الرياضات والألعاب بالإنجليزية
  const sportsList = [
    { name: 'Football', ar: 'كرة القدم اللعبة الأكثر شعبية بالعالم', img: '⚽', o: ['Football', 'Basketball', 'Tennis', 'Volleyball'] },
    { name: 'Basketball', ar: 'كرة السلة وتصويب الكرة داخل الطوق', img: '🏀', o: ['Basketball', 'Football', 'Baseball', 'Golf'] },
    { name: 'Tennis', ar: 'كرة المضرب (التنس) بمضرب وشبكة', img: '🎾', o: ['Tennis', 'Badminton', 'Table Tennis', 'Squash'] },
    { name: 'Volleyball', ar: 'الكرة الطائرة المتبادلة فوق الشبكة باليدين', img: '🏐', o: ['Volleyball', 'Basketball', 'Handball', 'Football'] },
    { name: 'Baseball', ar: 'البيسبول وضرب الكرة بالمضرب الخشبي', img: '⚾', o: ['Baseball', 'Cricket', 'Golf', 'Hockey'] },
    { name: 'Badminton', ar: 'كرة الريشة الطائرة بالمضرب الخفيف', img: '🏸', o: ['Badminton', 'Tennis', 'Squash', 'Ping Pong'] },
    { name: 'Table Tennis', ar: 'تنس الطاولة (بينغ بونغ) على الطاولة الخضراء', img: '🏓', o: ['Table Tennis', 'Tennis', 'Billiards', 'Hockey'] },
    { name: 'Swimming', ar: 'السباحة الحرة في المسبح', img: '🏊', o: ['Swimming', 'Diving', 'Surfing', 'Rowing'] },
    { name: 'Running', ar: 'الجري والعدو في مضمار السباق', img: '🏃', o: ['Running', 'Walking', 'Jumping', 'Cycling'] },
    { name: 'Cycling', ar: 'ركوب الدراجة الهوائية بالسباق', img: '🚴', o: ['Cycling', 'Motorcycling', 'Skating', 'Running'] },
    { name: 'Gymnastics', ar: 'الجمباز والحركات البهلوانية الرشيقة', img: '🤸', o: ['Gymnastics', 'Dance', 'Yoga', 'Jumping'] },
    { name: 'Karate', ar: 'الكاراتيه وفنون الدفاع عن النفس اليابانية', img: '🥋', o: ['Karate', 'Judo', 'Taekwondo', 'Boxing'] },
    { name: 'Judo', ar: 'رياضة الجودو القتالية', img: '🥋', o: ['Judo', 'Karate', 'Wrestling', 'Boxing'] },
    { name: 'Taekwondo', ar: 'التايكوندو الكورية وركلات القدم البارعة', img: '🥋', o: ['Taekwondo', 'Karate', 'Kung Fu', 'Fencing'] },
    { name: 'Boxing', ar: 'الملاكمة بقفازات الملاكمة في الحلبة', img: '🥊', o: ['Boxing', 'Wrestling', 'Karate', 'Fencing'] },
    { name: 'Skiing', ar: 'التزلج على الثلج بعصي التزلج', img: '⛷️', o: ['Skiing', 'Snowboarding', 'Ice Skating', 'Sledding'] },
    { name: 'Snowboarding', ar: 'التزلج على لوح الثلج الفردي', img: '🏂', o: ['Snowboarding', 'Skiing', 'Surfing', 'Skateboarding'] },
    { name: 'Ice Skating', ar: 'التزلج على الجليد بحذاء الشفرة الحادة', img: '⛸️', o: ['Ice Skating', 'Roller Skating', 'Skiing', 'Hockey'] },
    { name: 'Roller Skating', ar: 'التزلج بحذاء العجلات الأربع', img: '🛼', o: ['Roller Skating', 'Ice Skating', 'Skateboarding', 'Cycling'] },
    { name: 'Skateboarding', ar: 'ركوب لوح التزلج والقفز به', img: '🛹', o: ['Skateboarding', 'Scooter', 'Surfing', 'Skating'] },
    { name: 'Surfing', ar: 'ركوب أمواج البحر على اللوح المائي', img: '🏄', o: ['Surfing', 'Swimming', 'Diving', 'Sailing'] },
    { name: 'Diving', ar: 'الغطس من المنصة العالية في المسبح', img: '🤿', o: ['Diving', 'Swimming', 'Surfing', 'Jumping'] },
    { name: 'Rowing', ar: 'التجديف بالقارب في مياه النهر', img: '🚣', o: ['Rowing', 'Canoeing', 'Sailing', 'Kayaking'] },
    { name: 'Sailing', ar: 'الإبحار بالقارب الشراعي مع الرياح', img: '⛵', o: ['Sailing', 'Rowing', 'Surfing', 'Swimming'] },
    { name: 'Archery', ar: 'رياضة الرماية بالقوس والسهم نحو الهدف', img: '🏹', o: ['Archery', 'Shooting', 'Fencing', 'Darts'] },
    { name: 'Horse Riding', ar: 'الفروسية وركوب الخيل الأصيل', img: '🏇', o: ['Horse Riding', 'Cycling', 'Racing', 'Running'] },
    { name: 'Golf', ar: 'الجولف وإدخال الكرة في الحفرة بالمضرب', img: '⛳', o: ['Golf', 'Cricket', 'Hockey', 'Baseball'] },
    { name: 'Cricket', ar: 'الكريكيت بمضرب الخشب العريض والويكيت', img: '🏏', o: ['Cricket', 'Baseball', 'Golf', 'Tennis'] },
    { name: 'Rugby', ar: 'الرجبي بكرتها البيضاوية والاندفاع القوي', img: '🏉', o: ['Rugby', 'Football', 'Handball', 'Basketball'] },
    { name: 'Bowling', ar: 'البولينج وإسقاط الأقماع العشرة بالكرة الثقيلة', img: '🎳', o: ['Bowling', 'Billiards', 'Curling', 'Golf'] },
    { name: 'Hiking', ar: 'المشي الجبلي في الطبيعة بحذاء المشي', img: '🥾', o: ['Hiking', 'Running', 'Climbing', 'Walking'] },
    { name: 'Climbing', ar: 'تسلق الصخور والجدران المرتفعة بالحبال', img: '🧗', o: ['Climbing', 'Hiking', 'Jumping', 'Diving'] },
    { name: 'Yoga', ar: 'اليوغا وحركات الاسترخاء والتمدد', img: '🧘', o: ['Yoga', 'Gymnastics', 'Pilates', 'Meditation'] },
    { name: 'Jump Rope', ar: 'نط الحبل الرياضي الممتع للأطفال', img: '🪢', o: ['Jump Rope', 'Hopscotch', 'Hula Hoop', 'Tag'] },
    { name: 'Hula Hoop', ar: 'طوق الهولا هوب الدائري لتدويره حول الخصر', img: '⭕', o: ['Hula Hoop', 'Jump Rope', 'Ring', 'Frisbee'] },
    { name: 'Tug of War', ar: 'لعبة شد الحبل بين فريقين قويين', img: '🪢', o: ['Tug of War', 'Jump Rope', 'Arm Wrestling', 'Relay'] },
    { name: 'Hide and Seek', ar: 'لعبة الغميضة والاختباء المفضلة للأطفال', img: '🙈', o: ['Hide and Seek', 'Tag', 'Hopscotch', 'Musical Chairs'] },
    { name: 'Tag', ar: 'لعبة المطاردة والملاحقة بين الأصدقاء', img: '🏃', o: ['Tag', 'Hide and Seek', 'Relay', 'Dodgeball'] },
    { name: 'Hopscotch', ar: 'لعبة الحجلة والقفز على المربعات المرقمة', img: '🔢', o: ['Hopscotch', 'Jump Rope', 'Marbles', 'Dominos'] },
    { name: 'Chess', ar: 'الشطرنج لعبة التفكير الاستراتيجي والذكاء', img: '♟️', o: ['Chess', 'Checkers', 'Backgammon', 'Cards'] },
    { name: 'Checkers', ar: 'لعبة الداما بالأقراص الدائرية السوداء والبيضاء', img: '⚪', o: ['Checkers', 'Chess', 'Dominoes', 'Go'] },
    { name: 'Board Game', ar: 'لعبة الطاولة اللوحية بالنرد والبيادق', img: '🎲', o: ['Board Game', 'Video Game', 'Puzzle', 'Card Game'] },
    { name: 'Puzzle', ar: 'أحجية البازل وتركيب القطع المفقودة', img: '🧩', o: ['Puzzle', 'Crossword', 'Riddle', 'Maze'] },
    { name: 'Video Game', ar: 'ألعاب الفيديو والشاشات الرقمية', img: '🎮', o: ['Video Game', 'Board Game', 'Outdoor Game', 'Sport'] },
    { name: 'Trampoline', ar: 'الترامبولين وشبكة القفز الهوائي العالي', img: '🤸', o: ['Trampoline', 'Gymnastics', 'Mat', 'Slide'] },
    { name: 'Marathon', ar: 'سباق الماراثون الطويل لمسافة 42 كيلومتر', img: '🏃', o: ['Marathon', 'Sprint', 'Relay', 'Jog'] },
    { name: 'Medal', ar: 'الميدالية الذهبية للفائز بالمركز الأول', img: '🥇', o: ['Medal', 'Trophy', 'Cup', 'Ribbon'] },
    { name: 'Trophy', ar: 'الكأس الذهبي للبطولة والتتويج', img: '🏆', o: ['Trophy', 'Medal', 'Plate', 'Crown'] },
    { name: 'Whistle', ar: 'صافرة الحكم الرياضي لإيقاف اللعب', img: '📣', o: ['Whistle', 'Bell', 'Horn', 'Buzzer'] },
    { name: 'Referee', ar: 'الحكم العادل المسؤول عن ضبط قوانين المباراة', img: '🧑‍⚖️', o: ['Referee', 'Coach', 'Captain', 'Player'] }
  ];
  games['الرياضات والألعاب بالإنجليزية'] = sportsList.map((d, i) => ({
    id: 29001 + i,
    question: `ما اسم الرياضة أو اللعبة (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `رياضة أو لعبة ${d.ar} تُسمى بالإنجليزية '${d.name}'.`
  }));

  // 30. الأدوات المنزلية والمطبخ بالإنجليزية
  const kitchenHomeList = [
    { name: 'Spoon', ar: 'ملعقة تناول الطعام والحساء', img: '🥄', o: ['Spoon', 'Fork', 'Knife', 'Plate'] },
    { name: 'Fork', ar: 'شوكة تناول المعكرونة والسلطة', img: '🍴', o: ['Fork', 'Spoon', 'Knife', 'Cup'] },
    { name: 'Knife', ar: 'سكين المطبخ لتقطيع الفواكه والخبز', img: '🔪', o: ['Knife', 'Fork', 'Spoon', 'Peeler'] },
    { name: 'Plate', ar: 'الصحن والطبق المسطح للطعام', img: '🍽️', o: ['Plate', 'Bowl', 'Cup', 'Tray'] },
    { name: 'Bowl', ar: 'الزبدية والسلطانية العميقة للحساء', img: '🥣', o: ['Bowl', 'Plate', 'Cup', 'Pot'] },
    { name: 'Cup', ar: 'الفنجان الصغير للشاي والقهوة', img: '☕', o: ['Cup', 'Glass', 'Jug', 'Bottle'] },
    { name: 'Mug', ar: 'الكوب الكبير ذو المقبض للمشروبات الساخنة', img: '☕', o: ['Mug', 'Glass', 'Spoon', 'Bowl'] },
    { name: 'Glass', ar: 'كوب الزجاج الشفاف لشرب الماء والعصير', img: '🥛', o: ['Glass', 'Bottle', 'Cup', 'Plate'] },
    { name: 'Bottle', ar: 'زجاجة وقارورة الماء أو الحليب', img: '🍾', o: ['Bottle', 'Cup', 'Jug', 'Can'] },
    { name: 'Pitcher', ar: 'إبريق العصير والماء لصب المشروب', img: '🏺', o: ['Pitcher', 'Bottle', 'Glass', 'Pot'] },
    { name: 'Teapot', ar: 'إبريق إعداد الشاي الخزفي', img: '🫖', o: ['Teapot', 'Kettle', 'Cup', 'Jug'] },
    { name: 'Frying Pan', ar: 'مقلاة طهي البيض والفطائر', img: '🍳', o: ['Frying Pan', 'Pot', 'Oven', 'Bowl'] },
    { name: 'Pot', ar: 'قدر الطبخ العميق لطهي الأرز والشوربة', img: '🍲', o: ['Pot', 'Pan', 'Kettle', 'Dish'] },
    { name: 'Kettle', ar: 'غلاية المياه السريعة لإعداد الشاي', img: '🫖', o: ['Kettle', 'Teapot', 'Toaster', 'Blender'] },
    { name: 'Cutting Board', ar: 'لوح التقطيع الخشبي لتقطيع الخضار', img: '🪵', o: ['Cutting Board', 'Plate', 'Tray', 'Table'] },
    { name: 'Blender', ar: 'الخلاط الكهربائي لإعداد العصير والسموذي', img: '🥤', o: ['Blender', 'Mixer', 'Toaster', 'Microwave'] },
    { name: 'Toaster', ar: 'محمصة الخبز الكهربائية لصنع التوست المقرمش', img: '🍞', o: ['Toaster', 'Oven', 'Microwave', 'Kettle'] },
    { name: 'Microwave', ar: 'الميكروويف لتسخين الطعام بسرعة', img: '📻', o: ['Microwave', 'Oven', 'Fridge', 'Stove'] },
    { name: 'Oven', ar: 'الفرن الحراري لخبز الكعك والبيتزا', img: '🍳', o: ['Oven', 'Microwave', 'Stove', 'Toaster'] },
    { name: 'Refrigerator', ar: 'الثلاجة لحفظ الأطعمة طازجة وباردة', img: '🧊', o: ['Refrigerator', 'Freezer', 'Oven', 'Closet'] },
    { name: 'Freezer', ar: 'الفريزر (المجمدة) لتجميد اللحوم والآيس كريم', img: '🧊', o: ['Freezer', 'Fridge', 'Sink', 'Oven'] },
    { name: 'Dishwasher', ar: 'غسالة الصحون والأطباق الآلية', img: '🧼', o: ['Dishwasher', 'Washing Machine', 'Sink', 'Oven'] },
    { name: 'Kitchen Sink', ar: 'حوض ومجلى المطبخ لغسل الأواني', img: '🚰', o: ['Kitchen Sink', 'Bathtub', 'Shower', 'Bucket'] },
    { name: 'Faucet', ar: 'صنبور وحنفية المياه في المطبخ', img: '🚰', o: ['Faucet', 'Pipe', 'Shower', 'Hose'] },
    { name: 'Trash Can', ar: 'سلة المهملات والقمامة النظيفة', img: '🗑️', o: ['Trash Can', 'Box', 'Basket', 'Bag'] },
    { name: 'Broom', ar: 'المكنسة اليدوية لكنس الأرضيات', img: '🧹', o: ['Broom', 'Mop', 'Duster', 'Brush'] },
    { name: 'Dustpan', ar: 'الجاروف المخصص لجمع الأتربة بالمكنسة', img: '🧹', o: ['Dustpan', 'Broom', 'Bucket', 'Trash Can'] },
    { name: 'Mop', ar: 'الممسحة المائية لمسح وتلميع البلاط', img: '🪣', o: ['Mop', 'Broom', 'Sponge', 'Towel'] },
    { name: 'Bucket', ar: 'الدلو وسطل حمل المياه والتنظيف', img: '🪣', o: ['Bucket', 'Bowl', 'Pot', 'Basin'] },
    { name: 'Sponge', ar: 'إسفنجة غسيل الأطباق الماصة للرغوة', img: '🧽', o: ['Sponge', 'Cloth', 'Brush', 'Towel'] },
    { name: 'Table', ar: 'طاولة الطعام الخشبية للاجتماع', img: '🛋️', o: ['Table', 'Chair', 'Desk', 'Shelf'] },
    { name: 'Chair', ar: 'كرسي السفرة المريح', img: '🪑', o: ['Chair', 'Table', 'Sofa', 'Bench'] },
    { name: 'Sofa', ar: 'الأريكة والكنبة المريحة بغرفة الجلوس', img: '🛋️', o: ['Sofa', 'Bed', 'Chair', 'Cushion'] },
    { name: 'Bed', ar: 'السرير المريح في غرفة النوم', img: '🛏️', o: ['Bed', 'Sofa', 'Cot', 'Mattress'] },
    { name: 'Pillow', ar: 'الوسادة والمخدة الناعمة للرأس', img: '🛏️', o: ['Pillow', 'Blanket', 'Sheet', 'Cushion'] },
    { name: 'Blanket', ar: 'البطانية والغطاء الصوفي الدافئ', img: '🛌', o: ['Blanket', 'Pillow', 'Sheet', 'Curtain'] },
    { name: 'Wardrobe', ar: 'خزانة الملابس والدولاب لترتيب الثياب', img: '🚪', o: ['Wardrobe', 'Drawer', 'Shelf', 'Box'] },
    { name: 'Mirror', ar: 'المرآة العاكسة للوجه في الغرفة', img: '🪞', o: ['Mirror', 'Window', 'Glass', 'Picture'] },
    { name: 'Lamp', ar: 'المصباح وأباجورة الإضاءة للقراءة', img: '💡', o: ['Lamp', 'Bulb', 'Flashlight', 'Candle'] },
    { name: 'Clock', ar: 'ساعة الحائط المنزلية لدقة المواعيد', img: '⏰', o: ['Clock', 'Watch', 'Calendar', 'Timer'] },
    { name: 'Television', ar: 'التلفاز لمشاهدة البرامج المفيدة', img: '📺', o: ['Television', 'Radio', 'Computer', 'Screen'] },
    { name: 'Iron', ar: 'المكواة الكهربائية لكوي وتمليس الملابس', img: '👔', o: ['Iron', 'Washer', 'Dryer', 'Heater'] },
    { name: 'Washing Machine', ar: 'غسالة الملابس الكهربائية لتنظيف الثياب', img: '🧺', o: ['Washing Machine', 'Dishwasher', 'Dryer', 'Tub'] },
    { name: 'Laundry Basket', ar: 'سلة الغسيل لجمع الملابس المجهزة للغسل', img: '🧺', o: ['Laundry Basket', 'Trash Can', 'Box', 'Bag'] },
    { name: 'Towel', ar: 'المنشفة والبشكير القطني لتجفيف الجسم', img: '🧖', o: ['Towel', 'Blanket', 'Sheet', 'Cloth'] },
    { name: 'Soap', ar: 'الصابون المعطر لغسل الأيدي', img: '🧼', o: ['Soap', 'Shampoo', 'Lotion', 'Sponge'] },
    { name: 'Toothbrush', ar: 'فرشاة الأسنان لتنظيف الأسنان يومياً', img: '🪥', o: ['Toothbrush', 'Comb', 'Hairbrush', 'Razor'] },
    { name: 'Hairdryer', ar: 'مجفف الشعر الكهربائي (السشوار)', img: '💨', o: ['Hairdryer', 'Fan', 'Heater', 'Iron'] },
    { name: 'Carpet', ar: 'السجادة المزخرفة والمفروشة على الأرض', img: '🧶', o: ['Carpet', 'Mat', 'Blanket', 'Tile'] },
    { name: 'Curtain', ar: 'الستارة المنسدلة على نافذة الغرفة', img: '🪟', o: ['Curtain', 'Blanket', 'Towel', 'Sheet'] }
  ];
  games['الأدوات المنزلية والمطبخ بالإنجليزية'] = kitchenHomeList.map((d, i) => ({
    id: 30001 + i,
    question: `ما اسم الأداة المنزلية (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية تُسمى '${d.name}'.`
  }));

  return games;
}
