// Generators for English Games 1 to 10 (50 questions each = 500 questions)

export function getGames1to10() {
  const games = {};

  // 1. حروف اللغة الإنجليزية A-Z بالتسلسل
  const alphabetData = [
    { q: 'ما هو الحرف الأول في الأبجدية الإنجليزية (English Alphabet)؟', img: '🅰️', correct: 'A', opts: ['A', 'B', 'C', 'D'], exp: 'الحرف الأول هو A.' },
    { q: 'ما هو الحرف الأخير في الأبجدية الإنجليزية؟', img: '🔤', correct: 'Z', opts: ['Z', 'Y', 'X', 'W'], exp: 'الحرف الأخير هو Z.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة تفاحة (Apple)؟', img: '🍎', correct: 'A', opts: ['A', 'B', 'P', 'E'], exp: 'كلمة Apple تبدأ بحرف A.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة نحلة (Bee)؟', img: '🐝', correct: 'B', opts: ['B', 'D', 'P', 'E'], exp: 'كلمة Bee تبدأ بحرف B.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة قطة (Cat)؟', img: '🐱', correct: 'C', opts: ['C', 'K', 'S', 'T'], exp: 'كلمة Cat تبدأ بحرف C.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة كلب (Dog)؟', img: '🐶', correct: 'D', opts: ['D', 'B', 'P', 'G'], exp: 'كلمة Dog تبدأ بحرف D.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة فيل (Elephant)؟', img: '🐘', correct: 'E', opts: ['E', 'I', 'A', 'L'], exp: 'كلمة Elephant تبدأ بحرف E.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة سمكة (Fish)؟', img: '🐟', correct: 'F', opts: ['F', 'P', 'V', 'S'], exp: 'كلمة Fish تبدأ بحرف F.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة زرافة (Giraffe)؟', img: '🦒', correct: 'G', opts: ['G', 'J', 'Z', 'R'], exp: 'كلمة Giraffe تبدأ بحرف G.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة قبعة (Hat)؟', img: '🧢', correct: 'H', opts: ['H', 'A', 'T', 'W'], exp: 'كلمة Hat تبدأ بحرف H.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة آيس كريم (Ice cream)؟', img: '🍦', correct: 'I', opts: ['I', 'E', 'C', 'M'], exp: 'كلمة Ice cream تبدأ بحرف I.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة عصير أو مربى (Jam)؟', img: '🍓', correct: 'J', opts: ['J', 'G', 'Y', 'M'], exp: 'كلمة Jam تبدأ بحرف J.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة طائرة ورقية (Kite)؟', img: '🪁', correct: 'K', opts: ['K', 'C', 'T', 'Q'], exp: 'كلمة Kite تبدأ بحرف K.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة أسد (Lion)؟', img: '🦁', correct: 'L', opts: ['L', 'I', 'O', 'N'], exp: 'كلمة Lion تبدأ بحرف L.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة قرد (Monkey)؟', img: '🐒', correct: 'M', opts: ['M', 'W', 'N', 'K'], exp: 'كلمة Monkey تبدأ بحرف M.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة عش عصفور (Nest)؟', img: '🪺', correct: 'N', opts: ['N', 'M', 'H', 'E'], exp: 'كلمة Nest تبدأ بحرف N.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة برتقالة (Orange)؟', img: '🍊', correct: 'O', opts: ['O', 'Q', 'U', 'R'], exp: 'كلمة Orange تبدأ بحرف O.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة باندا (Panda)؟', img: '🐼', correct: 'P', opts: ['P', 'B', 'D', 'Q'], exp: 'كلمة Panda تبدأ بحرف P.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة ملكة (Queen)؟', img: '👑', correct: 'Q', opts: ['Q', 'K', 'O', 'P'], exp: 'كلمة Queen تبدأ بحرف Q.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة أرنب (Rabbit)؟', img: '🐰', correct: 'R', opts: ['R', 'B', 'P', 'D'], exp: 'كلمة Rabbit تبدأ بحرف R.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة شمس (Sun)؟', img: '☀️', correct: 'S', opts: ['S', 'C', 'Z', 'N'], exp: 'كلمة Sun تبدأ بحرف S.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة نمر (Tiger)؟', img: '🐅', correct: 'T', opts: ['T', 'F', 'I', 'R'], exp: 'كلمة Tiger تبدأ بحرف T.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة مظلة (Umbrella)؟', img: '☂️', correct: 'U', opts: ['U', 'V', 'W', 'O'], exp: 'كلمة Umbrella تبدأ بحرف U.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة كمانجة (Violin)؟', img: '🎻', correct: 'V', opts: ['V', 'U', 'W', 'F'], exp: 'كلمة Violin تبدأ بحرف V.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة حوت (Whale)؟', img: '🐋', correct: 'W', opts: ['W', 'M', 'V', 'H'], exp: 'كلمة Whale تبدأ بحرف W.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة آلة زيلوفون (Xylophone)؟', img: '🎶', correct: 'X', opts: ['X', 'Z', 'S', 'Y'], exp: 'كلمة Xylophone تبدأ بحرف X.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة يخت أو قارب (Yacht)؟', img: '🛥️', correct: 'Y', opts: ['Y', 'U', 'V', 'J'], exp: 'كلمة Yacht تبدأ بحرف Y.' },
    { q: 'ما هو الحرف الذي تبدأ به كلمة حمار وحشي (Zebra)؟', img: '🦓', correct: 'Z', opts: ['Z', 'S', 'X', 'C'], exp: 'كلمة Zebra تبدأ بحرف Z.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف A في الترتيب الأبجدي؟', img: '🔤', correct: 'B', opts: ['B', 'C', 'D', 'Z'], exp: 'الحرف الذي يلي A هو B.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف C في الترتيب الأبجدي؟', img: '🔤', correct: 'D', opts: ['D', 'E', 'B', 'F'], exp: 'الحرف الذي يلي C هو D.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف E في الترتيب الأبجدي؟', img: '🔤', correct: 'F', opts: ['F', 'G', 'D', 'H'], exp: 'الحرف الذي يلي E هو F.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف H في الترتيب الأبجدي؟', img: '🔤', correct: 'I', opts: ['I', 'J', 'G', 'K'], exp: 'الحرف الذي يلي H هو I.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف K في الترتيب الأبجدي؟', img: '🔤', correct: 'L', opts: ['L', 'M', 'J', 'N'], exp: 'الحرف الذي يلي K هو L.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف N في الترتيب الأبجدي؟', img: '🔤', correct: 'O', opts: ['O', 'P', 'M', 'Q'], exp: 'الحرف الذي يلي N هو O.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف P في الترتيب الأبجدي؟', img: '🔤', correct: 'Q', opts: ['Q', 'R', 'O', 'S'], exp: 'الحرف الذي يلي P هو Q.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف S في الترتيب الأبجدي؟', img: '🔤', correct: 'T', opts: ['T', 'U', 'R', 'V'], exp: 'الحرف الذي يلي S هو T.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف V في الترتيب الأبجدي؟', img: '🔤', correct: 'W', opts: ['W', 'X', 'U', 'Y'], exp: 'الحرف الذي يلي V هو W.' },
    { q: 'أي حرف يأتي مباشرة بعد الحرف X في الترتيب الأبجدي؟', img: '🔤', correct: 'Y', opts: ['Y', 'Z', 'W', 'V'], exp: 'الحرف الذي يلي X هو Y.' },
    { q: 'أي حرف يسبق الحرف B مباشرة؟', img: '🔤', correct: 'A', opts: ['A', 'C', 'D', 'E'], exp: 'الحرف السابق لـ B هو A.' },
    { q: 'أي حرف يسبق الحرف G مباشرة؟', img: '🔤', correct: 'F', opts: ['F', 'H', 'E', 'I'], exp: 'الحرف السابق لـ G هو F.' },
    { q: 'أي حرف يسبق الحرف M مباشرة؟', img: '🔤', correct: 'L', opts: ['L', 'N', 'K', 'O'], exp: 'الحرف السابق لـ M هو L.' },
    { q: 'أي حرف يسبق الحرف T مباشرة؟', img: '🔤', correct: 'S', opts: ['S', 'U', 'R', 'V'], exp: 'الحرف السابق لـ T هو S.' },
    { q: 'كم عدد الحروف في الأبجدية الإنجليزية بالكامل؟', img: '🔢', correct: '26', opts: ['26', '28', '24', '30'], exp: 'تتكون الأبجدية الإنجليزية من 26 حرفاً.' },
    { q: 'أي من الحروف التالية يُعتبر حرف علة (Vowel)؟', img: '🌟', correct: 'A', opts: ['A', 'B', 'C', 'D'], exp: 'حروف العلة الخمسة هي: A, E, I, O, U.' },
    { q: 'أي من الحروف التالية يُعتبر حرف علة (Vowel)؟', img: '🌟', correct: 'E', opts: ['E', 'K', 'T', 'P'], exp: 'حرف E من حروف العلة.' },
    { q: 'أي من الحروف التالية يُعتبر حرف علة (Vowel)؟', img: '🌟', correct: 'O', opts: ['O', 'B', 'M', 'R'], exp: 'حرف O من حروف العلة.' },
    { q: 'ما هو الشكل الصغير (Lowercase) لحرف G الكبير؟', img: '🔤', correct: 'g', opts: ['g', 'q', 'p', 'd'], exp: 'الحرف الصغير لـ G هو g.' },
    { q: 'ما هو الشكل الصغير (Lowercase) لحرف B الكبير؟', img: '🔤', correct: 'b', opts: ['b', 'd', 'p', 'q'], exp: 'الحرف الصغير لـ B هو b.' },
    { q: 'ما هو الشكل الصغير (Lowercase) لحرف D الكبير؟', img: '🔤', correct: 'd', opts: ['d', 'b', 'p', 'q'], exp: 'الحرف الصغير لـ D هو d.' },
    { q: 'ما هو الشكل الكبير (Uppercase) لحرف r الصغير؟', img: '🔤', correct: 'R', opts: ['R', 'P', 'B', 'D'], exp: 'الحرف الكبير لـ r هو R.' }
  ];
  games['حروف اللغة الإنجليزية A-Z بالتسلسل'] = alphabetData.map((d, i) => ({
    id: 1001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  // 2. تعلم أسماء الحيوانات بالإنجليزية
  const animalsList = [
    { name: 'Lion', ar: 'الأسد', img: '🦁', o: ['Lion', 'Tiger', 'Bear', 'Wolf'] },
    { name: 'Tiger', ar: 'النمر المخطط', img: '🐅', o: ['Tiger', 'Lion', 'Cheetah', 'Leopard'] },
    { name: 'Elephant', ar: 'الفيل الضخم', img: '🐘', o: ['Elephant', 'Hippo', 'Rhino', 'Giraffe'] },
    { name: 'Giraffe', ar: 'الزرافة طويلة الرقبة', img: '🦒', o: ['Giraffe', 'Zebra', 'Deer', 'Horse'] },
    { name: 'Zebra', ar: 'الحمار الوحشي المخطط', img: '🦓', o: ['Zebra', 'Donkey', 'Horse', 'Pony'] },
    { name: 'Monkey', ar: 'القرد المشاغب', img: '🐒', o: ['Monkey', 'Gorilla', 'Chimpanzee', 'Lemur'] },
    { name: 'Bear', ar: 'الدب القوي', img: '🐻', o: ['Bear', 'Wolf', 'Fox', 'Panda'] },
    { name: 'Panda', ar: 'دب الباندا المحبوب', img: '🐼', o: ['Panda', 'Bear', 'Koala', 'Raccoon'] },
    { name: 'Kangaroo', ar: 'الكنغر القافز', img: '🦘', o: ['Kangaroo', 'Koala', 'Rabbit', 'Deer'] },
    { name: 'Koala', ar: 'حيوان الكوالا الهادئ', img: '🐨', o: ['Koala', 'Panda', 'Sloth', 'Monkey'] },
    { name: 'Fox', ar: 'الثعلب الماكر', img: '🦊', o: ['Fox', 'Wolf', 'Dog', 'Hyena'] },
    { name: 'Wolf', ar: 'الذئب البري', img: '🐺', o: ['Wolf', 'Fox', 'Dog', 'Coyote'] },
    { name: 'Deer', ar: 'الغزال الرشيق', img: '🦌', o: ['Deer', 'Giraffe', 'Antelope', 'Goat'] },
    { name: 'Hippo', ar: 'فرس النهر (سيد قشطة)', img: '🦛', o: ['Hippo', 'Rhino', 'Elephant', 'Seal'] },
    { name: 'Rhino', ar: 'وحيد القرن', img: '🦏', o: ['Rhino', 'Hippo', 'Buffalo', 'Bull'] },
    { name: 'Gorilla', ar: 'الغوريلا الكبيرة', img: '🦍', o: ['Gorilla', 'Monkey', 'Chimpanzee', 'Baboon'] },
    { name: 'Cheetah', ar: 'الفهد الصياد الأسرع', img: '🐆', o: ['Cheetah', 'Leopard', 'Tiger', 'Lion'] },
    { name: 'Camel', ar: 'الجمل سفينة الصحراء', img: '🐪', o: ['Camel', 'Horse', 'Llama', 'Donkey'] },
    { name: 'Sloth', ar: 'الكسلان بطيء الحركة', img: '🦥', o: ['Sloth', 'Koala', 'Monkey', 'Panda'] },
    { name: 'Otter', ar: 'القضاعة المائية اللطيفة', img: '🦦', o: ['Otter', 'Beaver', 'Seal', 'Mink'] },
    { name: 'Beaver', ar: 'القندس باني السدود', img: '🦫', o: ['Beaver', 'Otter', 'Squirrel', 'Rat'] },
    { name: 'Hedgehog', ar: 'القنفذ الشوكي', img: '🦔', o: ['Hedgehog', 'Porcupine', 'Hamster', 'Mole'] },
    { name: 'Bat', ar: 'الخفاش الطائر ليلاً', img: '🦇', o: ['Bat', 'Bird', 'Owl', 'Moth'] },
    { name: 'Squirrel', ar: 'السنجاب جامع الجوز', img: '🐿️', o: ['Squirrel', 'Raccoon', 'Hamster', 'Mouse'] },
    { name: 'Raccoon', ar: 'حيوان الراكون اللطيف', img: '🦝', o: ['Raccoon', 'Badger', 'Skunk', 'Fox'] },
    { name: 'Skunk', ar: 'الظربان ذو الخط الأبيض', img: '🦨', o: ['Skunk', 'Raccoon', 'Badger', 'Ferret'] },
    { name: 'Badger', ar: 'الغرير الشجاع', img: '🦡', o: ['Badger', 'Beaver', 'Otter', 'Wolverine'] },
    { name: 'Hyena', ar: 'الضبع البري', img: '🐕', o: ['Hyena', 'Wolf', 'Jackal', 'Fox'] },
    { name: 'Chimpanzee', ar: 'الشمبانزي الذكي', img: '🦧', o: ['Chimpanzee', 'Gorilla', 'Monkey', 'Gibbon'] },
    { name: 'Antelope', ar: 'الظبي البري سريع الجري', img: '🦌', o: ['Antelope', 'Deer', 'Gazelle', 'Goat'] },
    { name: 'Buffalo', ar: 'الجاموس البري القوي', img: '🐃', o: ['Buffalo', 'Bull', 'Cow', 'Ox'] },
    { name: 'Yak', ar: 'حيوان الياك الجبلي ذو الفراء', img: '🐂', o: ['Yak', 'Bison', 'Buffalo', 'Bull'] },
    { name: 'Llama', ar: 'حيوان اللاما الصوفي', img: '🦙', o: ['Llama', 'Alpaca', 'Camel', 'Sheep'] },
    { name: 'Alpaca', ar: 'الألبكة ذات الصوف الناعم', img: '🦙', o: ['Alpaca', 'Llama', 'Sheep', 'Goat'] },
    { name: 'Leopard', ar: 'النمر المرقط المتسلق', img: '🐆', o: ['Leopard', 'Cheetah', 'Jaguar', 'Panther'] },
    { name: 'Polar Bear', ar: 'الدب القطبي الأبيض', img: '🐻‍❄️', o: ['Polar Bear', 'Brown Bear', 'Panda', 'Seal'] },
    { name: 'Red Panda', ar: 'الباندا الحمراء الصغيرة', img: '🐼', o: ['Red Panda', 'Fox', 'Raccoon', 'Squirrel'] },
    { name: 'Mole', ar: 'حيوان الخلد الحفار تحت الأرض', img: '🐾', o: ['Mole', 'Mouse', 'Hedgehog', 'Vole'] },
    { name: 'Meerkat', ar: 'حيوان السرقاط المراقب', img: '🐾', o: ['Meerkat', 'Weasel', 'Prairie Dog', 'Squirrel'] },
    { name: 'Armadillo', ar: 'المدرع ذو الدرع الواقي', img: '🛡️', o: ['Armadillo', 'Turtle', 'Pangolin', 'Hedgehog'] },
    { name: 'Walrus', ar: 'الفظ صاحب الأنياب الطويلة', img: '🦭', o: ['Walrus', 'Seal', 'Sea Lion', 'Whale'] },
    { name: 'Seal', ar: 'فقمة البحر الودودة', img: '🦭', o: ['Seal', 'Walrus', 'Dolphin', 'Otter'] },
    { name: 'Sea Lion', ar: 'أسد البحر اللعوب', img: '🦭', o: ['Sea Lion', 'Seal', 'Walrus', 'Otter'] },
    { name: 'Lemur', ar: 'حيوان الليمور ذو العيون الواسعة', img: '🐒', o: ['Lemur', 'Monkey', 'Raccoon', 'Koala'] },
    { name: 'Porcupine', ar: 'النيص ذو الأشواك الطويلة', img: '🦔', o: ['Porcupine', 'Hedgehog', 'Armadillo', 'Beaver'] },
    { name: 'Chameleon', ar: 'الحرباء متغيرة الألوان', img: '🦎', o: ['Chameleon', 'Lizard', 'Gecko', 'Iguana'] },
    { name: 'Crocodile', ar: 'التمساح ذو الفك القوي', img: '🐊', o: ['Crocodile', 'Alligator', 'Lizard', 'Snake'] },
    { name: 'Wild Boar', ar: 'الخنزير البري ذو الأنياب', img: '🐗', o: ['Wild Boar', 'Pig', 'Hippo', 'Rhino'] },
    { name: 'Platypus', ar: 'خلد الماء الفريد', img: '🦆', o: ['Platypus', 'Beaver', 'Duck', 'Otter'] },
    { name: 'Cheetah Cub', ar: 'شبل الفهد الصغير', img: '🐆', o: ['Cheetah Cub', 'Lion Cub', 'Puppy', 'Kitten'] }
  ];
  games['تعلم أسماء الحيوانات بالإنجليزية'] = animalsList.map((d, i) => ({
    id: 2001 + i,
    question: `ما اسم (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 3. تحدي تهجئة الكلمات البسيطة
  const spellingWords = [
    { word: 'Cat', mean: 'قطة', img: '🐱', o: ['Cat', 'Kat', 'Cet', 'Cot'] },
    { word: 'Dog', mean: 'كلب', img: '🐶', o: ['Dog', 'Dg', 'Doog', 'Dogg'] },
    { word: 'Sun', mean: 'شمس', img: '☀️', o: ['Sun', 'Son', 'San', 'Sn'] },
    { word: 'Book', mean: 'كتاب', img: '📖', o: ['Book', 'Boke', 'Buk', 'Bok'] },
    { word: 'Fish', mean: 'سمكة', img: '🐟', o: ['Fish', 'Fesh', 'Fsh', 'Fysh'] },
    { word: 'Ball', mean: 'كرة', img: '⚽', o: ['Ball', 'Bal', 'Bol', 'Boll'] },
    { word: 'Milk', mean: 'حليب', img: '🥛', o: ['Milk', 'Melk', 'Mlk', 'Milke'] },
    { word: 'Tree', mean: 'شجرة', img: '🌳', o: ['Tree', 'Tre', 'Tri', 'Trea'] },
    { word: 'Star', mean: 'نجمة', img: '⭐', o: ['Star', 'Ster', 'Staar', 'Stor'] },
    { word: 'Hand', mean: 'يد', img: '✋', o: ['Hand', 'Hend', 'Hnd', 'Hande'] },
    { word: 'Bird', mean: 'عصفور', img: '🐦', o: ['Bird', 'Burd', 'Brid', 'Berd'] },
    { word: 'Frog', mean: 'ضفدع', img: '🐸', o: ['Frog', 'Freg', 'Froog', 'Frg'] },
    { word: 'Duck', mean: 'بطة', img: '🦆', o: ['Duck', 'Duk', 'Dok', 'Dack'] },
    { word: 'Boat', mean: 'قارب', img: '⛵', o: ['Boat', 'Bote', 'Boot', 'Bot'] },
    { word: 'Ring', mean: 'خاتم', img: '💍', o: ['Ring', 'Reng', 'Ryng', 'Rng'] },
    { word: 'King', mean: 'ملك', img: '👑', o: ['King', 'Keng', 'Kyng', 'Kng'] },
    { word: 'Moon', mean: 'قمر', img: '🌙', o: ['Moon', 'Mune', 'Mone', 'Mon'] },
    { word: 'Rain', mean: 'مطر', img: '🌧️', o: ['Rain', 'Rane', 'Rayn', 'Ran'] },
    { word: 'Snow', mean: 'ثلج', img: '❄️', o: ['Snow', 'Sno', 'Snaow', 'Snw'] },
    { word: 'Cake', mean: 'كعكة', img: '🎂', o: ['Cake', 'Cak', 'Kaik', 'Kake'] },
    { word: 'Door', mean: 'باب', img: '🚪', o: ['Door', 'Dore', 'Dor', 'Doar'] },
    { word: 'Ship', mean: 'سفينة', img: '🚢', o: ['Ship', 'Shep', 'Schip', 'Shp'] },
    { word: 'Baby', mean: 'طفل رضيع', img: '👶', o: ['Baby', 'Babi', 'Babby', 'Bebi'] },
    { word: 'Desk', mean: 'مكتب دراسي', img: '🪑', o: ['Desk', 'Desck', 'Disc', 'Dsk'] },
    { word: 'Lamp', mean: 'مصباح', img: '💡', o: ['Lamp', 'Lemp', 'Lampe', 'Lmp'] },
    { word: 'Park', mean: 'حديقة عامة', img: '🏞️', o: ['Park', 'Parck', 'Perk', 'Prk'] },
    { word: 'Bell', mean: 'جرس', img: '🔔', o: ['Bell', 'Bel', 'Belle', 'Bal'] },
    { word: 'Fork', mean: 'شوكة طعام', img: '🍴', o: ['Fork', 'Forck', 'Forc', 'Frk'] },
    { word: 'Spoon', mean: 'ملعقة', img: '🥄', o: ['Spoon', 'Spun', 'Spone', 'Spon'] },
    { word: 'Wind', mean: 'رياح', img: '💨', o: ['Wind', 'Wynd', 'Wend', 'Wnd'] },
    { word: 'Nest', mean: 'عش طائر', img: '🪺', o: ['Nest', 'Nast', 'Nst', 'Nete'] },
    { word: 'Sock', mean: 'جورب', img: '🧦', o: ['Sock', 'Sok', 'Soc', 'Sak'] },
    { word: 'Leaf', mean: 'ورقة شجر', img: '🍃', o: ['Leaf', 'Leef', 'Lef', 'Leif'] },
    { word: 'Drum', mean: 'طبلة', img: '🥁', o: ['Drum', 'Dram', 'Drom', 'Drm'] },
    { word: 'Kite', mean: 'طائرة ورقية', img: '🪁', o: ['Kite', 'Kyte', 'Kit', 'Kiet'] },
    { word: 'Corn', mean: 'ذرة', img: '🌽', o: ['Corn', 'Korn', 'Cornn', 'Cron'] },
    { word: 'Goat', mean: 'ماعز', img: '🐐', o: ['Goat', 'Gote', 'Goot', 'Got'] },
    { word: 'Lion', mean: 'أسد', img: '🦁', o: ['Lion', 'Lyon', 'Lian', 'Lyen'] },
    { word: 'Crab', mean: 'سلطعون', img: '🦀', o: ['Crab', 'Kreb', 'Crabb', 'Cab'] },
    { word: 'Gold', mean: 'ذهب', img: '🪙', o: ['Gold', 'Goald', 'Golde', 'Gld'] },
    { word: 'Tent', mean: 'خيمة', img: '⛺', o: ['Tent', 'Tant', 'Tnt', 'Tente'] },
    { word: 'Flag', mean: 'علم دولة', img: '🚩', o: ['Flag', 'Flegg', 'Flagg', 'Flg'] },
    { word: 'Belt', mean: 'حزام', img: '🥋', o: ['Belt', 'Balt', 'Blt', 'Belte'] },
    { word: 'Wolf', mean: 'ذئب', img: '🐺', o: ['Wolf', 'Woolfe', 'Wulf', 'Wof'] },
    { word: 'Mask', mean: 'قناع', img: '🎭', o: ['Mask', 'Masck', 'Msk', 'Masc'] },
    { word: 'Bone', mean: 'عظمة', img: '🦴', o: ['Bone', 'Boan', 'Bown', 'Bon'] },
    { word: 'Rose', mean: 'وردة', img: '🌹', o: ['Rose', 'Roze', 'Roas', 'Ros'] },
    { word: 'Lock', mean: 'قفل', img: '🔒', o: ['Lock', 'Lok', 'Loak', 'Lck'] },
    { word: 'Camp', mean: 'مخيم', img: '🏕️', o: ['Camp', 'Kemp', 'Cemp', 'Cmp'] },
    { word: 'Blue', mean: 'لون أزرق', img: '🔵', o: ['Blue', 'Bloo', 'Blew', 'Blu'] }
  ];
  games['تحدي تهجئة الكلمات البسيطة'] = spellingWords.map((d, i) => ({
    id: 3001 + i,
    question: `ما هو التهجئة الصحيحة لكلمة (${d.mean}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.word,
    explanation: `التهجئة الصحيحة للكلمة هي '${d.word}'.`
  }));

  // 4. المترادفات والكلمات المتضادة بالإنجليزية
  const antonymsSynonyms = [
    { q: 'ما هو عكس كلمة كبير (Big) باللغة الإنجليزية؟', img: '🐘', correct: 'Small', opts: ['Small', 'Tall', 'Fast', 'Heavy'], exp: 'عكس Big (كبير) هو Small (صغير).' },
    { q: 'ما هو عكس كلمة سعيد (Happy) باللغة الإنجليزية؟', img: '😊', correct: 'Sad', opts: ['Sad', 'Angry', 'Glad', 'Tired'], exp: 'عكس Happy (سعيد) هو Sad (حزين).' },
    { q: 'ما هو عكس كلمة سريع (Fast) باللغة الإنجليزية؟', img: '🏃', correct: 'Slow', opts: ['Slow', 'Quick', 'Loud', 'Late'], exp: 'عكس Fast (سريع) هو Slow (بطيء).' },
    { q: 'ما هو عكس كلمة ساخن (Hot) باللغة الإنجليزية؟', img: '☀️', correct: 'Cold', opts: ['Cold', 'Warm', 'Cool', 'Dry'], exp: 'عكس Hot (حار) هو Cold (بارد).' },
    { q: 'ما هو عكس كلمة طويل (Tall) باللغة الإنجليزية؟', img: '🦒', correct: 'Short', opts: ['Short', 'Small', 'Thin', 'Fat'], exp: 'عكس Tall (طويل القامة) هو Short (قصير).' },
    { q: 'ما هو عكس كلمة للأعلى (Up) باللغة الإنجليزية؟', img: '⬆️', correct: 'Down', opts: ['Down', 'Left', 'Right', 'Back'], exp: 'عكس Up (أعلى) هو Down (أسفل).' },
    { q: 'ما هو عكس كلمة نظيف (Clean) باللغة الإنجليزية؟', img: '✨', correct: 'Dirty', opts: ['Dirty', 'Messy', 'Dark', 'Old'], exp: 'عكس Clean (نظيف) هو Dirty (متسخ).' },
    { q: 'ما هو عكس كلمة مفتوح (Open) باللغة الإنجليزية؟', img: '🚪', correct: 'Closed', opts: ['Closed', 'Locked', 'Broken', 'Hidden'], exp: 'عكس Open (مفتوح) هو Closed (مغلق).' },
    { q: 'ما هو عكس كلمة نهار (Day) باللغة الإنجليزية؟', img: '🌞', correct: 'Night', opts: ['Night', 'Evening', 'Morning', 'Dark'], exp: 'عكس Day (نهار) هو Night (ليل).' },
    { q: 'ما هو عكس كلمة ثقيل (Heavy) باللغة الإنجليزية؟', img: '🏋️', correct: 'Light', opts: ['Light', 'Soft', 'Thin', 'Easy'], exp: 'عكس Heavy (ثقيل) هو Light (خفيف).' },
    { q: 'ما هو عكس كلمة صلب (Hard) باللغة الإنجليزية؟', img: '🪨', correct: 'Soft', opts: ['Soft', 'Easy', 'Smooth', 'Weak'], exp: 'عكس Hard (صلب) هو Soft (ناعم أو لين).' },
    { q: 'ما هو عكس كلمة قوي (Strong) باللغة الإنجليزية؟', img: '💪', correct: 'Weak', opts: ['Weak', 'Sick', 'Tired', 'Small'], exp: 'عكس Strong (قوي) هو Weak (ضعيف).' },
    { q: 'ما هو عكس كلمة غني (Rich) باللغة الإنجليزية؟', img: '💰', correct: 'Poor', opts: ['Poor', 'Broke', 'Cheap', 'Sad'], exp: 'عكس Rich (غني) هو Poor (فقير).' },
    { q: 'ما هو عكس كلمة صوت عالٍ (Loud) باللغة الإنجليزية؟', img: '📢', correct: 'Quiet', opts: ['Quiet', 'Silent', 'Soft', 'Calm'], exp: 'عكس Loud (صاخب) هو Quiet (هادئ).' },
    { q: 'ما هو عكس كلمة مبكر (Early) باللغة الإنجليزية؟', img: '⏰', correct: 'Late', opts: ['Late', 'Slow', 'Old', 'Soon'], exp: 'عكس Early (مبكراً) هو Late (متأخراً).' },
    { q: 'ما هو عكس كلمة داخل (In) باللغة الإنجليزية؟', img: '📥', correct: 'Out', opts: ['Out', 'Down', 'Up', 'Off'], exp: 'عكس In (في الداخل) هو Out (في الخارج).' },
    { q: 'ما هو عكس كلمة ممتلئ (Full) باللغة الإنجليزية؟', img: '🥛', correct: 'Empty', opts: ['Empty', 'Light', 'Dry', 'Clean'], exp: 'عكس Full (ممتلئ) هو Empty (فارغ).' },
    { q: 'ما هو عكس كلمة مظلم (Dark) باللغة الإنجليزية؟', img: '🌑', correct: 'Light', opts: ['Light', 'Bright', 'White', 'Clear'], exp: 'عكس Dark (مظلم) هو Light أو Bright (مضيء).' },
    { q: 'ما هو عكس كلمة أمام (Front) باللغة الإنجليزية؟', img: '🚶', correct: 'Back', opts: ['Back', 'Behind', 'Side', 'End'], exp: 'عكس Front (أمام) هو Back (خلف).' },
    { q: 'ما هو عكس كلمة صحيح (Right) باللغة الإنجليزية؟', img: '✅', correct: 'Wrong', opts: ['Wrong', 'False', 'Bad', 'Left'], exp: 'عكس Right (صحيح) هو Wrong (خاطئ).' },
    { q: 'ما هو عكس كلمة قديم / عجوز (Old) باللغة الإنجليزية؟', img: '👴', correct: 'Young', opts: ['Young', 'New', 'Fresh', 'Little'], exp: 'عكس Old (عجوز) للأشخاص هو Young (شاب/صغير).' },
    { q: 'ما هو عكس كلمة مرتفع (High) باللغة الإنجليزية؟', img: '🏔️', correct: 'Low', opts: ['Low', 'Short', 'Deep', 'Flat'], exp: 'عكس High (مرتفع) هو Low (منخفض).' },
    { q: 'ما هو عكس كلمة قريب (Near) باللغة الإنجليزية؟', img: '📍', correct: 'Far', opts: ['Far', 'Away', 'Out', 'Distant'], exp: 'عكس Near (قريب) هو Far (بعيد).' },
    { q: 'ما هو عكس كلمة سميك (Thick) باللغة الإنجليزية؟', img: '📖', correct: 'Thin', opts: ['Thin', 'Flat', 'Skinny', 'Light'], exp: 'عكس Thick (سميك) هو Thin (نحيف/رقيق).' },
    { q: 'ما هو عكس كلمة حلو المذاق (Sweet) باللغة الإنجليزية؟', img: '🍬', correct: 'Sour', opts: ['Sour', 'Bitter', 'Salty', 'Spicy'], exp: 'عكس Sweet (حلو) هو Sour (حامض).' },
    { q: 'ما هو عكس كلمة جيد (Good) باللغة الإنجليزية؟', img: '👍', correct: 'Bad', opts: ['Bad', 'Worse', 'Evil', 'Poor'], exp: 'عكس Good (جيد) هو Bad (سيء).' },
    { q: 'ما هو عكس كلمة صادق / حقيقي (True) باللغة الإنجليزية؟', img: '✔️', correct: 'False', opts: ['False', 'Wrong', 'Lie', 'Fake'], exp: 'عكس True (حقيقي) هو False (خاطئ).' },
    { q: 'ما هو عكس كلمة آمن (Safe) باللغة الإنجليزية؟', img: '🛡️', correct: 'Dangerous', opts: ['Dangerous', 'Risky', 'Harmful', 'Bad'], exp: 'عكس Safe (آمن) هو Dangerous (خطير).' },
    { q: 'ما هو عكس كلمة بداية (Start) باللغة الإنجليزية؟', img: '🏁', correct: 'Finish', opts: ['Finish', 'End', 'Stop', 'Done'], exp: 'عكس Start (بداية) هو Finish أو End (نهاية).' },
    { q: 'ما هو عكس كلمة يدفع للأمام (Push) باللغة الإنجليزية؟', img: '🚪', correct: 'Pull', opts: ['Pull', 'Hold', 'Stop', 'Drop'], exp: 'عكس Push (يدفع) هو Pull (يسحب).' },
    { q: 'ما هو عكس كلمة يشتري (Buy) باللغة الإنجليزية؟', img: '🏷️', correct: 'Sell', opts: ['Sell', 'Pay', 'Give', 'Take'], exp: 'عكس Buy (يشتري) هو Sell (يبيع).' },
    { q: 'ما هو عكس كلمة يفوز (Win) باللغة الإنجليزية؟', img: '🏆', correct: 'Lose', opts: ['Lose', 'Fail', 'Drop', 'Quit'], exp: 'عكس Win (يفوز) هو Lose (يخسر).' },
    { q: 'ما هو عكس كلمة يبتسم (Smile) باللغة الإنجليزية؟', img: '😄', correct: 'Cry', opts: ['Cry', 'Frown', 'Sad', 'Angry'], exp: 'عكس Smile (يبتسم) هو Cry (يبكي).' },
    { q: 'ما هو عكس كلمة مبلل بالماء (Wet) باللغة الإنجليزية؟', img: '🌧️', correct: 'Dry', opts: ['Dry', 'Hot', 'Clean', 'Warm'], exp: 'عكس Wet (مبتل) هو Dry (جاف).' },
    { q: 'ما هو عكس كلمة نائم (Asleep) باللغة الإنجليزية؟', img: '😴', correct: 'Awake', opts: ['Awake', 'Up', 'Active', 'Alert'], exp: 'عكس Asleep (نائم) هو Awake (مستيقظ).' },
    { q: 'ما هو مرادف كلمة سعيد (Happy) باللغة الإنجليزية؟', img: '😊', correct: 'Glad', opts: ['Glad', 'Sad', 'Angry', 'Tired'], exp: 'كلمة Glad تعني مسرور، وهي مرادف لـ Happy.' },
    { q: 'ما هو مرادف كلمة صغير جداً (Tiny) بالإنجليزية؟', img: '🐜', correct: 'Small', opts: ['Small', 'Big', 'Huge', 'Tall'], exp: 'مرادف كلمة Tiny هو Small (صغير).' },
    { q: 'ما هو مرادف كلمة ضخم جداً (Huge) بالإنجليزية؟', img: '🐘', correct: 'Giant', opts: ['Giant', 'Tiny', 'Small', 'Short'], exp: 'مرادف Huge هو Giant أو Big (عملاق/ضخم).' },
    { q: 'ما هو مرادف كلمة سريع (Quick) بالإنجليزية؟', img: '🐆', correct: 'Fast', opts: ['Fast', 'Slow', 'Late', 'Heavy'], exp: 'مرادف Quick هو Fast (سريع).' },
    { q: 'ما هو مرادف كلمة ذكي (Smart) بالإنجليزية؟', img: '🧠', correct: 'Clever', opts: ['Clever', 'Silly', 'Slow', 'Quiet'], exp: 'مرادف Smart هو Clever (ذكي وماهر).' },
    { q: 'ما هو مرادف كلمة غاضب (Mad) بالإنجليزية؟', img: '😡', correct: 'Angry', opts: ['Angry', 'Happy', 'Calm', 'Sad'], exp: 'مرادف Mad هو Angry (غاضب).' },
    { q: 'ما هو مرادف كلمة سهل (Simple) بالإنجليزية؟', img: '🧩', correct: 'Easy', opts: ['Easy', 'Hard', 'Complex', 'Long'], exp: 'مرادف Simple هو Easy (بسيط/سهل).' },
    { q: 'ما هو مرادف كلمة جميلة (Pretty) بالإنجليزية؟', img: '🌸', correct: 'Beautiful', opts: ['Beautiful', 'Ugly', 'Old', 'Small'], exp: 'مرادف Pretty هو Beautiful (جميلة).' },
    { q: 'ما هو مرادف كلمة يصرخ (Shout) بالإنجليزية؟', img: '📢', correct: 'Yell', opts: ['Yell', 'Whisper', 'Talk', 'Listen'], exp: 'مرادف Shout هو Yell (يصرخ).' },
    { q: 'ما هو مرادف كلمة هادئ (Silent) بالإنجليزية؟', img: '🤫', correct: 'Quiet', opts: ['Quiet', 'Loud', 'Noisy', 'Active'], exp: 'مرادف Silent هو Quiet (صامت وهادئ).' },
    { q: 'ما هو مرادف كلمة هدية (Gift) بالإنجليزية؟', img: '🎁', correct: 'Present', opts: ['Present', 'Box', 'Toy', 'Game'], exp: 'مرادف Gift هو Present (هدية).' },
    { q: 'ما هو مرادف كلمة يبدأ (Start) بالإنجليزية؟', img: '🚀', correct: 'Begin', opts: ['Begin', 'End', 'Stop', 'Wait'], exp: 'مرادف Start هو Begin (يبدأ).' },
    { q: 'ما هو مرادف كلمة قمامة (Trash) بالإنجليزية؟', img: '🗑️', correct: 'Garbage', opts: ['Garbage', 'Clean', 'Dust', 'Box'], exp: 'مرادف Trash هو Garbage (قمامة/مهملات).' },
    { q: 'ما هو مرادف كلمة منتصف (Center) بالإنجليزية؟', img: '🎯', correct: 'Middle', opts: ['Middle', 'Edge', 'Corner', 'Side'], exp: 'مرادف Center هو Middle (الوسط أو المنتصف).' },
    { q: 'ما هو مرادف كلمة طفل (Kid) بالإنجليزية؟', img: '🧒', correct: 'Child', opts: ['Child', 'Baby', 'Adult', 'Man'], exp: 'مرادف Kid هو Child (طفل).' }
  ];
  games['المترادفات والكلمات المتضادة بالإنجليزية'] = antonymsSynonyms.map((d, i) => ({
    id: 4001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  // 5. الألوان الأساسية باللغة الإنجليزية
  const colorsList = [
    { name: 'Red', ar: 'الأحمر', img: '🔴', o: ['Red', 'Blue', 'Yellow', 'Green'] },
    { name: 'Blue', ar: 'الأزرق', img: '🔵', o: ['Blue', 'Red', 'Black', 'White'] },
    { name: 'Green', ar: 'الأخضر', img: '🟢', o: ['Green', 'Yellow', 'Orange', 'Purple'] },
    { name: 'Yellow', ar: 'الأصفر', img: '🟡', o: ['Yellow', 'Green', 'Red', 'Pink'] },
    { name: 'Orange', ar: 'البرتقالي', img: '🟠', o: ['Orange', 'Red', 'Brown', 'Yellow'] },
    { name: 'Purple', ar: 'البنفسجي (الأرجواني)', img: '🟣', o: ['Purple', 'Pink', 'Blue', 'Violet'] },
    { name: 'Pink', ar: 'الوردي (الزهري)', img: '🩷', o: ['Pink', 'Red', 'White', 'Purple'] },
    { name: 'Black', ar: 'الأسود', img: '🖤', o: ['Black', 'Brown', 'Gray', 'White'] },
    { name: 'White', ar: 'الأبيض', img: '🤍', o: ['White', 'Black', 'Silver', 'Yellow'] },
    { name: 'Brown', ar: 'البني', img: '🤎', o: ['Brown', 'Black', 'Orange', 'Gray'] },
    { name: 'Gray', ar: 'الرمادي', img: '🩶', o: ['Gray', 'Silver', 'Black', 'White'] },
    { name: 'Gold', ar: 'الذهبي اللامع', img: '🪙', o: ['Gold', 'Silver', 'Yellow', 'Bronze'] },
    { name: 'Silver', ar: 'الفضي اللامع', img: '🥈', o: ['Silver', 'Gold', 'Gray', 'White'] },
    { name: 'Violet', ar: 'البنفسجي الزهري', img: '🪻', o: ['Violet', 'Purple', 'Blue', 'Indigo'] },
    { name: 'Navy Blue', ar: 'الأزرق الداكن (الكحلي)', img: '🫐', o: ['Navy Blue', 'Sky Blue', 'Black', 'Teal'] },
    { name: 'Sky Blue', ar: 'الأزرق السماوي الفاتح', img: '🩵', o: ['Sky Blue', 'Navy Blue', 'Cyan', 'Turquoise'] },
    { name: 'Dark Green', ar: 'الأخضر الغامق', img: '🌲', o: ['Dark Green', 'Lime Green', 'Olive Green', 'Mint Green'] },
    { name: 'Lime Green', ar: 'الأخضر الليموني الفاتح', img: '🍋', o: ['Lime Green', 'Yellow', 'Dark Green', 'Emerald'] },
    { name: 'Peach', ar: 'اللون الخوخي الهادئ', img: '🍑', o: ['Peach', 'Orange', 'Pink', 'Coral'] },
    { name: 'Turquoise', ar: 'الفيروزي', img: '🩵', o: ['Turquoise', 'Teal', 'Cyan', 'Sky Blue'] },
    { name: 'Magenta', ar: 'الأحمر الأرجواني (ماجنتا)', img: '🌺', o: ['Magenta', 'Pink', 'Purple', 'Red'] },
    { name: 'Coral', ar: 'المرجاني المشرق', img: '🪸', o: ['Coral', 'Peach', 'Orange', 'Pink'] },
    { name: 'Maroon', ar: 'العنابي الداكن', img: '🪵', o: ['Maroon', 'Red', 'Brown', 'Purple'] },
    { name: 'Amber', ar: 'الكهرماني الدافئ', img: '🍯', o: ['Amber', 'Yellow', 'Gold', 'Orange'] },
    { name: 'Bronze', ar: 'البرونزي العتيق', img: '🥉', o: ['Bronze', 'Gold', 'Brown', 'Copper'] },
    { name: 'Beige', ar: 'البيج الفاتح', img: '🏷️', o: ['Beige', 'Cream', 'White', 'Brown'] },
    { name: 'Crimson', ar: 'القرمزي الزاهي', img: '🍓', o: ['Crimson', 'Ruby', 'Red', 'Maroon'] },
    { name: 'Lavender', ar: 'الخزامي (اللافندر)', img: '🪻', o: ['Lavender', 'Purple', 'Lilac', 'Pink'] },
    { name: 'Indigo', ar: 'النيلي العميق', img: '🌌', o: ['Indigo', 'Violet', 'Blue', 'Navy Blue'] },
    { name: 'Cyan', ar: 'السماوي المائي (السيان)', img: '💧', o: ['Cyan', 'Blue', 'Teal', 'Green'] },
    { name: 'Mint Green', ar: 'أخضر النعناع الهادئ', img: '🍃', o: ['Mint Green', 'Dark Green', 'Lime Green', 'Teal'] },
    { name: 'Olive Green', ar: 'الزيتوني', img: '🫒', o: ['Olive Green', 'Brown', 'Dark Green', 'Yellow'] },
    { name: 'Mustard', ar: 'لون الخردل الدافئ', img: '🌭', o: ['Mustard', 'Yellow', 'Gold', 'Brown'] },
    { name: 'Ruby', ar: 'الياقوتي الفاخر', img: '💎', o: ['Ruby', 'Red', 'Crimson', 'Garnet'] },
    { name: 'Emerald', ar: 'الزمردي النقي', img: '❇️', o: ['Emerald', 'Green', 'Mint', 'Jade'] },
    { name: 'Sapphire', ar: 'الياقوت الأزرق', img: '🔷', o: ['Sapphire', 'Blue', 'Navy', 'Indigo'] },
    { name: 'Teal', ar: 'الأزرق المخضر (التيل)', img: '💠', o: ['Teal', 'Turquoise', 'Cyan', 'Green'] },
    { name: 'Charcoal', ar: 'الفحمي الداكن', img: '⬛', o: ['Charcoal', 'Black', 'Gray', 'Dark Gray'] },
    { name: 'Cream', ar: 'الكريمي الناعم', img: '🍦', o: ['Cream', 'White', 'Beige', 'Yellow'] },
    { name: 'Khaki', ar: 'الكاكي العملي', img: '👖', o: ['Khaki', 'Beige', 'Brown', 'Olive'] },
    { name: 'Cherry Red', ar: 'أحمر الكرز الجميل', img: '🍒', o: ['Cherry Red', 'Red', 'Crimson', 'Pink'] },
    { name: 'Chocolate Brown', ar: 'بني الشوكولاتة اللذيذة', img: '🍫', o: ['Chocolate Brown', 'Brown', 'Dark Brown', 'Black'] },
    { name: 'Sunny Yellow', ar: 'أصفر مشرق كالشمس', img: '☀️', o: ['Sunny Yellow', 'Yellow', 'Gold', 'Orange'] },
    { name: 'Snow White', ar: 'أبيض ناصع كالثلج', img: '❄️', o: ['Snow White', 'White', 'Silver', 'Cream'] },
    { name: 'Jet Black', ar: 'أسود داكن كفحم الليل', img: '🐈‍⬛', o: ['Jet Black', 'Black', 'Charcoal', 'Dark Blue'] },
    { name: 'Lilac', ar: 'الليلكي الهادئ', img: '🌸', o: ['Lilac', 'Lavender', 'Purple', 'Pink'] },
    { name: 'Rust', ar: 'الصدئي المائل للبرتقالي', img: '🧱', o: ['Rust', 'Orange', 'Brown', 'Red'] },
    { name: 'Pastel Pink', ar: 'الوردي الباستيل الرقيق', img: '🎀', o: ['Pastel Pink', 'Pink', 'Rose', 'Magenta'] },
    { name: 'Royal Blue', ar: 'الأزرق الملكي الفخم', img: '👑', o: ['Royal Blue', 'Navy Blue', 'Blue', 'Indigo'] },
    { name: 'Golden Yellow', ar: 'الأصفر الذهبي البراق', img: '🌟', o: ['Golden Yellow', 'Gold', 'Yellow', 'Orange'] }
  ];
  games['الألوان الأساسية باللغة الإنجليزية'] = colorsList.map((d, i) => ({
    id: 5001 + i,
    question: `ما ترجمة اللون (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `اللون ${d.ar} يُسمى بالإنجليزية '${d.name}'.`
  }));

  // 6. الأرقام الإنجليزية من 1 إلى 20
  const numbersQuestions = [
    { q: 'كيف يُكتب الرقم (1) بالكلمات في الإنجليزية؟', img: '1️⃣', correct: 'One', opts: ['One', 'Two', 'Three', 'Four'], exp: 'الرقم 1 هو One.' },
    { q: 'كيف يُكتب الرقم (2) بالكلمات في الإنجليزية؟', img: '2️⃣', correct: 'Two', opts: ['Two', 'One', 'Three', 'Ten'], exp: 'الرقم 2 هو Two.' },
    { q: 'كيف يُكتب الرقم (3) بالكلمات في الإنجليزية؟', img: '3️⃣', correct: 'Three', opts: ['Three', 'Tree', 'Two', 'Four'], exp: 'الرقم 3 هو Three.' },
    { q: 'كيف يُكتب الرقم (4) بالكلمات في الإنجليزية؟', img: '4️⃣', correct: 'Four', opts: ['Four', 'Five', 'For', 'Three'], exp: 'الرقم 4 هو Four.' },
    { q: 'كيف يُكتب الرقم (5) بالكلمات في الإنجليزية؟', img: '5️⃣', correct: 'Five', opts: ['Five', 'Four', 'Six', 'Nine'], exp: 'الرقم 5 هو Five.' },
    { q: 'كيف يُكتب الرقم (6) بالكلمات في الإنجليزية؟', img: '6️⃣', correct: 'Six', opts: ['Six', 'Seven', 'Five', 'Eight'], exp: 'الرقم 6 هو Six.' },
    { q: 'كيف يُكتب الرقم (7) بالكلمات في الإنجليزية؟', img: '7️⃣', correct: 'Seven', opts: ['Seven', 'Six', 'Eight', 'Eleven'], exp: 'الرقم 7 هو Seven.' },
    { q: 'كيف يُكتب الرقم (8) بالكلمات في الإنجليزية؟', img: '8️⃣', correct: 'Eight', opts: ['Eight', 'Ate', 'Nine', 'Seven'], exp: 'الرقم 8 هو Eight.' },
    { q: 'كيف يُكتب الرقم (9) بالكلمات في الإنجليزية؟', img: '9️⃣', correct: 'Nine', opts: ['Nine', 'Eight', 'Ten', 'Five'], exp: 'الرقم 9 هو Nine.' },
    { q: 'كيف يُكتب الرقم (10) بالكلمات في الإنجليزية؟', img: '🔟', correct: 'Ten', opts: ['Ten', 'Two', 'Twelve', 'Twenty'], exp: 'الرقم 10 هو Ten.' },
    { q: 'كيف يُكتب الرقم (11) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Eleven', opts: ['Eleven', 'Twelve', 'Ten', 'Seven'], exp: 'الرقم 11 هو Eleven.' },
    { q: 'كيف يُكتب الرقم (12) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Twelve', opts: ['Twelve', 'Eleven', 'Twenty', 'Two'], exp: 'الرقم 12 هو Twelve.' },
    { q: 'كيف يُكتب الرقم (13) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Thirteen', opts: ['Thirteen', 'Thirty', 'Three', 'Fourteen'], exp: 'الرقم 13 هو Thirteen.' },
    { q: 'كيف يُكتب الرقم (14) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Fourteen', opts: ['Fourteen', 'Forty', 'Four', 'Fifteen'], exp: 'الرقم 14 هو Fourteen.' },
    { q: 'كيف يُكتب الرقم (15) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Fifteen', opts: ['Fifteen', 'Fifty', 'Five', 'Sixteen'], exp: 'الرقم 15 هو Fifteen.' },
    { q: 'كيف يُكتب الرقم (16) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Sixteen', opts: ['Sixteen', 'Sixty', 'Six', 'Seventeen'], exp: 'الرقم 16 هو Sixteen.' },
    { q: 'كيف يُكتب الرقم (17) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Seventeen', opts: ['Seventeen', 'Seventy', 'Seven', 'Eighteen'], exp: 'الرقم 17 هو Seventeen.' },
    { q: 'كيف يُكتب الرقم (18) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Eighteen', opts: ['Eighteen', 'Eighty', 'Eight', 'Nineteen'], exp: 'الرقم 18 هو Eighteen.' },
    { q: 'كيف يُكتب الرقم (19) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Nineteen', opts: ['Nineteen', 'Ninety', 'Nine', 'Twenty'], exp: 'الرقم 19 هو Nineteen.' },
    { q: 'كيف يُكتب الرقم (20) بالكلمات في الإنجليزية؟', img: '🔢', correct: 'Twenty', opts: ['Twenty', 'Twelve', 'Two', 'Ten'], exp: 'الرقم 20 هو Twenty.' },
    { q: 'كم عدد التفاحات في الصورة (🍎)؟', img: '🍎', correct: 'One', opts: ['One', 'Two', 'Three', 'Zero'], exp: 'توجد تفاحة واحدة: One.' },
    { q: 'كم عدد النجوم في الصورة (⭐⭐)؟', img: '⭐⭐', correct: 'Two', opts: ['Two', 'One', 'Three', 'Four'], exp: 'توجد نجمتان: Two.' },
    { q: 'كم عدد الكرات في الصورة (⚽⚽⚽)؟', img: '⚽⚽⚽', correct: 'Three', opts: ['Three', 'Two', 'Four', 'Five'], exp: 'توجد ثلاث كرات: Three.' },
    { q: 'كم عدد القلوب في الصورة (❤️❤️❤️❤️)؟', img: '❤️❤️❤️❤️', correct: 'Four', opts: ['Four', 'Three', 'Five', 'Six'], exp: 'توجد أربعة قلوب: Four.' },
    { q: 'كم عدد أصابع اليد الواحدة (✋)؟', img: '✋', correct: 'Five', opts: ['Five', 'Four', 'Six', 'Ten'], exp: 'في اليد الواحدة 5 أصابع: Five.' },
    { q: 'كم عدد السيارات في الصورة (🚗🚗🚗🚗🚗🚗)؟', img: '🚗🚗🚗🚗🚗🚗', correct: 'Six', opts: ['Six', 'Five', 'Seven', 'Eight'], exp: 'توجد 6 سيارات: Six.' },
    { q: 'كم عدد الأرانب في الصورة (🐰🐰🐰🐰🐰🐰🐰)؟', img: '🐰🐰🐰🐰🐰🐰🐰', correct: 'Seven', opts: ['Seven', 'Six', 'Eight', 'Nine'], exp: 'توجد 7 أرانب: Seven.' },
    { q: 'كم عدد الساعات في الصورة (⏰⏰⏰⏰⏰⏰⏰⏰)؟', img: '⏰⏰⏰⏰⏰⏰⏰⏰', correct: 'Eight', opts: ['Eight', 'Seven', 'Nine', 'Ten'], exp: 'توجد 8 ساعات: Eight.' },
    { q: 'كم عدد الأسماك في الصورة (🐟🐟🐟🐟🐟🐟🐟🐟🐟)؟', img: '🐟🐟🐟🐟🐟🐟🐟🐟🐟', correct: 'Nine', opts: ['Nine', 'Eight', 'Ten', 'Seven'], exp: 'توجد 9 أسماك: Nine.' },
    { q: 'كم عدد الأصابع في اليدين معاً (✋✋)؟', img: '👐', correct: 'Ten', opts: ['Ten', 'Five', 'Twenty', 'Eight'], exp: 'في اليدين معاً 10 أصابع: Ten.' },
    { q: 'أي رقم يأتي مباشرة بعد الرقم Nine (9)؟', img: '🔢', correct: 'Ten', opts: ['Ten', 'Eight', 'Eleven', 'Seven'], exp: 'بعد 9 يأتي 10 (Ten).' },
    { q: 'أي رقم يأتي مباشرة بعد الرقم Four (4)؟', img: '🔢', correct: 'Five', opts: ['Five', 'Three', 'Six', 'Two'], exp: 'بعد 4 يأتي 5 (Five).' },
    { q: 'أي رقم يأتي مباشرة بعد الرقم Fourteen (14)؟', img: '🔢', correct: 'Fifteen', opts: ['Fifteen', 'Thirteen', 'Sixteen', 'Twenty'], exp: 'بعد 14 يأتي 15 (Fifteen).' },
    { q: 'أي رقم يأتي مباشرة بعد الرقم Nineteen (19)؟', img: '🔢', correct: 'Twenty', opts: ['Twenty', 'Eighteen', 'Ten', 'Twelve'], exp: 'بعد 19 يأتي 20 (Twenty).' },
    { q: 'أي رقم يسبق الرقم Three (3) مباشرة؟', img: '🔢', correct: 'Two', opts: ['Two', 'One', 'Four', 'Five'], exp: 'قبل 3 يأتي 2 (Two).' },
    { q: 'أي رقم يسبق الرقم Seven (7) مباشرة؟', img: '🔢', correct: 'Six', opts: ['Six', 'Eight', 'Five', 'Four'], exp: 'قبل 7 يأتي 6 (Six).' },
    { q: 'أي رقم يسبق الرقم Eleven (11) مباشرة؟', img: '🔢', correct: 'Ten', opts: ['Ten', 'Twelve', 'Nine', 'Eight'], exp: 'قبل 11 يأتي 10 (Ten).' },
    { q: 'أي رقم يسبق الرقم Sixteen (16) مباشرة؟', img: '🔢', correct: 'Fifteen', opts: ['Fifteen', 'Seventeen', 'Fourteen', 'Twelve'], exp: 'قبل 16 يأتي 15 (Fifteen).' },
    { q: 'أي رقم يقع بين Six (6) و Eight (8)؟', img: '🔢', correct: 'Seven', opts: ['Seven', 'Five', 'Nine', 'Ten'], exp: 'بين 6 و 8 يقع الرقم 7 (Seven).' },
    { q: 'أي رقم يقع بين Twelve (12) و Fourteen (14)؟', img: '🔢', correct: 'Thirteen', opts: ['Thirteen', 'Eleven', 'Fifteen', 'Ten'], exp: 'بين 12 و 14 يقع الرقم 13 (Thirteen).' },
    { q: 'ما ناتج جمع (Two + Two = 2 + 2) باللغة الإنجليزية؟', img: '➕', correct: 'Four', opts: ['Four', 'Five', 'Three', 'Six'], exp: '2 + 2 = 4 (Four).' },
    { q: 'ما ناتج جمع (Three + Three = 3 + 3) باللغة الإنجليزية؟', img: '➕', correct: 'Six', opts: ['Six', 'Five', 'Seven', 'Eight'], exp: '3 + 3 = 6 (Six).' },
    { q: 'ما ناتج جمع (Five + Five = 5 + 5) بالإنجليزية؟', img: '➕', correct: 'Ten', opts: ['Ten', 'Nine', 'Eleven', 'Eight'], exp: '5 + 5 = 10 (Ten).' },
    { q: 'ما ناتج (Ten - Two = 10 - 2) بالإنجليزية؟', img: '➖', correct: 'Eight', opts: ['Eight', 'Nine', 'Seven', 'Six'], exp: '10 - 2 = 8 (Eight).' },
    { q: 'ما ناتج جمع (Seven + One = 7 + 1) بالإنجليزية؟', img: '➕', correct: 'Eight', opts: ['Eight', 'Nine', 'Seven', 'Six'], exp: '7 + 1 = 8 (Eight).' },
    { q: 'ما ناتج جمع (Four + Five = 4 + 5) بالإنجليزية؟', img: '➕', correct: 'Nine', opts: ['Nine', 'Eight', 'Ten', 'Seven'], exp: '4 + 5 = 9 (Nine).' },
    { q: 'ما ناتج جمع (Six + Six = 6 + 6) بالإنجليزية؟', img: '➕', correct: 'Twelve', opts: ['Twelve', 'Eleven', 'Thirteen', 'Ten'], exp: '6 + 6 = 12 (Twelve).' },
    { q: 'ما ناتج جمع (Ten + Five = 10 + 5) بالإنجليزية؟', img: '➕', correct: 'Fifteen', opts: ['Fifteen', 'Fourteen', 'Sixteen', 'Twenty'], exp: '10 + 5 = 15 (Fifteen).' },
    { q: 'ما ناتج جمع (Ten + Ten = 10 + 10) بالإنجليزية؟', img: '➕', correct: 'Twenty', opts: ['Twenty', 'Twelve', 'Fifteen', 'Nineteen'], exp: '10 + 10 = 20 (Twenty).' },
    { q: 'ما ناتج طرح (Nine - Three = 9 - 3) بالإنجليزية؟', img: '➖', correct: 'Six', opts: ['Six', 'Seven', 'Five', 'Three'], exp: '9 - 3 = 6 (Six).' }
  ];
  games['الأرقام الإنجليزية من 1 إلى 20'] = numbersQuestions.map((d, i) => ({
    id: 6001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  // 7. الحيوانات الأليفة والمزرعة بالإنجليزية
  const petsFarm = [
    { name: 'Cat', ar: 'القطة الأليفة', img: '🐱', o: ['Cat', 'Dog', 'Kitten', 'Rabbit'] },
    { name: 'Dog', ar: 'الكلب المخلص', img: '🐶', o: ['Dog', 'Cat', 'Puppy', 'Wolf'] },
    { name: 'Puppy', ar: 'الجرو الصغير (ابن الكلب)', img: '🐶', o: ['Puppy', 'Kitten', 'Dog', 'Bunny'] },
    { name: 'Kitten', ar: 'القطة الصغيرة اللطيفة', img: '🐱', o: ['Kitten', 'Puppy', 'Cat', 'Hamster'] },
    { name: 'Cow', ar: 'البقرة التي تعطينا الحليب', img: '🐮', o: ['Cow', 'Bull', 'Goat', 'Sheep'] },
    { name: 'Bull', ar: 'الثور القوي', img: '🐂', o: ['Bull', 'Cow', 'Ox', 'Horse'] },
    { name: 'Calf', ar: 'العجل الصغير (ابن البقرة)', img: '🐮', o: ['Calf', 'Foal', 'Lamb', 'Kid'] },
    { name: 'Horse', ar: 'الحصان السريع', img: '🐴', o: ['Horse', 'Donkey', 'Pony', 'Mule'] },
    { name: 'Foal', ar: 'المهر الصغير (ابن الحصان)', img: '🐴', o: ['Foal', 'Calf', 'Lamb', 'Horse'] },
    { name: 'Donkey', ar: 'الحمار الصبور', img: '🫏', o: ['Donkey', 'Horse', 'Mule', 'Zebra'] },
    { name: 'Sheep', ar: 'الخروف الصوفي', img: '🐑', o: ['Sheep', 'Lamb', 'Goat', 'Ram'] },
    { name: 'Lamb', ar: 'الحمل الصغير (ابن الخروف)', img: '🐑', o: ['Lamb', 'Kid', 'Calf', 'Sheep'] },
    { name: 'Goat', ar: 'الماعز النشيط', img: '🐐', o: ['Goat', 'Sheep', 'Deer', 'Cow'] },
    { name: 'Kid', ar: 'الجدي الصغير (ابن الماعز)', img: '🐐', o: ['Kid', 'Lamb', 'Calf', 'Goat'] },
    { name: 'Pig', ar: 'الخنزير في المزرعة', img: '🐷', o: ['Pig', 'Piglet', 'Boar', 'Cow'] },
    { name: 'Piglet', ar: 'صغير الخنزير', img: '🐷', o: ['Piglet', 'Pig', 'Puppy', 'Kitten'] },
    { name: 'Chicken', ar: 'الدجاجة عموماً', img: '🐔', o: ['Chicken', 'Hen', 'Rooster', 'Duck'] },
    { name: 'Rooster', ar: 'الديك صيّاح الصباح', img: '🐓', o: ['Rooster', 'Hen', 'Turkey', 'Duck'] },
    { name: 'Hen', ar: 'الدجاجة البياضة', img: '🐔', o: ['Hen', 'Rooster', 'Duck', 'Goose'] },
    { name: 'Chick', ar: 'الكتكوت الصغير الأصفر', img: '🐤', o: ['Chick', 'Duckling', 'Hen', 'Bird'] },
    { name: 'Duck', ar: 'البطة السابحة في الماء', img: '🦆', o: ['Duck', 'Goose', 'Swan', 'Duckling'] },
    { name: 'Duckling', ar: 'فرخ البط الصغير', img: '🦆', o: ['Duckling', 'Chick', 'Duck', 'Gosling'] },
    { name: 'Goose', ar: 'الإوزة البيضاء', img: '🪿', o: ['Goose', 'Duck', 'Swan', 'Turkey'] },
    { name: 'Turkey', ar: 'الديك الرومي الكبير', img: '🦃', o: ['Turkey', 'Rooster', 'Peacock', 'Hen'] },
    { name: 'Rabbit', ar: 'الأرنب السريع ذو الأذنين', img: '🐰', o: ['Rabbit', 'Bunny', 'Hare', 'Hamster'] },
    { name: 'Bunny', ar: 'الأرنب الصغير اللطيف', img: '🐰', o: ['Bunny', 'Rabbit', 'Hamster', 'Guinea Pig'] },
    { name: 'Hamster', ar: 'الهامستر الأليف ذو الخدود', img: '🐹', o: ['Hamster', 'Mouse', 'Rat', 'Guinea Pig'] },
    { name: 'Guinea Pig', ar: 'خنزير غينيا الأليف', img: '🐹', o: ['Guinea Pig', 'Hamster', 'Rabbit', 'Chinchilla'] },
    { name: 'Parrot', ar: 'الببغاء المتكلم الملون', img: '🦜', o: ['Parrot', 'Canary', 'Pigeon', 'Owl'] },
    { name: 'Goldfish', ar: 'السمكة الذهبية في الحوض', img: '🐠', o: ['Goldfish', 'Tuna', 'Shark', 'Catfish'] },
    { name: 'Canary', ar: 'طائر الكناري المغرد الأصفر', img: '🐤', o: ['Canary', 'Parrot', 'Sparrow', 'Robin'] },
    { name: 'Pigeon', ar: 'الحمامة الوديعة', img: '🐦', o: ['Pigeon', 'Dove', 'Crow', 'Seagull'] },
    { name: 'Pony', ar: 'المهر القصير اللطيف', img: '🐴', o: ['Pony', 'Horse', 'Donkey', 'Zebra'] },
    { name: 'Mule', ar: 'البغل القوي في العمل', img: '🫏', o: ['Mule', 'Donkey', 'Horse', 'Yak'] },
    { name: 'Barn Cat', ar: 'قط المزرعة الصياد للفئران', img: '🐈', o: ['Barn Cat', 'Dog', 'Tiger', 'Fox'] },
    { name: 'Dairy Cow', ar: 'بقرة الحليب الحلوب', img: '🐄', o: ['Dairy Cow', 'Bull', 'Goat', 'Sheep'] },
    { name: 'Woolly Sheep', ar: 'النعجة ذات الصوف الكثيف', img: '🐑', o: ['Woolly Sheep', 'Goat', 'Llama', 'Alpaca'] },
    { name: 'Farm Dog', ar: 'كلب المزرعة الحارس للماشية', img: '🐕', o: ['Farm Dog', 'Wolf', 'Fox', 'Jackal'] },
    { name: 'Farm Goat', ar: 'ماعز المزرعة الممتع', img: '🐐', o: ['Farm Goat', 'Sheep', 'Deer', 'Cow'] },
    { name: 'White Rabbit', ar: 'الأرنب الأبيض الأليف', img: '🐇', o: ['White Rabbit', 'Hamster', 'Cat', 'Dove'] },
    { name: 'Fluffy Chick', ar: 'الصوص الصغير ذو الريش الناعم', img: '🐥', o: ['Fluffy Chick', 'Duckling', 'Bird', 'Hen'] },
    { name: 'Barn Owl', ar: 'بومة المزرعة الساهرة ليلاً', img: '🦉', o: ['Barn Owl', 'Hawk', 'Eagle', 'Bat'] },
    { name: 'Farm Mouse', ar: 'فأر المزرعة الصغير', img: '🐁', o: ['Farm Mouse', 'Rat', 'Hamster', 'Mole'] },
    { name: 'Goose flock', ar: 'سرب الإوز بالمزرعة', img: '🪿', o: ['Goose flock', 'Duck group', 'Birds', 'Hens'] },
    { name: 'Farm Horse', ar: 'حصان المزرعة الرائع', img: '🐎', o: ['Farm Horse', 'Donkey', 'Cow', 'Camel'] },
    { name: 'Pet Turtle', ar: 'السلحفاة المنزلية الهادئة', img: '🐢', o: ['Pet Turtle', 'Lizard', 'Frog', 'Fish'] },
    { name: 'Farm Pig', ar: 'خنزير المزرعة الوردي', img: '🐖', o: ['Farm Pig', 'Cow', 'Sheep', 'Goat'] },
    { name: 'Country Rooster', ar: 'ديك القرية الملون', img: '🐓', o: ['Country Rooster', 'Hen', 'Duck', 'Goose'] },
    { name: 'Little Duck', ar: 'البطة الصغيرة السابحة', img: '🦆', o: ['Little Duck', 'Swan', 'Pelican', 'Goose'] },
    { name: 'Farm Turkey', ar: 'حبش المزرعة ذو الذيل المروحي', img: '🦃', o: ['Farm Turkey', 'Rooster', 'Peacock', 'Hen'] }
  ];
  games['الحيوانات الأليفة والمزرعة بالإنجليزية'] = petsFarm.map((d, i) => ({
    id: 7001 + i,
    question: `ما اسم (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} يُسمى بالإنجليزية '${d.name}'.`
  }));

  // 8. الطيور والمخلوقات البحرية بالإنجليزية
  const birdsSea = [
    { name: 'Eagle', ar: 'النسر القوي ملك الطيور', img: '🦅', o: ['Eagle', 'Falcon', 'Hawk', 'Owl'] },
    { name: 'Falcon', ar: 'الصقر السريع الجارح', img: '🦅', o: ['Falcon', 'Eagle', 'Owl', 'Seagull'] },
    { name: 'Owl', ar: 'البومة ذات النظر الليلي الثاقب', img: '🦉', o: ['Owl', 'Bat', 'Eagle', 'Parrot'] },
    { name: 'Flamingo', ar: 'طيور الفلامنجو الوردية', img: '🦩', o: ['Flamingo', 'Swan', 'Stork', 'Pelican'] },
    { name: 'Peacock', ar: 'الطاووس ذو الريش البديع', img: '🦚', o: ['Peacock', 'Turkey', 'Parrot', 'Rooster'] },
    { name: 'Penguin', ar: 'البطريق السابح في الجليد', img: '🐧', o: ['Penguin', 'Puffin', 'Seagull', 'Duck'] },
    { name: 'Swan', ar: 'البجعة البيضاء الأنيقة', img: '🦢', o: ['Swan', 'Goose', 'Duck', 'Flamingo'] },
    { name: 'Parrot', ar: 'الببغاء الذكي الملون', img: '🦜', o: ['Parrot', 'Toucan', 'Canary', 'Pigeon'] },
    { name: 'Toucan', ar: 'طائر الطوقان ذو المنقار الكبير', img: '🦜', o: ['Toucan', 'Parrot', 'Woodpecker', 'Pelican'] },
    { name: 'Woodpecker', ar: 'نقار الخشب البارع', img: '🐦', o: ['Woodpecker', 'Sparrow', 'Robin', 'Kingfisher'] },
    { name: 'Hummingbird', ar: 'طائر الطنان فائق السرعة', img: '🐦', o: ['Hummingbird', 'Canary', 'Bee', 'Sparrow'] },
    { name: 'Seagull', ar: 'نورس البحر المحلق فوق الشاطئ', img: '🐦', o: ['Seagull', 'Pelican', 'Albatross', 'Duck'] },
    { name: 'Pelican', ar: 'طائر البجع صاحب الجراب المنقاري', img: '🪿', o: ['Pelican', 'Stork', 'Seagull', 'Flamingo'] },
    { name: 'Stork', ar: 'طائر اللقلق طويل الأرجل', img: '🪿', o: ['Stork', 'Crane', 'Heron', 'Flamingo'] },
    { name: 'Pigeon', ar: 'الحمامة رمز السلام', img: '🐦', o: ['Pigeon', 'Crow', 'Sparrow', 'Robin'] },
    { name: 'Crow', ar: 'الغراب الأسود الذكي', img: '🐦‍⬛', o: ['Crow', 'Raven', 'Pigeon', 'Hawk'] },
    { name: 'Ostrich', ar: 'النعامة أسرع طائر عداء', img: '🐦', o: ['Ostrich', 'Emu', 'Flamingo', 'Turkey'] },
    { name: 'Sparrow', ar: 'العصفور الدوري الصغير', img: '🐦', o: ['Sparrow', 'Robin', 'Canary', 'Finches'] },
    { name: 'Robin', ar: 'أبو الحناء ذو الصدر الأحمر', img: '🐦', o: ['Robin', 'Sparrow', 'Bluebird', 'Swallow'] },
    { name: 'Kingfisher', ar: 'الرفراف صياد الأسماك الماهر', img: '🐦', o: ['Kingfisher', 'Hummingbird', 'Toucan', 'Woodpecker'] },
    { name: 'Blue Jay', ar: 'طائر القيق الأزرق الجذاب', img: '🐦', o: ['Blue Jay', 'Bluebird', 'Parrot', 'Robin'] },
    { name: 'Canary', ar: 'الكناري صاحب التغريد العذب', img: '🐤', o: ['Canary', 'Chaffinch', 'Sparrow', 'Goldfinch'] },
    { name: 'Hawk', ar: 'الصقر الحوام (الباشق)', img: '🦅', o: ['Hawk', 'Eagle', 'Falcon', 'Kite'] },
    { name: 'Duck', ar: 'البطة المائية اللطيفة', img: '🦆', o: ['Duck', 'Goose', 'Swan', 'Pelican'] },
    { name: 'Crane', ar: 'طائر الكركي الجميل', img: '🦩', o: ['Crane', 'Heron', 'Stork', 'Flamingo'] },
    { name: 'Dolphin', ar: 'الدولفين الصديق الودود للإنسان', img: '🐬', o: ['Dolphin', 'Whale', 'Shark', 'Seal'] },
    { name: 'Whale', ar: 'الحوت العملاق سيد المحيطات', img: '🐋', o: ['Whale', 'Dolphin', 'Shark', 'Walrus'] },
    { name: 'Blue Whale', ar: 'الحوت الأزرق أكبر كائن حي', img: '🐳', o: ['Blue Whale', 'Humpback Whale', 'Orca', 'Dolphin'] },
    { name: 'Shark', ar: 'سمكة القرش ذات الزعنفة المثلثة', img: '🦈', o: ['Shark', 'Whale', 'Dolphin', 'Swordfish'] },
    { name: 'Octopus', ar: 'الأخطبوط ذو الأذرع الثمانية', img: '🐙', o: ['Octopus', 'Squid', 'Jellyfish', 'Crab'] },
    { name: 'Squid', ar: 'الحبار سريع السباحة', img: '🦑', o: ['Squid', 'Octopus', 'Cuttlefish', 'Eel'] },
    { name: 'Sea Turtle', ar: 'سلحفاة البحر المعمرة', img: '🐢', o: ['Sea Turtle', 'Tortoise', 'Crab', 'Seal'] },
    { name: 'Crab', ar: 'السلطعون ذو الكماشتين', img: '🦀', o: ['Crab', 'Lobster', 'Shrimp', 'Clam'] },
    { name: 'Lobster', ar: 'الكركند (الاستاكوزا البحرية)', img: '🦞', o: ['Lobster', 'Crab', 'Crayfish', 'Shrimp'] },
    { name: 'Shrimp', ar: 'الجمبري (القريدس) الصغير', img: '🦐', o: ['Shrimp', 'Prawn', 'Crab', 'Lobster'] },
    { name: 'Starfish', ar: 'نجم البحر ذو الأشكال الخماسية', img: '⭐', o: ['Starfish', 'Jellyfish', 'Sea Urchin', 'Coral'] },
    { name: 'Seahorse', ar: 'فرس البحر ذو الذيل الملتف', img: '🐴', o: ['Seahorse', 'Pipefish', 'Eel', 'Goldfish'] },
    { name: 'Jellyfish', ar: 'قنديل البحر الشفاف المتوهج', img: '🪼', o: ['Jellyfish', 'Anemone', 'Octopus', 'Squid'] },
    { name: 'Stingray', ar: 'سمكة الراي اللاسعة المسطحة', img: '🐡', o: ['Stingray', 'Manta Ray', 'Flounder', 'Shark'] },
    { name: 'Clownfish', ar: 'سمكة المهرج (نيمو الملونة)', img: '🐠', o: ['Clownfish', 'Angelfish', 'Goldfish', 'Tuna'] },
    { name: 'Swordfish', ar: 'سمكة أبو سيف ذات السيف الحاد', img: '🐟', o: ['Swordfish', 'Sailfish', 'Marlin', 'Shark'] },
    { name: 'Seal', ar: 'فقمة البحر الوديعة', img: '🦭', o: ['Seal', 'Sea Lion', 'Walrus', 'Otter'] },
    { name: 'Sea Lion', ar: 'أسد البحر الصاخب', img: '🦭', o: ['Sea Lion', 'Seal', 'Walrus', 'Polar Bear'] },
    { name: 'Walrus', ar: 'حيوان الفظ ذو الأنياب العاجية', img: '🦭', o: ['Walrus', 'Seal', 'Hippo', 'Whale'] },
    { name: 'Coral', ar: 'الشعاب المرجانية الملونة البديعة', img: '🪸', o: ['Coral', 'Seaweed', 'Anemone', 'Sponge'] },
    { name: 'Oyster', ar: 'محار البحر الذي يخبئ اللؤلؤ', img: '🦪', o: ['Oyster', 'Clam', 'Mussel', 'Scallop'] },
    { name: 'Clam', ar: 'صدفة المحار ذات المصراعين', img: '🦪', o: ['Clam', 'Oyster', 'Snail', 'Conch'] },
    { name: 'Eel', ar: 'ثعبان البحر الانسيابي', img: '🐍', o: ['Eel', 'Snake', 'Fish', 'Worm'] },
    { name: 'Sea Otter', ar: 'قضاعة البحر السابحة على ظهرها', img: '🦦', o: ['Sea Otter', 'Beaver', 'Seal', 'Platypus'] },
    { name: 'Pufferfish', ar: 'السمكة المنتفخة كبالون شوكي', img: '🐡', o: ['Pufferfish', 'Clownfish', 'Angelfish', 'Starfish'] }
  ];
  games['الطيور والمخلوقات البحرية بالإنجليزية'] = birdsSea.map((d, i) => ({
    id: 8001 + i,
    question: `ما اسم (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية هو '${d.name}'.`
  }));

  // 9. أسماء الفواكه والخضار بالإنجليزية
  const fruitsVeggies = [
    { name: 'Apple', ar: 'تفاحة حمراء مقرمشة', img: '🍎', o: ['Apple', 'Orange', 'Banana', 'Peach'] },
    { name: 'Green Apple', ar: 'تفاحة خضراء منعشة', img: '🍏', o: ['Green Apple', 'Pear', 'Lime', 'Kiwi'] },
    { name: 'Banana', ar: 'موزة صفراء حلوة', img: '🍌', o: ['Banana', 'Lemon', 'Mango', 'Corn'] },
    { name: 'Orange', ar: 'برتقالة مليئة بالعصير', img: '🍊', o: ['Orange', 'Tangerine', 'Peach', 'Apricot'] },
    { name: 'Strawberry', ar: 'فراولة حمراء لذيذة', img: '🍓', o: ['Strawberry', 'Raspberry', 'Cherry', 'Grape'] },
    { name: 'Grape', ar: 'عنب عنقودي حلو', img: '🍇', o: ['Grape', 'Blueberry', 'Plum', 'Olive'] },
    { name: 'Watermelon', ar: 'بطيخ صيفي كبير ومنعش', img: '🍉', o: ['Watermelon', 'Melon', 'Cantaloupe', 'Papaya'] },
    { name: 'Mango', ar: 'مانجو استوائية شهية', img: '🥭', o: ['Mango', 'Peach', 'Papaya', 'Apricot'] },
    { name: 'Pineapple', ar: 'أناناس ذو تاج ورقي', img: '🍍', o: ['Pineapple', 'Coconut', 'Melon', 'Banana'] },
    { name: 'Peach', ar: 'خوخ مخملي الملمس', img: '🍑', o: ['Peach', 'Plum', 'Apricot', 'Apple'] },
    { name: 'Cherry', ar: 'كرز أحمر ثنائي الحبة', img: '🍒', o: ['Cherry', 'Berry', 'Grape', 'Strawberry'] },
    { name: 'Pear', ar: 'كمثرى لذيذة الشكل', img: '🍐', o: ['Pear', 'Avocado', 'Apple', 'Guava'] },
    { name: 'Lemon', ar: 'ليمون حامض أصفر', img: '🍋', o: ['Lemon', 'Lime', 'Orange', 'Banana'] },
    { name: 'Lime', ar: 'ليمون أخضر صغير', img: '🍋', o: ['Lime', 'Lemon', 'Apple', 'Kiwi'] },
    { name: 'Kiwi', ar: 'كيوي بني من الخارج وأخضر من الداخل', img: '🥝', o: ['Kiwi', 'Avocado', 'Coconut', 'Pear'] },
    { name: 'Blueberry', ar: 'توت أزرق مفيد وصحي', img: '🫐', o: ['Blueberry', 'Grape', 'Plum', 'Blackberry'] },
    { name: 'Coconut', ar: 'جوز الهند الصلب ذو الماء الحلو', img: '🥥', o: ['Coconut', 'Walnut', 'Kiwi', 'Melon'] },
    { name: 'Pomegranate', ar: 'رمان مليء بالحبوب الياقوتية', img: '🍎', o: ['Pomegranate', 'Apple', 'Cherry', 'Beetroot'] },
    { name: 'Fig', ar: 'تين حلو المذاق', img: '🫐', o: ['Fig', 'Date', 'Plum', 'Olive'] },
    { name: 'Plum', ar: 'برقوق بنفسجي شهي', img: '🫐', o: ['Plum', 'Grape', 'Peach', 'Cherry'] },
    { name: 'Apricot', ar: 'مشمش برتقالي ناعم', img: '🍑', o: ['Apricot', 'Peach', 'Orange', 'Mango'] },
    { name: 'Papaya', ar: 'بابايا استوائية برتقالية', img: '🥭', o: ['Papaya', 'Mango', 'Melon', 'Guava'] },
    { name: 'Melon', ar: 'شمام (بطيخ أصفر) حلو', img: '🍈', o: ['Melon', 'Watermelon', 'Cantaloupe', 'Squash'] },
    { name: 'Raspberry', ar: 'توت العليق الأحمر', img: '🍓', o: ['Raspberry', 'Strawberry', 'Blackberry', 'Cranberry'] },
    { name: 'Carrot', ar: 'جزر برتقالي يقوي النظر', img: '🥕', o: ['Carrot', 'Radish', 'Pepper', 'Sweet Potato'] },
    { name: 'Tomato', ar: 'طماطم حمراء طازجة للسلطة', img: '🍅', o: ['Tomato', 'Apple', 'Pepper', 'Pomegranate'] },
    { name: 'Potato', ar: 'بطاطس شهية للقلي والطهي', img: '🥔', o: ['Potato', 'Sweet Potato', 'Turnip', 'Ginger'] },
    { name: 'Cucumber', ar: 'خيار أخضر بارد ومنعش', img: '🥒', o: ['Cucumber', 'Zucchini', 'Celery', 'Pepper'] },
    { name: 'Broccoli', ar: 'بروكلي أخضر شبيه بالشجرة الصغيرة', img: '🥦', o: ['Broccoli', 'Cauliflower', 'Cabbage', 'Lettuce'] },
    { name: 'Onion', ar: 'بصل يضيف نكهة للطعام', img: '🧅', o: ['Onion', 'Garlic', 'Turnip', 'Shallot'] },
    { name: 'Garlic', ar: 'ثوم صحي ومفيد', img: '🧄', o: ['Garlic', 'Onion', 'Ginger', 'Mushroom'] },
    { name: 'Corn', ar: 'ذرة صفراء مسلوقة أو مشوية', img: '🌽', o: ['Corn', 'Banana', 'Carrot', 'Wheat'] },
    { name: 'Lettuce', ar: 'خس أخضر مقرمش', img: '🥬', o: ['Lettuce', 'Cabbage', 'Spinach', 'Celery'] },
    { name: 'Bell Pepper', ar: 'فلفل رومي حلو ملون', img: '🫑', o: ['Bell Pepper', 'Chili', 'Tomato', 'Apple'] },
    { name: 'Chili Pepper', ar: 'فلفل أحمر حار وحارق', img: '🌶️', o: ['Chili Pepper', 'Bell Pepper', 'Carrot', 'Tomato'] },
    { name: 'Eggplant', ar: 'باذنجان بنفسجي لامع', img: '🍆', o: ['Eggplant', 'Zucchini', 'Cucumber', 'Plum'] },
    { name: 'Green Peas', ar: 'بازلاء خضراء في القرون', img: '🫛', o: ['Green Peas', 'Beans', 'Corn', 'Grapes'] },
    { name: 'Mushroom', ar: 'فطر (عيش الغراب) المظلي', img: '🍄', o: ['Mushroom', 'Truffle', 'Potato', 'Garlic'] },
    { name: 'Pumpkin', ar: 'قرع عسلي برتقالي كبير', img: '🎃', o: ['Pumpkin', 'Melon', 'Squash', 'Watermelon'] },
    { name: 'Cabbage', ar: 'ملفوف (كرنب) دائري الأوراق', img: '🥬', o: ['Cabbage', 'Lettuce', 'Broccoli', 'Spinach'] },
    { name: 'Spinach', ar: 'سبانخ خضراء غنية بالحديد', img: '🥬', o: ['Spinach', 'Lettuce', 'Kale', 'Mint'] },
    { name: 'Radish', ar: 'فجل أحمر ذو ذيل أبيض', img: '🥗', o: ['Radish', 'Turnip', 'Beetroot', 'Carrot'] },
    { name: 'Zucchini', ar: 'كوسة خضراء لذيذة للطبخ', img: '🥒', o: ['Zucchini', 'Cucumber', 'Eggplant', 'Celery'] },
    { name: 'Beetroot', ar: 'شمندر (بنجر) أحمر داكن', img: '🍠', o: ['Beetroot', 'Radish', 'Sweet Potato', 'Turnip'] },
    { name: 'Sweet Potato', ar: 'بطاطا حلوة برتقالية مشوية', img: '🍠', o: ['Sweet Potato', 'Potato', 'Carrot', 'Yam'] },
    { name: 'Celery', ar: 'كرفس ذو سيقان خضراء مقرمشة', img: '🥬', o: ['Celery', 'Cucumber', 'Asparagus', 'Leek'] },
    { name: 'Cauliflower', ar: 'قرنبيط أبيض كريمي', img: '🥦', o: ['Cauliflower', 'Broccoli', 'Cabbage', 'Mushroom'] },
    { name: 'Ginger', ar: 'زنجبيل ذو نكهة قوية منعشة', img: '🫚', o: ['Ginger', 'Garlic', 'Potato', 'Turmeric'] },
    { name: 'Avocado', ar: 'أفوكادو صحي وغني بالدهون المفيدة', img: '🥑', o: ['Avocado', 'Pear', 'Kiwi', 'Mango'] },
    { name: 'Watercress', ar: 'جرجير طازج ذو طعم مميز', img: '🥗', o: ['Watercress', 'Spinach', 'Lettuce', 'Mint'] }
  ];
  games['أسماء الفواكه والخضار بالإنجليزية'] = fruitsVeggies.map((d, i) => ({
    id: 9001 + i,
    question: `ما اسم (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 10. أيام الأسبوع والشهور بالإنجليزية
  const daysMonths = [
    { q: 'ما اسم يوم (الأحد) باللغة الإنجليزية؟', img: '📅', correct: 'Sunday', opts: ['Sunday', 'Monday', 'Friday', 'Saturday'], exp: 'الأحد يعني Sunday.' },
    { q: 'ما اسم يوم (الاثنين) باللغة الإنجليزية؟', img: '📅', correct: 'Monday', opts: ['Monday', 'Sunday', 'Tuesday', 'Friday'], exp: 'الاثنين يعني Monday.' },
    { q: 'ما اسم يوم (الثلاثاء) باللغة الإنجليزية؟', img: '📅', correct: 'Tuesday', opts: ['Tuesday', 'Thursday', 'Wednesday', 'Monday'], exp: 'الثلاثاء يعني Tuesday.' },
    { q: 'ما اسم يوم (الأربعاء) باللغة الإنجليزية؟', img: '📅', correct: 'Wednesday', opts: ['Wednesday', 'Thursday', 'Tuesday', 'Friday'], exp: 'الأربعاء يعني Wednesday.' },
    { q: 'ما اسم يوم (الخميس) باللغة الإنجليزية؟', img: '📅', correct: 'Thursday', opts: ['Thursday', 'Tuesday', 'Friday', 'Saturday'], exp: 'الخميس يعني Thursday.' },
    { q: 'ما اسم يوم (الجمعة) باللغة الإنجليزية؟', img: '📅', correct: 'Friday', opts: ['Friday', 'Saturday', 'Thursday', 'Monday'], exp: 'الجمعة يعني Friday.' },
    { q: 'ما اسم يوم (السبت) باللغة الإنجليزية؟', img: '📅', correct: 'Saturday', opts: ['Saturday', 'Sunday', 'Friday', 'Thursday'], exp: 'السبت يعني Saturday.' },
    { q: 'كم عدد أيام الأسبوع بالكامل في الإنجليزية؟', img: '🗓️', correct: 'Seven (7)', opts: ['Seven (7)', 'Five (5)', 'Six (6)', 'Ten (10)'], exp: 'أيام الأسبوع سبعة: 7 days.' },
    { q: 'أي يوم يأتي مباشرة بعد يوم Sunday (الأحد)؟', img: '📅', correct: 'Monday', opts: ['Monday', 'Tuesday', 'Saturday', 'Friday'], exp: 'اليوم التالي للأحد هو الاثنين: Monday.' },
    { q: 'أي يوم يأتي مباشرة بعد يوم Monday (الاثنين)؟', img: '📅', correct: 'Tuesday', opts: ['Tuesday', 'Wednesday', 'Sunday', 'Thursday'], exp: 'اليوم التالي للاثنين هو الثلاثاء: Tuesday.' },
    { q: 'أي يوم يأتي مباشرة بعد يوم Tuesday (الثلاثاء)؟', img: '📅', correct: 'Wednesday', opts: ['Wednesday', 'Thursday', 'Monday', 'Friday'], exp: 'اليوم التالي للثلاثاء هو الأربعاء: Wednesday.' },
    { q: 'أي يوم يأتي مباشرة بعد يوم Wednesday (الأربعاء)؟', img: '📅', correct: 'Thursday', opts: ['Thursday', 'Friday', 'Tuesday', 'Saturday'], exp: 'اليوم التالي للأربعاء هو الخميس: Thursday.' },
    { q: 'أي يوم يأتي مباشرة بعد يوم Thursday (الخميس)؟', img: '📅', correct: 'Friday', opts: ['Friday', 'Saturday', 'Wednesday', 'Sunday'], exp: 'اليوم التالي للخميس هو الجمعة: Friday.' },
    { q: 'أي يوم يأتي مباشرة بعد يوم Friday (الجمعة)؟', img: '📅', correct: 'Saturday', opts: ['Saturday', 'Sunday', 'Thursday', 'Monday'], exp: 'اليوم التالي للجمعة هو السبت: Saturday.' },
    { q: 'ماذا نسمي عطلة نهاية الأسبوع باللغة الإنجليزية؟', img: '🏖️', correct: 'Weekend', opts: ['Weekend', 'Weekday', 'Holiday', 'Vacation'], exp: 'عطلة نهاية الأسبوع هي Weekend.' },
    { q: 'ماذا تعني كلمة (Today) باللغة العربية؟', img: '📍', correct: 'اليوم أو الحاضر', opts: ['اليوم أو الحاضر', 'أمس أو البارحة', 'غداً في المستقبل', 'الأسبوع القادم'], exp: 'Today تعني اليوم.' },
    { q: 'ماذا تعني كلمة (Yesterday) باللغة العربية؟', img: '⏪', correct: 'أمس (البارحة)', opts: ['أمس (البارحة)', 'اليوم', 'غداً', 'بعد قليل'], exp: 'Yesterday تعني الأمس.' },
    { q: 'ماذا تعني كلمة (Tomorrow) باللغة العربية؟', img: '⏩', correct: 'غداً (في الغد)', opts: ['غداً (في الغد)', 'أمس', 'اليوم', 'الآن'], exp: 'Tomorrow تعني غداً.' },
    { q: 'ما هو الشهر الأول في السنة الميلادية بالإنجليزية؟', img: '❄️', correct: 'January', opts: ['January', 'February', 'December', 'March'], exp: 'الشهر الأول (يناير) هو January.' },
    { q: 'ما اسم الشهر الثاني (فبراير) باللغة الإنجليزية؟', img: '❄️', correct: 'February', opts: ['February', 'January', 'March', 'April'], exp: 'شهر فبراير هو February.' },
    { q: 'ما اسم الشهر الثالث (مارس) باللغة الإنجليزية؟', img: '🌸', correct: 'March', opts: ['March', 'May', 'April', 'June'], exp: 'شهر مارس هو March.' },
    { q: 'ما اسم الشهر الرابع (أبريل) باللغة الإنجليزية؟', img: '🌸', correct: 'April', opts: ['April', 'August', 'May', 'March'], exp: 'شهر أبريل هو April.' },
    { q: 'ما اسم الشهر الخامس (مايو) باللغة الإنجليزية؟', img: '🌸', correct: 'May', opts: ['May', 'March', 'June', 'July'], exp: 'شهر مايو هو May.' },
    { q: 'ما اسم الشهر السادس (يونيو) باللغة الإنجليزية؟', img: '☀️', correct: 'June', opts: ['June', 'July', 'January', 'August'], exp: 'شهر يونيو هو June.' },
    { q: 'ما اسم الشهر السابع (يوليو) باللغة الإنجليزية؟', img: '☀️', correct: 'July', opts: ['July', 'June', 'August', 'September'], exp: 'شهر يوليو هو July.' },
    { q: 'ما اسم الشهر الثامن (أغسطس) باللغة الإنجليزية؟', img: '☀️', correct: 'August', opts: ['August', 'April', 'September', 'October'], exp: 'شهر أغسطس هو August.' },
    { q: 'ما اسم الشهر التاسع (سبتمبر) باللغة الإنجليزية؟', img: '🍂', correct: 'September', opts: ['September', 'October', 'November', 'December'], exp: 'شهر سبتمبر هو September.' },
    { q: 'ما اسم الشهر العاشر (أكتوبر) باللغة الإنجليزية؟', img: '🍂', correct: 'October', opts: ['October', 'November', 'September', 'August'], exp: 'شهر أكتوبر هو October.' },
    { q: 'ما اسم الشهر الحادي عشر (نوفمبر) باللغة الإنجليزية؟', img: '🍂', correct: 'November', opts: ['November', 'December', 'October', 'January'], exp: 'شهر نوفمبر هو November.' },
    { q: 'ما هو الشهر الأخير (الثاني عشر - ديسمبر) في السنة؟', img: '❄️', correct: 'December', opts: ['December', 'November', 'January', 'October'], exp: 'الشهر الأخير (ديسمبر) هو December.' },
    { q: 'كم عدد شهور السنة الميلادية بالكامل؟', img: '🗓️', correct: 'Twelve (12)', opts: ['Twelve (12)', 'Ten (10)', 'Eleven (11)', 'Fourteen (14)'], exp: 'في السنة 12 شهراً: 12 months.' },
    { q: 'ما هو الشهر الذي يأتي مباشرة بعد شهر January؟', img: '🗓️', correct: 'February', opts: ['February', 'March', 'December', 'April'], exp: 'بعد January يأتي February.' },
    { q: 'ما هو الشهر الذي يأتي مباشرة بعد شهر March؟', img: '🗓️', correct: 'April', opts: ['April', 'May', 'February', 'June'], exp: 'بعد March يأتي April.' },
    { q: 'ما هو الشهر الذي يأتي مباشرة بعد شهر June؟', img: '🗓️', correct: 'July', opts: ['July', 'August', 'May', 'September'], exp: 'بعد June يأتي July.' },
    { q: 'ما هو الشهر الذي يأتي مباشرة بعد شهر August؟', img: '🗓️', correct: 'September', opts: ['September', 'October', 'July', 'November'], exp: 'بعد August يأتي September.' },
    { q: 'ما هو الشهر الذي يأتي مباشرة بعد شهر October؟', img: '🗓️', correct: 'November', opts: ['November', 'December', 'September', 'January'], exp: 'بعد October يأتي November.' },
    { q: 'ماذا تعني كلمة (Week) باللغة العربية؟', img: '📅', correct: 'أسبوع', opts: ['أسبوع', 'يوم', 'شهر', 'سنة'], exp: 'Week تعني أسبوع.' },
    { q: 'ماذا تعني كلمة (Month) باللغة العربية؟', img: '🗓️', correct: 'شهر', opts: ['شهر', 'أسبوع', 'سنة', 'ساعة'], exp: 'Month تعني شهر.' },
    { q: 'ماذا تعني كلمة (Year) باللغة العربية؟', img: '🎆', correct: 'سنة أو عام', opts: ['سنة أو عام', 'شهر', 'عقد', 'يوم'], exp: 'Year تعني سنة.' },
    { q: 'في أي فصل تبدأ الزهور بالتفتح (Spring)؟', img: '🌸', correct: 'الربيع', opts: ['الربيع', 'الشتاء', 'الصيف', 'الخريف'], exp: 'Spring هو فصل الربيع.' },
    { q: 'ماذا يعني فصل (Summer) باللغة العربية؟', img: '☀️', correct: 'الصيف', opts: ['الصيف', 'الربيع', 'الخريف', 'الشتاء'], exp: 'Summer هو فصل الصيف.' },
    { q: 'ماذا يعني فصل (Autumn / Fall) باللغة العربية؟', img: '🍂', correct: 'الخريف', opts: ['الخريف', 'الربيع', 'الصيف', 'الشتاء'], exp: 'Autumn أو Fall هو فصل الخريف.' },
    { q: 'ماذا يعني فصل (Winter) باللغة العربية؟', img: '⛄', correct: 'الشتاء', opts: ['الشتاء', 'الصيف', 'الربيع', 'الخريف'], exp: 'Winter هو فصل الشتاء.' },
    { q: 'ما اسم أداة التقويم الجداري باللغة الإنجليزية؟', img: '📅', correct: 'Calendar', opts: ['Calendar', 'Clock', 'Watch', 'Book'], exp: 'التقويم يُسمى Calendar.' },
    { q: 'ما هو اليوم الذي يسبق الجمعة (Friday) مباشرة؟', img: '📅', correct: 'Thursday', opts: ['Thursday', 'Wednesday', 'Saturday', 'Tuesday'], exp: 'اليوم السابق للجمعة هو الخميس: Thursday.' },
    { q: 'ما هو الشهر الذي يتميز بأقصر عدد أيام (28 أو 29 يوماً)؟', img: '🗓️', correct: 'February', opts: ['February', 'January', 'March', 'April'], exp: 'فبراير (February) هو أقصر شهر.' },
    { q: 'ما معنى كلمة (Morning) باللغة العربية؟', img: '🌅', correct: 'الصباح', opts: ['الصباح', 'المساء', 'الظهيرة', 'الليل'], exp: 'Morning تعني الصباح.' },
    { q: 'ما معنى كلمة (Evening) باللغة العربية؟', img: '🌆', correct: 'المساء', opts: ['المساء', 'الصباح', 'الفجر', 'الظهر'], exp: 'Evening تعني المساء.' },
    { q: 'ما معنى كلمة (Night) باللغة العربية؟', img: '🌙', correct: 'الليل', opts: ['الليل', 'النهار', 'الصباح', 'العصر'], exp: 'Night تعني الليل.' },
    { q: 'ماذا نقول لتحية الصباح باللغة الإنجليزية؟', img: '☀️', correct: 'Good morning', opts: ['Good morning', 'Good night', 'Good evening', 'Goodbye'], exp: 'صباح الخير بالإنجليزية هي Good morning.' }
  ];
  games['أيام الأسبوع والشهور بالإنجليزية'] = daysMonths.map((d, i) => ({
    id: 10001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  return games;
}
