// Generators for English Games 11 to 20 (50 questions each = 500 questions)

export function getGames11to20() {
  const games = {};

  // 11. الأطعمة والمشروبات بالإنجليزية
  const foodDrinks = [
    { name: 'Water', ar: 'ماء نقي عذب', img: '💧', o: ['Water', 'Milk', 'Juice', 'Tea'] },
    { name: 'Milk', ar: 'حليب أبيض مغذٍ', img: '🥛', o: ['Milk', 'Water', 'Yogurt', 'Juice'] },
    { name: 'Orange Juice', ar: 'عصير برتقال طبيعي', img: '🧃', o: ['Orange Juice', 'Apple Juice', 'Lemonade', 'Soda'] },
    { name: 'Apple Juice', ar: 'عصير تفاح لذيذ', img: '🧃', o: ['Apple Juice', 'Orange Juice', 'Water', 'Tea'] },
    { name: 'Bread', ar: 'خبز طازج دافئ', img: '🍞', o: ['Bread', 'Cake', 'Rice', 'Pasta'] },
    { name: 'Rice', ar: 'أرز أبيض مطبوخ', img: '🍚', o: ['Rice', 'Bread', 'Soup', 'Noodles'] },
    { name: 'Egg', ar: 'بيضة مسلوقة أو مقلية', img: '🥚', o: ['Egg', 'Cheese', 'Butter', 'Bread'] },
    { name: 'Cheese', ar: 'جبن أصفر لذيذ', img: '🧀', o: ['Cheese', 'Butter', 'Milk', 'Egg'] },
    { name: 'Pizza', ar: 'بيتزا بالجبن الشهية', img: '🍕', o: ['Pizza', 'Burger', 'Sandwich', 'Pie'] },
    { name: 'Burger', ar: 'شطيرة برجر باللحم', img: '🍔', o: ['Burger', 'Pizza', 'Sandwich', 'Taco'] },
    { name: 'Sandwich', ar: 'ساندويتش خفيف وصحي', img: '🥪', o: ['Sandwich', 'Burger', 'Bread', 'Toast'] },
    { name: 'Soup', ar: 'حساء (شوربة) دافئ', img: '🍲', o: ['Soup', 'Salad', 'Tea', 'Water'] },
    { name: 'Salad', ar: 'سلطة خضراء طازجة', img: '🥗', o: ['Salad', 'Soup', 'Pasta', 'Rice'] },
    { name: 'Pasta', ar: 'معكرونة بصلصة الطماطم', img: '🍝', o: ['Pasta', 'Rice', 'Noodles', 'Pizza'] },
    { name: 'Pancake', ar: 'بان كيك بالعسل اللذيذ', img: '🥞', o: ['Pancake', 'Waffle', 'Cake', 'Bread'] },
    { name: 'Waffle', ar: 'وافل مقرمش ومحلى', img: '🧇', o: ['Waffle', 'Pancake', 'Cookie', 'Toast'] },
    { name: 'Cake', ar: 'كعكة عيد ميلاد مزينة', img: '🎂', o: ['Cake', 'Bread', 'Cookie', 'Cupcake'] },
    { name: 'Cupcake', ar: 'كب كيك صغير ملون', img: '🧁', o: ['Cupcake', 'Cake', 'Cookie', 'Muffin'] },
    { name: 'Cookie', ar: 'بسكويت شوكولاتة كوكيز', img: '🍪', o: ['Cookie', 'Cake', 'Candy', 'Bread'] },
    { name: 'Chocolate', ar: 'لوح شوكولاتة حلوة', img: '🍫', o: ['Chocolate', 'Candy', 'Cake', 'Ice Cream'] },
    { name: 'Ice Cream', ar: 'آيس كريم مثلج بنكهات', img: '🍦', o: ['Ice Cream', 'Yogurt', 'Cake', 'Milkshake'] },
    { name: 'Doughnut', ar: 'دونات دائرية محلاة', img: '🍩', o: ['Doughnut', 'Cookie', 'Cake', 'Bagel'] },
    { name: 'Tea', ar: 'شاي ساخن بنكهة النعناع', img: '🍵', o: ['Tea', 'Coffee', 'Water', 'Milk'] },
    { name: 'Coffee', ar: 'قهوة دافئة معطرة', img: '☕', o: ['Coffee', 'Tea', 'Cocoa', 'Juice'] },
    { name: 'Hot Chocolate', ar: 'شوكولاتة ساخنة بالمارشميلو', img: '☕', o: ['Hot Chocolate', 'Coffee', 'Tea', 'Milk'] },
    { name: 'Honey', ar: 'عسل النحل الصافي', img: '🍯', o: ['Honey', 'Jam', 'Butter', 'Sugar'] },
    { name: 'Butter', ar: 'زبدة كريمية صفراء', img: '🧈', o: ['Butter', 'Cheese', 'Cream', 'Honey'] },
    { name: 'Jam', ar: 'مربى الفراولة الحلوة', img: '🍓', o: ['Jam', 'Honey', 'Jelly', 'Butter'] },
    { name: 'French Fries', ar: 'بطاطس مقلية مقرمشة', img: '🍟', o: ['French Fries', 'Chips', 'Burger', 'Popcorn'] },
    { name: 'Hot Dog', ar: 'شطيرة هوت دوغ', img: '🌭', o: ['Hot Dog', 'Burger', 'Sandwich', 'Taco'] },
    { name: 'Popcorn', ar: 'فشار السينما اللذيذ', img: '🍿', o: ['Popcorn', 'Chips', 'Corn', 'Cookie'] },
    { name: 'Taco', ar: 'تاكو مكسيكي مقرمش', img: '🌮', o: ['Taco', 'Burrito', 'Pizza', 'Sandwich'] },
    { name: 'Burrito', ar: 'بوريتو ملفوف شهي', img: '🌯', o: ['Burrito', 'Taco', 'Sandwich', 'Pancake'] },
    { name: 'Noodles', ar: 'نودلز معكرونة شرائط', img: '🍜', o: ['Noodles', 'Pasta', 'Soup', 'Rice'] },
    { name: 'Sushi', ar: 'سوشي أرز وسمك ياباني', img: '🍣', o: ['Sushi', 'Fish', 'Rice', 'Salad'] },
    { name: 'Grilled Fish', ar: 'سمك مشوي صحي', img: '🐟', o: ['Grilled Fish', 'Chicken', 'Steak', 'Meat'] },
    { name: 'Roast Chicken', ar: 'دجاج محمر لذيذ', img: '🍗', o: ['Roast Chicken', 'Turkey', 'Duck', 'Steak'] },
    { name: 'Meat Steak', ar: 'قطعة لحم ستيك مشوية', img: '🥩', o: ['Meat Steak', 'Chicken', 'Burger', 'Sausage'] },
    { name: 'Fruit Pie', ar: 'فطيرة فواكه مخبوزة', img: '🥧', o: ['Fruit Pie', 'Cake', 'Pizza', 'Pancake'] },
    { name: 'Toast', ar: 'توست محمص ذهبي', img: '🍞', o: ['Toast', 'Bread', 'Croissant', 'Cracker'] },
    { name: 'Croissant', ar: 'كرواسون فرنسي هش', img: '🥐', o: ['Croissant', 'Bread', 'Toast', 'Doughnut'] },
    { name: 'Bagel', ar: 'خبز البيغل الدائري', img: '🥯', o: ['Bagel', 'Doughnut', 'Bread', 'Bun'] },
    { name: 'Morning Cereal', ar: 'رقائق الحبوب مع الحليب', img: '🥣', o: ['Morning Cereal', 'Soup', 'Salad', 'Yogurt'] },
    { name: 'Fresh Yogurt', ar: 'زبادي (لبن رائب) طازج', img: '🥛', o: ['Fresh Yogurt', 'Milk', 'Cream', 'Cheese'] },
    { name: 'Cold Lemonade', ar: 'عصير ليموناضة مثلج', img: '🍋', o: ['Cold Lemonade', 'Orange Juice', 'Water', 'Tea'] },
    { name: 'Fruit Smoothie', ar: 'سموذي فواكه مخفوقة', img: '🥤', o: ['Fruit Smoothie', 'Juice', 'Milkshake', 'Soda'] },
    { name: 'Milkshake', ar: 'ميلك شيك بالحليب والآيس كريم', img: '🥤', o: ['Milkshake', 'Smoothie', 'Coffee', 'Juice'] },
    { name: 'Sweet Biscuit', ar: 'بسكويت شاي مقرمش', img: '🍪', o: ['Sweet Biscuit', 'Cookie', 'Cracker', 'Cake'] },
    { name: 'Muffin', ar: 'مافن الكعك الصغير', img: '🧁', o: ['Muffin', 'Cupcake', 'Bread', 'Cake'] },
    { name: 'Olive Oil', ar: 'زيت زيتون بكر صحي', img: '🫒', o: ['Olive Oil', 'Butter', 'Vinegar', 'Sauce'] }
  ];
  games['الأطعمة والمشروبات بالإنجليزية'] = foodDrinks.map((d, i) => ({
    id: 11001 + i,
    question: `ما اسم (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} يُسمى بالإنجليزية '${d.name}'.`
  }));

  // 12. أسئلة وأدوات الاستفهام بالإنجليزية
  const questionWords = [
    { q: 'ما هي أداة الاستفهام المستخدمة للسؤال عن الأشياء (ما أو ماذا)؟', img: '❓', correct: 'What', opts: ['What', 'Where', 'Who', 'When'], exp: 'نستخدم What للسؤال عن الأشياء وغير العاقل.' },
    { q: 'ما هي أداة الاستفهام المستخدمة للسؤال عن المكان (أين)؟', img: '📍', correct: 'Where', opts: ['Where', 'What', 'Who', 'Why'], exp: 'نستخدم Where للسؤال عن المكان.' },
    { q: 'ما هي أداة الاستفهام المستخدمة للسؤال عن الأشخاص العاقلين (مَن)؟', img: '👤', correct: 'Who', opts: ['Who', 'What', 'Where', 'How'], exp: 'نستخدم Who للسؤال عن الشخص العاقل.' },
    { q: 'ما هي أداة الاستفهام المستخدمة للسؤال عن الزمان والوقت (متى)؟', img: '⏰', correct: 'When', opts: ['When', 'Where', 'Why', 'What'], exp: 'نستخدم When للسؤال عن الزمان والوقت.' },
    { q: 'ما هي أداة الاستفهام المستخدمة للسؤال عن السبب (لماذا)؟', img: '💡', correct: 'Why', opts: ['Why', 'How', 'Where', 'Who'], exp: 'نستخدم Why للسؤال عن السبب وتعلّل بـ Because.' },
    { q: 'ما هي أداة الاستفهام المستخدمة للسؤال عن الكيفية والحال (كيف)؟', img: '⚙️', correct: 'How', opts: ['How', 'Why', 'Who', 'When'], exp: 'نستخدم How للسؤال عن الحال والكيفية.' },
    { q: 'ما هي أداة الاستفهام المستخدمة للاختيار بين أمرين (أيّهما أو أي)؟', img: '🎯', correct: 'Which', opts: ['Which', 'What', 'Where', 'Who'], exp: 'نستخدم Which للاختيار والتفضيل.' },
    { q: 'ما هي أداة الاستفهام المستخدمة للسؤال عن الملكية (لمَن)؟', img: '🎒', correct: 'Whose', opts: ['Whose', 'Who', 'What', 'Where'], exp: 'نستخدم Whose للسؤال عن مالك الشيء.' },
    { q: 'ما هي الصيغة المستخدمة للسؤال عن العدد والمعدود (كم عدد)؟', img: '🔢', correct: 'How many', opts: ['How many', 'How much', 'How old', 'How long'], exp: 'نستخدم How many للسؤال عن العدد.' },
    { q: 'ما هي الصيغة المستخدمة للسؤال عن السعر أو الكميات غير المعدودة؟', img: '💰', correct: 'How much', opts: ['How much', 'How many', 'How far', 'How tall'], exp: 'نستخدم How much للسؤال عن السعر والكمية غير المعدودة.' },
    { q: 'ما هي الصيغة المستخدمة للسؤال عن العمر (كم عمرك)؟', img: '🎂', correct: 'How old', opts: ['How old', 'How tall', 'How many', 'How much'], exp: 'نستخدم How old للسؤال عن السن والعمر.' },
    { q: 'ما هي الصيغة المستخدمة للسؤال عن الطول والمسافة الزمنية؟', img: '📏', correct: 'How long', opts: ['How long', 'How old', 'How many', 'How fast'], exp: 'نستخدم How long للمدة أو الطول.' },
    { q: 'سؤال: (... is your name?) ماذا نضع في الفراغ؟', img: '❓', correct: 'What', opts: ['What', 'Where', 'Who', 'Why'], exp: 'السؤال الشهير عن الاسم هو: What is your name?' },
    { q: 'سؤال: (... are you from?) للسؤال عن البلد والمكان، نضع:', img: '🌍', correct: 'Where', opts: ['Where', 'When', 'Who', 'What'], exp: 'السؤال عن الموطن هو: Where are you from?' },
    { q: 'سؤال: (... is that teacher?) للسؤال عن هوية المعلم، نضع:', img: '👨‍🏫', correct: 'Who', opts: ['Who', 'Where', 'When', 'Why'], exp: 'السؤال عن شخص هو: Who is that teacher?' },
    { q: 'سؤال: (... do you wake up in the morning?) للسؤال عن وقت الاستيقاظ:', img: '⏰', correct: 'When', opts: ['When', 'Where', 'Who', 'Why'], exp: 'السؤال عن الوقت: When do you wake up?' },
    { q: 'سؤال: (... are you smiling?) للسؤال عن سبب ابتسامتك، نضع:', img: '😊', correct: 'Why', opts: ['Why', 'Where', 'When', 'Who'], exp: 'السؤال عن السبب: Why are you smiling?' },
    { q: 'سؤال: (... are you today?) للتحية والسؤال عن الصحة، نضع:', img: '👋', correct: 'How', opts: ['How', 'What', 'Where', 'Who'], exp: 'كيف حالك اليوم تُقال: How are you today?' },
    { q: 'سؤال: (... color do you prefer, red or blue?) للاختيار نضع:', img: '🎨', correct: 'Which', opts: ['Which', 'Where', 'When', 'Who'], exp: 'للاختيار بين خيارات نستخدم: Which color do you prefer?' },
    { q: 'سؤال: (... bag is on the table?) للسؤال عن صاحب الحقيبة نضع:', img: '🎒', correct: 'Whose', opts: ['Whose', 'Who', 'What', 'Where'], exp: 'Whose bag is on the table?' },
    { q: 'سؤال: (... apples are in the basket?) للسؤال عن عدد التفاحات:', img: '🍎', correct: 'How many', opts: ['How many', 'How much', 'How long', 'How old'], exp: 'التفاح معدود فنقول: How many apples?' },
    { q: 'سؤال: (... is this pencil?) للسؤال عن سعر القلم نضع:', img: '✏️', correct: 'How much', opts: ['How much', 'How many', 'How long', 'How far'], exp: 'للسؤال عن السعر: How much is this pencil?' },
    { q: 'سؤال: (... are you? - I am seven years old) لمعرفة العمر نضع:', img: '🎂', correct: 'How old', opts: ['How old', 'How many', 'How much', 'How long'], exp: 'How old are you?' },
    { q: 'أين يعالج الطبيب المرضى؟ (Where does the doctor work?)', img: '🏥', correct: 'In the hospital', opts: ['In the hospital', 'In the zoo', 'In the kitchen', 'In the park'], exp: 'يعمل الطبيب في المستشفى: In the hospital.' },
    { q: 'مَن يعلم الأطفال في المدرسة؟ (Who teaches children at school?)', img: '🏫', correct: 'Teacher', opts: ['Teacher', 'Pilot', 'Baker', 'Farmer'], exp: 'المعلم هو من يدرس: Teacher.' },
    { q: 'ماذا تعطينا البقرة في المزرعة؟ (What do cows give us?)', img: '🥛', correct: 'Fresh milk', opts: ['Fresh milk', 'Apples', 'Bread', 'Juice'], exp: 'البقرة تعطي الحليب: Fresh milk.' },
    { q: 'متى تشرق الشمس في السماء؟ (When does the sun rise?)', img: '🌅', correct: 'In the morning', opts: ['In the morning', 'At midnight', 'In the evening', 'In winter only'], exp: 'تشرق الشمس في الصباح: In the morning.' },
    { q: 'أين تعيش الأسماك؟ (Where do fish live?)', img: '🌊', correct: 'In the water', opts: ['In the water', 'In the sky', 'In the trees', 'In the sand'], exp: 'تعيش الأسماك في الماء: In the water.' },
    { q: 'مَن يقود الطائرة في الجو؟ (Who flies the airplane?)', img: '✈️', correct: 'Pilot', opts: ['Pilot', 'Driver', 'Captain', 'Doctor'], exp: 'الطيار هو Pilot.' },
    { q: 'لماذا نتناول الطعام الصحي؟ (Why do we eat healthy food?)', img: '🥗', correct: 'To grow strong', opts: ['To grow strong', 'To feel sleepy', 'To cry', 'To be cold'], exp: 'نأكل الطعام الصحي لننمو أقوياء: To grow strong.' },
    { q: 'كيف يسير الضفدع؟ (How does a frog move?)', img: '🐸', correct: 'It jumps', opts: ['It jumps', 'It flies', 'It drives', 'It reads'], exp: 'الضفدع يقفز: It jumps.' },
    { q: 'ماذا يضيء السماء ليلاً؟ (What shines in the sky at night?)', img: '🌙', correct: 'The moon and stars', opts: ['The moon and stars', 'The sun', 'Traffic lights', 'A flashlight'], exp: 'القمر والنجوم: The moon and stars.' },
    { q: 'كم يوماً في الأسبوع الواحد؟ (How many days in a week?)', img: '📅', correct: 'Seven days', opts: ['Seven days', 'Ten days', 'Five days', 'Twelve days'], exp: 'في الأسبوع سبعة أيام: Seven days.' },
    { q: 'أين نشتري الخبز الطازج؟ (Where do we buy fresh bread?)', img: '🥖', correct: 'At the bakery', opts: ['At the bakery', 'At the hospital', 'At the airport', 'At the park'], exp: 'في المخبز: At the bakery.' },
    { q: 'مَن يطفئ الحرائق وينقذ الناس؟ (Who puts out fires?)', img: '🚒', correct: 'Firefighter', opts: ['Firefighter', 'Police officer', 'Doctor', 'Teacher'], exp: 'رجل الإطفاء: Firefighter.' },
    { q: 'متى نتناول وجبة الإفطار؟ (When do we eat breakfast?)', img: '🥞', correct: 'In the morning', opts: ['In the morning', 'At night', 'In the afternoon', 'At midnight'], exp: 'وجبة الإفطار في الصباح: In the morning.' },
    { q: 'ما هو الحيوان الذي يُلقب بملك الغابة؟ (What is the king of the jungle?)', img: '🦁', correct: 'The lion', opts: ['The lion', 'The rabbit', 'The mouse', 'The frog'], exp: 'الأسد: The lion.' },
    { q: 'كيف يذهب الطائر من شجرة لأخرى؟ (How do birds move?)', img: '🦅', correct: 'They fly with wings', opts: ['They fly with wings', 'They drive cars', 'They swim deep', 'They walk only'], exp: 'الطيور تطير بأجنحتها: They fly.' },
    { q: 'ما هو لون السماء في يوم مشمس صافٍ؟ (What color is the sky?)', img: '☀️', correct: 'Blue', opts: ['Blue', 'Green', 'Red', 'Yellow'], exp: 'السماء زرقاء: Blue.' },
    { q: 'أين نذهب لمشاهدة الحيوانات البرية؟ (Where can we see wild animals?)', img: '🦁', correct: 'At the zoo', opts: ['At the zoo', 'At the bakery', 'At the school', 'At the pharmacy'], exp: 'في حديقة الحيوان: At the zoo.' },
    { q: 'مَن يساعد الطبيب في رعاية المرضى؟ (Who helps the doctor?)', img: '👩‍⚕️', correct: 'The nurse', opts: ['The nurse', 'The baker', 'The pilot', 'The driver'], exp: 'الممرضة: The nurse.' },
    { q: 'ماذا نستخدم لكتابة الواجبات المدرسية؟ (What do we use to write?)', img: '✏️', correct: 'A pencil', opts: ['A pencil', 'An apple', 'A cup', 'A fork'], exp: 'القلم الرصاص: A pencil.' },
    { q: 'متى ننام في الليل؟ (When do we go to sleep?)', img: '🛏️', correct: 'At bedtime', opts: ['At bedtime', 'At noon', 'In the morning', 'At school'], exp: 'عند وقت النوم ليلاً: At bedtime.' },
    { q: 'لماذا نغسل أيدينا بالماء والصابون؟ (Why do we wash our hands?)', img: '🧼', correct: 'To stay clean and healthy', opts: ['To stay clean and healthy', 'To get dirty', 'To play games', 'To run fast'], exp: 'لنبقى نظيفين وبصحة جيدة: To stay clean.' },
    { q: 'كم إصبعاً في القدم الواحدة؟ (How many toes on one foot?)', img: '🦶', correct: 'Five toes', opts: ['Five toes', 'Ten toes', 'Four toes', 'Two toes'], exp: 'خمسة أصابع: Five toes.' },
    { q: 'أين نضع الكتب المدرسية لنحملها؟ (Where do we put schoolbooks?)', img: '🎒', correct: 'In the backpack', opts: ['In the backpack', 'In the cup', 'In the shoe', 'Under the pillow'], exp: 'في حقيبة الظهر: In the backpack.' },
    { q: 'مَن يزرع الخضار والفواكه في الحقل؟ (Who grows vegetables?)', img: '👨‍🌾', correct: 'The farmer', opts: ['The farmer', 'The pilot', 'The dentist', 'The police officer'], exp: 'المزارع: The farmer.' },
    { q: 'ماذا نشرب عندما نشعر بالعطش؟ (What do we drink when thirsty?)', img: '💧', correct: 'Water', opts: ['Water', 'Cake', 'Bread', 'Apple'], exp: 'الماء: Water.' },
    { q: 'كيف تكون رائحة الورد والزهور؟ (How do flowers smell?)', img: '🌸', correct: 'Sweet and nice', opts: ['Sweet and nice', 'Bad', 'Cold', 'Loud'], exp: 'رائحتها جميلة وعطرة: Sweet and nice.' },
    { q: 'أي أداة استفهام تستخدم للسؤال عن وسيلة المواصلات؟ (How do you go to school?)', img: '🚌', correct: 'How', opts: ['How', 'Who', 'When', 'Whose'], exp: 'كيف تذهب للمدرسة: How do you go to school?' }
  ];
  games['أسئلة وأدوات الاستفهام بالإنجليزية'] = questionWords.map((d, i) => ({
    id: 12001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  // 13. أفراد العائلة والمنزل بالإنجليزية
  const familyList = [
    { name: 'Father', ar: 'الأب الحنون', img: '👨', o: ['Father', 'Mother', 'Brother', 'Grandpa'] },
    { name: 'Mother', ar: 'الأم الطيبة', img: '👩', o: ['Mother', 'Father', 'Sister', 'Grandma'] },
    { name: 'Brother', ar: 'الأخ الأكبر أو الأصغر', img: '👦', o: ['Brother', 'Sister', 'Uncle', 'Father'] },
    { name: 'Sister', ar: 'الأخت المحبوبة', img: '👧', o: ['Sister', 'Brother', 'Aunt', 'Mother'] },
    { name: 'Baby', ar: 'الطفل الرضيع الصغير', img: '👶', o: ['Baby', 'Child', 'Boy', 'Girl'] },
    { name: 'Grandfather', ar: 'الجد العزيز (الحكيم)', img: '👴', o: ['Grandfather', 'Father', 'Uncle', 'Brother'] },
    { name: 'Grandmother', ar: 'الجدة الحنونة الوديعة', img: '👵', o: ['Grandmother', 'Mother', 'Aunt', 'Sister'] },
    { name: 'Uncle', ar: 'العم أو الخال', img: '👨', o: ['Uncle', 'Aunt', 'Father', 'Brother'] },
    { name: 'Aunt', ar: 'العمة أو الخالة', img: '👩', o: ['Aunt', 'Uncle', 'Mother', 'Sister'] },
    { name: 'Cousin', ar: 'ابن العم أو ابن الخال', img: '🧒', o: ['Cousin', 'Brother', 'Sister', 'Friend'] },
    { name: 'Parents', ar: 'الوالدان (الأب والأم معاً)', img: '👨‍👩‍👧', o: ['Parents', 'Family', 'Children', 'Friends'] },
    { name: 'Family', ar: 'الأسرة أو العائلة بأكملها', img: '👨‍👩‍👧‍👦', o: ['Family', 'Parents', 'People', 'Team'] },
    { name: 'Son', ar: 'الابن (للأبوين)', img: '👦', o: ['Son', 'Daughter', 'Brother', 'Father'] },
    { name: 'Daughter', ar: 'الابنة (للأبوين)', img: '👧', o: ['Daughter', 'Son', 'Sister', 'Mother'] },
    { name: 'Grandson', ar: 'الحفيد (ابن الابن أو الابنة)', img: '👦', o: ['Grandson', 'Granddaughter', 'Son', 'Brother'] },
    { name: 'Granddaughter', ar: 'الحفيدة اللطيفة', img: '👧', o: ['Granddaughter', 'Grandson', 'Daughter', 'Sister'] },
    { name: 'Twins', ar: 'التوأمان المتشابهان', img: '👥', o: ['Twins', 'Friends', 'Brothers', 'Children'] },
    { name: 'Big Brother', ar: 'الأخ الكبير السند', img: '👦', o: ['Big Brother', 'Little Sister', 'Father', 'Cousin'] },
    { name: 'Little Sister', ar: 'الأخت الصغرى المرحة', img: '👧', o: ['Little Sister', 'Big Brother', 'Mother', 'Aunt'] },
    { name: 'Dad', ar: 'بابا (الاسم اللطيف للأب)', img: '👨', o: ['Dad', 'Mom', 'Grandpa', 'Boy'] },
    { name: 'Mom', ar: 'ماما (الاسم اللطيف للأم)', img: '👩', o: ['Mom', 'Dad', 'Grandma', 'Girl'] },
    { name: 'Grandpa', ar: 'جدو (اسم التحبب للجد)', img: '👴', o: ['Grandpa', 'Grandma', 'Dad', 'Uncle'] },
    { name: 'Grandma', ar: 'تيتا (اسم التحبب للجدة)', img: '👵', o: ['Grandma', 'Grandpa', 'Mom', 'Aunt'] },
    { name: 'Newborn Baby', ar: 'المولود الجديد بالعائلة', img: '👶', o: ['Newborn Baby', 'Toddler', 'Child', 'Puppy'] },
    { name: 'Loving Family', ar: 'العائلة المحبة المترابطة', img: '❤️', o: ['Loving Family', 'School', 'Class', 'Neighbors'] },
    { name: 'Home', ar: 'البيت الدافئ المستقر', img: '🏠', o: ['Home', 'School', 'Office', 'Hotel'] },
    { name: 'House', ar: 'منزل العائلة الجميل', img: '🏡', o: ['House', 'Apartment', 'Building', 'Room'] },
    { name: 'Family Dinner', ar: 'عشاء العائلة المجتمع معاً', img: '🍽️', o: ['Family Dinner', 'Breakfast', 'Party', 'Lunch'] },
    { name: 'Family Walk', ar: 'نزهة المشي العائلية الممتعة', img: '🚶', o: ['Family Walk', 'Race', 'Run', 'Ride'] },
    { name: 'Family Picnic', ar: 'رحلة تنزه العائلة في الحديقة', img: '🧺', o: ['Family Picnic', 'Camp', 'Market', 'Cinema'] },
    { name: 'Living Room', ar: 'غرفة المعيشة والجلوس', img: '🛋️', o: ['Living Room', 'Kitchen', 'Bathroom', 'Bedroom'] },
    { name: 'Mother Love', ar: 'حب الأم وحنانها', img: '💖', o: ['Mother Love', 'Gift', 'Toy', 'Game'] },
    { name: 'Father Support', ar: 'دعم الأب ومساعدته', img: '🤝', o: ['Father Support', 'Work', 'Lesson', 'Job'] },
    { name: 'Playing with Brother', ar: 'اللعب الممتع مع الأخ', img: '⚽', o: ['Playing with Brother', 'Sleeping', 'Eating', 'Studying'] },
    { name: 'Reading with Sister', ar: 'القراءة الهادئة مع الأخت', img: '📖', o: ['Reading with Sister', 'Running', 'Cooking', 'Drawing'] },
    { name: 'Visiting Grandma', ar: 'زيارة بيت الجدة', img: '👵', o: ['Visiting Grandma', 'Going to School', 'Shopping', 'Working'] },
    { name: 'Grandfather Story', ar: 'قصة الجد المشوقة', img: '📖', o: ['Grandfather Story', 'Movie', 'Song', 'Game'] },
    { name: 'Baby Brother', ar: 'الأخ الرضيع الصغير', img: '👶', o: ['Baby Brother', 'Uncle', 'Grandpa', 'Dad'] },
    { name: 'Elder Sister', ar: 'الأخت الكبرى المساعدة', img: '👧', o: ['Elder Sister', 'Aunt', 'Mom', 'Grandma'] },
    { name: 'Uncle Visit', ar: 'زيارة العم والخال لنا', img: '👨', o: ['Uncle Visit', 'Trip', 'Holiday', 'Doctor Visit'] },
    { name: 'Aunt Cake', ar: 'كعكة العمة والخالة اللذيذة', img: '🎂', o: ['Aunt Cake', 'Bread', 'Apple', 'Pizza'] },
    { name: 'Cheerful Cousin', ar: 'ابن العم الصديق المرح', img: '🧒', o: ['Cheerful Cousin', 'Neighbor', 'Stranger', 'Doctor'] },
    { name: 'Happy Family', ar: 'الأسرة السعيدة المبتسمة', img: '🥳', o: ['Happy Family', 'Sad Crowd', 'Team', 'Class'] },
    { name: 'Family Tree', ar: 'شجرة العائلة والنسب', img: '🌳', o: ['Family Tree', 'Oak Tree', 'Plant', 'Garden'] },
    { name: 'Family Photo', ar: 'صورة العائلة التذكارية', img: '📸', o: ['Family Photo', 'Painting', 'Mirror', 'Book'] },
    { name: 'Cozy House', ar: 'المنزل المريح المبهج', img: '🏡', o: ['Cozy House', 'Tent', 'Castle', 'Tower'] },
    { name: 'Welcome Home', ar: 'أهلاً بك في بيتك', img: '🚪', o: ['Welcome Home', 'Goodbye', 'Good Night', 'Hello School'] },
    { name: 'Family Breakfast', ar: 'فطور الصباح العائلي اللذيذ', img: '🥞', o: ['Family Breakfast', 'Dinner', 'Supper', 'Lunch'] },
    { name: 'Evening Gathering', ar: 'جلسة المساء والسمر العائلي', img: '☕', o: ['Evening Gathering', 'Morning Class', 'Trip', 'Meeting'] },
    { name: 'Best Family', ar: 'أفضل وأجمل عائلة في العالم', img: '🌟', o: ['Best Family', 'Best Friend', 'Best Team', 'Best Class'] }
  ];
  games['أفراد العائلة والمنزل بالإنجليزية'] = familyList.map((d, i) => ({
    id: 13001 + i,
    question: `ما اسم (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 14. أعضاء جسم الإنسان بالإنجليزية
  const bodyParts = [
    { name: 'Head', ar: 'الرأس', img: '👤', o: ['Head', 'Hand', 'Foot', 'Arm'] },
    { name: 'Hair', ar: 'الشعر', img: '💇', o: ['Hair', 'Head', 'Hand', 'Hat'] },
    { name: 'Eye', ar: 'العين التي نرى بها', img: '👁️', o: ['Eye', 'Ear', 'Nose', 'Mouth'] },
    { name: 'Ear', ar: 'الأذن التي نسمع بها', img: '👂', o: ['Ear', 'Eye', 'Nose', 'Lip'] },
    { name: 'Nose', ar: 'الأنف الذي نشم به', img: '👃', o: ['Nose', 'Mouth', 'Ear', 'Neck'] },
    { name: 'Mouth', ar: 'الفم الذي نتحدث ونأكل به', img: '👄', o: ['Mouth', 'Nose', 'Tooth', 'Tongue'] },
    { name: 'Teeth', ar: 'الأسنان البيضاء النظيفة', img: '🦷', o: ['Teeth', 'Tongue', 'Lips', 'Mouth'] },
    { name: 'Tongue', ar: 'اللسان الذي نتذوق به الطعام', img: '👅', o: ['Tongue', 'Teeth', 'Lip', 'Mouth'] },
    { name: 'Lips', ar: 'الشفاه المبتسمة', img: '👄', o: ['Lips', 'Teeth', 'Tongue', 'Cheeks'] },
    { name: 'Face', ar: 'الوجه الباسم', img: '😊', o: ['Face', 'Head', 'Hair', 'Eyes'] },
    { name: 'Neck', ar: 'الرقبة (العنق)', img: '👤', o: ['Neck', 'Shoulder', 'Chest', 'Head'] },
    { name: 'Shoulder', ar: 'الكتف القوي', img: '👤', o: ['Shoulder', 'Arm', 'Elbow', 'Chest'] },
    { name: 'Arm', ar: 'الذراع بأكمله', img: '💪', o: ['Arm', 'Hand', 'Leg', 'Foot'] },
    { name: 'Elbow', ar: 'المرفق (الكوع)', img: '💪', o: ['Elbow', 'Knee', 'Wrist', 'Ankle'] },
    { name: 'Hand', ar: 'اليد التي نمسك بها الأشياء', img: '✋', o: ['Hand', 'Foot', 'Arm', 'Finger'] },
    { name: 'Palm', ar: 'راحة وباطن اليد', img: '✋', o: ['Palm', 'Hand', 'Fingers', 'Wrist'] },
    { name: 'Finger', ar: 'إصبع اليد', img: '☝️', o: ['Finger', 'Toe', 'Thumb', 'Nail'] },
    { name: 'Thumb', ar: 'إصبع الإبهام', img: '👍', o: ['Thumb', 'Finger', 'Toe', 'Palm'] },
    { name: 'Chest', ar: 'الصدر والقفص الصدري', img: '🫁', o: ['Chest', 'Stomach', 'Back', 'Neck'] },
    { name: 'Stomach', ar: 'البطن (المعدة)', img: '🫃', o: ['Stomach', 'Chest', 'Heart', 'Back'] },
    { name: 'Leg', ar: 'الساق التي نمشي بها', img: '🦵', o: ['Leg', 'Arm', 'Foot', 'Knee'] },
    { name: 'Knee', ar: 'الركبة في منتصف الساق', img: '🦵', o: ['Knee', 'Elbow', 'Ankle', 'Foot'] },
    { name: 'Foot', ar: 'القدم الواحدة', img: '🦶', o: ['Foot', 'Feet', 'Hand', 'Leg'] },
    { name: 'Feet', ar: 'الأقدام (جمع قدم)', img: '🦶', o: ['Feet', 'Foot', 'Hands', 'Legs'] },
    { name: 'Toe', ar: 'إصبع القدم', img: '🦶', o: ['Toe', 'Finger', 'Thumb', 'Heel'] },
    { name: 'Back', ar: 'الظهر المستقيم', img: '👤', o: ['Back', 'Chest', 'Stomach', 'Shoulder'] },
    { name: 'Heart', ar: 'القلب النابض بالحياة', img: '❤️', o: ['Heart', 'Brain', 'Lungs', 'Stomach'] },
    { name: 'Brain', ar: 'العقل والدماغ المفكر', img: '🧠', o: ['Brain', 'Heart', 'Head', 'Skull'] },
    { name: 'Bone', ar: 'العظم القوي في الهيكل', img: '🦴', o: ['Bone', 'Muscle', 'Skin', 'Blood'] },
    { name: 'Skin', ar: 'الجلد السليم الذي يغطي الجسم', img: '🧴', o: ['Skin', 'Hair', 'Nails', 'Muscle'] },
    { name: 'Nails', ar: 'الأظافر النظيفة المقلمة', img: '💅', o: ['Nails', 'Fingers', 'Hands', 'Skin'] },
    { name: 'Ankle', ar: 'الكاحل فوق القدم', img: '🦶', o: ['Ankle', 'Wrist', 'Knee', 'Elbow'] },
    { name: 'Wrist', ar: 'المعصم (الرسغ) مكان وضع الساعة', img: '⌚', o: ['Wrist', 'Ankle', 'Elbow', 'Palm'] },
    { name: 'Forehead', ar: 'الجبهة (الجبين)', img: '👤', o: ['Forehead', 'Chin', 'Cheek', 'Nose'] },
    { name: 'Cheek', ar: 'الخد الوردي', img: '😊', o: ['Cheek', 'Chin', 'Nose', 'Ear'] },
    { name: 'Chin', ar: 'الذقن أسفل الفم', img: '👤', o: ['Chin', 'Cheek', 'Neck', 'Forehead'] },
    { name: 'Eyebrow', ar: 'الحاجب فوق العين', img: '👁️', o: ['Eyebrow', 'Eyelash', 'Forehead', 'Eye'] },
    { name: 'Eyelash', ar: 'الرموش الحامية للعين', img: '👁️', o: ['Eyelash', 'Eyebrow', 'Hair', 'Eye'] },
    { name: 'Muscle', ar: 'العضلة القوية', img: '💪', o: ['Muscle', 'Bone', 'Skin', 'Fat'] },
    { name: 'Throat', ar: 'الحلق أو الحنجرة', img: '🗣️', o: ['Throat', 'Neck', 'Mouth', 'Chest'] },
    { name: 'Heel', ar: 'كعب القدم', img: '🦶', o: ['Heel', 'Toe', 'Ankle', 'Knee'] },
    { name: 'Waist', ar: 'الخصر (محيط الوسط)', img: '👤', o: ['Waist', 'Hip', 'Back', 'Stomach'] },
    { name: 'Hip', ar: 'الورك وعظم الحوض', img: '👤', o: ['Hip', 'Waist', 'Leg', 'Knee'] },
    { name: 'Index Finger', ar: 'إصبع السبابة للإشارة', img: '☝️', o: ['Index Finger', 'Thumb', 'Little Finger', 'Toe'] },
    { name: 'Little Finger', ar: 'إصبع الخنصر الصغير', img: '🖐️', o: ['Little Finger', 'Thumb', 'Index Finger', 'Middle Finger'] },
    { name: 'Lungs', ar: 'الرئتان للتنفس وأخذ الأكسجين', img: '🫁', o: ['Lungs', 'Heart', 'Stomach', 'Liver'] },
    { name: 'Skeleton', ar: 'الهيكل العظمي الكامل', img: '💀', o: ['Skeleton', 'Bone', 'Body', 'Muscle'] },
    { name: 'Smile', ar: 'الابتسامة الجميلة للوجه', img: '😊', o: ['Smile', 'Mouth', 'Teeth', 'Laugh'] },
    { name: 'Body', ar: 'جسم الإنسان كاملاً', img: '🧍', o: ['Body', 'Head', 'Hand', 'Feet'] },
    { name: 'Shoulders', ar: 'الكتفان معاً', img: '👤', o: ['Shoulders', 'Arms', 'Elbows', 'Hands'] }
  ];
  games['أعضاء جسم الإنسان بالإنجليزية'] = bodyParts.map((d, i) => ({
    id: 14001 + i,
    question: `ما اسم عضو (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 15. الصفات والأوصاف بالإنجليزية
  const adjectivesList = [
    { name: 'Big', ar: 'كبير الحجم وضخم', img: '🐘', o: ['Big', 'Small', 'Short', 'Thin'] },
    { name: 'Small', ar: 'صغير الحجم والقد', img: '🐜', o: ['Small', 'Big', 'Huge', 'Tall'] },
    { name: 'Tall', ar: 'طويل القامة كالشجرة', img: '🦒', o: ['Tall', 'Short', 'Small', 'Fat'] },
    { name: 'Short', ar: 'قصير القامة', img: '🐁', o: ['Short', 'Tall', 'Long', 'Wide'] },
    { name: 'Fast', ar: 'سريع كالصاروخ', img: '🐆', o: ['Fast', 'Slow', 'Late', 'Heavy'] },
    { name: 'Slow', ar: 'بطيء كالسلحفاة', img: '🐢', o: ['Slow', 'Fast', 'Quick', 'Loud'] },
    { name: 'Hot', ar: 'حار وساخن جداً', img: '☀️', o: ['Hot', 'Cold', 'Cool', 'Dry'] },
    { name: 'Cold', ar: 'بارد ومثلج كالشتاء', img: '❄️', o: ['Cold', 'Hot', 'Warm', 'Fresh'] },
    { name: 'Happy', ar: 'سعيد ومبتهج', img: '😊', o: ['Happy', 'Sad', 'Angry', 'Tired'] },
    { name: 'Sad', ar: 'حزين وباكٍ', img: '😢', o: ['Sad', 'Happy', 'Glad', 'Funny'] },
    { name: 'Strong', ar: 'قوي مفتول العضلات', img: '💪', o: ['Strong', 'Weak', 'Sick', 'Soft'] },
    { name: 'Weak', ar: 'ضعيف البنية', img: '🪶', o: ['Weak', 'Strong', 'Tough', 'Hard'] },
    { name: 'Heavy', ar: 'ثقيل الوزن كالحديد', img: '🏋️', o: ['Heavy', 'Light', 'Thin', 'Soft'] },
    { name: 'Light', ar: 'خفيف الوزن كالريشة', img: '🪶', o: ['Light', 'Heavy', 'Hard', 'Dark'] },
    { name: 'Hard', ar: 'صلب وقاسٍ كالصخر', img: '🪨', o: ['Hard', 'Soft', 'Smooth', 'Easy'] },
    { name: 'Soft', ar: 'ناعم الملمس كالدمية القطنية', img: '🧸', o: ['Soft', 'Hard', 'Rough', 'Tough'] },
    { name: 'Clean', ar: 'نظيف ولامع ومرتب', img: '✨', o: ['Clean', 'Dirty', 'Messy', 'Dark'] },
    { name: 'Dirty', ar: 'متسخ بالوحل والغبار', img: '泥', o: ['Dirty', 'Clean', 'Bright', 'White'] },
    { name: 'Sweet', ar: 'حلو المذاق كالحلوى', img: '🍬', o: ['Sweet', 'Sour', 'Salty', 'Bitter'] },
    { name: 'Sour', ar: 'حامض كالليمون', img: '🍋', o: ['Sour', 'Sweet', 'Spicy', 'Cold'] },
    { name: 'Loud', ar: 'صاخب وعالي الصوت', img: '📢', o: ['Loud', 'Quiet', 'Silent', 'Soft'] },
    { name: 'Quiet', ar: 'هادئ ومريح للأعصاب', img: '🤫', o: ['Quiet', 'Loud', 'Noisy', 'Hard'] },
    { name: 'Bright', ar: 'مشرق ومضيء كالشمس', img: '💡', o: ['Bright', 'Dark', 'Dim', 'Dull'] },
    { name: 'Dark', ar: 'مظلم وداكن كالليل', img: '🌑', o: ['Dark', 'Bright', 'Light', 'Clear'] },
    { name: 'Sharp', ar: 'حاد كالقلم المبري', img: '✏️', o: ['Sharp', 'Blunt', 'Soft', 'Round'] },
    { name: 'Round', ar: 'مستدير كالدائرة والكرة', img: '⚪', o: ['Round', 'Square', 'Flat', 'Sharp'] },
    { name: 'Flat', ar: 'مسطح ومستوٍ كالورقة', img: '📄', o: ['Flat', 'Round', 'Deep', 'Tall'] },
    { name: 'Long', ar: 'طويل كالمسطرة والشارع', img: '📏', o: ['Long', 'Short', 'Tiny', 'Narrow'] },
    { name: 'Deep', ar: 'عميق كقاع المحيط', img: '🌊', o: ['Deep', 'Shallow', 'High', 'Flat'] },
    { name: 'Shallow', ar: 'ضحل وقليل العمق', img: '🪣', o: ['Shallow', 'Deep', 'Dark', 'Wide'] },
    { name: 'Warm', ar: 'دافئ ومريح', img: '☕', o: ['Warm', 'Hot', 'Cold', 'Cool'] },
    { name: 'Cool', ar: 'معتدل البرودة ومنعش', img: '🧊', o: ['Cool', 'Warm', 'Hot', 'Dry'] },
    { name: 'Fresh', ar: 'طازج كالسلطة الخضراء', img: '🥗', o: ['Fresh', 'Old', 'Rotten', 'Dry'] },
    { name: 'Delicious', ar: 'شهي ولذيذ الطعم', img: '😋', o: ['Delicious', 'Bad', 'Bitter', 'Sour'] },
    { name: 'Pretty', ar: 'جميلة وبديعة كالأزهار', img: '🌸', o: ['Pretty', 'Ugly', 'Old', 'Dark'] },
    { name: 'Brave', ar: 'شجاع ومقدام كالأسد', img: '🦁', o: ['Brave', 'Scared', 'Shy', 'Weak'] },
    { name: 'Clever', ar: 'ذكي وماهر في التفكير', img: '🧠', o: ['Clever', 'Silly', 'Slow', 'Tired'] },
    { name: 'Kind', ar: 'عطوف وطيب القلب', img: '🤝', o: ['Kind', 'Mean', 'Angry', 'Bad'] },
    { name: 'Funny', ar: 'مضحك ومرح كالمهرج', img: '🤡', o: ['Funny', 'Serious', 'Sad', 'Boring'] },
    { name: 'Young', ar: 'شاب وصغير السن كالطفل', img: '👶', o: ['Young', 'Old', 'Ancient', 'Tired'] },
    { name: 'Old', ar: 'عجوز وكبير في السن', img: '👴', o: ['Old', 'Young', 'New', 'Fresh'] },
    { name: 'New', ar: 'جديد تماماً كالهدية', img: '🎁', o: ['New', 'Old', 'Broken', 'Lost'] },
    { name: 'Friendly', ar: 'ودود وأليف كالجرو', img: '🐶', o: ['Friendly', 'Fierce', 'Wild', 'Mean'] },
    { name: 'Dry', ar: 'جاف وخالٍ من الماء كالصحراء', img: '🏜️', o: ['Dry', 'Wet', 'Rainy', 'Cold'] },
    { name: 'Wet', ar: 'مبتل بقطرات المطر', img: '🌧️', o: ['Wet', 'Dry', 'Warm', 'Sunny'] },
    { name: 'Rich', ar: 'غني وثري بالمال', img: '💰', o: ['Rich', 'Poor', 'Cheap', 'Broke'] },
    { name: 'Busy', ar: 'مشغول بالعمل كالنحلة النشيطة', img: '🐝', o: ['Busy', 'Free', 'Lazy', 'Asleep'] },
    { name: 'Gentle', ar: 'وديع ورقيق كالحمامة', img: '🕊️', o: ['Gentle', 'Rough', 'Fierce', 'Loud'] },
    { name: 'Colorful', ar: 'ملون ومبهج كقوس قزح', img: '🌈', o: ['Colorful', 'Dark', 'Plain', 'Black'] },
    { name: 'Magical', ar: 'سحري وخيالي رائع', img: '✨', o: ['Magical', 'Real', 'Simple', 'Boring'] }
  ];
  games['الصفات والأوصاف بالإنجليزية'] = adjectivesList.map((d, i) => ({
    id: 15001 + i,
    question: `ما هي الصفة بالإنجليزية التي تعبر عن (${d.ar})؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `الصفة التي تعني ${d.ar} هي '${d.name}'.`
  }));

  // 16. الأفعال والحركات بالإنجليزية
  const verbsList = [
    { name: 'Run', ar: 'يجري أو يركض بسرعة', img: '🏃', o: ['Run', 'Walk', 'Sleep', 'Sit'] },
    { name: 'Walk', ar: 'يمشي بهدوء', img: '🚶', o: ['Walk', 'Run', 'Jump', 'Fly'] },
    { name: 'Jump', ar: 'يقفز في الهواء للأعلى', img: '🦘', o: ['Jump', 'Fall', 'Sit', 'Lie'] },
    { name: 'Hop', ar: 'يقفز على قدم واحدة كالأرنب', img: '🐰', o: ['Hop', 'Run', 'Walk', 'Crawl'] },
    { name: 'Swim', ar: 'يسبح بمهارة في الماء', img: '🏊', o: ['Swim', 'Fly', 'Walk', 'Climb'] },
    { name: 'Fly', ar: 'يطير ويحلق بجناحيه في السماء', img: '🦅', o: ['Fly', 'Swim', 'Crawl', 'Jump'] },
    { name: 'Climb', ar: 'يتسلق الجبل أو الشجرة', img: '🧗', o: ['Climb', 'Fall', 'Slide', 'Run'] },
    { name: 'Crawl', ar: 'يزحف على الأرض كالطفل الصغير', img: '👶', o: ['Crawl', 'Walk', 'Run', 'Fly'] },
    { name: 'Eat', ar: 'يأكل الطعام بشهية', img: '🍽️', o: ['Eat', 'Drink', 'Cook', 'Sleep'] },
    { name: 'Drink', ar: 'يشرب الماء أو العصير', img: '🥤', o: ['Drink', 'Eat', 'Wash', 'Pour'] },
    { name: 'Sleep', ar: 'ينام نوماً هنيئاً في السرير', img: '😴', o: ['Sleep', 'Wake up', 'Run', 'Play'] },
    { name: 'Wake up', ar: 'يستيقظ من النوم بنشاط', img: '⏰', o: ['Wake up', 'Sleep', 'Rest', 'Dream'] },
    { name: 'Read', ar: 'يقرأ في كتاب مفيد', img: '📖', o: ['Read', 'Write', 'Draw', 'Listen'] },
    { name: 'Write', ar: 'يكتب بالقلم في الدفتر', img: '✍️', o: ['Write', 'Read', 'Color', 'Paint'] },
    { name: 'Draw', ar: 'يرسم لوحة جميلة', img: '🎨', o: ['Draw', 'Write', 'Sing', 'Read'] },
    { name: 'Sing', ar: 'يغني أنشودة مبهجة', img: '🎤', o: ['Sing', 'Dance', 'Talk', 'Listen'] },
    { name: 'Dance', ar: 'يرقص على إيقاع الموسيقى', img: '💃', o: ['Dance', 'Sing', 'Sit', 'Walk'] },
    { name: 'Play', ar: 'يلعب ويمرح بالألعاب', img: '⚽', o: ['Play', 'Work', 'Sleep', 'Study'] },
    { name: 'Laugh', ar: 'يضحك من قلبه بفرح', img: '😂', o: ['Laugh', 'Cry', 'Frown', 'Sleep'] },
    { name: 'Cry', ar: 'يبكي بحرقة', img: '😭', o: ['Cry', 'Laugh', 'Smile', 'Sing'] },
    { name: 'Smile', ar: 'يبتسم ابتسامة لطيفة', img: '😊', o: ['Smile', 'Frown', 'Cry', 'Yawn'] },
    { name: 'Listen', ar: 'يستمع وينصت للأصوات', img: '🎧', o: ['Listen', 'Speak', 'Watch', 'Read'] },
    { name: 'Watch', ar: 'يشاهد التلفاز أو المشهد', img: '📺', o: ['Watch', 'Listen', 'Sleep', 'Close'] },
    { name: 'Speak', ar: 'يتحدث ويتكلم بالكلمات', img: '🗣️', o: ['Speak', 'Listen', 'Silence', 'Sing'] },
    { name: 'Shout', ar: 'يصرخ بصوت عالٍ جداً', img: '📢', o: ['Shout', 'Whisper', 'Talk', 'Listen'] },
    { name: 'Whisper', ar: 'يهمس بصوت منخفض خافت', img: '🤫', o: ['Whisper', 'Shout', 'Yell', 'Sing'] },
    { name: 'Wash', ar: 'يغسل يديه ووجهه بالماء', img: '🧼', o: ['Wash', 'Dry', 'Dirty', 'Cook'] },
    { name: 'Clean', ar: 'ينظف الغرفة والأغراض', img: '🧹', o: ['Clean', 'Mess', 'Break', 'Drop'] },
    { name: 'Cook', ar: 'يطبخ وجبة لذيذة في المطبخ', img: '🍳', o: ['Cook', 'Eat', 'Drink', 'Wash'] },
    { name: 'Cut', ar: 'يقص أو يقطع بالمقص', img: '✂️', o: ['Cut', 'Glue', 'Tear', 'Fold'] },
    { name: 'Push', ar: 'يدفع الشيء للأمام بعيداً', img: '🚪', o: ['Push', 'Pull', 'Hold', 'Drop'] },
    { name: 'Pull', ar: 'يسحب الشيء نحوه باليد', img: '🧲', o: ['Pull', 'Push', 'Throw', 'Hit'] },
    { name: 'Open', ar: 'يفتح الباب أو الكتاب', img: '📖', o: ['Open', 'Close', 'Lock', 'Break'] },
    { name: 'Close', ar: 'يغلق الصندوق أو النافذة', img: '📕', o: ['Close', 'Open', 'Drop', 'Push'] },
    { name: 'Catch', ar: 'يمسك الكرة الملتقطة ببراعة', img: '⚾', o: ['Catch', 'Throw', 'Drop', 'Kick'] },
    { name: 'Throw', ar: 'يرمي أو يقذف الكرة عالياً', img: '🏐', o: ['Throw', 'Catch', 'Hold', 'Kick'] },
    { name: 'Kick', ar: 'يركل الكرة بقدمه', img: '⚽', o: ['Kick', 'Throw', 'Catch', 'Hit'] },
    { name: 'Ride', ar: 'يركب الدراجة أو الحصان', img: '🚲', o: ['Ride', 'Drive', 'Walk', 'Fly'] },
    { name: 'Drive', ar: 'يقود السيارة على الطريق', img: '🚗', o: ['Drive', 'Ride', 'Fly', 'Sail'] },
    { name: 'Build', ar: 'يبني برجاً من المكعبات', img: '🧱', o: ['Build', 'Break', 'Drop', 'Cut'] },
    { name: 'Plant', ar: 'يزرع شتلة في الحديقة', img: '🌱', o: ['Plant', 'Cut', 'Burn', 'Pull'] },
    { name: 'Touch', ar: 'يلمس الشيء بإصبعه', img: '👆', o: ['Touch', 'See', 'Hear', 'Taste'] },
    { name: 'Smell', ar: 'يشم الرائحة الزكية بالأنف', img: '👃', o: ['Smell', 'Taste', 'Touch', 'See'] },
    { name: 'Taste', ar: 'يتذوق النكهة باللسان', img: '👅', o: ['Taste', 'Smell', 'Touch', 'Hear'] },
    { name: 'Help', ar: 'يساعد ويقدم العون للآخرين', img: '🤝', o: ['Help', 'Hurt', 'Leave', 'Stop'] },
    { name: 'Wait', ar: 'ينتظر وصول الحافلة بصبر', img: '⏳', o: ['Wait', 'Go', 'Hurry', 'Run'] },
    { name: 'Think', ar: 'يفكر بعمق لإيجاد الحل', img: '🤔', o: ['Think', 'Forget', 'Sleep', 'Talk'] },
    { name: 'Sit', ar: 'يجلس على الكرسي باعتدال', img: '🪑', o: ['Sit', 'Stand', 'Run', 'Lie'] },
    { name: 'Stand', ar: 'يقف مستقيماً على قدميه', img: '🧍', o: ['Stand', 'Sit', 'Kneel', 'Fall'] },
    { name: 'Clap', ar: 'يصفق بيديه تشجيعاً وفرحاً', img: '👏', o: ['Clap', 'Wave', 'Punch', 'Hold'] }
  ];
  games['الأفعال والحركات بالإنجليزية'] = verbsList.map((d, i) => ({
    id: 16001 + i,
    question: `ما هو الفعل بالإنجليزية الذي يعبر عن (${d.ar})؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `الفعل الذي يعني ${d.ar} هو '${d.name}'.`
  }));

  // 17. المهن والوظائف بالإنجليزية
  const jobsList = [
    { name: 'Teacher', ar: 'المعلم والمربي الفاضل', img: '👨‍🏫', o: ['Teacher', 'Doctor', 'Pilot', 'Chef'] },
    { name: 'Doctor', ar: 'الطبيب الذي يعالج المرضى', img: '👨‍⚕️', o: ['Doctor', 'Nurse', 'Dentist', 'Vet'] },
    { name: 'Nurse', ar: 'الممرضة الرحيمة المساعدة', img: '👩‍⚕️', o: ['Nurse', 'Doctor', 'Teacher', 'Baker'] },
    { name: 'Police Officer', ar: 'ضابط الشرطة حامي الأمان', img: '👮', o: ['Police Officer', 'Firefighter', 'Soldier', 'Guard'] },
    { name: 'Firefighter', ar: 'رجل الإطفاء الشجاع', img: '👨‍🚒', o: ['Firefighter', 'Police Officer', 'Pilot', 'Builder'] },
    { name: 'Pilot', ar: 'الطيار قائد الطائرة في الجو', img: '👨‍✈️', o: ['Pilot', 'Captain', 'Driver', 'Astronaut'] },
    { name: 'Chef', ar: 'الطاهي والشيف المحترف', img: '👨‍🍳', o: ['Chef', 'Baker', 'Waiter', 'Farmer'] },
    { name: 'Farmer', ar: 'المزارع حاصد الزرع والخير', img: '👨‍🌾', o: ['Farmer', 'Gardener', 'Builder', 'Fisherman'] },
    { name: 'Builder', ar: 'البنّاء المشيد للمنازل', img: '👷', o: ['Builder', 'Carpenter', 'Painter', 'Plumber'] },
    { name: 'Astronaut', ar: 'رائد الفضاء المستكشف للكواكب', img: '👨‍🚀', o: ['Astronaut', 'Pilot', 'Scientist', 'Diver'] },
    { name: 'Dentist', ar: 'طبيب الأسنان المعالج للتسوس', img: '🦷', o: ['Dentist', 'Doctor', 'Optician', 'Surgeon'] },
    { name: 'Vet', ar: 'الطبيب البيطري معالج الحيوانات', img: '🐶', o: ['Vet', 'Doctor', 'Farmer', 'Zookeeper'] },
    { name: 'Artist', ar: 'الفنان الرسام المبدع', img: '🎨', o: ['Artist', 'Singer', 'Writer', 'Photographer'] },
    { name: 'Singer', ar: 'المغني صاحب الصوت العذب', img: '🎤', o: ['Singer', 'Musician', 'Actor', 'Dancer'] },
    { name: 'Musician', ar: 'العازف الموسيقي على الآلات', img: '🎸', o: ['Musician', 'Singer', 'Composer', 'Conductor'] },
    { name: 'Driver', ar: 'السائق المحترف للحافلة أو السيارة', img: '🚗', o: ['Driver', 'Pilot', 'Captain', 'Rider'] },
    { name: 'Baker', ar: 'الخباز صانع المعجنات والخبز', img: '🥖', o: ['Baker', 'Chef', 'Cook', 'Butcher'] },
    { name: 'Carpenter', ar: 'النجار صانع الأثاث الخشبي', img: '🪚', o: ['Carpenter', 'Builder', 'Blacksmith', 'Plumber'] },
    { name: 'Mechanic', ar: 'الميكانيكي مصلح محركات السيارات', img: '🔧', o: ['Mechanic', 'Electrician', 'Plumber', 'Driver'] },
    { name: 'Plumber', ar: 'السباك مصلح أنابيب المياه والصنابير', img: '🪠', o: ['Plumber', 'Mechanic', 'Electrician', 'Carpenter'] },
    { name: 'Electrician', ar: 'فني الكهرباء المصلح للإنارة', img: '💡', o: ['Electrician', 'Mechanic', 'Plumber', 'Builder'] },
    { name: 'Mail Carrier', ar: 'ساعي البريد موصل الرسائل والطرود', img: '📬', o: ['Mail Carrier', 'Driver', 'Delivery Man', 'Officer'] },
    { name: 'Scientist', ar: 'العالم والباحث في المختبر', img: '🔬', o: ['Scientist', 'Doctor', 'Teacher', 'Astronaut'] },
    { name: 'Judge', ar: 'القاضي العادل في المحكمة', img: '⚖️', o: ['Judge', 'Lawyer', 'Police Officer', 'Guard'] },
    { name: 'Lawyer', ar: 'المحامي المدافع عن الحقوق', img: '💼', o: ['Lawyer', 'Judge', 'Teacher', 'Officer'] },
    { name: 'Captain', ar: 'قبطان السفينة البحرية', img: '👨‍✈️', o: ['Captain', 'Pilot', 'Sailor', 'Diver'] },
    { name: 'Sailor', ar: 'البحار على ظهر السفينة', img: '⛵', o: ['Sailor', 'Captain', 'Fisherman', 'Swimmer'] },
    { name: 'Football Player', ar: 'لاعب كرة القدم الهداف', img: '⚽', o: ['Football Player', 'Coach', 'Referee', 'Athlete'] },
    { name: 'Swimmer', ar: 'السباح الماهر في المسبح', img: '🏊', o: ['Swimmer', 'Diver', 'Lifeguard', 'Sailor'] },
    { name: 'Photographer', ar: 'المصور الملتقط لأجمل الصور', img: '📷', o: ['Photographer', 'Artist', 'Reporter', 'Director'] },
    { name: 'Writer', ar: 'الكاتب والمؤلف للقصص المشوقة', img: '✍️', o: ['Writer', 'Journalist', 'Reader', 'Teacher'] },
    { name: 'Librarian', ar: 'أمين المكتبة المشرف على الكتب', img: '📚', o: ['Librarian', 'Teacher', 'Bookseller', 'Writer'] },
    { name: 'Florist', ar: 'بائع الأزهار والورود المنسقة', img: '💐', o: ['Florist', 'Gardener', 'Farmer', 'Decorator'] },
    { name: 'Barber', ar: 'الحلاق مصفف وقاص الشعر', img: '💇', o: ['Barber', 'Tailor', 'Doctor', 'Artist'] },
    { name: 'Tailor', ar: 'الخياط صانع وحائك الملابس', img: '🧵', o: ['Tailor', 'Barber', 'Designer', 'Shoemaker'] },
    { name: 'Waiter', ar: 'نادل المطعم المقدم للأطباق', img: '🍽️', o: ['Waiter', 'Chef', 'Cook', 'Manager'] },
    { name: 'Lifeguard', ar: 'منقذ الشاطئ والمسبح الماهر', img: '🛟', o: ['Lifeguard', 'Swimmer', 'Diver', 'Police Officer'] },
    { name: 'Guard', ar: 'الحارس الأمين للمبنى', img: '💂', o: ['Guard', 'Police Officer', 'Soldier', 'Doorman'] },
    { name: 'Cleaner', ar: 'عامل النظافة المجتهد', img: '🧹', o: ['Cleaner', 'Gardener', 'Worker', 'Painter'] },
    { name: 'Gardener', ar: 'البستاني المعتني بزهور الحديقة', img: '🌻', o: ['Gardener', 'Farmer', 'Florist', 'Cleaner'] },
    { name: 'Diver', ar: 'الغواص المستكشف لأعماق البحر', img: '🤿', o: ['Diver', 'Swimmer', 'Sailor', 'Fisherman'] },
    { name: 'Reporter', ar: 'المراسل الصحفي ومقدم الأخبار', img: '📺', o: ['Reporter', 'Writer', 'Photographer', 'Actor'] },
    { name: 'Actor', ar: 'الممثل المسرحي والسينمائي', img: '🎭', o: ['Actor', 'Singer', 'Director', 'Dancer'] },
    { name: 'Magician', ar: 'الساحر الاستعراضي لاعب الخدع', img: '🎩', o: ['Magician', 'Actor', 'Clown', 'Musician'] },
    { name: 'Soldier', ar: 'الجندي المدافع عن الوطن', img: '🪖', o: ['Soldier', 'Police Officer', 'Guard', 'Pilot'] },
    { name: 'Coach', ar: 'المدرب الرياضي الموجه للفريق', img: '📣', o: ['Coach', 'Player', 'Referee', 'Teacher'] },
    { name: 'Fisherman', ar: 'صياد الأسماك بالشباك والصنارة', img: '🎣', o: ['Fisherman', 'Sailor', 'Captain', 'Diver'] },
    { name: 'Zookeeper', ar: 'حارس ومربي حيوانات الحديقة', img: '🦁', o: ['Zookeeper', 'Vet', 'Farmer', 'Gardener'] },
    { name: 'Cashier', ar: 'أمين الصندوق (الكاشير) بالمتجر', img: '🛒', o: ['Cashier', 'Banker', 'Seller', 'Waiter'] },
    { name: 'Optician', ar: 'أخصائي العيون وفاحص النظارات', img: '👓', o: ['Optician', 'Dentist', 'Doctor', 'Pharmacist'] }
  ];
  games['المهن والوظائف بالإنجليزية'] = jobsList.map((d, i) => ({
    id: 17001 + i,
    question: `ما اسم مهنة (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `مهنة ${d.ar} تُسمى بالإنجليزية '${d.name}'.`
  }));

  // 18. وسائل النقل والمواصلات بالإنجليزية
  const transportList = [
    { name: 'Car', ar: 'السيارة العائلية المريحة', img: '🚗', o: ['Car', 'Bus', 'Bike', 'Train'] },
    { name: 'Bus', ar: 'حافلة الركاب الكبيرة', img: '🚌', o: ['Bus', 'Car', 'Truck', 'Train'] },
    { name: 'School Bus', ar: 'حافلة المدرسة الصفراء للطلاب', img: '🚌', o: ['School Bus', 'Taxi', 'Car', 'Van'] },
    { name: 'Taxi', ar: 'سيارة الأجرة (التاكسي)', img: '🚕', o: ['Taxi', 'Police Car', 'Bus', 'Truck'] },
    { name: 'Police Car', ar: 'سيارة الشرطة ذات الصفارة', img: '🚓', o: ['Police Car', 'Ambulance', 'Fire Truck', 'Taxi'] },
    { name: 'Ambulance', ar: 'سيارة الإسعاف لنقل المرضى', img: '🚑', o: ['Ambulance', 'Police Car', 'Fire Engine', 'Van'] },
    { name: 'Fire Engine', ar: 'شاحنة الإطفاء لإخماد النيران', img: '🚒', o: ['Fire Engine', 'Ambulance', 'Truck', 'Tractor'] },
    { name: 'Train', ar: 'القطار الطويل على السكك الحديدية', img: '🚆', o: ['Train', 'Subway', 'Tram', 'Bus'] },
    { name: 'Bullet Train', ar: 'القطار السريع فائق السرعة', img: '🚅', o: ['Bullet Train', 'Tram', 'Bus', 'Airplane'] },
    { name: 'Subway', ar: 'مترو الأنفاق السائر تحت الأرض', img: '🚇', o: ['Subway', 'Train', 'Bus', 'Tram'] },
    { name: 'Tram', ar: 'الترام الكهربائي داخل المدينة', img: '🚊', o: ['Tram', 'Subway', 'Train', 'Bus'] },
    { name: 'Airplane', ar: 'الطائرة المحلقة بين السحاب', img: '✈️', o: ['Airplane', 'Helicopter', 'Rocket', 'Bird'] },
    { name: 'Helicopter', ar: 'الهليكوبتر (المروحية) ذات المروحة', img: '🚁', o: ['Helicopter', 'Airplane', 'Drone', 'Parachute'] },
    { name: 'Rocket', ar: 'الصاروخ المنطلق نحو الفضاء', img: '🚀', o: ['Rocket', 'Airplane', 'Satellite', 'Meteor'] },
    { name: 'Bicycle', ar: 'الدراجة الهوائية الرياضية', img: '🚲', o: ['Bicycle', 'Motorcycle', 'Scooter', 'Skateboard'] },
    { name: 'Motorcycle', ar: 'الدراجة النارية السريعة', img: '🏍️', o: ['Motorcycle', 'Bicycle', 'Scooter', 'Car'] },
    { name: 'Scooter', ar: 'السكوتر الممتع للأطفال', img: '🛴', o: ['Scooter', 'Skateboard', 'Bicycle', 'Roller Skates'] },
    { name: 'Boat', ar: 'القارب الصغير في البحيرة', img: '⛵', o: ['Boat', 'Ship', 'Submarine', 'Canoe'] },
    { name: 'Ship', ar: 'السفينة البحرية الضخمة', img: '🚢', o: ['Ship', 'Boat', 'Yacht', 'Ferry'] },
    { name: 'Cruise Ship', ar: 'السفينة السياحية الفاخرة', img: '🛳️', o: ['Cruise Ship', 'Cargo Ship', 'Boat', 'Submarine'] },
    { name: 'Yacht', ar: 'اليخت الأبيض الراقي', img: '🛥️', o: ['Yacht', 'Boat', 'Ferry', 'Canoe'] },
    { name: 'Submarine', ar: 'الغواصة الغائصة في أعماق المحيط', img: '🤿', o: ['Submarine', 'Ship', 'Boat', 'Fish'] },
    { name: 'Truck', ar: 'الشاحنة القوية لنقل البضائع', img: '🚚', o: ['Truck', 'Van', 'Bus', 'Car'] },
    { name: 'Delivery Van', ar: 'شاحنة التوصيل المغلقة (الفان)', img: '🚐', o: ['Delivery Van', 'Car', 'Bus', 'Taxi'] },
    { name: 'Tractor', ar: 'الجرار الزراعي في الحقل', img: '🚜', o: ['Tractor', 'Bulldozer', 'Truck', 'Car'] },
    { name: 'Hot Air Balloon', ar: 'منطاد الهواء الساخن الملون', img: '🎈', o: ['Hot Air Balloon', 'Parachute', 'Airplane', 'Glider'] },
    { name: 'Canoe', ar: 'قارب الكانو النهري ذو المجداف', img: '🛶', o: ['Canoe', 'Raft', 'Boat', 'Sailboat'] },
    { name: 'Raft', ar: 'الطوافة الخشبية العائمة', img: '🪵', o: ['Raft', 'Boat', 'Canoe', 'Ship'] },
    { name: 'Jet Ski', ar: 'الدراجة المائية (الجيت سكي)', img: '🌊', o: ['Jet Ski', 'Motorboat', 'Boat', 'Surfboard'] },
    { name: 'Cable Car', ar: 'التلفريك المعلق بين الجبال', img: '🚠', o: ['Cable Car', 'Train', 'Elevator', 'Helicopter'] },
    { name: 'Skateboard', ar: 'لوح التزلج ذو العجلات الأربع', img: '🛹', o: ['Skateboard', 'Scooter', 'Roller Skates', 'Sled'] },
    { name: 'Roller Skates', ar: 'حذاء التزلج المدولب', img: '🛼', o: ['Roller Skates', 'Skateboard', 'Ice Skates', 'Shoes'] },
    { name: 'Ferry', ar: 'العبّارة الناقلة للسيارات والركاب', img: '⛴️', o: ['Ferry', 'Ship', 'Yacht', 'Boat'] },
    { name: 'Sailboat', ar: 'القارب الشراعي المعتمد على الرياح', img: '⛵', o: ['Sailboat', 'Motorboat', 'Ship', 'Canoe'] },
    { name: 'Monorail', ar: 'قطار المونوريل أحادي السكة', img: '🚝', o: ['Monorail', 'Subway', 'Train', 'Tram'] },
    { name: 'Bulldozer', ar: 'الجرافة الضخمة لتمهيد الطرق', img: '🚜', o: ['Bulldozer', 'Tractor', 'Truck', 'Crane'] },
    { name: 'Garbage Truck', ar: 'شاحنة جمع النفايات النظيفة', img: '🚛', o: ['Garbage Truck', 'Fire Engine', 'Delivery Van', 'Bus'] },
    { name: 'Cement Mixer', ar: 'خلاطة الإسمنت الدوارة للبناء', img: '🚚', o: ['Cement Mixer', 'Bulldozer', 'Truck', 'Tractor'] },
    { name: 'Horse Carriage', ar: 'العربة التي يجرها الحصان', img: '🐴', o: ['Horse Carriage', 'Car', 'Wagon', 'Cart'] },
    { name: 'Sled', ar: 'الزلاجة المنزلقة على الجليد', img: '🛷', o: ['Sled', 'Skateboard', 'Skis', 'Snowboard'] },
    { name: 'Spaceship', ar: 'مركبة الفضاء الكونية', img: '🛸', o: ['Spaceship', 'Airplane', 'Rocket', 'Satellite'] },
    { name: 'Cargo Ship', ar: 'سفينة شحن الحاويات العملاقة', img: '🚢', o: ['Cargo Ship', 'Cruise Ship', 'Boat', 'Ferry'] },
    { name: 'Kayak', ar: 'قارب الكاياك الرياضي السريع', img: '🛶', o: ['Kayak', 'Canoe', 'Boat', 'Raft'] },
    { name: 'Motorboat', ar: 'القارب المزود بمحرك سريع', img: '🚤', o: ['Motorboat', 'Sailboat', 'Canoe', 'Raft'] },
    { name: 'Airport', ar: 'المطار الدولي مهبط الطائرات', img: '🛫', o: ['Airport', 'Train Station', 'Harbor', 'Bus Stop'] },
    { name: 'Train Station', ar: 'محطة القطار المركزية', img: '🚉', o: ['Train Station', 'Airport', 'Bus Station', 'Port'] },
    { name: 'Bus Stop', ar: 'موقف ومحطة انتظار الحافلات', img: '🚏', o: ['Bus Stop', 'Train Station', 'Airport', 'Taxi Stand'] },
    { name: 'Harbor', ar: 'الميناء والخلجان لرسو السفن', img: '⚓', o: ['Harbor', 'Airport', 'Station', 'Road'] },
    { name: 'Traffic Light', ar: 'إشارة المرور ثلاثية الألوان', img: '🚦', o: ['Traffic Light', 'Street Lamp', 'Signboard', 'Stop Sign'] },
    { name: 'Parachute', ar: 'مظلة الهبوط الآمن من الطائرة', img: '🪂', o: ['Parachute', 'Balloon', 'Kite', 'Airplane'] }
  ];
  games['وسائل النقل والمواصلات بالإنجليزية'] = transportList.map((d, i) => ({
    id: 18001 + i,
    question: `ما اسم وسيلة النقل (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية تُسمى '${d.name}'.`
  }));

  // 19. الاتجاهات والأماكن بالإنجليزية
  const directionsPlaces = [
    { name: 'Left', ar: 'جهة اليسار', img: '⬅️', o: ['Left', 'Right', 'Up', 'Down'] },
    { name: 'Right', ar: 'جهة اليمين', img: '➡️', o: ['Right', 'Left', 'Straight', 'Back'] },
    { name: 'Up', ar: 'نحو الأعلى والقمة', img: '⬆️', o: ['Up', 'Down', 'North', 'South'] },
    { name: 'Down', ar: 'نحو الأسفل والقاع', img: '⬇️', o: ['Down', 'Up', 'East', 'West'] },
    { name: 'North', ar: 'اتجاه الشمال بالبوصلة', img: '🧭', o: ['North', 'South', 'East', 'West'] },
    { name: 'South', ar: 'اتجاه الجنوب بالبوصلة', img: '🧭', o: ['South', 'North', 'West', 'East'] },
    { name: 'East', ar: 'اتجاه الشرق شروق الشمس', img: '🧭', o: ['East', 'West', 'North', 'South'] },
    { name: 'West', ar: 'اتجاه الغرب غروب الشمس', img: '🧭', o: ['West', 'East', 'South', 'North'] },
    { name: 'Straight', ar: 'السير للأمام مباشرة بخط مستقيم', img: '⬆️', o: ['Straight', 'Left', 'Right', 'Back'] },
    { name: 'Behind', ar: 'في الخلف وخلف الشيء', img: '🔙', o: ['Behind', 'In front', 'Inside', 'Outside'] },
    { name: 'In front', ar: 'في الأمام وقدام الشيء', img: '🚶', o: ['In front', 'Behind', 'Under', 'Over'] },
    { name: 'Between', ar: 'بين الشيئين في الوسط', img: '↔️', o: ['Between', 'Next to', 'Behind', 'Inside'] },
    { name: 'Inside', ar: 'في الداخل', img: '📥', o: ['Inside', 'Outside', 'Under', 'Above'] },
    { name: 'Outside', ar: 'في الخارج بالهواء الطلق', img: '📤', o: ['Outside', 'Inside', 'Near', 'Far'] },
    { name: 'Near', ar: 'قريب على مقربة', img: '📍', o: ['Near', 'Far', 'Away', 'Over'] },
    { name: 'Far', ar: 'بعيد في المسافة', img: '📍', o: ['Far', 'Near', 'Here', 'Close'] },
    { name: 'School', ar: 'المدرسة صرح التعليم', img: '🏫', o: ['School', 'Hospital', 'Park', 'Library'] },
    { name: 'Park', ar: 'الحديقة والمنتزه العام', img: '🏞️', o: ['Park', 'Zoo', 'Garden', 'Forest'] },
    { name: 'Hospital', ar: 'المستشفى مكان علاج المرضى', img: '🏥', o: ['Hospital', 'Clinic', 'Pharmacy', 'School'] },
    { name: 'Library', ar: 'المكتبة المليئة بالكتب العلمية', img: '📚', o: ['Library', 'Bookstore', 'School', 'Museum'] },
    { name: 'Zoo', ar: 'حديقة الحيوانات المتنوعة', img: '🦁', o: ['Zoo', 'Farm', 'Park', 'Circus'] },
    { name: 'Museum', ar: 'المتحف حافظ الآثار والتاريخ', img: '🏛️', o: ['Museum', 'Palace', 'Library', 'Theater'] },
    { name: 'Supermarket', ar: 'السوبرماركت لشراء الأطعمة والمستلزمات', img: '🛒', o: ['Supermarket', 'Bakery', 'Pharmacy', 'Mall'] },
    { name: 'Bakery', ar: 'المخبز صانع الفطائر والخبز', img: '🥖', o: ['Bakery', 'Restaurant', 'Cafe', 'Kitchen'] },
    { name: 'Cinema', ar: 'صالة السينما لعرض الأفلام', img: '🎬', o: ['Cinema', 'Theater', 'Stadium', 'Museum'] },
    { name: 'Playground', ar: 'ملعب الأطفال المزود بالمراجيح والألعاب', img: '🛝', o: ['Playground', 'Stadium', 'Gym', 'Park'] },
    { name: 'Bank', ar: 'البنك المصرفي لحفظ الأموال', img: '🏦', o: ['Bank', 'Post Office', 'Hotel', 'Shop'] },
    { name: 'Hotel', ar: 'الفندق المريح لإقامة المسافرين', img: '🏨', o: ['Hotel', 'House', 'Apartment', 'Motel'] },
    { name: 'Restaurant', ar: 'المطعم لتقديم أشهى الوجبات', img: '🍽️', o: ['Restaurant', 'Cafe', 'Bakery', 'Kitchen'] },
    { name: 'Farm', ar: 'المزرعة الخضراء لتربية الماشية', img: '🚜', o: ['Farm', 'Garden', 'Forest', 'Village'] },
    { name: 'Beach', ar: 'شاطئ البحر ذو الرمال الذهبية', img: '🏖️', o: ['Beach', 'Pool', 'Island', 'Desert'] },
    { name: 'Mosque', ar: 'المسجد المبارك للصلاة والعبادة', img: '🕌', o: ['Mosque', 'Palace', 'Tower', 'Castle'] },
    { name: 'Post Office', ar: 'مكتب البريد لإرسال الطرود', img: '🏣', o: ['Post Office', 'Bank', 'Police Station', 'Office'] },
    { name: 'Police Station', ar: 'مركز وقسم الشرطة لحفظ النظام', img: '👮', o: ['Police Station', 'Fire Station', 'Court', 'Prison'] },
    { name: 'Fire Station', ar: 'محطة الإطفاء ومقر سيارات الإطفاء', img: '🚒', o: ['Fire Station', 'Police Station', 'Hospital', 'Garage'] },
    { name: 'Stadium', ar: 'ملعب واستاد كرة القدم الكبير', img: '🏟️', o: ['Stadium', 'Gym', 'Playground', 'Arena'] },
    { name: 'Pharmacy', ar: 'الصيدلية لصرف الدواء والعلاج', img: '💊', o: ['Pharmacy', 'Hospital', 'Clinic', 'Shop'] },
    { name: 'Castle', ar: 'القلعة الأثرية والحصن الشامخ', img: '🏰', o: ['Castle', 'Tower', 'House', 'Palace'] },
    { name: 'Forest', ar: 'الغابة الكثيفة ذات الأشجار العالية', img: '🌲', o: ['Forest', 'Jungle', 'Park', 'Garden'] },
    { name: 'Mountain', ar: 'الجبل الشاهق ذو القمة العالية', img: '🏔️', o: ['Mountain', 'Hill', 'Valley', 'Rock'] },
    { name: 'Island', ar: 'الجزيرة المحاطة بالمياه من كل جهة', img: '🏝️', o: ['Island', 'Beach', 'Peninsula', 'Coast'] },
    { name: 'Bridge', ar: 'الجسر المشيد فوق النهر لتسهيل العبور', img: '🌉', o: ['Bridge', 'Road', 'Tunnel', 'Highway'] },
    { name: 'Swimming Pool', ar: 'حمام ومسبح السباحة المنعش', img: '🏊', o: ['Swimming Pool', 'Lake', 'Beach', 'River'] },
    { name: 'Bookstore', ar: 'متجر بيع الكتب والقصص', img: '📚', o: ['Bookstore', 'Library', 'School', 'Shop'] },
    { name: 'Toy Store', ar: 'متجر الألعاب المفضلة للأطفال', img: '🧸', o: ['Toy Store', 'Supermarket', 'Mall', 'Game Room'] },
    { name: 'Cafe', ar: 'المقهى الهادئ لتناول المشروبات', img: '☕', o: ['Cafe', 'Restaurant', 'Bakery', 'Bar'] },
    { name: 'Petrol Station', ar: 'محطة الوقود لتزويد السيارات بالبنزين', img: '⛽', o: ['Petrol Station', 'Garage', 'Car Wash', 'Parking'] },
    { name: 'Tunnel', ar: 'النفق الممر عبر الجبل تحت الأرض', img: '🚇', o: ['Tunnel', 'Bridge', 'Road', 'Track'] },
    { name: 'Market', ar: 'السوق الشعبي لبيع الخضار والفواكه', img: '🏪', o: ['Market', 'Mall', 'Supermarket', 'Bazaar'] },
    { name: 'City', ar: 'المدينة الكبيرة ذات الأبراج الشاهقة', img: '🏙️', o: ['City', 'Village', 'Town', 'Country'] }
  ];
  games['الاتجاهات والأماكن بالإنجليزية'] = directionsPlaces.map((d, i) => ({
    id: 19001 + i,
    question: `ما هو المصطلح بالإنجليزية الذي يعبر عن (${d.ar})؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} يُسمى بالإنجليزية '${d.name}'.`
  }));

  // 20. تحدي تكوين الجمل المفيدة بالإنجليزية
  const sentencesQuestions = [
    { q: 'أكمل الجملة: (The cat is ___ on the sofa) 🐱', img: '🐱', correct: 'sleeping', opts: ['sleeping', 'flying', 'driving', 'reading'], exp: 'القطة نائمة: The cat is sleeping.' },
    { q: 'أكمل الجملة: (The boy drinks fresh ___ every morning) 🥛', img: '🥛', correct: 'milk', opts: ['milk', 'stone', 'pencil', 'shoe'], exp: 'يشرب الحليب: drinks milk.' },
    { q: 'أكمل الجملة: (She is reading an interesting ___ in the library) 📖', img: '📖', correct: 'book', opts: ['book', 'car', 'tree', 'spoon'], exp: 'تقرأ كتاباً: reading a book.' },
    { q: 'أكمل الجملة: (The sun is ___ in the bright sky) ☀️', img: '☀️', correct: 'shining', opts: ['shining', 'jumping', 'crying', 'cooking'], exp: 'الشمس مشرقة: The sun is shining.' },
    { q: 'أكمل الجملة: (Birds can ___ high with their wings) 🦅', img: '🦅', correct: 'fly', opts: ['fly', 'drive', 'write', 'swim'], exp: 'الطيور تطير: Birds can fly.' },
    { q: 'أكمل الجملة: (Fish live in the blue ___) 🐟', img: '🐟', correct: 'water', opts: ['water', 'fire', 'sky', 'space'], exp: 'الأسماك تعيش في الماء: Fish live in water.' },
    { q: 'أكمل الجملة: (I brush my ___ before going to sleep) 🦷', img: '🦷', correct: 'teeth', opts: ['teeth', 'shoes', 'chair', 'bed'], exp: 'أنظف أسناني بالفرشاة: brush my teeth.' },
    { q: 'أكمل الجملة: (The rabbit loves to eat a crunchy ___) 🥕', img: '🥕', correct: 'carrot', opts: ['carrot', 'stone', 'plate', 'key'], exp: 'الأرنب يأكل الجزر: eats a carrot.' },
    { q: 'أكمل الجملة: (The football player kicks the ___) ⚽', img: '⚽', correct: 'ball', opts: ['ball', 'tree', 'cloud', 'book'], exp: 'يركل الكرة: kicks the ball.' },
    { q: 'أكمل الجملة: (We go to ___ to study and learn new things) 🏫', img: '🏫', correct: 'school', opts: ['school', 'bed', 'moon', 'river'], exp: 'نذهب للمدرسة: We go to school.' },
    { q: 'أكمل الجملة: (An elephant is very ___) 🐘', img: '🐘', correct: 'big', opts: ['big', 'tiny', 'thin', 'flying'], exp: 'الفيل ضخم وكبير: An elephant is big.' },
    { q: 'أكمل الجملة: (The sky is ___ on a sunny day) ☀️', img: '🌤️', correct: 'blue', opts: ['blue', 'green', 'black', 'red'], exp: 'السماء زرقاء: The sky is blue.' },
    { q: 'أكمل الجملة: (I wash my hands with water and ___) 🧼', img: '🧼', correct: 'soap', opts: ['soap', 'juice', 'sand', 'bread'], exp: 'نغسل أيدينا بالماء والصابون: with water and soap.' },
    { q: 'أكمل الجملة: (A dog has ___ legs) 🐶', img: '🐶', correct: 'four', opts: ['four', 'two', 'eight', 'ten'], exp: 'للكلب 4 أرجل: has four legs.' },
    { q: 'أكمل الجملة: (Apples grow on ___ in the orchard) 🍎', img: '🌳', correct: 'trees', opts: ['trees', 'clouds', 'water', 'stones'], exp: 'التفاح ينمو على الأشجار: grow on trees.' },
    { q: 'أكمل الجملة: (Firefighters put out ___ to save houses) 🚒', img: '🔥', correct: 'fires', opts: ['fires', 'water', 'books', 'lights'], exp: 'يطفئون الحرائق: put out fires.' },
    { q: 'أكمل الجملة: (A clock tells us the correct ___) ⏰', img: '⏰', correct: 'time', opts: ['time', 'color', 'weight', 'speed'], exp: 'الساعة تخبرنا بالوقت: tells us the time.' },
    { q: 'أكمل الجملة: (We use an umbrella when it is ___) 🌧️', img: '☂️', correct: 'raining', opts: ['raining', 'sunny', 'hot', 'dark'], exp: 'نستخدم المظلة عند المطر: when it is raining.' },
    { q: 'أكمل الجملة: (Cars drive on the paved ___) 🚗', img: '🛣️', correct: 'road', opts: ['road', 'sky', 'sea', 'cloud'], exp: 'تسير السيارات على الطريق: on the road.' },
    { q: 'أكمل الجملة: (Ships sail across the wide ___) 🚢', img: '🌊', correct: 'sea', opts: ['sea', 'mountain', 'forest', 'desert'], exp: 'تبحر السفن في البحر: sail across the sea.' },
    { q: 'أكمل الجملة: (My teacher writes with a marker on the ___) 📋', img: '📋', correct: 'whiteboard', opts: ['whiteboard', 'floor', 'window', 'ceiling'], exp: 'يكتب على اللوح الأبيض: on the whiteboard.' },
    { q: 'أكمل الجملة: (Cows eat green ___ in the meadow) 🐮', img: '🌱', correct: 'grass', opts: ['grass', 'meat', 'fish', 'stones'], exp: 'تأكل البقرة العشب الأخضر: eat grass.' },
    { q: 'أكمل الجملة: (I write notes with a blue ___) 🖊️', img: '🖊️', correct: 'pen', opts: ['pen', 'spoon', 'fork', 'cup'], exp: 'أكتب بالقلم: with a pen.' },
    { q: 'أكمل الجملة: (Frogs can ___ very high into the pond) 🐸', img: '🐸', correct: 'jump', opts: ['jump', 'fly', 'drive', 'cook'], exp: 'تقفز الضفادع عالياً: can jump.' },
    { q: 'أكمل الجملة: (A giraffe has a very long ___) 🦒', img: '🦒', correct: 'neck', opts: ['neck', 'ear', 'finger', 'nose'], exp: 'للزرافة رقبة طويلة: a long neck.' },
    { q: 'أكمل الجملة: (We listen to sounds with our two ___) 👂', img: '👂', correct: 'ears', opts: ['ears', 'eyes', 'teeth', 'knees'], exp: 'نستمع بالأذنين: with our ears.' },
    { q: 'أكمل الجملة: (We see the colorful world with our ___) 👁️', img: '👁️', correct: 'eyes', opts: ['eyes', 'ears', 'mouth', 'hands'], exp: 'نرى بالعينين: with our eyes.' },
    { q: 'أكمل الجملة: (A pilot flies an ___ across countries) ✈️', img: '✈️', correct: 'airplane', opts: ['airplane', 'bicycle', 'boat', 'tractor'], exp: 'يقود الطيار طائرة: flies an airplane.' },
    { q: 'أكمل الجملة: (Ice cream is sweet and ___) 🍦', img: '🍦', correct: 'cold', opts: ['cold', 'hot', 'warm', 'spicy'], exp: 'الآيس كريم بارد وحلو: sweet and cold.' },
    { q: 'أكمل الجملة: (Hot tea is very ___ to drink quickly) ☕', img: '☕', correct: 'hot', opts: ['hot', 'freezing', 'cold', 'sour'], exp: 'الشاي ساخن: very hot.' },
    { q: 'أكمل الجملة: (The doctor works in the city ___) 🏥', img: '🏥', correct: 'hospital', opts: ['hospital', 'zoo', 'park', 'airport'], exp: 'يعمل في المستشفى: in the hospital.' },
    { q: 'أكمل الجملة: (We put on warm coats in ___) ❄️', img: '🧥', correct: 'winter', opts: ['winter', 'summer', 'beach', 'pool'], exp: 'نرتدي المعاطف في الشتاء: in winter.' },
    { q: 'أكمل الجملة: (Flowers bloom beautifully in ___) 🌸', img: '🌸', correct: 'spring', opts: ['spring', 'winter', 'snow', 'night'], exp: 'تتفتح الأزهار في الربيع: in spring.' },
    { q: 'أكمل الجملة: (The moon shines brightly at ___) 🌙', img: '🌙', correct: 'night', opts: ['night', 'noon', 'morning', 'breakfast'], exp: 'يضيء القمر ليلاً: at night.' },
    { q: 'أكمل الجملة: (Children play fun games in the ___) 🛝', img: '🛝', correct: 'playground', opts: ['playground', 'hospital', 'kitchen', 'office'], exp: 'يلعب الأطفال في الملعب: in the playground.' },
    { q: 'أكمل الجملة: (A baker bakes fresh ___ every morning) 🥖', img: '🥖', correct: 'bread', opts: ['bread', 'shoes', 'paper', 'chairs'], exp: 'يخبز الخبز الطازج: fresh bread.' },
    { q: 'أكمل الجملة: (A banana is sweet and ___) 🍌', img: '🍌', correct: 'yellow', opts: ['yellow', 'blue', 'black', 'purple'], exp: 'الموزة صفراء: yellow.' },
    { q: 'أكمل الجملة: (I wear a warm hat on my ___) 🧢', img: '🧢', correct: 'head', opts: ['head', 'foot', 'hand', 'knee'], exp: 'أرتدي القبعة على رأسي: on my head.' },
    { q: 'أكمل الجملة: (Shoes protect our two ___) 👟', img: '👟', correct: 'feet', opts: ['feet', 'hands', 'ears', 'eyes'], exp: 'تحمي الأحذية أقدامنا: protect our feet.' },
    { q: 'أكمل الجملة: (A lion can roar very ___) 🦁', img: '🦁', correct: 'loudly', opts: ['loudly', 'quietly', 'silently', 'softly'], exp: 'يزأر الأسد بصوت عالٍ: roar loudly.' },
    { q: 'أكمل الجملة: (A turtle moves very ___) 🐢', img: '🐢', correct: 'slowly', opts: ['slowly', 'fast', 'quick', 'flying'], exp: 'تمشي السلحفاة ببطء شديد: moves slowly.' },
    { q: 'أكمل الجملة: (Cheetahs can run extremely ___) 🐆', img: '🐆', correct: 'fast', opts: ['fast', 'slow', 'late', 'heavy'], exp: 'يركض الفهد بسرعة فائقة: run fast.' },
    { q: 'أكمل الجملة: (We smell blooming roses with our ___) 👃', img: '👃', correct: 'nose', opts: ['nose', 'ear', 'mouth', 'eye'], exp: 'نشم الزهور بأنفنا: with our nose.' },
    { q: 'أكمل الجملة: (We taste delicious food with our ___) 👅', img: '👅', correct: 'tongue', opts: ['tongue', 'hand', 'foot', 'hair'], exp: 'نتذوق الطعام بلساننا: with our tongue.' },
    { q: 'أكمل الجملة: (A baby drinks milk from a ___) 🍼', img: '🍼', correct: 'bottle', opts: ['bottle', 'plate', 'shoe', 'book'], exp: 'يشرب الرضيع من الزجاجة: from a bottle.' },
    { q: 'أكمل الجملة: (Astronauts travel to outer ___ in a rocket) 🚀', img: '🚀', correct: 'space', opts: ['space', 'water', 'forest', 'garden'], exp: 'يسافرون إلى الفضاء: to outer space.' },
    { q: 'أكمل الجملة: (We keep milk cold inside the ___) 🧊', img: '🧊', correct: 'refrigerator', opts: ['refrigerator', 'oven', 'toaster', 'microwave'], exp: 'نحفظ الحليب في الثلاجة: inside the refrigerator.' },
    { q: 'أكمل الجملة: (At a birthday party, we blow out the ___ on the cake) 🎂', img: '🕯️', correct: 'candles', opts: ['candles', 'forks', 'tables', 'books'], exp: 'نطفئ الشموع: blow out candles.' },
    { q: 'أكمل الجملة: (A duck can swim happily in the ___) 🦆', img: '🦆', correct: 'pond', opts: ['pond', 'tree', 'roof', 'cloud'], exp: 'تسبح البطة في البركة: in the pond.' },
    { q: 'أكمل الجملة: (Every morning, I say "Good ___" to my family) ☀️', img: '🌅', correct: 'morning', opts: ['morning', 'night', 'bye', 'evening'], exp: 'أقول صباح الخير: Good morning.' }
  ];
  games['تحدي تكوين الجمل المفيدة بالإنجليزية'] = sentencesQuestions.map((d, i) => ({
    id: 20001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  return games;
}
