// Generators for English Games 31 to 40 (Exact titles from constants.tsx)
// 50 questions each = 500 questions

export function getGames31to40() {
  const games = {};

  // 31. مفردات الفضاء والكواكب بالإنجليزية
  const spaceList = [
    { name: 'Sun', ar: 'الشمس النجم المضيء مركز مجموعتنا الشمسية', img: '☀️', o: ['Sun', 'Moon', 'Earth', 'Star'] },
    { name: 'Mercury', ar: 'عطارد أقرب كواكب المجموعة الشمسية للشمس', img: '🪐', o: ['Mercury', 'Venus', 'Mars', 'Jupiter'] },
    { name: 'Venus', ar: 'الزهرة ألمع وأسخن كواكب مجموعتنا الشمسية', img: '🪐', o: ['Venus', 'Mercury', 'Earth', 'Saturn'] },
    { name: 'Earth', ar: 'كوكب الأرض كوكب الحياة والماء العذب', img: '🌍', o: ['Earth', 'Mars', 'Jupiter', 'Neptune'] },
    { name: 'Mars', ar: 'المريخ الكوكب الأحمر بصخوره وغباره', img: '🔴', o: ['Mars', 'Venus', 'Jupiter', 'Mercury'] },
    { name: 'Jupiter', ar: 'المشتري أكبر وأضخم كواكب المجموعة الشمسية', img: '🪐', o: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'] },
    { name: 'Saturn', ar: 'زحل كوكب الحلقات البديعة الملونة', img: '🪐', o: ['Saturn', 'Jupiter', 'Uranus', 'Mars'] },
    { name: 'Uranus', ar: 'أورانوس الكوكب الأزرق الجليدي شديد البرودة', img: '🪐', o: ['Uranus', 'Neptune', 'Saturn', 'Venus'] },
    { name: 'Neptune', ar: 'نبتون الكوكب الأزرق العاصف أبعد الكواكب عن الشمس', img: '🪐', o: ['Neptune', 'Uranus', 'Pluto', 'Jupiter'] },
    { name: 'Pluto', ar: 'بلوتو الكوكب القزم الجليدي البعيد', img: '🌑', o: ['Pluto', 'Neptune', 'Ceres', 'Moon'] },
    { name: 'Moon', ar: 'القمر التابع المنير للأرض ليلاً', img: '🌙', o: ['Moon', 'Sun', 'Star', 'Comet'] },
    { name: 'Star', ar: 'النجم اللامع المتلألئ في السماء', img: '⭐', o: ['Star', 'Planet', 'Moon', 'Meteor'] },
    { name: 'Shooting Star', ar: 'الشهاب والنجم الهاوي السريع المضيء', img: '🌠', o: ['Shooting Star', 'Comet', 'Asteroid', 'Satellite'] },
    { name: 'Comet', ar: 'المذنب الجليدي ذو الذيل الطويل البراق', img: '☄️', o: ['Comet', 'Asteroid', 'Meteor', 'Moon'] },
    { name: 'Asteroid', ar: 'الكويكب الصخري السابح في الفضاء', img: '🪨', o: ['Asteroid', 'Comet', 'Planet', 'Star'] },
    { name: 'Galaxy', ar: 'المجرة الضخمة التي تضم مليارات النجوم', img: '🌌', o: ['Galaxy', 'Universe', 'Solar System', 'Cluster'] },
    { name: 'Milky Way', ar: 'درب التبانة مجرتنا التي نعيش فيها', img: '🌌', o: ['Milky Way', 'Andromeda', 'Orion', 'Centaurus'] },
    { name: 'Black Hole', ar: 'الثقب الأسود ذو الجاذبية الفائقة المبتلعة للضوء', img: '🕳️', o: ['Black Hole', 'Wormhole', 'White Dwarf', 'Neutron Star'] },
    { name: 'Space', ar: 'الفضاء الخارجي الفسيح الممتد', img: '🚀', o: ['Space', 'Sky', 'Atmosphere', 'Cloud'] },
    { name: 'Universe', ar: 'الكون الشامل لكل المجرات والمادة', img: '🌌', o: ['Universe', 'Galaxy', 'Solar System', 'World'] },
    { name: 'Astronaut', ar: 'رائد الفضاء المستكشف للأجرام السماوية', img: '👨‍🚀', o: ['Astronaut', 'Pilot', 'Scientist', 'Captain'] },
    { name: 'Spaceship', ar: 'سفينة ومركبة الفضاء المنطلقة نحو الكواكب', img: '🚀', o: ['Spaceship', 'Airplane', 'Helicopter', 'Submarine'] },
    { name: 'Rocket', ar: 'الصاروخ الفضائي الدافع للمركبات بقوة المحركات', img: '🚀', o: ['Rocket', 'Jet', 'Missile', 'Satellite'] },
    { name: 'Space Shuttle', ar: 'مكوك الفضاء القابل للعودة والهبوط للأرض', img: '🚀', o: ['Space Shuttle', 'Capsule', 'Station', 'Probe'] },
    { name: 'Space Station', ar: 'محطة الفضاء الدولية التي يقيم فيها الرواد', img: '🛰️', o: ['Space Station', 'Observatory', 'Satellite', 'Base'] },
    { name: 'Satellite', ar: 'القمر الصناعي الذي يدور في مدار حول الأرض', img: '🛰️', o: ['Satellite', 'Telescope', 'Rocket', 'Radar'] },
    { name: 'Space Suit', ar: 'بدلة الفضاء لحماية الرواد من الفراغ والبرد', img: '👨‍🚀', o: ['Space Suit', 'Armor', 'Uniform', 'Diving Suit'] },
    { name: 'Space Helmet', ar: 'خوذة رائد الفضاء المزودة بالواقي الشمسي', img: '👨‍🚀', o: ['Space Helmet', 'Mask', 'Cap', 'Visor'] },
    { name: 'Telescope', ar: 'التلسكوب الفضائي لرصد أعماق الكون والنجوم', img: '🔭', o: ['Telescope', 'Microscope', 'Binoculars', 'Periscope'] },
    { name: 'Observatory', ar: 'المرصد الفلكي المزود بمقراب عملاق', img: '🔭', o: ['Observatory', 'Planetarium', 'Laboratory', 'Station'] },
    { name: 'Alien', ar: 'الكائن الفضائي الخيالي من كواكب أخرى', img: '👽', o: ['Alien', 'Human', 'Robot', 'Monster'] },
    { name: 'UFO', ar: 'الطبق الطائر والجسم الفضائي المجهول', img: '🛸', o: ['UFO', 'Drone', 'Rocket', 'Glider'] },
    { name: 'Constellation', ar: 'الكوكبة والمجموعة النجمية المشكلة رسماً بالسماء', img: '✨', o: ['Constellation', 'Galaxy', 'Solar System', 'Cluster'] },
    { name: 'Big Dipper', ar: 'كوكبة الدب الأكبر ومغرفة النجوم الشهيرة', img: '🌌', o: ['Big Dipper', 'Orion', 'Cassiopeia', 'Polaris'] },
    { name: 'Orbit', ar: 'المدار والمسار المنحني للكوكب حول الشمس', img: '🪐', o: ['Orbit', 'Axis', 'Circle', 'Line'] },
    { name: 'Gravity', ar: 'الجاذبية الكونية التي تحافظ على تماسك الكواكب', img: '🍎', o: ['Gravity', 'Inertia', 'Speed', 'Friction'] },
    { name: 'Zero Gravity', ar: 'انعدام الجاذبية والسباحة الحرة بالفضاء', img: '🎈', o: ['Zero Gravity', 'High Pressure', 'Vacuum', 'Float'] },
    { name: 'Lunar Eclipse', ar: 'خسوف القمر عند حجب الأرض لضوء الشمس عنه', img: '🌑', o: ['Lunar Eclipse', 'Solar Eclipse', 'Full Moon', 'New Moon'] },
    { name: 'Solar Eclipse', ar: 'كسوف الشمس عند وقوع القمر بيننا وبين الشمس', img: '🌘', o: ['Solar Eclipse', 'Lunar Eclipse', 'Sunset', 'Dawn'] },
    { name: 'Crater', ar: 'الفوهة النيزكية الدائرية على سطح القمر', img: '🕳️', o: ['Crater', 'Volcano', 'Cave', 'Canyon'] },
    { name: 'Solar System', ar: 'المجموعة الشمسية بنجمها وكواكبها وأقمارها', img: '☀️', o: ['Solar System', 'Galaxy', 'Universe', 'Constellation'] },
    { name: 'Space Dust', ar: 'الغبار الكوني المتناثر بين أرجاء المجرة', img: '🌌', o: ['Space Dust', 'Meteorite', 'Gas', 'Plasma'] },
    { name: 'Nebula', ar: 'السديم السحابي البديع المضيء حاضن النجوم', img: '🌌', o: ['Nebula', 'Galaxy', 'Pulsar', 'Quasar'] },
    { name: 'Supernova', ar: 'المستعر الأعظم والانفجار النجمي الهائل', img: '💥', o: ['Supernova', 'Big Bang', 'Flare', 'Eclipse'] },
    { name: 'Light Year', ar: 'السنة الضوئية مقياس المسافة بين النجوم والمجرات', img: '💫', o: ['Light Year', 'Kilometer', 'Mile', 'Hour'] },
    { name: 'Rocket Launch', ar: 'إطلاق الصاروخ الفضائي من المنصة', img: '🚀', o: ['Rocket Launch', 'Landing', 'Orbit', 'Blast'] },
    { name: 'Countdown', ar: 'العد التنازلي قبل إقلاع الصاروخ', img: '🔟', o: ['Countdown', 'Timer', 'Clock', 'Score'] },
    { name: 'Mars Rover', ar: 'مسبار وروفر المريخ الاستكشافي المتجول', img: '🤖', o: ['Mars Rover', 'Satellite', 'Robot', 'Drone'] },
    { name: 'Space Walk', ar: 'المشي في الفضاء الحر خارج المركبة الفضائية', img: '👨‍🚀', o: ['Space Walk', 'Moon Landing', 'Flight', 'Spacelab'] },
    { name: 'Astronomy', ar: 'علم الفلك ودراسة النجوم والكواكب والكون', img: '🔭', o: ['Astronomy', 'Astrology', 'Geology', 'Physics'] }
  ];
  games['مفردات الفضاء والكواكب بالإنجليزية'] = spaceList.map((d, i) => ({
    id: 31001 + i,
    question: `ما اسم المصطلح أو الجرم الفضائي (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 32. التاريخ والساعات بالإنجليزية
  const timeList = [
    { name: 'Clock', ar: 'ساعة الحائط لمعرفة الوقت', img: '⏰', o: ['Clock', 'Watch', 'Calendar', 'Timer'] },
    { name: 'Watch', ar: 'ساعة اليد المعصمية الأنيقة', img: '⌚', o: ['Watch', 'Clock', 'Compass', 'Ring'] },
    { name: 'Hour', ar: 'الساعة الزمنية المكونة من 60 دقيقة', img: '⌛', o: ['Hour', 'Minute', 'Second', 'Day'] },
    { name: 'Minute', ar: 'الدقيقة المكونة من 60 ثانية', img: '⏱️', o: ['Minute', 'Hour', 'Second', 'Week'] },
    { name: 'Second', ar: 'الثانية كوحدة زمنية سريعة', img: '⏲️', o: ['Second', 'Minute', 'Hour', 'Day'] },
    { name: 'Morning', ar: 'الصباح وبداية شروق الشمس', img: '🌅', o: ['Morning', 'Evening', 'Night', 'Afternoon'] },
    { name: 'Noon', ar: 'وقت الظهيرة منتصف النهار (12 ظهراً)', img: '☀️', o: ['Noon', 'Midnight', 'Morning', 'Dawn'] },
    { name: 'Afternoon', ar: 'بعد الظهر وفترة العصر', img: '🌤️', o: ['Afternoon', 'Morning', 'Night', 'Dawn'] },
    { name: 'Evening', ar: 'المساء وبداية غروب الشمس', img: '🌇', o: ['Evening', 'Morning', 'Noon', 'Midnight'] },
    { name: 'Night', ar: 'الليل وظهور القمر والنجوم', img: '🌙', o: ['Night', 'Day', 'Morning', 'Noon'] },
    { name: 'Midnight', ar: 'منتصف الليل تمام الساعة 12 ليلاً', img: '🕛', o: ['Midnight', 'Noon', 'Dawn', 'Dusk'] },
    { name: 'Dawn', ar: 'الفجر وانبثاق أول خيوط النور', img: '🌄', o: ['Dawn', 'Dusk', 'Night', 'Noon'] },
    { name: 'Dusk', ar: 'الغسق والشفق الأحمر بعد الغروب', img: '🌆', o: ['Dusk', 'Dawn', 'Morning', 'Noon'] },
    { name: 'Today', ar: 'اليوم في الحاضر', img: '📅', o: ['Today', 'Yesterday', 'Tomorrow', 'Tonight'] },
    { name: 'Yesterday', ar: 'أمس واليوم الماضي الذي انقضى', img: '⏮️', o: ['Yesterday', 'Today', 'Tomorrow', 'Tonight'] },
    { name: 'Tomorrow', ar: 'غداً واليوم القادم في المستقبل', img: '⏭️', o: ['Tomorrow', 'Yesterday', 'Today', 'Now'] },
    { name: 'Tonight', ar: 'الليلة في هذا المساء', img: '🌃', o: ['Tonight', 'Today', 'Tomorrow', 'Yesterday'] },
    { name: 'Day', ar: 'اليوم والنهار المشرق', img: '☀️', o: ['Day', 'Night', 'Hour', 'Year'] },
    { name: 'Week', ar: 'الأسبوع المكون من سبعة أيام', img: '🗓️', o: ['Week', 'Month', 'Year', 'Day'] },
    { name: 'Month', ar: 'الشهر المكون من ثلاثين يوماً', img: '📅', o: ['Month', 'Week', 'Year', 'Day'] },
    { name: 'Year', ar: 'السنة والـعام المكون من 12 شهراً', img: '🗓️', o: ['Year', 'Month', 'Decade', 'Century'] },
    { name: 'Century', ar: 'القرن الزمني المكون من 100 عام', img: '📜', o: ['Century', 'Decade', 'Millennium', 'Year'] },
    { name: 'Decade', ar: 'العقد الزمني المكون من 10 سنوات', img: '🔟', o: ['Decade', 'Century', 'Year', 'Month'] },
    { name: 'Calendar', ar: 'التقويم السنوي الموضح للتواريخ والأيام', img: '📅', o: ['Calendar', 'Clock', 'Diary', 'Book'] },
    { name: 'Date', ar: 'تاريخ اليوم باليوم والشهر والسنة', img: '🗓️', o: ['Date', 'Time', 'Clock', 'Hour'] },
    { name: 'Early', ar: 'مبكراً في أول الوقت', img: '🌅', o: ['Early', 'Late', 'Now', 'Never'] },
    { name: 'Late', ar: 'متأخراً بعد فوات الأوان', img: '⏳', o: ['Late', 'Early', 'Fast', 'Soon'] },
    { name: 'On time', ar: 'في الموعد المحدد تماماً وبدقة', img: '🎯', o: ['On time', 'Late', 'Early', 'Never'] },
    { name: 'Half past', ar: 'والنصف في قراءة الساعة (مثل 3:30)', img: '🕞', o: ['Half past', 'Quarter to', 'O’clock', 'Quarter past'] },
    { name: 'Quarter past', ar: 'والربع في قراءة الساعة (مثل 3:15)', img: '🕒', o: ['Quarter past', 'Quarter to', 'Half past', 'O’clock'] },
    { name: 'Quarter to', ar: 'إلا ربع في قراءة الساعة (مثل 2:45)', img: '🕤', o: ['Quarter to', 'Quarter past', 'Half past', 'O’clock'] },
    { name: 'O’clock', ar: 'تمام الساعة بالضبط (مثل 4:00)', img: '🕓', o: ['O’clock', 'Half past', 'Quarter to', 'Minutes'] },
    { name: 'Hour hand', ar: 'عقرب الساعات القصير في الساعة', img: '🕐', o: ['Hour hand', 'Minute hand', 'Second hand', 'Dial'] },
    { name: 'Minute hand', ar: 'عقرب الدقائق الطويل في الساعة', img: '🕛', o: ['Minute hand', 'Hour hand', 'Second hand', 'Clock'] },
    { name: 'Second hand', ar: 'عقرب الثواني الرفيع السريع الحركة', img: '⏲️', o: ['Second hand', 'Minute hand', 'Hour hand', 'Face'] },
    { name: 'AM', ar: 'صباحاً (الفترة من بعد منتصف الليل حتى الظهر)', img: '🌅', o: ['AM', 'PM', 'AD', 'BC'] },
    { name: 'PM', ar: 'مساءً (الفترة من بعد الظهر حتى منتصف الليل)', img: '🌆', o: ['PM', 'AM', 'BC', 'AD'] },
    { name: 'Timer', ar: 'المؤقت التنازلي لضبط وقت الطهي أو السباق', img: '⏲️', o: ['Timer', 'Alarm', 'Clock', 'Watch'] },
    { name: 'Stopwatch', ar: 'ساعة الإيقاف لحساب أجزاء الثانية في الجري', img: '⏱️', o: ['Stopwatch', 'Compass', 'Thermometer', 'Ruler'] },
    { name: 'Hourglass', ar: 'الساعة الرملية التراثية بحبيبات الرمل', img: '⌛', o: ['Hourglass', 'Clock', 'Sundial', 'Calendar'] },
    { name: 'Sundial', ar: 'المزولة الشمسية القديمة لمعرفة الوقت بالظل', img: '☀️', o: ['Sundial', 'Hourglass', 'Compass', 'Telescope'] },
    { name: 'Alarm clock', ar: 'المنبه الصباحي الرنان للاستيقاظ', img: '⏰', o: ['Alarm clock', 'Stopwatch', 'Watch', 'Timer'] },
    { name: 'Past', ar: 'الماضي والزمن الذي مضى وانتهى', img: '📜', o: ['Past', 'Present', 'Future', 'Now'] },
    { name: 'Present', ar: 'الحاضر والوقت الراهن الذي نعيشه الآن', img: '🎁', o: ['Present', 'Past', 'Future', 'History'] },
    { name: 'Future', ar: 'المستقبل والزمن الآتي القادم', img: '🚀', o: ['Future', 'Past', 'Present', 'History'] },
    { name: 'Always', ar: 'دائماً وفي كل الأوقات', img: '♾️', o: ['Always', 'Never', 'Sometimes', 'Rarely'] },
    { name: 'Never', ar: 'أبداً ولا يحدث في أي وقت', img: '🚫', o: ['Never', 'Always', 'Often', 'Usually'] },
    { name: 'Sometimes', ar: 'أحياناً في بعض الأوقات دون غيرها', img: '🌓', o: ['Sometimes', 'Always', 'Never', 'Daily'] },
    { name: 'Soon', ar: 'قريباً بعد وقت يسير', img: '🔜', o: ['Soon', 'Late', 'Never', 'Yesterday'] },
    { name: 'History', ar: 'التاريخ وأحداث الأمم والشعوب القديمة', img: '🏛️', o: ['History', 'Future', 'Science', 'Math'] }
  ];
  games['التاريخ والساعات بالإنجليزية'] = timeList.map((d, i) => ({
    id: 32001 + i,
    question: `ما هو المصطلح الإنجليزي المعبر عن (${d.ar}) في سياق الوقت والتاريخ؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 33. الطبيعة والكون بالإنجليزية
  const natureCosmosList = [
    { name: 'Mountain', ar: 'الجبل الشامخ بقممه الثلجية العالية', img: '🏔️', o: ['Mountain', 'Valley', 'Desert', 'Plains'] },
    { name: 'Valley', ar: 'الوادي المنخفض الأخضر بين الجبال', img: '🏞️', o: ['Valley', 'Mountain', 'Hill', 'Cliff'] },
    { name: 'Hill', ar: 'التل والمرتفع الصغير الأقل ارتفاعاً من الجبل', img: '⛰️', o: ['Hill', 'Mountain', 'Plains', 'Forest'] },
    { name: 'Forest', ar: 'الغابة الكثيفة بأشجارها وظلالها', img: '🌲', o: ['Forest', 'Desert', 'Ocean', 'Swamp'] },
    { name: 'Desert', ar: 'الصحراء الذهبية الشاسعة برمالها', img: '🏜️', o: ['Desert', 'Forest', 'Oasis', 'Jungle'] },
    { name: 'Oasis', ar: 'الواحة الخضراء بنخيلها ومائها وسط الصحراء', img: '🌴', o: ['Oasis', 'Desert', 'Island', 'Beach'] },
    { name: 'River', ar: 'النهر العذب الجاري بين الحقول', img: '🏞️', o: ['River', 'Sea', 'Ocean', 'Pond'] },
    { name: 'Lake', ar: 'البحيرة الهادئة المحاطة باليابسة', img: '🌊', o: ['Lake', 'River', 'Ocean', 'Waterfall'] },
    { name: 'Waterfall', ar: 'الشلال المتدفق بمياهه المنهمرة من المرتفعات', img: '🌊', o: ['Waterfall', 'Stream', 'Lake', 'Spring'] },
    { name: 'Ocean', ar: 'المحيط الهائل بأعماقه وأمواجه العاتية', img: '🌊', o: ['Ocean', 'Pond', 'River', 'Pool'] },
    { name: 'Sea', ar: 'البحر المالح بشواطئه وأسماكه', img: '🌊', o: ['Sea', 'Lake', 'River', 'Stream'] },
    { name: 'Beach', ar: 'الشاطئ الرملي الذهبي على حافة البحر', img: '🏖️', o: ['Beach', 'Desert', 'Cliff', 'Cave'] },
    { name: 'Island', ar: 'الجزيرة الخلابة المحاطة بالمياه من كل جهة', img: '🏝️', o: ['Island', 'Peninsula', 'Coast', 'Port'] },
    { name: 'Cave', ar: 'الكهف والمغارة الصخرية في قلب الجبل', img: '🕳️', o: ['Cave', 'Mine', 'Canyon', 'Hole'] },
    { name: 'Canyon', ar: 'الأخدود الصخري المنحوت بالمياه عبر العصور', img: '🏜️', o: ['Canyon', 'Mountain', 'Valley', 'Hill'] },
    { name: 'Volcano', ar: 'البركان الثائر بالحمم والصهارة الملتهبة', img: '🌋', o: ['Volcano', 'Mountain', 'Earthquake', 'Geyser'] },
    { name: 'Geyser', ar: 'النبع الحار الفوار الذي يقذف الماء الساخن', img: '⛲', o: ['Geyser', 'Waterfall', 'Fountain', 'Well'] },
    { name: 'Glacier', ar: 'الكتلة الجليدية الهائلة المتراكمة في القطب', img: '🧊', o: ['Glacier', 'Iceberg', 'Frost', 'Snowbank'] },
    { name: 'Iceberg', ar: 'الجبل الجليدي العائم في مياه المحيط الباردة', img: '🧊', o: ['Iceberg', 'Glacier', 'Island', 'Rock'] },
    { name: 'Sky', ar: 'السماء الزرقاء الممتدة فوق رؤوسنا', img: '🌌', o: ['Sky', 'Earth', 'Space', 'Cloud'] },
    { name: 'Clouds', ar: 'الغيوم والسحب البيضاء والرمادية المحملة بالمطر', img: '☁️', o: ['Clouds', 'Fog', 'Stars', 'Sky'] },
    { name: 'Rainbow', ar: 'قوس قزح البديع المتلألئ بألوان الطيف', img: '🌈', o: ['Rainbow', 'Aurora', 'Lightning', 'Sunbeam'] },
    { name: 'Sunrise', ar: 'شروق الشمس الصباحي المبهج بالنور والجمال', img: '🌅', o: ['Sunrise', 'Sunset', 'Noon', 'Dusk'] },
    { name: 'Sunset', ar: 'غروب الشمس المهيب بلونه البرتقالي الذهبي', img: '🌇', o: ['Sunset', 'Sunrise', 'Dawn', 'Morning'] },
    { name: 'Stars', ar: 'النجوم البراقة المضيئة لظلمات الليل', img: '⭐', o: ['Stars', 'Planets', 'Moons', 'Comets'] },
    { name: 'Aurora', ar: 'الشفق القطبي والستائر الضوئية الملونة بالسماء', img: '🌌', o: ['Aurora', 'Rainbow', 'Lightning', 'Comet'] },
    { name: 'Ecosystem', ar: 'النظام البيئي الحيوي المتكامل', img: '🌿', o: ['Ecosystem', 'Nature', 'Planet', 'Climate'] },
    { name: 'Jungle', ar: 'الأدغال الاستوائية الكثيفة موطن الحيوانات', img: '🌳', o: ['Jungle', 'Meadow', 'Desert', 'Plains'] },
    { name: 'Meadow', ar: 'المرج الأخضر المزهر بالزهور البرية', img: '🏞️', o: ['Meadow', 'Forest', 'Jungle', 'Swamp'] },
    { name: 'Swamp', ar: 'المستنقع والأرض الرطبة المغطاة بالمياه الضحلة', img: '🐊', o: ['Swamp', 'Desert', 'Meadow', 'Lake'] },
    { name: 'Coral Reef', ar: 'الشعاب المرجانية الملونة في أعماق البحار', img: '🐠', o: ['Coral Reef', 'Trench', 'Lagoon', 'Island'] },
    { name: 'Wave', ar: 'الموجة المائية المرتفعة المتكسرة على الشاطئ', img: '🌊', o: ['Wave', 'Tide', 'Current', 'Ripple'] },
    { name: 'Tide', ar: 'المد والجزر وتغير مستوى مياه البحر بجاذبية القمر', img: '🌊', o: ['Tide', 'Wave', 'Storm', 'Current'] },
    { name: 'Soil', ar: 'التربة الخصبة التي تنبت النباتات والثمار', img: '🪴', o: ['Soil', 'Rock', 'Clay', 'Dust'] },
    { name: 'Rock', ar: 'الصخر والحجر الصلب', img: '🪨', o: ['Rock', 'Soil', 'Sand', 'Pebble'] },
    { name: 'Mineral', ar: 'المعدن الثمين المستخرج من باطن الأرض', img: '💎', o: ['Mineral', 'Rock', 'Fossil', 'Clay'] },
    { name: 'Diamond', ar: 'الألماس أصلب الأحجار الكريمة وأنقاها بريقاً', img: '💎', o: ['Diamond', 'Ruby', 'Emerald', 'Gold'] },
    { name: 'Gold', ar: 'الذهب الأصفر اللامع الثمين', img: '🪙', o: ['Gold', 'Silver', 'Copper', 'Iron'] },
    { name: 'Silver', ar: 'الفضة المعدنية اللامعة', img: '🥈', o: ['Silver', 'Gold', 'Bronze', 'Steel'] },
    { name: 'Crystal', ar: 'البلورة الكريستالية الهندسية البراقة', img: '🔮', o: ['Crystal', 'Glass', 'Stone', 'Diamond'] },
    { name: 'Fossil', ar: 'الأحفورة وبصمة الكائنات القديمة بالصخر', img: '🦴', o: ['Fossil', 'Skeleton', 'Rock', 'Statue'] },
    { name: 'Spring (water)', ar: 'عين وينبوع الماء الطبيعي المتفجر من الأرض', img: '💧', o: ['Spring (water)', 'River', 'Pond', 'Well'] },
    { name: 'Stream', ar: 'الجدول المائي الرقراق الصغير بين المروج', img: '🏞️', o: ['Stream', 'River', 'Ocean', 'Canal'] },
    { name: 'Earthquake', ar: 'الزلزال والهزة الأرضية في القشرة', img: '🏚️', o: ['Earthquake', 'Tsunami', 'Volcano', 'Flood'] },
    { name: 'Tsunami', ar: 'أمواج التسونامي البحرية الهائلة الناجمة عن الزلازل', img: '🌊', o: ['Tsunami', 'Tide', 'Tornado', 'Cyclone'] },
    { name: 'Tornado', ar: 'الإعصار القمعي الدوامي العاصف في الهواء', img: '🌪️', o: ['Tornado', 'Breeze', 'Rain', 'Storm'] },
    { name: 'Lightning', ar: 'البرق الكهربائي الوامض في قلب العاصفة', img: '⚡', o: ['Lightning', 'Thunder', 'Rain', 'Cloud'] },
    { name: 'Thunder', ar: 'الرعد وصوت دويه المجلجل في السماء', img: '⚡', o: ['Thunder', 'Lightning', 'Wind', 'Storm'] },
    { name: 'Wilderness', ar: 'البرية والطبيعة العذراء البكر البعيدة عن العمران', img: '🏕️', o: ['Wilderness', 'City', 'Suburb', 'Farm'] },
    { name: 'Cosmos', ar: 'الكون الفسيح البديع بنجومه ومجراته', img: '🌌', o: ['Cosmos', 'Earth', 'Ocean', 'Nature'] }
  ];
  games['الطبيعة والكون بالإنجليزية'] = natureCosmosList.map((d, i) => ({
    id: 33001 + i,
    question: `ما اسم العنصر أو المعلم الطبيعي والكوني (${d.ar}) بالإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية هو '${d.name}'.`
  }));

  // 34. الاحتفالات والهدايا بالإنجليزية
  const giftsCelebrationList = [
    { name: 'Gift', ar: 'الهدية الجميلة المغلفة بشريط ملون', img: '🎁', o: ['Gift', 'Card', 'Box', 'Letter'] },
    { name: 'Present', ar: 'الهدية والعطية المقدمة في المناسبات السعيدة', img: '🎁', o: ['Present', 'Cake', 'Toy', 'Award'] },
    { name: 'Birthday', ar: 'عيد الميلاد السعيد وذكرى المولد', img: '🎂', o: ['Birthday', 'Holiday', 'Wedding', 'Feast'] },
    { name: 'Party', ar: 'الحفلة البهيجة العامرة بالأصدقاء والألعاب', img: '🥳', o: ['Party', 'Meeting', 'Class', 'Game'] },
    { name: 'Birthday Cake', ar: 'كعكة عيد الميلاد اللذيذة بالشوكولاتة والشموع', img: '🎂', o: ['Birthday Cake', 'Pie', 'Pancake', 'Biscuit'] },
    { name: 'Candle', ar: 'الشمعة المضيئة فوق الكعكة لإطفائها بعد التمني', img: '🕯️', o: ['Candle', 'Lamp', 'Torch', 'Light'] },
    { name: 'Balloon', ar: 'البالون الملون الطائر في سماء الحفلة', img: '🎈', o: ['Balloon', 'Ball', 'Lantern', 'Ribbon'] },
    { name: 'Confetti', ar: 'قصاصات الورق الملونة المنثورة فرحاً وتصفيقاً', img: '🎊', o: ['Confetti', 'Glitter', 'Fireworks', 'Ribbon'] },
    { name: 'Ribbon', ar: 'شريط الساتان الأنيق الملفوف بعقدة على الهدية', img: '🎀', o: ['Ribbon', 'String', 'Tape', 'Rope'] },
    { name: 'Wrapping Paper', ar: 'ورق التغليف المزخرف لتغطية الهدايا والمفاجآت', img: '🎁', o: ['Wrapping Paper', 'Cardboard', 'Newspaper', 'Poster'] },
    { name: 'Greeting Card', ar: 'بطاقة التهنئة المكتوبة بأجمل عبارات المحبة', img: '💌', o: ['Greeting Card', 'Letter', 'Book', 'Postcard'] },
    { name: 'Invitation', ar: 'بطاقة الدعوة لحضور الحفل والمناسبة', img: '✉️', o: ['Invitation', 'Ticket', 'Pass', 'Envelope'] },
    { name: 'Celebration', ar: 'الاحتفال والابتهاج بحدث رائع وسعيد', img: '🥳', o: ['Celebration', 'Sadness', 'Work', 'Silence'] },
    { name: 'Surprise', ar: 'المفاجأة السارة التي تسعد القلب', img: '🎉', o: ['Surprise', 'Secret', 'Plan', 'Shock'] },
    { name: 'Eid Mubarak', ar: 'عيد مبارك التهنئة الخاصة بالأعياد المباركة', img: '🌙', o: ['Eid Mubarak', 'Happy Birthday', 'Good Morning', 'Welcome'] },
    { name: 'Eid al-Fitr', ar: 'عيد الفطر السعيد بعد صيام شهر رمضان', img: '🌙', o: ['Eid al-Fitr', 'Eid al-Adha', 'Ramadan', 'Hajj'] },
    { name: 'Eid al-Adha', ar: 'عيد الأضحى المبارك ويوم الأضحية والتكبيرات', img: '🐑', o: ['Eid al-Adha', 'Eid al-Fitr', 'New Year', 'National Day'] },
    { name: 'Lantern', ar: 'الفانوس المضيء ذو الزجاج الملون والأناشيد', img: '🏮', o: ['Lantern', 'Candle', 'Lamp', 'Flashlight'] },
    { name: 'Fireworks', ar: 'الألعاب النارية البراقة المنفجرة بألوان زاهية', img: '🎆', o: ['Fireworks', 'Stars', 'Campfire', 'Lightning'] },
    { name: 'Holiday', ar: 'الإجازة والعطلة المدرسية للاستجمام واللعب', img: '🏖️', o: ['Holiday', 'Workday', 'Exam', 'School'] },
    { name: 'Festival', ar: 'المهرجان الاحتفالي الكبير العامر بالفعاليات', img: '🎪', o: ['Festival', 'Carnival', 'Exhibition', 'Concert'] },
    { name: 'Parade', ar: 'الاستعراض والمسيرة الاحتفالية في الشارع', img: '🎺', o: ['Parade', 'March', 'Race', 'Traffic'] },
    { name: 'Costume', ar: 'الزي التنكري المبهج في المسرحيات المدرسية', img: '🦸', o: ['Costume', 'Uniform', 'Suit', 'Pajamas'] },
    { name: 'Mask', ar: 'القناع الاحتفالي المرح للوجه', img: '🎭', o: ['Mask', 'Hat', 'Glasses', 'Helmet'] },
    { name: 'Decoration', ar: 'الزينة المعلقة والشرائط المضيئة بالحفل', img: '🎀', o: ['Decoration', 'Furniture', 'Paint', 'Curtain'] },
    { name: 'Garland', ar: 'إكليل وعقد الزهور المنسوج للزينة والترحيب', img: '💐', o: ['Garland', 'Bouquet', 'Ribbon', 'Wreath'] },
    { name: 'Bouquet', ar: 'باقة الورد الطبيعي العطرة المهداة', img: '💐', o: ['Bouquet', 'Flowerpot', 'Vase', 'Garden'] },
    { name: 'Sweets', ar: 'الحلويات اللذيذة الموزعة على الضيوف', img: '🍬', o: ['Sweets', 'Fruit', 'Bread', 'Soup'] },
    { name: 'Chocolate', ar: 'قطع الشوكولاتة الفاخرة ذات المذاق الحلو', img: '🍫', o: ['Chocolate', 'Sugar', 'Honey', 'Cake'] },
    { name: 'Cupcake', ar: 'كب كيك الكعكة الصغيرة المزينة بالكريمة', img: '🧁', o: ['Cupcake', 'Cookie', 'Donut', 'Pancake'] },
    { name: 'Lollipop', ar: 'المصاصة الحلوة الملونة للأطفال', img: '🍭', o: ['Lollipop', 'Candy', 'Chocolate', 'Gum'] },
    { name: 'Party Horn', ar: 'بوق وزامور الحفلات الورقي المبهج', img: '🎺', o: ['Party Horn', 'Whistle', 'Bell', 'Flute'] },
    { name: 'Crown', ar: 'تاج الاحتفال الورقي الذهبي لملكة أو ملك الحفل', img: '👑', o: ['Crown', 'Hat', 'Cap', 'Helmet'] },
    { name: 'Party Hat', ar: 'قبعة الحفلات المخروطية الملونة', img: '🥳', o: ['Party Hat', 'Crown', 'Cap', 'Beanie'] },
    { name: 'Clown', ar: 'المهرج اللطيف صانع الضحكات والبهجة', img: '🤡', o: ['Clown', 'Magician', 'Actor', 'Dancer'] },
    { name: 'Magic Trick', ar: 'الخدعة السحرية الممتعة بالحفلة بالمناديل والأرانب', img: '🪄', o: ['Magic Trick', 'Game', 'Puzzle', 'Joke'] },
    { name: 'Piñata', ar: 'البينياتا الممتلئة بالحلوى التي يكسرها الأطفال بالمرح', img: '🪅', o: ['Piñata', 'Balloon', 'Basket', 'Box'] },
    { name: 'Cheering', ar: 'الهتاف والصياح فرحاً وتشجيعاً للمحتفى به', img: '📣', o: ['Cheering', 'Silence', 'Weeping', 'Yawning'] },
    { name: 'Applause', ar: 'التصفيق الحار بالأيدي تعبيراً عن التقدير والسرور', img: '👏', o: ['Applause', 'Cheering', 'Singing', 'Dancing'] },
    { name: 'Congratulations', ar: 'مبارك وألف مبروك التهنئة بالنجاح الباهر', img: '👏', o: ['Congratulations', 'Condolences', 'Apology', 'Welcome'] },
    { name: 'Thank You', ar: 'شكراً جزيلاً لتقدير الهدية والاهتمام', img: '🙏', o: ['Thank You', 'Please', 'Sorry', 'Welcome'] },
    { name: 'Welcome', ar: 'أهلاً وسهلاً وحياكم الله باستقبال الضيوف', img: '🤗', o: ['Welcome', 'Goodbye', 'Leave', 'Stop'] },
    { name: 'Best Wishes', ar: 'أطيب التمنيات والدعوات الطيبة بالبركة', img: '🌟', o: ['Best Wishes', 'Good Luck', 'Regards', 'Cheers'] },
    { name: 'Good Luck', ar: 'حظاً موفقاً وبالتوفيق الدائم في مسيرتك', img: '🍀', o: ['Good Luck', 'Best Wishes', 'Cheers', 'Welcome'] },
    { name: 'Feast', ar: 'الوليمة والمأدبة العامرة بألذ المأكولات', img: '🍗', o: ['Feast', 'Snack', 'Breakfast', 'Diet'] },
    { name: 'Family Gathering', ar: 'الاجتماع واللقاء العائلي المبهج في العيد', img: '👨‍👩‍👧‍👦', o: ['Family Gathering', 'Meeting', 'Class', 'Crowd'] },
    { name: 'Graduation', ar: 'حفل التخرج والتفوق بارتداء وشاح النجاح', img: '🎓', o: ['Graduation', 'Wedding', 'Birthday', 'Party'] },
    { name: 'Wedding', ar: 'حفل الزواج والزفاف المبهج باجتماع الأهل', img: '💍', o: ['Wedding', 'Graduation', 'Birthday', 'Anniversary'] },
    { name: 'Memory', ar: 'الذكرى الطيبة الخالدة في سجل الأيام', img: '📸', o: ['Memory', 'Dream', 'Wish', 'Thought'] },
    { name: 'Joy', ar: 'الفرحة الغامرة والسرور العظيم في الاحتفال', img: '🥳', o: ['Joy', 'Sorrow', 'Grief', 'Fear'] }
  ];
  games['الاحتفالات والهدايا بالإنجليزية'] = giftsCelebrationList.map((d, i) => ({
    id: 34001 + i,
    question: `ما اسم المصطلح الاحتفالي أو الهدية (${d.ar}) بالإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 35. الموسيقى والآلات بالإنجليزية
  const musicInstrumentsList = [
    { name: 'Piano', ar: 'البيانو الكبير ذو المفاتيح البيضاء والسوداء', img: '🎹', o: ['Piano', 'Guitar', 'Violin', 'Drum'] },
    { name: 'Guitar', ar: 'الجيتار ذو الأوتار الموسيقية الرنانة', img: '🎸', o: ['Guitar', 'Violin', 'Piano', 'Harp'] },
    { name: 'Violin', ar: 'الكمان المعزوف بالقوس الخشبي الناعم', img: '🎻', o: ['Violin', 'Cello', 'Guitar', 'Flute'] },
    { name: 'Drum', ar: 'الطبلة والدرامز الإيقاعية بالعصي', img: '🥁', o: ['Drum', 'Tambourine', 'Bell', 'Triangle'] },
    { name: 'Flute', ar: 'الناي والمزمار الهوائي ذو الثقوب', img: '🪈', o: ['Flute', 'Trumpet', 'Clarinet', 'Saxophone'] },
    { name: 'Trumpet', ar: 'البوق النحاسي اللامع عالي النغمة', img: '🎺', o: ['Trumpet', 'Saxophone', 'Flute', 'Trombone'] },
    { name: 'Saxophone', ar: 'الساكسفون النحاسي المنحني لموسيقى الجاز', img: '🎷', o: ['Saxophone', 'Trumpet', 'Clarinet', 'Horn'] },
    { name: 'Harp', ar: 'القيثارة والهارب متعدد الأوتار الرقيقة', img: '🪕', o: ['Harp', 'Guitar', 'Violin', 'Lute'] },
    { name: 'Accordion', ar: 'الأكورديون المنفاخي ذو لوحة المفاتيح', img: '🪗', o: ['Accordion', 'Piano', 'Harmonica', 'Organ'] },
    { name: 'Xylophone', ar: 'الزايلوفون الملون ذو الألواح الخشبية والمطارق', img: '🎶', o: ['Xylophone', 'Piano', 'Drum', 'Cymbals'] },
    { name: 'Tambourine', ar: 'الدَف ذو الصنوج المعدنية الصغيرة', img: '🪘', o: ['Tambourine', 'Drum', 'Triangle', 'Cymbals'] },
    { name: 'Triangle', ar: 'المثلث الموسيقي المعدني الرنان', img: '🔺', o: ['Triangle', 'Bell', 'Cymbals', 'Gong'] },
    { name: 'Cymbals', ar: 'الصنجان النحاسيان المتقرعان معاً', img: '🥁', o: ['Cymbals', 'Drums', 'Gong', 'Bell'] },
    { name: 'Clarinet', ar: 'الكلارينيت الخشبي الأسود', img: '🎷', o: ['Clarinet', 'Flute', 'Oboe', 'Trumpet'] },
    { name: 'Cello', ar: 'التشيلو الكبير الذي يعزف بين الركبتين', img: '🎻', o: ['Cello', 'Violin', 'Guitar', 'Harp'] },
    { name: 'Banjo', ar: 'البانجو ذو الصندوق الدائري والأوتار', img: '🪕', o: ['Banjo', 'Guitar', 'Ukulele', 'Mandolin'] },
    { name: 'Ukulele', ar: 'اليوكوليلي الصغير ذو الأوتار الأربعة', img: '🎸', o: ['Ukulele', 'Guitar', 'Banjo', 'Violin'] },
    { name: 'Harmonica', ar: 'الهرمونيكا (آلة النفخ الفموية)', img: '🎶', o: ['Harmonica', 'Flute', 'Whistle', 'Horn'] },
    { name: 'Bell', ar: 'الجرس الرنان ذو الصوت النقي', img: '🔔', o: ['Bell', 'Chime', 'Horn', 'Whistle'] },
    { name: 'Whistle', ar: 'الصافرة المخرجة لصوت حاد', img: '📣', o: ['Whistle', 'Flute', 'Horn', 'Bell'] },
    { name: 'Microphone', ar: 'ميكروفون الغناء للمطرب', img: '🎙️', o: ['Microphone', 'Speaker', 'Headphone', 'Recorder'] },
    { name: 'Headphones', ar: 'سماعات الأذن للاستماع للموسيقى', img: '🎧', o: ['Headphones', 'Speaker', 'Earbuds', 'Glasses'] },
    { name: 'Speaker', ar: 'مكبر صوت الحفلات الموسيقية', img: '🔊', o: ['Speaker', 'Microphone', 'Radio', 'Amp'] },
    { name: 'Music Note', ar: 'النوتة الموسيقية المكتوبة', img: '🎵', o: ['Music Note', 'Clef', 'Letter', 'Number'] },
    { name: 'Treble Clef', ar: 'مفتاح صول الموسيقي الأنيق', img: '🎼', o: ['Treble Clef', 'Bass Clef', 'Staff', 'Sharp'] },
    { name: 'Sheet Music', ar: 'ورقة ونوتة اللحن الموسيقي المدونة', img: '📄', o: ['Sheet Music', 'Book', 'Paper', 'Letter'] },
    { name: 'Melody', ar: 'اللحن العذب المتناغم', img: '🎶', o: ['Melody', 'Noise', 'Rhythm', 'Beat'] },
    { name: 'Rhythm', ar: 'الإيقاع المنتظم وضبط الوقت', img: '🥁', o: ['Rhythm', 'Melody', 'Harmony', 'Silence'] },
    { name: 'Song', ar: 'الأغنية والنشيد الجميل', img: '🎤', o: ['Song', 'Story', 'Poem', 'Speech'] },
    { name: 'Singer', ar: 'المغني والمطرب ذو الصوت الرخيم', img: '👨‍🎤', o: ['Singer', 'Dancer', 'Actor', 'Painter'] },
    { name: 'Band', ar: 'الفرقة الموسيقية المتكاملة العازفة', img: '🎸', o: ['Band', 'Orchestra', 'Choir', 'Team'] },
    { name: 'Orchestra', ar: 'الأوركسترا السمفونية الكبيرة المتعددة الآلات', img: '🎻', o: ['Orchestra', 'Band', 'Choir', 'Duet'] },
    { name: 'Choir', ar: 'الكورال وفرقة الإنشاد الجماعي', img: '🎶', o: ['Choir', 'Band', 'Orchestra', 'Solo'] },
    { name: 'Concert', ar: 'الحفل الموسيقي الحي أمام الجمهور', img: '🏟️', o: ['Concert', 'Play', 'Cinema', 'Match'] },
    { name: 'Stage', ar: 'مسرح العرض الموسيقي', img: '🎭', o: ['Stage', 'Hall', 'Room', 'Arena'] },
    { name: 'Composer', ar: 'المؤلف الموسيقي والمبتكر للألحان', img: '🎼', o: ['Composer', 'Writer', 'Director', 'Singer'] },
    { name: 'Conductor', ar: 'المايسترو وقائد الأوركسترا بالعصا', img: '🪄', o: ['Conductor', 'Leader', 'Director', 'Pianist'] },
    { name: 'Guitar Pick', ar: 'ريشة عزف الجيتار البلاستيكية', img: '🎸', o: ['Guitar Pick', 'String', 'Bow', 'Drumstick'] },
    { name: 'Drumsticks', ar: 'عصي قرع الطبول الخشبية', img: '🥢', o: ['Drumsticks', 'Picks', 'Bows', 'Sticks'] },
    { name: 'Volume', ar: 'مستوى علو وانخفاض الصوت', img: '🔊', o: ['Volume', 'Tone', 'Pitch', 'Echo'] },
    { name: 'Loud', ar: 'صوت مرتفع وقوي وعالٍ', img: '📢', o: ['Loud', 'Quiet', 'Soft', 'Silent'] },
    { name: 'Soft', ar: 'صوت هادئ ومنخفض ورقيق', img: '🤫', o: ['Soft', 'Loud', 'Noisy', 'Harsh'] },
    { name: 'Fast Tempo', ar: 'سرعة الإيقاع الموسيقي السريع', img: '🏃', o: ['Fast Tempo', 'Slow Tempo', 'Silence', 'Pause'] },
    { name: 'Slow Tempo', ar: 'الإيقاع الهادئ والبطيء للموسيقى', img: '🐢', o: ['Slow Tempo', 'Fast Tempo', 'Rapid', 'Rush'] },
    { name: 'Dance', ar: 'الرقص والتناغم الحركي مع النغمات', img: '💃', o: ['Dance', 'Sing', 'Jump', 'Clap'] },
    { name: 'Applause', ar: 'تصفيق الجمهور الحار إعجاباً بالعزف', img: '👏', o: ['Applause', 'Cheering', 'Silence', 'Singing'] },
    { name: 'Beat', ar: 'النبضة والضربة الإيقاعية للقلب أو الطبل', img: '🥁', o: ['Beat', 'Pause', 'Wave', 'Chord'] },
    { name: 'Harmony', ar: 'التوافق والانسجام بين النغمات', img: '🎶', o: ['Harmony', 'Noise', 'Discord', 'Clash'] },
    { name: 'Instrument', ar: 'الآلة الموسيقية بصفة عامة', img: '🎺', o: ['Instrument', 'Tool', 'Device', 'Toy'] },
    { name: 'Musical Scale', ar: 'السلم الموسيقي (دو ري مي فا صول لا سي)', img: '🎹', o: ['Musical Scale', 'Staff', 'Chords', 'Notes'] }
  ];
  games['الموسيقى والآلات بالإنجليزية'] = musicInstrumentsList.map((d, i) => ({
    id: 35001 + i,
    question: `ما اسم الآلة الموسيقية أو المصطلح (${d.ar}) بالإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 36. الاختبار الشامل في الإنجليزية
  const comprehensiveExamList = [
    { q: 'ما معنى كلمة Book باللغة العربية؟', img: '📖', correct: 'كتاب', opts: ['كتاب', 'قلم', 'دفتر', 'طاولة'], exp: 'Book تعني كتاب مفيد للقراءة.' },
    { q: 'ما معنى كلمة Water باللغة العربية؟', img: '💧', correct: 'ماء', opts: ['ماء', 'عصير', 'حليب', 'شاي'], exp: 'Water تعني ماء نقي للشرب.' },
    { q: 'ما الترجمة الإنجليزية لكلمة (مدرسة)؟', img: '🏫', correct: 'School', opts: ['School', 'House', 'Hospital', 'Park'], exp: 'مدرسة بالإنجليزية هي School.' },
    { q: 'ما الترجمة الإنجليزية لكلمة (معلم)؟', img: '🧑‍🏫', correct: 'Teacher', opts: ['Teacher', 'Doctor', 'Nurse', 'Driver'], exp: 'معلم أو أستاذ بالإنجليزية هو Teacher.' },
    { q: 'ما معنى كلمة Apple بالإنجليزية؟', img: '🍎', correct: 'تفاحة', opts: ['تفاحة', 'موزة', 'برتقالة', 'عنب'], exp: 'Apple تعني فاكهة التفاح اللذيذة.' },
    { q: 'أي مما يلي يمثل ضمير الغائب المذكر (هو) بالإنجليزية؟', img: '👦', correct: 'He', opts: ['He', 'She', 'It', 'They'], exp: 'He تعني هو للمفرد المذكر.' },
    { q: 'أي مما يلي يمثل ضمير الغائب المؤنث (هي) بالإنجليزية؟', img: '👧', correct: 'She', opts: ['She', 'He', 'We', 'You'], exp: 'She تعني هي للمفرد المؤنث.' },
    { q: 'ما الجمع الصحيح لكلمة Cat (قطة)؟', img: '🐱', correct: 'Cats', opts: ['Cats', 'Cates', 'Caties', 'Catss'], exp: 'جمع Cat هو إضافة حرف s فتصبح Cats.' },
    { q: 'ما عكس كلمة Big (كبير)؟', img: '🐘', correct: 'Small', opts: ['Small', 'Tall', 'Fast', 'Heavy'], exp: 'عكس Big (كبير) هو Small (صغير).' },
    { q: 'ما عكس كلمة Hot (حار)؟', img: '🔥', correct: 'Cold', opts: ['Cold', 'Warm', 'Wet', 'Dry'], exp: 'عكس Hot (حار) هو Cold (بارد).' },
    { q: 'ما هو الفعل الذي يعني (يأكل) بالإنجليزية؟', img: '🍽️', correct: 'Eat', opts: ['Eat', 'Drink', 'Sleep', 'Walk'], exp: 'Eat يعني يتناول الطعام أو يأكل.' },
    { q: 'ما هو الفعل الذي يعني (يشرب) بالإنجليزية؟', img: '🥛', correct: 'Drink', opts: ['Drink', 'Eat', 'Run', 'Cook'], exp: 'Drink يعني يشرب السوائل.' },
    { q: 'ما هو اللون الناتج عن كلمة Yellow؟', img: '🟡', correct: 'أصفر', opts: ['أصفر', 'أخضر', 'أحمر', 'أزرق'], exp: 'Yellow هو اللون الأصفر المشرق كالشمس.' },
    { q: 'ما هو الرقم المقابل لكلمة Ten؟', img: '🔟', correct: '10', opts: ['10', '5', '8', '20'], exp: 'Ten تعني الرقم عشرة (10).' },
    { q: 'ما هو اليوم الأول من الأسبوع بالإنجليزية (الأحد)؟', img: '📅', correct: 'Sunday', opts: ['Sunday', 'Monday', 'Friday', 'Saturday'], exp: 'Sunday هو يوم الأحد.' },
    { q: 'ما معنى كلمة Family باللغة العربية؟', img: '👨‍👩‍👧‍👦', correct: 'عائلة', opts: ['عائلة', 'أصدقاء', 'جيران', 'زملاء'], exp: 'Family تعني الأسرة والعائلة الكريمة.' },
    { q: 'ما هي الكلمة الإنجليزية التي تعني (شمس)؟', img: '☀️', correct: 'Sun', opts: ['Sun', 'Moon', 'Star', 'Cloud'], exp: 'Sun تعني الشمس المضيئة.' },
    { q: 'ما هي الكلمة الإنجليزية التي تعني (قمر)؟', img: '🌙', correct: 'Moon', opts: ['Moon', 'Sun', 'Earth', 'Sky'], exp: 'Moon تعني القمر المنير.' },
    { q: 'أي من الكلمات التالية تعتبر فاكهة خضراء صيفية (Watermelon)؟', img: '🍉', correct: 'بطيخ', opts: ['بطيخ', 'فراولة', 'خوخ', 'كرز'], exp: 'Watermelon هو البطيخ المنعش.' },
    { q: 'ماذا نقول بالإنجليزية للتحية في الصباح الباكر؟', img: '🌅', correct: 'Good morning', opts: ['Good morning', 'Good night', 'Good evening', 'Goodbye'], exp: 'نقول Good morning لتحية الصباح.' },
    { q: 'ماذا نقول بالإنجليزية قبل الذهاب للنوم؟', img: '🌙', correct: 'Good night', opts: ['Good night', 'Good afternoon', 'Hello', 'Please'], exp: 'نقول Good night أي تصبح على خير.' },
    { q: 'ما هي أداة السؤال التي تسأل عن المكان (أين)؟', img: '📍', correct: 'Where', opts: ['Where', 'When', 'Who', 'Why'], exp: 'Where تعني أين وتستخدم للسؤال عن المكان.' },
    { q: 'ما هي أداة السؤال التي تسأل عن الزمان (متى)؟', img: '⏰', correct: 'When', opts: ['When', 'Where', 'What', 'How'], exp: 'When تعني متى وتستخدم للسؤال عن الوقت.' },
    { q: 'ما هي أداة السؤال التي تسأل عن الأشخاص (مَن)؟', img: '👤', correct: 'Who', opts: ['Who', 'Which', 'Why', 'What'], exp: 'Who تعني مَن وتسأل عن العاقل والأشخاص.' },
    { q: 'أي كلمة تعني (أخي) باللغة الإنجليزية؟', img: '👦', correct: 'Brother', opts: ['Brother', 'Sister', 'Father', 'Mother'], exp: 'Brother تعني الأخ.' },
    { q: 'أي كلمة تعني (أختي) باللغة الإنجليزية؟', img: '👧', correct: 'Sister', opts: ['Sister', 'Brother', 'Aunt', 'Cousin'], exp: 'Sister تعني الأخت.' },
    { q: 'ما معنى كلمة Eyes في جسم الإنسان؟', img: '👁️', correct: 'عيون', opts: ['عيون', 'آذان', 'أنف', 'أيدي'], exp: 'Eyes تعني العيون المبصرة.' },
    { q: 'ما معنى كلمة Hands في جسم الإنسان؟', img: '🖐️', correct: 'أيدي', opts: ['أيدي', 'أقدام', 'أرجل', 'أصابع'], exp: 'Hands تعني الأيدي الكريمة.' },
    { q: 'ما هي الكلمة التي تعني (سيارة) بالإنجليزية؟', img: '🚗', correct: 'Car', opts: ['Car', 'Bus', 'Bike', 'Train'], exp: 'Car تعني السيارة الصغيرة.' },
    { q: 'ما هي الكلمة التي تعني (طائرة) بالإنجليزية؟', img: '✈️', correct: 'Plane', opts: ['Plane', 'Boat', 'Car', 'Truck'], exp: 'Plane تعني الطائرة المحلقة.' },
    { q: 'ما هي الكلمة التي تعني (سعيد) بالإنجليزية؟', img: '😊', correct: 'Happy', opts: ['Happy', 'Sad', 'Angry', 'Tired'], exp: 'Happy تعني مسرور وسعيد.' },
    { q: 'ما هي الكلمة التي تعني (حزين) بالإنجليزية؟', img: '😢', correct: 'Sad', opts: ['Sad', 'Happy', 'Excited', 'Glad'], exp: 'Sad تعني حزين وكئيب.' },
    { q: 'ماذا نسمي وجبة الصباح الأولى بالإنجليزية؟', img: '🥞', correct: 'Breakfast', opts: ['Breakfast', 'Lunch', 'Dinner', 'Snack'], exp: 'Breakfast هي وجبة الإفطار الصباحية.' },
    { q: 'ماذا نسمي وجبة المساء الختامية بالإنجليزية؟', img: '🍲', correct: 'Dinner', opts: ['Dinner', 'Breakfast', 'Lunch', 'Brunch'], exp: 'Dinner هي وجبة العشاء المسائية.' },
    { q: 'ما هو الحرف الأول في الأبجدية الإنجليزية؟', img: '🔤', correct: 'A', opts: ['A', 'B', 'C', 'Z'], exp: 'الحرف الأول هو حرف A (Apple, Ant).' },
    { q: 'ما هو الحرف الأخير في الأبجدية الإنجليزية؟', img: '🔤', correct: 'Z', opts: ['Z', 'Y', 'X', 'A'], exp: 'الحرف الأخير هو حرف Z (Zebra, Zoo).' },
    { q: 'أي من الكلمات التالية يعني (كلب)؟', img: '🐶', correct: 'Dog', opts: ['Dog', 'Cat', 'Lion', 'Duck'], exp: 'Dog هو الكلب الوفي.' },
    { q: 'أي من الكلمات التالية يعني (أسد ملك الغابة)؟', img: '🦁', correct: 'Lion', opts: ['Lion', 'Tiger', 'Bear', 'Elephant'], exp: 'Lion هو الأسد الشجاع.' },
    { q: 'ما معنى كلمة Bird باللغة العربية؟', img: '🐦', correct: 'طائر', opts: ['طائر', 'سمكة', 'حشرة', 'أرنب'], exp: 'Bird تعني الطائر المغرد في السماء.' },
    { q: 'ما معنى كلمة Fish باللغة العربية؟', img: '🐟', correct: 'سمكة', opts: ['سمكة', 'ضفدع', 'سلحفاة', 'قرش'], exp: 'Fish تعني السمكة السابحة بالماء.' },
    { q: 'كيف نقول (شكراً لك) بالإنجليزية؟', img: '🙏', correct: 'Thank you', opts: ['Thank you', 'Please', 'Sorry', 'Excuse me'], exp: 'Thank you تعني شكراً لك للامتنان.' },
    { q: 'كيف نطلب شيئاً بأدب ونقول (من فضلك)؟', img: '🤲', correct: 'Please', opts: ['Please', 'Thank you', 'Welcome', 'Stop'], exp: 'Please تعني من فضلك أو لو سمحت.' },
    { q: 'ما عكس كلمة Fast (سريع)؟', img: '🐢', correct: 'Slow', opts: ['Slow', 'Quick', 'Loud', 'Hard'], exp: 'عكس Fast (سريع) هو Slow (بطيء كالسلحفاة).' },
    { q: 'ما عكس كلمة Easy (سهل)؟', img: '🧩', correct: 'Hard', opts: ['Hard', 'Simple', 'Soft', 'Light'], exp: 'عكس Easy (سهل) هو Hard أو Difficult (صعب).' },
    { q: 'ماذا يسمى الطبيب المعالج للمرضى بالإنجليزية؟', img: '👨‍⚕️', correct: 'Doctor', opts: ['Doctor', 'Engineer', 'Pilot', 'Chef'], exp: 'طبيب بالإنجليزية هو Doctor.' },
    { q: 'ماذا يسمى المهندس المعماري بالإنجليزية؟', img: '👷', correct: 'Engineer', opts: ['Engineer', 'Doctor', 'Teacher', 'Farmer'], exp: 'مهندس بالإنجليزية هو Engineer.' },
    { q: 'ما هي الكلمة التي تعني (مطر) بالإنجليزية؟', img: '🌧️', correct: 'Rain', opts: ['Rain', 'Snow', 'Wind', 'Sun'], exp: 'Rain تعني ماء المطر المنهمر.' },
    { q: 'ما هي الكلمة التي تعني (ثلج) بالإنجليزية؟', img: '❄️', correct: 'Snow', opts: ['Snow', 'Rain', 'Ice', 'Fog'], exp: 'Snow تعني الثلج الأبيض المتساقط.' },
    { q: 'أي من الكلمات التالية تعني (حديقة) بالإنجليزية؟', img: '🌳', correct: 'Garden', opts: ['Garden', 'Room', 'Kitchen', 'Street'], exp: 'Garden تعني الحديقة والروضة المزهرة.' },
    { q: 'ما هو التعبير الذي يعني (أنا أحب القراءة) بالإنجليزية؟', img: '📖', correct: 'I like reading', opts: ['I like reading', 'I like sleeping', 'I like eating', 'I like running'], exp: 'I like reading تعني أنا أحب القراءة والمطالعة.' }
  ];
  games['الاختبار الشامل في الإنجليزية'] = comprehensiveExamList.map((d, i) => ({
    id: 36001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  // 37. الحشرات والزواحف بالإنجليزية
  const insectsReptilesList = [
    { name: 'Butterfly', ar: 'الفراشة الملونة الجميلة ذات الجناحين', img: '🦋', o: ['Butterfly', 'Bee', 'Fly', 'Moth'] },
    { name: 'Bee', ar: 'النحلة العاملة صانعة العسل في الخلية', img: '🐝', o: ['Bee', 'Wasp', 'Ant', 'Beetle'] },
    { name: 'Ant', ar: 'النملة النشيطة المجتهدة في جمع الحبوب', img: '🐜', o: ['Ant', 'Termite', 'Fly', 'Flea'] },
    { name: 'Ladybug', ar: 'الدعسوقة الحمراء المنقطة بالأسود', img: '🐞', o: ['Ladybug', 'Beetle', 'Spider', 'Caterpillar'] },
    { name: 'Spider', ar: 'العنكبوت ناسج الشبكة الحريرية بثمانية أرجل', img: '🕷️', o: ['Spider', 'Scorpion', 'Tick', 'Crab'] },
    { name: 'Caterpillar', ar: 'اليرقة الخضراء الصغيرة التي تتحول لفراشة', img: '🐛', o: ['Caterpillar', 'Worm', 'Snail', 'Centipede'] },
    { name: 'Grasshopper', ar: 'الجراد والنطاط القافز فوق الأعشاب الخضراء', img: '🦗', o: ['Grasshopper', 'Cricket', 'Mantis', 'Locust'] },
    { name: 'Dragonfly', ar: 'اليعسوب الرشيق السريع ذو الأجنحة الشفافة', img: '🪰', o: ['Dragonfly', 'Mosquito', 'Fly', 'Bee'] },
    { name: 'Mosquito', ar: 'البعوضة التي تصدر طنيناً وتتغذى على اللدغ', img: '🦟', o: ['Mosquito', 'Fly', 'Wasp', 'Gnat'] },
    { name: 'Fly', ar: 'الذبابة المنزلية الشائعة', img: '🪰', o: ['Fly', 'Mosquito', 'Bee', 'Beetle'] },
    { name: 'Beetle', ar: 'الخنفساء ذات الدرع الصلب اللامع', img: '🪲', o: ['Beetle', 'Cockroach', 'Ant', 'Bug'] },
    { name: 'Cockroach', ar: 'الصرصور السريع الحركة في الظلام', img: '🪳', o: ['Cockroach', 'Cricket', 'Beetle', 'Bug'] },
    { name: 'Cricket', ar: 'صرار الليل ذو الصوت الموسيقي الصيفي', img: '🦗', o: ['Cricket', 'Grasshopper', 'Beetle', 'Fly'] },
    { name: 'Snail', ar: 'الحلزون البطيء الحامل قوقعته على ظهره', img: '🐌', o: ['Snail', 'Slug', 'Turtle', 'Worm'] },
    { name: 'Slug', ar: 'البصاق والحلزون العاري دون قوقعة', img: '🐌', o: ['Slug', 'Snail', 'Worm', 'Leech'] },
    { name: 'Earthworm', ar: 'دودة الأرض الوردية التي تحفر الأنفاق بالتربة', img: '🪱', o: ['Earthworm', 'Caterpillar', 'Snake', 'Centipede'] },
    { name: 'Centipede', ar: 'أم أربعة وأربعين كثيرة الأرجل السريعة', img: '🐛', o: ['Centipede', 'Millipede', 'Worm', 'Caterpillar'] },
    { name: 'Mantis', ar: 'فرس النبي (السرعوف) الواقف بوضعية الصلاة', img: '🦗', o: ['Mantis', 'Grasshopper', 'Locust', 'Cricket'] },
    { name: 'Scorpion', ar: 'العقرب ذو الكماشتين والذيل المنتهي بالإبرة', img: '🦂', o: ['Scorpion', 'Spider', 'Crab', 'Beetle'] },
    { name: 'Wasp', ar: 'الدبور الأصفر ذو اللدغة الحادة المؤلمة', img: '🐝', o: ['Wasp', 'Bee', 'Hornet', 'Fly'] },
    { name: 'Snake', ar: 'الثعبان والأفعى الزاحفة بلا أرجل', img: '🐍', o: ['Snake', 'Lizard', 'Worm', 'Eel'] },
    { name: 'Lizard', ar: 'السحلية الرشيقة المتسلقة للجدران', img: '🦎', o: ['Lizard', 'Chameleon', 'Gecko', 'Crocodile'] },
    { name: 'Gecko', ar: 'البرص والوزغ المتسلق للزجاج بأصابعه اللاصقة', img: '🦎', o: ['Gecko', 'Lizard', 'Frog', 'Chameleon'] },
    { name: 'Chameleon', ar: 'الحرباء المتلونة التي تغير لون جلدها للتمويه', img: '🦎', o: ['Chameleon', 'Lizard', 'Iguana', 'Gecko'] },
    { name: 'Turtle', ar: 'السلحفاة البرية المعمرة ذات الدرع القوي', img: '🐢', o: ['Turtle', 'Tortoise', 'Snail', 'Crab'] },
    { name: 'Tortoise', ar: 'سلحفاة اليابسة الضخمة البطيئة المشي', img: '🐢', o: ['Tortoise', 'Turtle', 'Chameleon', 'Crocodile'] },
    { name: 'Sea Turtle', ar: 'سلحفاة البحر السابحة بزعانفها في المحيط', img: '🐢', o: ['Sea Turtle', 'Seal', 'Whale', 'Dolphin'] },
    { name: 'Crocodile', ar: 'التمساح النيلي المفترس ذو الفك القوي والأسنان الحادة', img: '🐊', o: ['Crocodile', 'Alligator', 'Lizard', 'Dinosaur'] },
    { name: 'Alligator', ar: 'القاطور التمساحي عريض الخطم في المستنقعات', img: '🐊', o: ['Alligator', 'Crocodile', 'Iguana', 'Monitor'] },
    { name: 'Frog', ar: 'الضفدع البرمائي القافز ناعم الجلد', img: '🐸', o: ['Frog', 'Toad', 'Lizard', 'Salamander'] },
    { name: 'Toad', ar: 'العلجوم الأرضي ذو الجلد الخشن المحبب', img: '🐸', o: ['Toad', 'Frog', 'Turtle', 'Gecko'] },
    { name: 'Tadpole', ar: 'أبو ذنيبة صغير الضفدع السابح بالذيل في الماء', img: '🐟', o: ['Tadpole', 'Fish', 'Larva', 'Minnow'] },
    { name: 'Salamander', ar: 'السمندل البرمائي ذو الذيل الطويل والألوان البراقة', img: '🦎', o: ['Salamander', 'Lizard', 'Gecko', 'Frog'] },
    { name: 'Iguana', ar: 'الإغوانا الخضراء الكبيرة ذات الشوكة الظهرية', img: '🦎', o: ['Iguana', 'Chameleon', 'Lizard', 'Crocodile'] },
    { name: 'Komodo Dragon', ar: 'تنين كومودو أضخم وأكبر سحلية مفترسة بالعالم', img: '🦎', o: ['Komodo Dragon', 'Crocodile', 'Dinosaur', 'Alligator'] },
    { name: 'Cobra', ar: 'أفعى الكوبرا الملكية ذات القلنسوة العريضة', img: '🐍', o: ['Cobra', 'Viper', 'Python', 'Anaconda'] },
    { name: 'Python', ar: 'أفعى الأصلة العاصرة الضخمة غير السامة', img: '🐍', o: ['Python', 'Cobra', 'Rattlesnake', 'Viper'] },
    { name: 'Rattlesnake', ar: 'الأفعى المجلجلة ذات الجرس الصوتي بذيلها', img: '🐍', o: ['Rattlesnake', 'Cobra', 'Python', 'Mamba'] },
    { name: 'Firefly', ar: 'حشرة اليراعة والمصباح المضيء في ظلام الليل', img: '✨', o: ['Firefly', 'Moth', 'Beetle', 'Glowworm'] },
    { name: 'Moth', ar: 'عثة الليل الفراشية المنجذبة لضوء المصابيح', img: '🦋', o: ['Moth', 'Butterfly', 'Fly', 'Bee'] },
    { name: 'Flea', ar: 'البرغوث الصغير الماهر في القفز العالي', img: '🪲', o: ['Flea', 'Tick', 'Louse', 'Ant'] },
    { name: 'Tick', ar: 'القرادة الملتصقة بفراء الحيوانات الأليفة', img: '🕷️', o: ['Tick', 'Flea', 'Mite', 'Spider'] },
    { name: 'Termite', ar: 'النمل الأبيض آكل الأخشاب وباني التلال الطينية', img: '🐜', o: ['Termite', 'Ant', 'Beetle', 'Worm'] },
    { name: 'Ant Colony', ar: 'مستعمرة وقرية النمل المنظمة تحت الأرض', img: '🐜', o: ['Ant Colony', 'Beehive', 'Nest', 'Burrow'] },
    { name: 'Beehive', ar: 'خلية النحل العامرة بالشمع والعسل اللذيذ', img: '🐝', o: ['Beehive', 'Wasp Nest', 'Ant Colony', 'Hole'] },
    { name: 'Cocoon', ar: 'شرنقة الحرير التي تغزلها دودة القز لتتحول لفراشة', img: '🧶', o: ['Cocoon', 'Shell', 'Egg', 'Web'] },
    { name: 'Spiderweb', ar: 'شبكة العنكبوت الحريرية الدقيقة لصيد الحشرات', img: '🕸️', o: ['Spiderweb', 'Nest', 'Cocoon', 'String'] },
    { name: 'Venom', ar: 'السم الزعاف للأفاعي والعقارب للدفاع والصيد', img: '🧪', o: ['Venom', 'Poison', 'Acid', 'Water'] },
    { name: 'Scale', ar: 'الحرشفة المكسوة على جلد الثعبان والتمساح', img: '🦎', o: ['Scale', 'Fur', 'Feather', 'Skin'] },
    { name: 'Antennae', ar: 'قرون الاستشعار لدى الحشرات لتلمس الروائح', img: '🐜', o: ['Antennae', 'Wings', 'Legs', 'Eyes'] }
  ];
  games['الحشرات والزواحف بالإنجليزية'] = insectsReptilesList.map((d, i) => ({
    id: 37001 + i,
    question: `ما اسم الحشرة أو الزاحف (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 38. أجزاء البيت والغرف بالإنجليزية
  const houseRoomsList = [
    { name: 'Living Room', ar: 'غرفة المعيشة والجلوس واستقبال العائلة', img: '🛋️', o: ['Living Room', 'Bedroom', 'Kitchen', 'Bathroom'] },
    { name: 'Bedroom', ar: 'غرفة النوم الهادئة المجهزة بالسرير للراحة', img: '🛏️', o: ['Bedroom', 'Living Room', 'Dining Room', 'Hall'] },
    { name: 'Kitchen', ar: 'المطبخ لإعداد وطهي الوجبات الشهية', img: '🍳', o: ['Kitchen', 'Bathroom', 'Balcony', 'Garage'] },
    { name: 'Bathroom', ar: 'الحمام للاستحمام والنظافة الشخصية', img: '🛁', o: ['Bathroom', 'Kitchen', 'Bedroom', 'Basement'] },
    { name: 'Dining Room', ar: 'غرفة الطعام المخصصة لتناول الوجبات العائلية', img: '🍽️', o: ['Dining Room', 'Living Room', 'Pantry', 'Hall'] },
    { name: 'Balcony', ar: 'الشرفة والبلكونة المطلة على الخارج للهواء النقي', img: '🏡', o: ['Balcony', 'Roof', 'Yard', 'Attic'] },
    { name: 'Garden', ar: 'حديقة المنزل المزهرة بالورود والأشجار', img: '🌳', o: ['Garden', 'Garage', 'Hall', 'Porch'] },
    { name: 'Garage', ar: 'المرآب وجراج ركن السيارة بأمان', img: '🚗', o: ['Garage', 'Basement', 'Attic', 'Shed'] },
    { name: 'Hall', ar: 'الممر والرواق الواصل بين غرف البيت', img: '🚪', o: ['Hall', 'Room', 'Porch', 'Stairs'] },
    { name: 'Attic', ar: 'العلية والغرفة أسفل السقف لحفظ الأمتعة', img: '🏠', o: ['Attic', 'Basement', 'Balcony', 'Roof'] },
    { name: 'Basement', ar: 'القبو والطابق السفلي تحت الأرض', img: '🏚️', o: ['Basement', 'Attic', 'Garage', 'Yard'] },
    { name: 'Roof', ar: 'سطح المنزل وسقفه العلوي الحامي من الأمطار', img: '🏠', o: ['Roof', 'Floor', 'Wall', 'Ceiling'] },
    { name: 'Ceiling', ar: 'السقف الداخلي للغرفة المعلقة به الثريا', img: '💡', o: ['Ceiling', 'Floor', 'Roof', 'Wall'] },
    { name: 'Floor', ar: 'أرضية الغرفة المفروشة بالسجاد أو البلاط', img: '🪵', o: ['Floor', 'Ceiling', 'Wall', 'Door'] },
    { name: 'Wall', ar: 'الجدار والحائط المزين باللوحات والدهان', img: '🧱', o: ['Wall', 'Floor', 'Window', 'Door'] },
    { name: 'Door', ar: 'الباب الخشبي لمدخل الغرفة والمنزل', img: '🚪', o: ['Door', 'Window', 'Wall', 'Gate'] },
    { name: 'Window', ar: 'النافذة والشباك لدخول ضوء الشمس والتهوية', img: '🪟', o: ['Window', 'Door', 'Curtain', 'Mirror'] },
    { name: 'Stairs', ar: 'الدرج والسلالم للصعود للطابق العلوي', img: '🪜', o: ['Stairs', 'Elevator', 'Ladder', 'Ramp'] },
    { name: 'Elevator', ar: 'المصعد الكهربائي للصعود بين الطوابق بسهولة', img: '🛗', o: ['Elevator', 'Stairs', 'Escalator', 'Door'] },
    { name: 'Chimney', ar: 'المدخنة على السطح لخروج دخان المدفأة', img: '🏠', o: ['Chimney', 'Roof', 'Pipe', 'Vent'] },
    { name: 'Fireplace', ar: 'المدفأة المنزلية الحطبية للشتاء البارد', img: '🔥', o: ['Fireplace', 'Heater', 'Stove', 'Oven'] },
    { name: 'Closet', ar: 'خزانة الملابس الجدارية لحفظ الثياب', img: '🚪', o: ['Closet', 'Drawer', 'Shelf', 'Box'] },
    { name: 'Drawer', ar: 'الدرج القابل للسحب في الطاولة أو الخزانة', img: '🗄️', o: ['Drawer', 'Closet', 'Shelf', 'Desk'] },
    { name: 'Shelf', ar: 'الرف الجداري لترتيب الكتب والتحف', img: '📚', o: ['Shelf', 'Table', 'Desk', 'Floor'] },
    { name: 'Curtains', ar: 'الستائر القماشية الأنيقة لحجب الضوء عند النوم', img: '🪟', o: ['Curtains', 'Blinds', 'Sheet', 'Blanket'] },
    { name: 'Carpet', ar: 'السجاد المنسوج والمفروش على الأرضية', img: '🧶', o: ['Carpet', 'Mat', 'Tile', 'Sheet'] },
    { name: 'Mat', ar: 'الممسحة والدواسة عند عتبة باب المنزل', img: '🚪', o: ['Mat', 'Carpet', 'Towel', 'Blanket'] },
    { name: 'Bed', ar: 'السرير المريح المزود بالمرتبة للنوم الهانئ', img: '🛏️', o: ['Bed', 'Sofa', 'Couch', 'Crib'] },
    { name: 'Pillow', ar: 'الوسادة والمخدة المريحة للرأس', img: '🛏️', o: ['Pillow', 'Blanket', 'Sheet', 'Cushion'] },
    { name: 'Blanket', ar: 'البطانية واللحاف الصوفي الدافئ', img: '🛌', o: ['Blanket', 'Pillow', 'Curtain', 'Towel'] },
    { name: 'Sofa', ar: 'الكنبة والأريكة المريحة في غرفة الجلوس', img: '🛋️', o: ['Sofa', 'Chair', 'Bed', 'Bench'] },
    { name: 'Armchair', ar: 'الكرسي الوثير ذو المسندين المريحين للذراعين', img: '🪑', o: ['Armchair', 'Sofa', 'Stool', 'Bench'] },
    { name: 'Coffee Table', ar: 'طاولة القهوة الصغيرة بمنتصف غرفة المعيشة', img: '☕', o: ['Coffee Table', 'Dining Table', 'Desk', 'Nightstand'] },
    { name: 'Desk', ar: 'مكتب الدراسة والمذاكرة المزود بالدرج', img: '🖥️', o: ['Desk', 'Dining Table', 'Bench', 'Shelf'] },
    { name: 'Bookshelf', ar: 'مكتبة وحاملة الكتب المرتبة في الغرفة', img: '📚', o: ['Bookshelf', 'Wardrobe', 'Desk', 'Locker'] },
    { name: 'Lamp', ar: 'المصباح وأباجورة الإضاءة على الطاولة', img: '💡', o: ['Lamp', 'Bulb', 'Chandelier', 'Candle'] },
    { name: 'Chandelier', ar: 'الثريا الفخمة المتدلية من منتصف السقف', img: '💡', o: ['Chandelier', 'Lamp', 'Fan', 'Light'] },
    { name: 'Ceiling Fan', ar: 'مروحة السقف لتلطيف هواء الغرفة صيفاً', img: '🌀', o: ['Ceiling Fan', 'Air Conditioner', 'Heater', 'Lamp'] },
    { name: 'Air Conditioner', ar: 'مكيف الهواء لتبريد وتدفئة البيت', img: '❄️', o: ['Air Conditioner', 'Fan', 'Heater', 'Fridge'] },
    { name: 'Heater', ar: 'المدفأة الكهربائية لتسخين الغرفة بالبرد', img: '🔥', o: ['Heater', 'Air Conditioner', 'Fan', 'Oven'] },
    { name: 'Mirror', ar: 'المرآة الصافية العاكسة للوجه في الحمام', img: '🪞', o: ['Mirror', 'Window', 'Glass', 'Picture'] },
    { name: 'Bathtub', ar: 'حوض الاستحمام (البانيو) المليء بالرغوة الدافئة', img: '🛁', o: ['Bathtub', 'Sink', 'Shower', 'Pool'] },
    { name: 'Shower', ar: 'دش ورشاش الاستحمام السريع', img: '🚿', o: ['Shower', 'Bathtub', 'Sink', 'Faucet'] },
    { name: 'Sink', ar: 'حوض ومغسلة الأيدي بالصابون في الحمام', img: '🚰', o: ['Sink', 'Bathtub', 'Shower', 'Bucket'] },
    { name: 'Faucet', ar: 'صنبور وحنفية تدفق الماء العذب', img: '🚰', o: ['Faucet', 'Pipe', 'Hose', 'Drain'] },
    { name: 'Toilet', ar: 'المرحاض الصحي في الحمام', img: '🚽', o: ['Toilet', 'Sink', 'Tub', 'Bidet'] },
    { name: 'Towel Rack', ar: 'علاقة وحامل المناشف القطنية بالحمام', img: '🧖', o: ['Towel Rack', 'Shelf', 'Hook', 'Hanger'] },
    { name: 'Doorknob', ar: 'مقبض الباب لفتحه وإغلاقه بسهولة', img: '🚪', o: ['Doorknob', 'Key', 'Lock', 'Hinge'] },
    { name: 'Key', ar: 'المفتاح لقفل وفتح قفل الباب بأمان', img: '🔑', o: ['Key', 'Lock', 'Doorknob', 'Chain'] },
    { name: 'Doorbell', ar: 'جرس الباب الخارجي لإعلام أهل البيت بقدوم ضيف', img: '🔔', o: ['Doorbell', 'Alarm', 'Lock', 'Intercom'] }
  ];
  games['أجزاء البيت والغرف بالإنجليزية'] = houseRoomsList.map((d, i) => ({
    id: 38001 + i,
    question: `ما اسم جزء البيت أو الأثاث (${d.ar}) باللغة الإنجليزية؟`,
    image: d.img,
    options: d.o,
    correctAnswer: d.name,
    explanation: `${d.ar} باللغة الإنجليزية يُسمى '${d.name}'.`
  }));

  // 39. قصص ومحادثات قصيرة بالإنجليزية
  const shortStoriesList = [
    { q: 'عندما تقابل صديقك أحمد في الصباح، ماذا تقول له كتحية؟', img: '🌅', correct: 'Good morning, Ahmed!', opts: ['Good morning, Ahmed!', 'Good night, Ahmed!', 'Goodbye, Ahmed!', 'See you never!'], exp: 'في الصباح نقول Good morning.' },
    { q: 'إذا سألك المعلم: What is your favorite color? بماذا تجيب؟', img: '🎨', correct: 'My favorite color is blue.', opts: ['My favorite color is blue.', 'I am seven years old.', 'I like apples.', 'My name is Ali.'], exp: 'السؤال عن اللون المفضل يُجاب بـ My favorite color is...' },
    { q: 'إذا أردت استعارة قلم من زميلك بأدب، ماذا تقول له؟', img: '✏️', correct: 'Can I borrow your pencil, please?', opts: ['Can I borrow your pencil, please?', 'Give me the pencil now!', 'Where is my pencil?', 'I hate pencils.'], exp: 'الطلب المهذب يبدأ بـ Can I... وينتهي بـ please.' },
    { q: 'عندما يقدم لك شخص هدية جميلة، ماذا تجيبه تقديراً له؟', img: '🎁', correct: 'Thank you very much!', opts: ['Thank you very much!', 'I do not care.', 'Excuse me!', 'No problem.'], exp: 'عند تلقي الهدية نقول Thank you very much.' },
    { q: 'إذا صدمت زميلك عن غير قصد واعتذرت، ماذا تقول؟', img: '🥺', correct: 'I am so sorry!', opts: ['I am so sorry!', 'Good job!', 'You are welcome!', 'Congratulations!'], exp: 'للاعتذار نقول I am sorry.' },
    { q: 'في القصة: (The cat is sleeping under the tree). أين تنام القطة؟', img: '🐱', correct: 'تحت الشجرة', opts: ['تحت الشجرة', 'فوق الشجرة', 'في المنزل', 'في السيارة'], exp: 'Under the tree تعني تحت الشجرة.' },
    { q: 'في القصة: (The rabbit loves to eat orange carrots). ماذا يحب الأرنب أن يأكل؟', img: '🥕', correct: 'جزر برتقالي', opts: ['جزر برتقالي', 'تفاح أحمر', 'خس أخضر', 'خبز طازج'], exp: 'Orange carrots تعني جزر برتقالي.' },
    { q: 'في الحوار: (How old are you? - I am eight years old). كم عمر الطفل؟', img: '🎂', correct: '8 سنوات', opts: ['8 سنوات', '5 سنوات', '10 سنوات', '7 سنوات'], exp: 'Eight years old تعني 8 سنوات.' },
    { q: 'في الحوار: (Where is the book? - It is on the desk). أين الكتاب؟', img: '📖', correct: 'على المكتب', opts: ['على المكتب', 'تحت السرير', 'في الحقيبة', 'خارج الغرفة'], exp: 'On the desk تعني على سطح المكتب.' },
    { q: 'في القصة: (Sami has a red bicycle. He rides it in the park). ماذا يملك سامي؟', img: '🚲', correct: 'دراجة هوائية حمراء', opts: ['دراجة هوائية حمراء', 'سيارة زرقاء', 'لوح تزلج أصفر', 'طائرة ورقية'], exp: 'Red bicycle تعني دراجة هوائية حمراء.' },
    { q: 'عند مغادرة بيت صديقك عائداً لمنزلك، ماذا تقول له؟', img: '👋', correct: 'Goodbye! See you tomorrow!', opts: ['Goodbye! See you tomorrow!', 'Good morning!', 'Hello there!', 'Welcome back!'], exp: 'عند الوداع نقول Goodbye! See you tomorrow!' },
    { q: 'إذا سألك السائح: Where is the library? ماذا تعني كلمة library؟', img: '📚', correct: 'المكتبة العامة', opts: ['المكتبة العامة', 'المطعم', 'الملعب', 'المطار'], exp: 'Library تعني المكتبة الممتلئة بالكتب.' },
    { q: 'في القصة: (The bird is singing on the branch). ماذا يفعل الطائر؟', img: '🐦', correct: 'يغرد وينشد', opts: ['يغرد وينشد', 'ينام في عشه', 'يأكل حبة قمح', 'يشرب ماء'], exp: 'Singing تعني يغرد ويغني بصوت عذب.' },
    { q: 'في الحوار: (Do you like milk? - Yes, I do!). هل يحب الحليب؟', img: '🥛', correct: 'نعم، هو يحبه كثيراً', opts: ['نعم، هو يحبه كثيراً', 'كلا، لا يحبه', 'هو يفضل العصير', 'هو لا يدري'], exp: 'Yes, I do تعني نعم بالتأكيد.' },
    { q: 'في القصة: (The dog wags its tail when it is happy). متى يهز الكلب ذيله؟', img: '🐕', correct: 'عندما يكون سعيداً', opts: ['عندما يكون سعيداً', 'عندما يغضب', 'عندما يجوع', 'عندما ينعس'], exp: 'When it is happy تعني عندما يشعر بالفرح والسرور.' },
    { q: 'إذا أردت أن تسأل رفيقك عن حاله، أي جملة تختار؟', img: '😊', correct: 'How are you today?', opts: ['How are you today?', 'What time is it?', 'Where do you live?', 'How much is this?'], exp: 'How are you today تعني كيف حالك اليوم.' },
    { q: 'في القصة: (The sun is shining and the sky is blue). ما هي حالة الطقس؟', img: '☀️', correct: 'مشمس والسماء زرقاء صافية', opts: ['مشمس والسماء زرقاء صافية', 'ماطر وعاصف بالرعد', 'مثلج شديد البرودة', 'ضبابي معتم'], exp: 'Sun is shining تعني الشمس مشرقة وساطعة.' },
    { q: 'في الحوار: (What time is it? - It is five o’clock). كم الساعة الآن؟', img: '🕔', correct: 'الساعة الخامسة تماماً', opts: ['الساعة الخامسة تماماً', 'الساعة السادسة والنصف', 'الساعة الرابعة والربع', 'منتصف الليل'], exp: 'Five o’clock تعني الخامسة تماماً.' },
    { q: 'في القصة: (Mona drinks orange juice every morning). ماذا تشرب منى؟', img: '🍊', correct: 'عصير البرتقال', opts: ['عصير البرتقال', 'الحليب الدافئ', 'الشاي بالنعناع', 'الماء المثلج'], exp: 'Orange juice يعني عصير البرتقال الطازج.' },
    { q: 'عندما يطرق ضيف الباب، ماذا تقول له مرحباً بدخوله؟', img: '🚪', correct: 'Welcome! Please come in.', opts: ['Welcome! Please come in.', 'Goodbye forever.', 'Close the door!', 'Who are you?'], exp: 'Welcome! Please come in تعني مرحباً تفضل بالدخول.' },
    { q: 'في القصة: (The little fish swims fast in the blue sea). أين تسبح السمكة؟', img: '🐟', correct: 'في البحر الأزرق', opts: ['في البحر الأزرق', 'في حوض الزجاج', 'في النهر الصغير', 'في البحيرة'], exp: 'Blue sea تعني البحر الأزرق الفسيح.' },
    { q: 'في الحوار: (Can you help me? - Of course, with pleasure!). ما هو رد المساعد؟', img: '🤝', correct: 'بالتأكيد وبكل سرور!', opts: ['بالتأكيد وبكل سرور!', 'أنا مشغول جداً', 'لا أستطيع المساعدة', 'اذهب بعيداً'], exp: 'Of course, with pleasure تعني طبعاً بكل سرور.' },
    { q: 'في القصة: (The baby is laughing loudly). ماذا يفعل الرضيع الصغير؟', img: '👶', correct: 'يضحك بصوت عالٍ ومرح', opts: ['يضحك بصوت عالٍ ومرح', 'يبكي من الجوع', 'ينام في مهده', 'يحبو على الأرض'], exp: 'Laughing loudly تعني يضحك بصوت مرتفع مسرور.' },
    { q: 'عندما ينهي صديقك رسم لوحة مبهرة، ماذا تقول لتشجيعه؟', img: '🎨', correct: 'Great job! It looks wonderful!', opts: ['Great job! It looks wonderful!', 'This is very bad.', 'Erase it now!', 'I do not like it.'], exp: 'Great job تعني عمل رائع ومتقن.' },
    { q: 'في القصة: (The green frog jumps into the water with a splash). ماذا فعل الضفدع؟', img: '🐸', correct: 'قفز في الماء برشة مائية', opts: ['قفز في الماء برشة مائية', 'نام تحت الورقة', 'مشى على الطين', 'تسلق الشجرة'], exp: 'Jumps into the water تعني يقفز داخل الماء.' },
    { q: 'في الحوار: (Are you hungry? - Yes, I want a sandwich). ماذا يريد الجائع؟', img: '🥪', correct: 'شطيرة ساندويتش', opts: ['شطيرة ساندويتش', 'كوب عصير', 'حبة تفاح', 'قطعة كعك'], exp: 'A sandwich تعني شطيرة لذيذة.' },
    { q: 'في القصة: (The monkey climbs the tall tree and eats a yellow banana). ماذا يأكل القرد؟', img: '🐒', correct: 'موزة صفراء حلوة', opts: ['موزة صفراء حلوة', 'برتقالة حامضة', 'حبة جوز هند', 'عنقود عنب'], exp: 'Yellow banana تعني موزة صفراء.' },
    { q: 'إذا سألك المعلم: How do you go to school? وأجبت: By school bus. كيف تذهب؟', img: '🚌', correct: 'بحافلة المدرسة الصفراء', opts: ['بحافلة المدرسة الصفراء', 'مشياً على الأقدام', 'بالدراجة الهوائية', 'بسيارة والدي'], exp: 'By school bus تعني بواسطة باص المدرسة.' },
    { q: 'في القصة: (Layla opens the window to see the birds). لماذا فتحت ليلى النافذة؟', img: '🪟', correct: 'لتشاهد الطيور الجميلة', opts: ['لتشاهد الطيور الجميلة', 'لترمي القمامة', 'لتنادي أخاها', 'لتغلق الستارة'], exp: 'To see the birds تعني لترى وتتأمل الطيور.' },
    { q: 'عندما يخبرك صديقك: I won the race! بماذا تهنئه؟', img: '🏆', correct: 'Congratulations! You are the champion!', opts: ['Congratulations! You are the champion!', 'I am so sorry.', 'Try again later.', 'Excuse me.'], exp: 'للفائز نقول Congratulations.' },
    { q: 'في القصة: (The bear loves sweet honey from the beehive). ماذا يحب الدب؟', img: '🐻', correct: 'العسل الحلو اللذيذ', opts: ['العسل الحلو اللذيذ', 'السمك المشوي', 'أوراق الأشجار', 'التوت البري'], exp: 'Sweet honey تعني العسل الحلو الطبيعي.' },
    { q: 'في الحوار: (What are you doing? - I am reading a storybook). ماذا يفعل؟', img: '📖', correct: 'يقرأ كتاب قصة شائقة', opts: ['يقرأ كتاب قصة شائقة', 'يرسم لوحة زيتية', 'يكتب واجبه المدرسي', 'يشاهد التلفاز'], exp: 'Reading a storybook تعني يقرأ قصة ممتعة.' },
    { q: 'في القصة: (The lion is the king of the jungle). ماذا يلقب الأسد؟', img: '🦁', correct: 'ملك الغابة القوي', opts: ['ملك الغابة القوي', 'صديق الحيوانات', 'أسرع عداء', 'أصغر مخلوق'], exp: 'King of the jungle تعني ملك الغابة.' },
    { q: 'إذا أردت معرفة سعر لعبة في المتجر، ماذا تسأل البائع؟', img: '🧸', correct: 'How much is this toy, please?', opts: ['How much is this toy, please?', 'Where is the toy?', 'Who made this toy?', 'What color is the toy?'], exp: 'How much is... للسؤال عن الثمن والسعر.' },
    { q: 'في القصة: (The butterfly has colorful wings). بماذا تتميز أجنحة الفراشة؟', img: '🦋', correct: 'ملونة وزاهية الألوان', opts: ['ملونة وزاهية الألوان', 'بيضاء فقط', 'سوداء مظلمة', 'صغيرة جداً'], exp: 'Colorful wings تعني أجنحة مفعمة بالألوان.' },
    { q: 'في الحوار: (Is this your pen? - No, it is not mine. It is Omar’s). لمن القلم؟', img: '🖊️', correct: 'لعمر', opts: ['لعمر', 'لي شخصياً', 'للمعلم', 'لا أحد يعلم'], exp: 'It is Omar’s تعني القلم يعود لعمر.' },
    { q: 'في القصة: (The stars twinkle brightly in the dark night). متى تتلألأ النجوم؟', img: '✨', correct: 'في الليل المظلم', opts: ['في الليل المظلم', 'في وضح النهار', 'عند الظهيرة', 'وقت العصر'], exp: 'In the dark night تعني في ظلمة الليل.' },
    { q: 'إذا كنت تشعر بالنعاس والتعب بعد يوم طويل، ماذا تقول؟', img: '🥱', correct: 'I am tired. I want to sleep.', opts: ['I am tired. I want to sleep.', 'I want to play football.', 'Let’s go outside!', 'I am very hungry.'], exp: 'I am tired تعني أنا متعب وأريد النوم.' },
    { q: 'في القصة: (The elephant has large ears and a long trunk). بماذا يتصف الفيل؟', img: '🐘', correct: 'آذان كبيرة وخرطوم طويل', opts: ['آذان كبيرة وخرطوم طويل', 'ذيل طويل وأنياب قصيرة', 'رقبة طويلة كالنخلة', 'جناحان كبيران'], exp: 'Large ears and long trunk تصف الفيل بدقة.' },
    { q: 'في الحوار: (Where do you live? - I live in Riyadh). أين يسكن؟', img: '🏙️', correct: 'في مدينة الرياض', opts: ['في مدينة الرياض', 'في مدينة جدة', 'في مدينة دبي', 'في القاهرة'], exp: 'I live in Riyadh تعني أعيش في الرياض.' },
    { q: 'في القصة: (The yellow duck swims in the small pond). أين تسبح البطة الصفراء؟', img: '🦆', correct: 'في البركة المائية الصغيرة', opts: ['في البركة المائية الصغيرة', 'في البحر الكبير', 'في حوض الحمام', 'في النهر الجاري'], exp: 'In the small pond تعني في البركة الصغيرة.' },
    { q: 'إذا سكب صديقك العصير بالخطأ وقال: I am sorry. بماذا تطمئنه؟', img: '🥤', correct: 'Never mind! It’s okay.', opts: ['Never mind! It’s okay.', 'You are very bad!', 'Cry now!', 'Pay for it!'], exp: 'Never mind تعني لا عليك، الأمر بسيط.' },
    { q: 'في القصة: (The ant works hard in the summer to prepare for winter). متى يجتهد النمل؟', img: '🐜', correct: 'في فصل الصيف', opts: ['في فصل الصيف', 'في الشتاء فقط', 'في الربيع', 'في الخريف'], exp: 'In the summer تعني في موسم الصيف.' },
    { q: 'في الحوار: (Can I have an apple, mom? - Here you are, sweetie). ماذا أعطته أمه؟', img: '🍎', correct: 'تفاحة طازجة', opts: ['تفاحة طازجة', 'موزة ناضجة', 'حلوى مصاصة', 'كوب حليب'], exp: 'Here you are تعني تفضل ما طلبت.' },
    { q: 'في القصة: (The tortoise is slow, but it never gives up). ما هي صفة السلحفاة؟', img: '🐢', correct: 'بطيئة لكنها لا تستسلم أبداً', opts: ['بطيئة لكنها لا تستسلم أبداً', 'سريعة جداً كالأرنب', 'كسولة تحب النوم', 'خائفة ومترددة'], exp: 'Never gives up تعني لا تستسلم وتواصل السعي.' },
    { q: 'إذا أراد الطبيب فحص حلقك في العيادة، ماذا يطلب منك بالإنجليزية؟', img: '👨‍⚕️', correct: 'Open your mouth and say: Aaah!', opts: ['Open your mouth and say: Aaah!', 'Close your eyes now.', 'Jump on one foot.', 'Run outside.'], exp: 'Open your mouth تعني افتح فمك للفحص.' },
    { q: 'في القصة: (The children are building a sandcastle on the beach). ماذا يبني الأطفال؟', img: '🏖️', correct: 'قلعة رملية على الشاطئ', opts: ['قلعة رملية على الشاطئ', 'كوخاً خشبياً بالحديقة', 'برجاً من المكعبات', 'مركبة فضائية'], exp: 'Sandcastle تعني قلعة من الرمال.' },
    { q: 'في الحوار: (Nice to meet you! - Nice to meet you too!). متى يقال هذا التعبير؟', img: '🤝', correct: 'عند التعرف على شخص لأول مرة', opts: ['عند التعرف على شخص لأول مرة', 'عند توديع الأهل للمطار', 'عند الخلود للنوم', 'عند طلب الطعام'], exp: 'Nice to meet you تعني سررت بلقائك.' },
    { q: 'في القصة: (The sheep gives us warm wool for winter sweaters). ماذا تعطينا الخراف؟', img: '🐑', correct: 'الصوف الدافئ لكنزات الشتاء', opts: ['الصوف الدافئ لكنزات الشتاء', 'القطن الناعم', 'الحرير الطبيعي', 'الريش الخفيف'], exp: 'Warm wool يعني الصوف الدافئ.' },
    { q: 'ما هي النصيحة الذهبية التي يقولها المعلم دائماً: (Practice makes perfect!)؟', img: '🌟', correct: 'التدريب والممارسة تصنع الإتقان والتميز', opts: ['التدريب والممارسة تصنع الإتقان والتميز', 'النوم المبكر مفيد', 'لا تلعب مع أحد', 'السرعة أهم من الدقة'], exp: 'Practice makes perfect تعني بالممارسة والتدريب يتحقق الإتقان.' }
  ];
  games['قصص ومحادثات قصيرة بالإنجليزية'] = shortStoriesList.map((d, i) => ({
    id: 39001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  // 40. اختبار الكفاءة الشامل في الإنجليزية
  const masterProficiencyList = [
    { q: 'أي من الكلمات التالية تعتبر مرادفاً دقيقاً لكلمة Smart (ذكي)؟', img: '🧠', correct: 'Clever', opts: ['Clever', 'Lazy', 'Slow', 'Foolish'], exp: 'Clever و Smart كلاهما يعني ذكي وفطن.' },
    { q: 'أي من الكلمات التالية تعتبر مرادفاً لكلمة Quick (سريع)؟', img: '⚡', correct: 'Fast', opts: ['Fast', 'Heavy', 'Calm', 'Late'], exp: 'Fast و Quick كلاهما يعني سريع الخُطى.' },
    { q: 'ما هو الضد العكسي لكلمة Strong (قوي البنية)؟', img: '💪', correct: 'Weak', opts: ['Weak', 'Brave', 'Tall', 'Fierce'], exp: 'عكس Strong (قوي) هو Weak (ضعيف).' },
    { q: 'ما هو الضد العكسي لكلمة Clean (نظيف)؟', img: '🧼', correct: 'Dirty', opts: ['Dirty', 'Neat', 'Tidy', 'Shiny'], exp: 'عكس Clean (نظيف) هو Dirty (متسخ).' },
    { q: 'اختر الكلمة الصحيحة لإكمال الجملة: (She ___ playing tennis now).', img: '🎾', correct: 'is', opts: ['is', 'are', 'am', 'be'], exp: 'مع المفرد المؤنث She في المضارع المستمر نستخدم is.' },
    { q: 'اختر الكلمة الصحيحة لإكمال الجملة: (They ___ reading English books).', img: '📚', correct: 'are', opts: ['are', 'is', 'am', 'was'], exp: 'مع ضمير الجمع They نستخدم are.' },
    { q: 'اختر الكلمة الصحيحة لإكمال الجملة: (I ___ very happy today).', img: '😊', correct: 'am', opts: ['am', 'is', 'are', 'be'], exp: 'مع ضمير المتكلم I نستخدم am.' },
    { q: 'ما هو الماضي للفعل Go (يذهب)؟', img: '🚶', correct: 'Went', opts: ['Went', 'Goed', 'Gone', 'Going'], exp: 'الماضي البسيط الشاذ لفعل Go هو Went.' },
    { q: 'ما هو الماضي للفعل See (يرى)؟', img: '👁️', correct: 'Saw', opts: ['Saw', 'Seed', 'Seen', 'Seeing'], exp: 'الماضي البسيط لفعل See هو Saw.' },
    { q: 'ما هو الماضي للفعل Eat (يأكل)؟', img: '🍽️', correct: 'Ate', opts: ['Ate', 'Eated', 'Eaten', 'Eating'], exp: 'الماضي البسيط لفعل Eat هو Ate.' },
    { q: 'ما الجمع الشاذ لكلمة Child (طفل)؟', img: '🧒', correct: 'Children', opts: ['Children', 'Childs', 'Childes', 'Childies'], exp: 'جمع Child الشاذ هو Children (أطفال).' },
    { q: 'ما الجمع الشاذ لكلمة Foot (قدم)؟', img: '🦶', correct: 'Feet', opts: ['Feet', 'Foots', 'Footes', 'Feets'], exp: 'جمع Foot الشاذ هو Feet (أقدام).' },
    { q: 'ما الجمع الشاذ لكلمة Tooth (سن)؟', img: '🦷', correct: 'Teeth', opts: ['Teeth', 'Tooths', 'Toothes', 'Toothies'], exp: 'جمع Tooth الشاذ هو Teeth (أسنان).' },
    { q: 'ما الجمع الشاذ لكلمة Mouse (فأر)؟', img: '🐭', correct: 'Mice', opts: ['Mice', 'Mouses', 'Mices', 'Mousey'], exp: 'جمع Mouse الشاذ هو Mice (فئران).' },
    { q: 'أي حرف جر يناسب الأيام مثل (___ Monday)?', img: '📅', correct: 'On', opts: ['On', 'In', 'At', 'By'], exp: 'مع أيام الأسبوع نستخدم حرف الجر On.' },
    { q: 'أي حرف جر يناسب الساعات الدقيقة مثل (___ 5 o’clock)?', img: '⏰', correct: 'At', opts: ['At', 'In', 'On', 'For'], exp: 'مع الساعات المحددة نستخدم حرف الجر At.' },
    { q: 'أي حرف جر يناسب الشهور والسنوات مثل (___ May)?', img: '🌸', correct: 'In', opts: ['In', 'At', 'On', 'With'], exp: 'مع الشهور وفصول السنة نستخدم In.' },
    { q: 'ما هو الحيوان الذي يوصف بـ (The tallest animal on Earth)؟', img: '🦒', correct: 'Giraffe', opts: ['Giraffe', 'Elephant', 'Camel', 'Horse'], exp: 'Giraffe (الزرافة) هي أطول كائن حي يابس.' },
    { q: 'ما هو الحيوان الذي يوصف بـ (The largest animal in the world)؟', img: '🐋', correct: 'Blue Whale', opts: ['Blue Whale', 'Shark', 'Hippo', 'Elephant'], exp: 'Blue Whale (الحوت الأزرق) هو أضخم كائن في العالم.' },
    { q: 'ما هو الطائر الذي لا يطير ويعيش في القطب المتجمد؟', img: '🐧', correct: 'Penguin', opts: ['Penguin', 'Eagle', 'Parrot', 'Owl'], exp: 'Penguin (البطريق) طائر بحري غطاس قطبي لا يطير.' },
    { q: 'ما الكلمة التي تعني (عطوف ورحيم بالآخرين)؟', img: '❤️', correct: 'Kind', opts: ['Kind', 'Rude', 'Angry', 'Noisy'], exp: 'Kind تعني طيب القلب وعطوف.' },
    { q: 'ما الكلمة التي تعني (شجاع لا يهاب المخاطر)؟', img: '🦁', correct: 'Brave', opts: ['Brave', 'Afraid', 'Timid', 'Quiet'], exp: 'Brave تعني شجاع وباسل كالأبطال.' },
    { q: 'ما معنى التعبير الإنجليزي للأطفال (Piece of cake) مجازياً؟', img: '🍰', correct: 'أمر سهل جداً وبسيط', opts: ['أمر سهل جداً وبسيط', 'قطعة كيك للأكل', 'حفلة عيد ميلاد', 'شيء صعب ومعقد'], exp: 'Piece of cake هو تعبير اصطلاحي يعني سهل جداً للغاية.' },
    { q: 'ما معنى التعبير المجازي اللطيف (Raining cats and dogs)؟', img: '🌧️', correct: 'المطر يهطل بغزارة شديدة', opts: ['المطر يهطل بغزارة شديدة', 'سقوط حيوانات من السماء', 'الجو حار وجاف', 'هبوب رياح خفيفة'], exp: 'Raining cats and dogs يعني أمطار غزيرة طوفانية.' },
    { q: 'اختر أداة التعريف المناسبة قبل كلمة Apple: (___ apple)?', img: '🍎', correct: 'An', opts: ['An', 'A', 'Them', 'Those'], exp: 'الكلمات التي تبدأ بحرف صوتي علّة (a, e, i, o, u) تأخذ An.' },
    { q: 'اختر أداة النكرة المناسبة قبل كلمة Book: (___ book)?', img: '📖', correct: 'A', opts: ['A', 'An', 'Some', 'Many'], exp: 'الكلمات التي تبدأ بحرف ساكن تأخذ أداة النكرة A.' },
    { q: 'أي من الكلمات التالية تمثل ضمير الملكية للمتكلم (لي أو ملكي)؟', img: '🏷️', correct: 'My', opts: ['My', 'You', 'He', 'She'], exp: 'My تعني ملكي الخاص مثل My book.' },
    { q: 'أي من الكلمات التالية تمثل ضمير الملكية للمخاطب (لك أو ملكك)؟', img: '🤝', correct: 'Your', opts: ['Your', 'My', 'Our', 'Their'], exp: 'Your تعني ملكك مثل Your name.' },
    { q: 'أي من الكلمات التالية تعني (مكتبة لبيع واستعارة الكتب)؟', img: '📚', correct: 'Library', opts: ['Library', 'Bakery', 'Pharmacy', 'Station'], exp: 'Library هي مكتبة الكتب والمطالعة.' },
    { q: 'أي من الكلمات التالية تعني (صيدلية لشراء الدواء)؟', img: '💊', correct: 'Pharmacy', opts: ['Pharmacy', 'Bakery', 'Grocery', 'Butcher'], exp: 'Pharmacy تعني الصيدلية.' },
    { q: 'أي من الكلمات التالية تعني (مخبز لشراء الخبز والكعك)؟', img: '🥖', correct: 'Bakery', opts: ['Bakery', 'Florist', 'Jeweler', 'Market'], exp: 'Bakery هو المخبز وفرن الكعك.' },
    { q: 'ما هو العضو المسؤول عن ضخ الدم في جسم الإنسان؟', img: '🫀', correct: 'Heart', opts: ['Heart', 'Lungs', 'Stomach', 'Brain'], exp: 'Heart (القلب) يضخ الدم لجميع أنحاء الجسم.' },
    { q: 'ما هو العضو المسؤول عن التفكير والتذكر في رأس الإنسان؟', img: '🧠', correct: 'Brain', opts: ['Brain', 'Heart', 'Kidney', 'Liver'], exp: 'Brain (الدماغ والمخ) هو مركز التفكير.' },
    { q: 'ما هو الفصل الذي تتفتح فيه الأزهار وتورق الأشجار؟', img: '🌸', correct: 'Spring', opts: ['Spring', 'Summer', 'Autumn', 'Winter'], exp: 'Spring هو فصل الربيع الزاهي.' },
    { q: 'ما هو الفصل الذي تتساقط فيه أوراق الأشجار الصفراء؟', img: '🍂', correct: 'Autumn', opts: ['Autumn', 'Spring', 'Summer', 'Winter'], exp: 'Autumn (أو Fall) هو فصل الخريف.' },
    { q: 'ما هي الكلمة التي تعني (مستقيم) في الخطوط الهندسية؟', img: '📏', correct: 'Straight', opts: ['Straight', 'Curved', 'Zigzag', 'Round'], exp: 'Straight تعني مستقيم ومضبوط.' },
    { q: 'ما هي الكلمة التي تعني (منحنٍ ومقوس)؟', img: '〰️', correct: 'Curved', opts: ['Curved', 'Straight', 'Sharp', 'Flat'], exp: 'Curved تعني منحنٍ ومائل بانسيابية.' },
    { q: 'ما معنى كلمة Honest في وصف شخصية الإنسان؟', img: '🪞', correct: 'صادق وأمين لا يكذب', opts: ['صادق وأمين لا يكذب', 'شديد الغضب', 'كثير النوم', 'يحب التفاخر'], exp: 'Honest تعني صادق وأمين.' },
    { q: 'ما معنى كلمة Polite في تعامل الطالب مع أساتذته؟', img: '👔', correct: 'مهذب ومؤدب حسن الخلق', opts: ['مهذب ومؤدب حسن الخلق', 'كسول ومشاغب', 'سريع الركض', 'صامت دائماً'], exp: 'Polite تعني مؤدب وذو ذوق رفيع.' },
    { q: 'اختر الفعل المناسب: (Birds ___ in the sky).', img: '🦅', correct: 'fly', opts: ['fly', 'swim', 'crawl', 'run'], exp: 'الطيور تطير في السماء (Birds fly).' },
    { q: 'اختر الفعل المناسب: (Fish ___ in the water).', img: '🐠', correct: 'swim', opts: ['swim', 'fly', 'walk', 'jump'], exp: 'الأسماك تسبح في الماء (Fish swim).' },
    { q: 'ما الكلمة التي تعني (شروق الشمس الذهبي)؟', img: '🌅', correct: 'Sunrise', opts: ['Sunrise', 'Sunset', 'Moonlight', 'Eclipse'], exp: 'Sunrise تعني شروق الشمس فجراً.' },
    { q: 'ما الكلمة التي تعني (غروب الشمس المسائي)؟', img: '🌇', correct: 'Sunset', opts: ['Sunset', 'Sunrise', 'Noon', 'Midday'], exp: 'Sunset تعني مغيب وغروب الشمس.' },
    { q: 'ما هو المصطلح الإنجليزي لكلمة (موسوعة علمية مفيدة)؟', img: '📚', correct: 'Encyclopedia', opts: ['Encyclopedia', 'Dictionary', 'Newspaper', 'Novel'], exp: 'Encyclopedia تعني موسوعة شاملة للمعلومات.' },
    { q: 'ما هو المصطلح الإنجليزي لكلمة (قاموس ومعجم لغوي للكلمات)؟', img: '📖', correct: 'Dictionary', opts: ['Dictionary', 'Atlas', 'Magazine', 'Diary'], exp: 'Dictionary تعني القاموس والمعجم.' },
    { q: 'ما هو كتاب الخرائط الجغرافية للعالم بالإنجليزية؟', img: '🗺️', correct: 'Atlas', opts: ['Atlas', 'Novel', 'Dictionary', 'Notebook'], exp: 'Atlas هو أطلس الخرائط الجغرافية.' },
    { q: 'أي من الكلمات التالية تصف طقساً دافئاً ومعتدلاً؟', img: '🌤️', correct: 'Warm', opts: ['Warm', 'Freezing', 'Stormy', 'Boiling'], exp: 'Warm تعني طقس دافئ ولطيف.' },
    { q: 'أي من الكلمات التالية تصف طقساً بارداً متجمداً؟', img: '🧊', correct: 'Freezing', opts: ['Freezing', 'Hot', 'Sunny', 'Warm'], exp: 'Freezing تعني قارس البرودة ويتجمد منه الماء.' },
    { q: 'ما هي الكلمة التي تعني (التفوق والنجاح الباهر)؟', img: '🏆', correct: 'Success', opts: ['Success', 'Failure', 'Mistake', 'Delay'], exp: 'Success تعني النجاح والتفوق المثمر.' },
    { q: 'ما هي الكلمة التي تعني (المستقبل المشرق والأمل الواعد)؟', img: '🌟', correct: 'Future', opts: ['Future', 'Past', 'Yesterday', 'History'], exp: 'Future تعني المستقبل المأمول بإذن الله.' }
  ];
  games['اختبار الكفاءة الشامل في الإنجليزية'] = masterProficiencyList.map((d, i) => ({
    id: 40001 + i,
    question: d.q,
    image: d.img,
    options: d.opts,
    correctAnswer: d.correct,
    explanation: d.exp
  }));

  return games;
}
