import { QuizQuestion } from '../newGamesData';

export const WORD_IMAGE_TITLES = [
  'فواكه مشكلة وكلماتها',
  'حيوانات المزرعة والغابة',
  'الخضروات الطازجة المفيدة',
  'ألوان وأشكال هندسية',
  'وسائل النقل والمواصلات السريعة',
  'الملابس والأزياء اليومية',
  'الألعاب والدمى المفضلة',
  'أفراد العائلة والمنزل',
  'أدوات المدرسة والكتابة',
  'أطعمة ومشروبات لذيذة',
  'الطبيعة والزهور والورود',
  'الطقس والمواسم والسماء',
  'الطيور والمخلوقات البحرية',
  'أدوات البيت والمطبخ',
  'المهن والأدوات المجتمعية'
];

const itemsPools: Record<string, { name: string; emoji: string; distractor: string }[]> = {
  'فواكه مشكلة وكلماتها': [
    { name: 'Apple', emoji: '🍎', distractor: 'Banana' },
    { name: 'Banana', emoji: '🍌', distractor: 'Orange' },
    { name: 'Orange', emoji: '🍊', distractor: 'Grape' },
    { name: 'Grapes', emoji: '🍇', distractor: 'Strawberry' },
    { name: 'Strawberry', emoji: '🍓', distractor: 'Watermelon' },
    { name: 'Watermelon', emoji: '🍉', distractor: 'Pineapple' },
    { name: 'Pineapple', emoji: '🍍', distractor: 'Peach' },
    { name: 'Peach', emoji: '🍑', distractor: 'Cherry' },
    { name: 'Cherry', emoji: '🍒', distractor: 'Lemon' },
    { name: 'Lemon', emoji: '🍋', distractor: 'Pear' },
    { name: 'Pear', emoji: '🍐', distractor: 'Kiwi' },
    { name: 'Kiwi', emoji: '🥝', distractor: 'Mango' },
    { name: 'Mango', emoji: '🥭', distractor: 'Coconut' },
    { name: 'Coconut', emoji: '🥥', distractor: 'Melon' },
    { name: 'Melon', emoji: '🍈', distractor: 'Apple' },
    { name: 'Blueberry', emoji: '🫐', distractor: 'Raspberry' },
    { name: 'Raspberry', emoji: '🍓', distractor: 'Blackberry' },
    { name: 'Papaya', emoji: '🍈', distractor: 'Mango' },
    { name: 'Fig', emoji: '🟣', distractor: 'Date' },
    { name: 'Date', emoji: '🟤', distractor: 'Fig' },
    { name: 'Pomegranate', emoji: '🔴', distractor: 'Apple' },
    { name: 'Plum', emoji: '🟣', distractor: 'Peach' },
    { name: 'Lime', emoji: '🟢', distractor: 'Lemon' },
    { name: 'Apricot', emoji: '🟠', distractor: 'Peach' },
    { name: 'Avocado', emoji: '🥑', distractor: 'Pear' },
    { name: 'Guava', emoji: '🟢', distractor: 'Apple' },
    { name: 'Tangerine', emoji: '🍊', distractor: 'Orange' },
    { name: 'Cantaloupe', emoji: '🍈', distractor: 'Watermelon' },
    { name: 'Passionfruit', emoji: '🟣', distractor: 'Kiwi' },
    { name: 'Dragonfruit', emoji: '🩷', distractor: 'Pineapple' },
    { name: 'Blackberry', emoji: '🫐', distractor: 'Blueberry' },
    { name: 'Cranberry', emoji: '🔴', distractor: 'Cherry' },
    { name: 'Persimmon', emoji: '🟠', distractor: 'Peach' },
    { name: 'Starfruit', emoji: '⭐', distractor: 'Lemon' },
    { name: 'Lychee', emoji: '⚪', distractor: 'Cherry' },
    { name: 'Rhubarb', emoji: '🟢', distractor: 'Celery' },
    { name: 'Quince', emoji: '🟡', distractor: 'Pear' },
    { name: 'Mulberry', emoji: '🫐', distractor: 'Blackberry' },
    { name: 'Elderberry', emoji: '🫐', distractor: 'Blueberry' },
    { name: 'Gooseberry', emoji: '🟢', distractor: 'Grape' },
    { name: 'Clementine', emoji: '🍊', distractor: 'Orange' },
    { name: 'Satsuma', emoji: '🍊', distractor: 'Tangerine' },
    { name: 'Plantain', emoji: '🍌', distractor: 'Banana' },
    { name: 'Durian', emoji: '🟢', distractor: 'Jackfruit' },
    { name: 'Jackfruit', emoji: '🟢', distractor: 'Durian' },
    { name: 'Kumquat', emoji: '🍊', distractor: 'Lemon' },
    { name: 'Pomelo', emoji: '🟢', distractor: 'Grapefruit' },
    { name: 'Grapefruit', emoji: '🩷', distractor: 'Pomelo' },
    { name: 'Nectarine', emoji: '🍑', distractor: 'Peach' },
    { name: 'Boysenberry', emoji: '🫐', distractor: 'Blackberry' }
  ],
  'حيوانات المزرعة والغابة': [
    { name: 'Lion', emoji: '🦁', distractor: 'Tiger' },
    { name: 'Tiger', emoji: '🐅', distractor: 'Lion' },
    { name: 'Elephant', emoji: '🐘', distractor: 'Giraffe' },
    { name: 'Giraffe', emoji: '🦒', distractor: 'Elephant' },
    { name: 'Monkey', emoji: '🐵', distractor: 'Gorilla' },
    { name: 'Cat', emoji: '🐱', distractor: 'Dog' },
    { name: 'Dog', emoji: '🐶', distractor: 'Cat' },
    { name: 'Cow', emoji: '🐮', distractor: 'Sheep' },
    { name: 'Sheep', emoji: '🐑', distractor: 'Goat' },
    { name: 'Goat', emoji: '🐐', distractor: 'Cow' },
    { name: 'Horse', emoji: '🐴', distractor: 'Donkey' },
    { name: 'Donkey', emoji: '🫏', distractor: 'Horse' },
    { name: 'Rabbit', emoji: '🐰', distractor: 'Mouse' },
    { name: 'Mouse', emoji: '🐭', distractor: 'Rabbit' },
    { name: 'Fox', emoji: '🦊', distractor: 'Wolf' },
    { name: 'Wolf', emoji: '🐺', distractor: 'Fox' },
    { name: 'Bear', emoji: '🐻', distractor: 'Panda' },
    { name: 'Panda', emoji: '🐼', distractor: 'Bear' },
    { name: 'Koala', emoji: '🐨', distractor: 'Monkey' },
    { name: 'Kangaroo', emoji: '🦘', distractor: 'Rabbit' },
    { name: 'Zebra', emoji: '🦓', distractor: 'Horse' },
    { name: 'Hippopotamus', emoji: '🦛', distractor: 'Rhinoceros' },
    { name: 'Rhinoceros', emoji: '🦏', distractor: 'Hippopotamus' },
    { name: 'Camel', emoji: '🐪', distractor: 'Horse' },
    { name: 'Deer', emoji: '🦌', distractor: 'Goat' },
    { name: 'Pig', emoji: '🐷', distractor: 'Sheep' },
    { name: 'Chicken', emoji: '🐔', distractor: 'Duck' },
    { name: 'Duck', emoji: '🦆', distractor: 'Chicken' },
    { name: 'Rooster', emoji: '🐓', distractor: 'Chicken' },
    { name: 'Turkey', emoji: '🦃', distractor: 'Chicken' },
    { name: 'Penguin', emoji: '🐧', distractor: 'Duck' },
    { name: 'Owl', emoji: '🦉', distractor: 'Eagle' },
    { name: 'Eagle', emoji: '🦅', distractor: 'Owl' },
    { name: 'Parrot', emoji: '🦜', distractor: 'Pigeon' },
    { name: 'Pigeon', emoji: '🐦', distractor: 'Parrot' },
    { name: 'Frog', emoji: '🐸', distractor: 'Turtle' },
    { name: 'Turtle', emoji: '🐢', distractor: 'Frog' },
    { name: 'Snake', emoji: '🐍', distractor: 'Lizard' },
    { name: 'Lizard', emoji: '🦎', distractor: 'Snake' },
    { name: 'Crocodile', emoji: '🐊', distractor: 'Alligator' },
    { name: 'Alligator', emoji: '🐊', distractor: 'Crocodile' },
    { name: 'Cheetah', emoji: '🐆', distractor: 'Tiger' },
    { name: 'Leopard', emoji: '🐆', distractor: 'Cheetah' },
    { name: 'Hedgehog', emoji: '🦔', distractor: 'Porcupine' },
    { name: 'Squirrel', emoji: '🐿️', distractor: 'Mouse' },
    { name: 'Bat', emoji: '🦇', distractor: 'Owl' },
    { name: 'Snail', emoji: '🐌', distractor: 'Worm' },
    { name: 'Bee', emoji: '🐝', distractor: 'Wasp' },
    { name: 'Butterfly', emoji: '🦋', distractor: 'Bee' },
    { name: 'Ladybug', emoji: '🐞', distractor: 'Ant' }
  ],
  'الخضروات الطازجة المفيدة': [
    { name: 'Tomato', emoji: '🍅', distractor: 'Potato' },
    { name: 'Potato', emoji: '🥔', distractor: 'Tomato' },
    { name: 'Carrot', emoji: '🥕', distractor: 'Cucumber' },
    { name: 'Cucumber', emoji: '🥒', distractor: 'Carrot' },
    { name: 'Broccoli', emoji: '🥦', distractor: 'Cabbage' },
    { name: 'Cabbage', emoji: '🥬', distractor: 'Lettuce' },
    { name: 'Lettuce', emoji: '🥗', distractor: 'Spinach' },
    { name: 'Onion', emoji: '🧅', distractor: 'Garlic' },
    { name: 'Garlic', emoji: '🧄', distractor: 'Onion' },
    { name: 'Corn', emoji: '🌽', distractor: 'Peas' },
    { name: 'Peas', emoji: '🫛', distractor: 'Corn' },
    { name: 'Pepper', emoji: '🫑', distractor: 'Tomato' },
    { name: 'Eggplant', emoji: '🍆', distractor: 'Potato' },
    { name: 'Mushroom', emoji: '🍄', distractor: 'Potato' },
    { name: 'Pumpkin', emoji: '🎃', distractor: 'Melon' },
    { name: 'Radish', emoji: '🧅', distractor: 'Beetroot' },
    { name: 'Beetroot', emoji: '🥔', distractor: 'Radish' },
    { name: 'Turnip', emoji: '🥔', distractor: 'Potato' },
    { name: 'Celery', emoji: '🥬', distractor: 'Lettuce' },
    { name: 'Spinach', emoji: '🍃', distractor: 'Cabbage' },
    { name: 'Zucchini', emoji: '🥒', distractor: 'Cucumber' },
    { name: 'Sweet Potato', emoji: '🍠', distractor: 'Potato' },
    { name: 'Artichoke', emoji: '🌿', distractor: 'Broccoli' },
    { name: 'Asparagus', emoji: '🎋', distractor: 'Celery' },
    { name: 'Cauliflower', emoji: '🥦', distractor: 'Broccoli' },
    { name: 'Kale', emoji: '🥬', distractor: 'Lettuce' },
    { name: 'Leek', emoji: '🧅', distractor: 'Garlic' },
    { name: 'Okra', emoji: '🥒', distractor: 'Green Bean' },
    { name: 'Green Bean', emoji: '🫘', distractor: 'Peas' },
    { name: 'Chili', emoji: '🌶️', distractor: 'Pepper' },
    { name: 'Ginger', emoji: '🫚', distractor: 'Garlic' },
    { name: 'Parsley', emoji: '🌿', distractor: 'Coriander' },
    { name: 'Coriander', emoji: '🌿', distractor: 'Parsley' },
    { name: 'Dill', emoji: '🌿', distractor: 'Parsley' },
    { name: 'Mint', emoji: '🍃', distractor: 'Basil' },
    { name: 'Basil', emoji: '🌿', distractor: 'Mint' },
    { name: 'Olive', emoji: '🫒', distractor: 'Grape' },
    { name: 'Soybean', emoji: '🫘', distractor: 'Peas' },
    { name: 'Lentil', emoji: '🫘', distractor: 'Bean' },
    { name: 'Chickpea', emoji: '🫘', distractor: 'Peas' },
    { name: 'Bean', emoji: '🫘', distractor: 'Peas' },
    { name: 'Radicchio', emoji: '🥬', distractor: 'Cabbage' },
    { name: 'Fennel', emoji: '🌿', distractor: 'Celery' },
    { name: 'Bok Choy', emoji: '🥬', distractor: 'Cabbage' },
    { name: 'Bamboo Shoot', emoji: '🎋', distractor: 'Celery' },
    { name: 'Watercress', emoji: '🌿', distractor: 'Spinach' },
    { name: 'Alfalfa', emoji: '🌱', distractor: 'Sprout' },
    { name: 'Sprout', emoji: '🌱', distractor: 'Alfalfa' },
    { name: 'Yam', emoji: '🥔', distractor: 'Sweet Potato' },
    { name: 'Taro', emoji: '🥔', distractor: 'Potato' }
  ],
  'ألوان وأشكال هندسية': [
    { name: 'Circle', emoji: '⚪', distractor: 'Square' },
    { name: 'Square', emoji: '⬛', distractor: 'Circle' },
    { name: 'Triangle', emoji: '🔺', distractor: 'Rectangle' },
    { name: 'Rectangle', emoji: ' retângulo', distractor: 'Square' },
    { name: 'Star', emoji: '⭐', distractor: 'Heart' },
    { name: 'Heart', emoji: '❤️', distractor: 'Star' },
    { name: 'Diamond', emoji: '💎', distractor: 'Triangle' },
    { name: 'Oval', emoji: '🥚', distractor: 'Circle' },
    { name: 'Pentagon', emoji: '⬟', distractor: 'Hexagon' },
    { name: 'Hexagon', emoji: '⬡', distractor: 'Pentagon' },
    { name: 'Red', emoji: '🔴', distractor: 'Blue' },
    { name: 'Blue', emoji: '🔵', distractor: 'Red' },
    { name: 'Yellow', emoji: '🟡', distractor: 'Green' },
    { name: 'Green', emoji: '🟢', distractor: 'Yellow' },
    { name: 'Orange', emoji: '🟠', distractor: 'Purple' },
    { name: 'Purple', emoji: '🟣', distractor: 'Pink' },
    { name: 'Pink', emoji: '🩷', distractor: 'Purple' },
    { name: 'Black', emoji: '🖤', distractor: 'White' },
    { name: 'White', emoji: '🤍', distractor: 'Black' },
    { name: 'Brown', emoji: '🤎', distractor: 'Gray' },
    { name: 'Gray', emoji: '🩶', distractor: 'Brown' },
    { name: 'Crescent', emoji: '🌙', distractor: 'Star' },
    { name: 'Cube', emoji: '🧊', distractor: 'Sphere' },
    { name: 'Sphere', emoji: '⚽', distractor: 'Cube' },
    { name: 'Cone', emoji: '🍦', distractor: 'Cylinder' },
    { name: 'Cylinder', emoji: '🔋', distractor: 'Cone' },
    { name: 'Pyramid', emoji: '⛺', distractor: 'Cube' },
    { name: 'Cross', emoji: '➕', distractor: 'Star' },
    { name: 'Line', emoji: '📏', distractor: 'Curve' },
    { name: 'Spiral', emoji: '🌀', distractor: 'Line' },
    { name: 'Gold', emoji: '🪙', distractor: 'Silver' },
    { name: 'Silver', emoji: '🥈', distractor: 'Gold' },
    { name: 'Bronze', emoji: '🥉', distractor: 'Gold' },
    { name: 'Turquoise', emoji: '💠', distractor: 'Blue' },
    { name: 'Indigo', emoji: '🟣', distractor: 'Violet' },
    { name: 'Violet', emoji: '🟣', distractor: 'Indigo' },
    { name: 'Maroon', emoji: '🟤', distractor: 'Red' },
    { name: 'Navy', emoji: '🔵', distractor: 'Black' },
    { name: 'Teal', emoji: '🟢', distractor: 'Cyan' },
    { name: 'Cyan', emoji: '🔵', distractor: 'Teal' },
    { name: 'Magenta', emoji: '🟣', distractor: 'Pink' },
    { name: 'Beige', emoji: '🟡', distractor: 'Brown' },
    { name: 'Octagon', emoji: '🛑', distractor: 'Pentagon' },
    { name: 'Parallel', emoji: '⏸️', distractor: 'Cross' },
    { name: 'Angle', emoji: '📐', distractor: 'Line' },
    { name: 'Dot', emoji: '🔘', distractor: 'Circle' },
    { name: 'Ring', emoji: '💍', distractor: 'Circle' },
    { name: 'Target', emoji: '🎯', distractor: 'Ring' },
    { name: 'Blob', emoji: '🎨', distractor: 'Square' },
    { name: 'Shade', emoji: '🕶️', distractor: 'Color' }
  ],
  'وسائل النقل والمواصلات السريعة': [
    { name: 'Car', emoji: '🚗', distractor: 'Bus' },
    { name: 'Bus', emoji: '🚌', distractor: 'Car' },
    { name: 'Train', emoji: '🚂', distractor: 'Subway' },
    { name: 'Airplane', emoji: '✈️', distractor: 'Helicopter' },
    { name: 'Helicopter', emoji: '🚁', distractor: 'Airplane' },
    { name: 'Bicycle', emoji: '🚲', distractor: 'Motorcycle' },
    { name: 'Motorcycle', emoji: '🏍️', distractor: 'Bicycle' },
    { name: 'Ship', emoji: '🚢', distractor: 'Boat' },
    { name: 'Boat', emoji: '⛵', distractor: 'Ship' },
    { name: 'Rocket', emoji: '🚀', distractor: 'Airplane' },
    { name: 'Taxi', emoji: '🚕', distractor: 'Car' },
    { name: 'Ambulance', emoji: '🚑', distractor: 'Firetruck' },
    { name: 'Firetruck', emoji: '🚒', distractor: 'Police Car' },
    { name: 'Police Car', emoji: '🚓', distractor: 'Taxi' },
    { name: 'Truck', emoji: '🚚', distractor: 'Van' },
    { name: 'Van', emoji: '🚐', distractor: 'Truck' },
    { name: 'Tractor', emoji: '🚜', distractor: 'Truck' },
    { name: 'Scooter', emoji: '🛴', distractor: 'Bicycle' },
    { name: 'Subway', emoji: '🚇', distractor: 'Train' },
    { name: 'Tram', emoji: '🚊', distractor: 'Train' },
    { name: 'Yacht', emoji: '🛥️', distractor: 'Boat' },
    { name: 'Submarine', emoji: ' submarines', distractor: 'Ship' },
    { name: 'Hot Air Balloon', emoji: '🎈', distractor: 'Airplane' },
    { name: 'Spaceship', emoji: '🛸', distractor: 'Rocket' },
    { name: 'Skateboard', emoji: '🛹', distractor: 'Scooter' },
    { name: 'Rollerblades', emoji: '🛼', distractor: 'Skateboard' },
    { name: 'Sled', emoji: '🛷', distractor: 'Car' },
    { name: 'Canoe', emoji: '🛶', distractor: 'Boat' },
    { name: 'Ferry', emoji: '⛴️', distractor: 'Ship' },
    { name: 'Tuk-Tuk', emoji: '🛺', distractor: 'Car' },
    { name: 'Tow Truck', emoji: ' tow truck', distractor: 'Truck' },
    { name: 'Bulldozer', emoji: '🚜', distractor: 'Tractor' },
    { name: 'Crane', emoji: '🏗️', distractor: 'Truck' },
    { name: 'Forklift', emoji: ' forklift', distractor: 'Truck' },
    { name: 'Segway', emoji: '🛴', distractor: 'Scooter' },
    { name: 'Jet Ski', emoji: '🚤', distractor: 'Boat' },
    { name: 'Parachute', emoji: '🪂', distractor: 'Balloon' },
    { name: 'Cable Car', emoji: '🚠', distractor: 'Train' },
    { name: 'Gondola', emoji: '🛶', distractor: 'Boat' },
    { name: 'Limousine', emoji: '🚗', distractor: 'Taxi' },
    { name: 'Pickup', emoji: '🛻', distractor: 'Truck' },
    { name: 'RV', emoji: '🚐', distractor: 'Bus' },
    { name: 'Mail Truck', emoji: '🚚', distractor: 'Van' },
    { name: 'Streetcar', emoji: '🚊', distractor: 'Tram' },
    { name: 'Hovercraft', emoji: '🛸', distractor: 'Boat' },
    { name: 'Seaplane', emoji: '✈️', distractor: 'Boat' },
    { name: 'Tricycle', emoji: '🚲', distractor: 'Bicycle' },
    { name: 'Wheelchair', emoji: '🦽', distractor: 'Car' },
    { name: 'Sailing Boat', emoji: '⛵', distractor: 'Ship' },
    { name: 'Speedboat', emoji: '🚤', distractor: 'Ship' }
  ],
  'الملابس والأزياء اليومية': [
    { name: 'Shirt', emoji: '👕', distractor: 'Pants' },
    { name: 'Pants', emoji: '👖', distractor: 'Shirt' },
    { name: 'Dress', emoji: '👗', distractor: 'Skirt' },
    { name: 'Skirt', emoji: '👚', distractor: 'Dress' },
    { name: 'Shoes', emoji: '👟', distractor: 'Socks' },
    { name: 'Socks', emoji: '🧦', distractor: 'Shoes' },
    { name: 'Hat', emoji: '👒', distractor: 'Cap' },
    { name: 'Cap', emoji: '🧢', distractor: 'Hat' },
    { name: 'Coat', emoji: '🧥', distractor: 'Jacket' },
    { name: 'Jacket', emoji: '🧥', distractor: 'Coat' },
    { name: 'Sweater', emoji: '🧶', distractor: 'Shirt' },
    { name: 'Scarf', emoji: '🧣', distractor: 'Gloves' },
    { name: 'Gloves', emoji: '🧤', distractor: 'Scarf' },
    { name: 'Boots', emoji: '🥾', distractor: 'Shoes' },
    { name: 'Sandals', emoji: '🩴', distractor: 'Shoes' },
    { name: 'Tie', emoji: '👔', distractor: 'Belt' },
    { name: 'Belt', emoji: '👖', distractor: 'Tie' },
    { name: 'Glasses', emoji: '👓', distractor: 'Sunglasses' },
    { name: 'Sunglasses', emoji: '🕶️', distractor: 'Glasses' },
    { name: 'Backpack', emoji: '🎒', distractor: 'Bag' },
    { name: 'Bag', emoji: '👜', distractor: 'Backpack' },
    { name: 'Pyjamas', emoji: '👚', distractor: 'Shirt' },
    { name: 'Suit', emoji: '🤵', distractor: 'Shirt' },
    { name: 'Uniform', emoji: '👕', distractor: 'Suit' },
    { name: 'Ring', emoji: '💍', distractor: 'Watch' },
    { name: 'Watch', emoji: '⌚', distractor: 'Ring' },
    { name: 'Necklace', emoji: '📿', distractor: 'Tie' },
    { name: 'Crown', emoji: '👑', distractor: 'Hat' },
    { name: 'Mask', emoji: '😷', distractor: 'Glasses' },
    { name: 'Umbrella', emoji: '☂️', distractor: 'Coat' },
    { name: 'Wallet', emoji: '👛', distractor: 'Bag' },
    { name: 'Purse', emoji: '👜', distractor: 'Wallet' },
    { name: 'Earmuffs', emoji: '🎧', distractor: 'Hat' },
    { name: 'Swimsuit', emoji: '🩱', distractor: 'Pants' },
    { name: 'Shorts', emoji: '🩳', distractor: 'Pants' },
    { name: 'Overalls', emoji: '👖', distractor: 'Pants' },
    { name: 'Vest', emoji: '🦺', distractor: 'Shirt' },
    { name: 'Robe', emoji: '👘', distractor: 'Dress' },
    { name: 'Apron', emoji: '🧵', distractor: 'Shirt' },
    { name: 'Sneakers', emoji: '👟', distractor: 'Boots' },
    { name: 'High Heels', emoji: '👠', distractor: 'Shoes' },
    { name: 'Slippers', emoji: '🩴', distractor: 'Shoes' },
    { name: 'Helmet', emoji: '⛑️', distractor: 'Cap' },
    { name: 'Mittens', emoji: '🧤', distractor: 'Gloves' },
    { name: 'T-Shirt', emoji: '👕', distractor: 'Shirt' },
    { name: 'Hoodie', emoji: '🧥', distractor: 'Sweater' },
    { name: 'Jeans', emoji: '👖', distractor: 'Pants' },
    { name: 'Blouse', emoji: '👚', distractor: 'Shirt' },
    { name: 'Cardigan', emoji: '🧥', distractor: 'Sweater' },
    { name: 'Raincoat', emoji: '🧥', distractor: 'Coat' }
  ],
  'الألعاب والدمى المفضلة': [
    { name: 'Ball', emoji: '⚽', distractor: 'Balloon' },
    { name: 'Balloon', emoji: '🎈', distractor: 'Ball' },
    { name: 'Teddy Bear', emoji: '🧸', distractor: 'Doll' },
    { name: 'Doll', emoji: '🪆', distractor: 'Teddy Bear' },
    { name: 'Robot', emoji: '🤖', distractor: 'Toy Car' },
    { name: 'Toy Car', emoji: '🏎️', distractor: 'Robot' },
    { name: 'Puzzle', emoji: '🧩', distractor: 'Blocks' },
    { name: 'Blocks', emoji: '🧱', distractor: 'Puzzle' },
    { name: 'Kite', emoji: '🪁', distractor: 'Frisbee' },
    { name: 'Frisbee', emoji: '🥏', distractor: 'Kite' },
    { name: 'Yo-Yo', emoji: '🪀', distractor: 'Top' },
    { name: 'Top', emoji: '🌀', distractor: 'Yo-Yo' },
    { name: 'Drum', emoji: '🥁', distractor: 'Guitar' },
    { name: 'Guitar', emoji: '🎸', distractor: 'Piano' },
    { name: 'Piano', emoji: '🎹', distractor: 'Drum' },
    { name: 'Xylophone', emoji: '🎼', distractor: 'Piano' },
    { name: 'Whistle', emoji: '🎵', distractor: 'Horn' },
    { name: 'Rattle', emoji: '🪇', distractor: 'Whistle' },
    { name: 'Hula Hoop', emoji: '⭕', distractor: 'Ring' },
    { name: 'Skipping Rope', emoji: '🪢', distractor: 'Ribbon' },
    { name: 'Marble', emoji: '🔮', distractor: 'Ball' },
    { name: 'Crayons', emoji: '🖍️', distractor: 'Pencils' },
    { name: 'Pencils', emoji: '✏️', distractor: 'Crayons' },
    { name: 'Paintbrush', emoji: '🖌️', distractor: 'Marker' },
    { name: 'Notebook', emoji: '📓', distractor: 'Book' },
    { name: 'Book', emoji: '📖', distractor: 'Notebook' },
    { name: 'Bicycle', emoji: '🚲', distractor: 'Scooter' },
    { name: 'Scooter', emoji: '🛴', distractor: 'Skateboard' },
    { name: 'Skateboard', emoji: '🛹', distractor: 'Bicycle' },
    { name: 'Swings', emoji: '🛝', distractor: 'Slide' },
    { name: 'Slide', emoji: '🛝', distractor: 'Swings' },
    { name: 'Sandbox', emoji: '🏖️', distractor: 'Pool' },
    { name: 'Pool', emoji: '🏊', distractor: 'Sandbox' },
    { name: 'Trampoline', emoji: '🤸', distractor: 'Mat' },
    { name: 'Tent', emoji: '⛺', distractor: 'House' },
    { name: 'Magic Wand', emoji: '🪄', distractor: 'Stick' },
    { name: 'Costume', emoji: '🦸', distractor: 'Mask' },
    { name: 'Cape', emoji: '🦸‍♂️', distractor: 'Coat' },
    { name: 'Mask', emoji: '🎭', distractor: 'Costume' },
    { name: 'Bubbles', emoji: '🫧', distractor: 'Balloon' },
    { name: 'Water Gun', emoji: '🔫', distractor: 'Gun' },
    { name: 'Binoculars', emoji: '🔭', distractor: 'Glasses' },
    { name: 'Magnifying Glass', emoji: '🔍', distractor: 'Glasses' },
    { name: 'Camera', emoji: '📷', distractor: 'Phone' },
    { name: 'Phone', emoji: '📱', distractor: 'Camera' },
    { name: 'Computer', emoji: '💻', distractor: 'Tablet' },
    { name: 'Tablet', emoji: '📱', distractor: 'Computer' },
    { name: 'Video Game', emoji: '🎮', distractor: 'Joystick' },
    { name: 'Joystick', emoji: '🕹️', distractor: 'Video Game' },
    { name: 'Board Game', emoji: '🎲', distractor: 'Cards' }
  ],
  'أفراد العائلة والمنزل': [
    { name: 'Father', emoji: '👨', distractor: 'Mother' },
    { name: 'Mother', emoji: '👩', distractor: 'Father' },
    { name: 'Brother', emoji: '👦', distractor: 'Sister' },
    { name: 'Sister', emoji: '👧', distractor: 'Brother' },
    { name: 'Baby', emoji: '👶', distractor: 'Child' },
    { name: 'Grandfather', emoji: '👴', distractor: 'Grandmother' },
    { name: 'Grandmother', emoji: '👵', distractor: 'Grandfather' },
    { name: 'Uncle', emoji: '👨‍🦰', distractor: 'Aunt' },
    { name: 'Aunt', emoji: '👩‍🦰', distractor: 'Uncle' },
    { name: 'Family', emoji: '👨‍👩‍👧‍👦', distractor: 'Friends' },
    { name: 'House', emoji: '🏠', distractor: 'Building' },
    { name: 'Door', emoji: '🚪', distractor: 'Window' },
    { name: 'Window', emoji: '🪟', distractor: 'Door' },
    { name: 'Key', emoji: '🔑', distractor: 'Lock' },
    { name: 'Lock', emoji: '🔒', distractor: 'Key' },
    { name: 'Bed', emoji: '🛏️', distractor: 'Sofa' },
    { name: 'Sofa', emoji: '🛋️', distractor: 'Chair' },
    { name: 'Chair', emoji: '🪑', distractor: 'Table' },
    { name: 'Table', emoji: '🪵', distractor: 'Desk' },
    { name: 'Lamp', emoji: '🛋️', distractor: 'Light' },
    { name: 'Clock', emoji: '⏰', distractor: 'Watch' },
    { name: 'Mirror', emoji: '🪞', distractor: 'Glass' },
    { name: 'Broom', emoji: '🧹', distractor: 'Mop' },
    { name: 'Bucket', emoji: '🪣', distractor: 'Bowl' },
    { name: 'Towel', emoji: '🧻', distractor: 'Blanket' },
    { name: 'Soap', emoji: '🧼', distractor: 'Shampoo' },
    { name: 'Toothbrush', emoji: '🪥', distractor: 'Toothpaste' },
    { name: 'Comb', emoji: '💇', distractor: 'Brush' },
    { name: 'Scissors', emoji: '✂️', distractor: 'Knife' },
    { name: 'Hammer', emoji: '🔨', distractor: 'Screwdriver' },
    { name: 'Garden', emoji: '🏡', distractor: 'Park' },
    { name: 'Tree', emoji: '🌳', distractor: 'Flower' },
    { name: 'Flower', emoji: '🌷', distractor: 'Tree' },
    { name: 'Grass', emoji: '🌿', distractor: 'Plant' },
    { name: 'Fence', emoji: '🪵', distractor: 'Gate' },
    { name: 'Gate', emoji: '🚪', distractor: 'Door' },
    { name: 'Roof', emoji: '🏠', distractor: 'Floor' },
    { name: 'Floor', emoji: '🪵', distractor: 'Roof' },
    { name: 'Wall', emoji: '🧱', distractor: 'Door' },
    { name: 'Stairs', emoji: '🪜', distractor: 'Ladder' },
    { name: 'Kitchen', emoji: '🍳', distractor: 'Bathroom' },
    { name: 'Bathroom', emoji: '🛁', distractor: 'Kitchen' },
    { name: 'Bedroom', emoji: '🛏️', distractor: 'Living Room' },
    { name: 'Living Room', emoji: '🛋️', distractor: 'Bedroom' },
    { name: 'Garage', emoji: '🚗', distractor: 'House' },
    { name: 'Balcony', emoji: '🌇', distractor: 'Window' },
    { name: 'Chimney', emoji: '🏠', distractor: 'Roof' },
    { name: 'Mailbox', emoji: '📭', distractor: 'Door' },
    { name: 'Rug', emoji: '🧶', distractor: 'Floor' },
    { name: 'Curtain', emoji: '🪟', distractor: 'Door' }
  ],
  'أدوات المدرسة والكتابة': [
    { name: 'Pen', emoji: '🖊️', distractor: 'Pencil' },
    { name: 'Pencil', emoji: '✏️', distractor: 'Pen' },
    { name: 'Eraser', emoji: '🧼', distractor: 'Ruler' },
    { name: 'Ruler', emoji: '📏', distractor: 'Scissors' },
    { name: 'Book', emoji: '📚', distractor: 'Notebook' },
    { name: 'Notebook', emoji: '📓', distractor: 'Book' },
    { name: 'Bag', emoji: '🎒', distractor: 'Pencil Case' },
    { name: 'Pencil Case', emoji: '👝', distractor: 'Bag' },
    { name: 'Scissors', emoji: '✂️', distractor: 'Glue' },
    { name: 'Glue', emoji: '🧴', distractor: 'Scissors' },
    { name: 'Crayons', emoji: '🖍️', distractor: 'Markers' },
    { name: 'Markers', emoji: '🖊️', distractor: 'Crayons' },
    { name: 'Paint', emoji: '🎨', distractor: 'Brush' },
    { name: 'Brush', emoji: '🖌️', distractor: 'Paint' },
    { name: 'Desk', emoji: '🪑', distractor: 'Chair' },
    { name: 'Chair', emoji: '🪑', distractor: 'Desk' },
    { name: 'Blackboard', emoji: '⬛', distractor: 'Whiteboard' },
    { name: 'Whiteboard', emoji: '⬜', distractor: 'Blackboard' },
    { name: 'Chalk', emoji: '⚪', distractor: 'Marker' },
    { name: 'Globe', emoji: '🌍', distractor: 'Map' },
    { name: 'Map', emoji: '🗺️', distractor: 'Globe' },
    { name: 'Calculator', emoji: '🔢', distractor: 'Computer' },
    { name: 'Computer', emoji: '💻', distractor: 'Tablet' },
    { name: 'Tablet', emoji: '📱', distractor: 'Computer' },
    { name: 'Library', emoji: '🏛️', distractor: 'School' },
    { name: 'School', emoji: '🏫', distractor: 'Library' },
    { name: 'Teacher', emoji: '👩‍🏫', distractor: 'Student' },
    { name: 'Student', emoji: '👨‍🎓', distractor: 'Teacher' },
    { name: 'Classroom', emoji: '🏫', distractor: 'School' },
    { name: 'Bell', emoji: '🔔', distractor: 'Clock' },
    { name: 'Clock', emoji: '⏰', distractor: 'Watch' },
    { name: 'Bus', emoji: '🚌', distractor: 'Car' },
    { name: 'Paper', emoji: '📄', distractor: 'Card' },
    { name: 'Card', emoji: '💳', distractor: 'Paper' },
    { name: 'Folder', emoji: '📁', distractor: 'File' },
    { name: 'File', emoji: '📂', distractor: 'Folder' },
    { name: 'Stapler', emoji: '📎', distractor: 'Clip' },
    { name: 'Clip', emoji: '📎', distractor: 'Stapler' },
    { name: 'Sharpener', emoji: '⚙️', distractor: 'Eraser' },
    { name: 'Compass', emoji: '🧭', distractor: 'Ruler' },
    { name: 'Protractor', emoji: '📐', distractor: 'Compass' },
    { name: 'Dictionary', emoji: '📖', distractor: 'Book' },
    { name: 'Colors', emoji: '🎨', distractor: 'Paint' },
    { name: 'Graduation Cap', emoji: '🎓', distractor: 'Hat' },
    { name: 'Diploma', emoji: '📜', distractor: 'Paper' },
    { name: 'Projector', emoji: '📽️', distractor: 'Screen' },
    { name: 'Screen', emoji: '🖥️', distractor: 'Board' },
    { name: 'Microscope', emoji: '🔬', distractor: 'Telescope' },
    { name: 'Telescope', emoji: '🔭', distractor: 'Microscope' },
    { name: 'Test Tube', emoji: '🧪', distractor: 'Beaker' }
  ],
  'أطعمة ومشروبات لذيذة': [
    { name: 'Milk', emoji: '🥛', distractor: 'Juice' },
    { name: 'Juice', emoji: '🧃', distractor: 'Milk' },
    { name: 'Water', emoji: '💧', distractor: 'Milk' },
    { name: 'Tea', emoji: '🍵', distractor: 'Coffee' },
    { name: 'Coffee', emoji: '☕', distractor: 'Tea' },
    { name: 'Bread', emoji: '🍞', distractor: 'Cake' },
    { name: 'Cake', emoji: '🎂', distractor: 'Bread' },
    { name: 'Cookie', emoji: '🍪', distractor: 'Candy' },
    { name: 'Candy', emoji: '🍬', distractor: 'Chocolate' },
    { name: 'Chocolate', emoji: '🍫', distractor: 'Candy' },
    { name: 'Ice Cream', emoji: '🍦', distractor: 'Cake' },
    { name: 'Pizza', emoji: '🍕', distractor: 'Burger' },
    { name: 'Burger', emoji: '🍔', distractor: 'Pizza' },
    { name: 'Sandwich', emoji: '🥪', distractor: 'Burger' },
    { name: 'Hot Dog', emoji: '🌭', distractor: 'Sandwich' },
    { name: 'French Fries', emoji: '🍟', distractor: 'Chips' },
    { name: 'Chips', emoji: '🥔', distractor: 'French Fries' },
    { name: 'Soup', emoji: '🥣', distractor: 'Salad' },
    { name: 'Salad', emoji: '🥗', distractor: 'Soup' },
    { name: 'Rice', emoji: '🍚', distractor: 'Pasta' },
    { name: 'Pasta', emoji: '🍝', distractor: 'Rice' },
    { name: 'Noodles', emoji: '🍜', distractor: 'Pasta' },
    { name: 'Egg', emoji: '🥚', distractor: 'Cheese' },
    { name: 'Cheese', emoji: '🧀', distractor: 'Butter' },
    { name: 'Butter', emoji: '🧈', distractor: 'Cheese' },
    { name: 'Honey', emoji: '🍯', distractor: 'Jam' },
    { name: 'Jam', emoji: '🍓', distractor: 'Honey' },
    { name: 'Pancake', emoji: '🥞', distractor: 'Waffle' },
    { name: 'Waffle', emoji: '🧇', distractor: 'Pancake' },
    { name: 'Donut', emoji: '🍩', distractor: 'Cookie' },
    { name: 'Popcorn', emoji: '🍿', distractor: 'Chips' },
    { name: 'Pie', emoji: '🥧', distractor: 'Cake' },
    { name: 'Taco', emoji: '🌮', distractor: 'Burrito' },
    { name: 'Burrito', emoji: '🌯', distractor: 'Taco' },
    { name: 'Sushi', emoji: '🍣', distractor: 'Fish' },
    { name: 'Dumpling', emoji: '🥟', distractor: 'Bread' },
    { name: 'Steak', emoji: '🥩', distractor: 'Chicken' },
    { name: 'Chicken', emoji: '🍗', distractor: 'Steak' },
    { name: 'Fish', emoji: '🐟', distractor: 'Shrimp' },
    { name: 'Shrimp', emoji: '🍤', distractor: 'Fish' },
    { name: 'Ketchup', emoji: '🍅', distractor: 'Mustard' },
    { name: 'Mustard', emoji: '🟡', distractor: 'Ketchup' },
    { name: 'Salt', emoji: '🧂', distractor: 'Sugar' },
    { name: 'Sugar', emoji: '🧊', distractor: 'Salt' },
    { name: 'Lemonade', emoji: '🍋', distractor: 'Juice' },
    { name: 'Smoothie', emoji: '🥤', distractor: 'Milkshake' },
    { name: 'Milkshake', emoji: '🥤', distractor: 'Smoothie' },
    { name: 'Cereal', emoji: '🥣', distractor: 'Soup' },
    { name: 'Oatmeal', emoji: '🥣', distractor: 'Cereal' },
    { name: 'Muffin', emoji: '🧁', distractor: 'Cupcake' }
  ],
  'الطبيعة والزهور والورود': [
    { name: 'Sun', emoji: '☀️', distractor: 'Moon' },
    { name: 'Moon', emoji: '🌙', distractor: 'Sun' },
    { name: 'Star', emoji: '⭐', distractor: 'Cloud' },
    { name: 'Cloud', emoji: '☁️', distractor: 'Rain' },
    { name: 'Rain', emoji: '🌧️', distractor: 'Snow' },
    { name: 'Snow', emoji: '❄️', distractor: 'Rain' },
    { name: 'Rainbow', emoji: '🌈', distractor: 'Sun' },
    { name: 'Tree', emoji: '🌳', distractor: 'Flower' },
    { name: 'Flower', emoji: '🌹', distractor: 'Tree' },
    { name: 'Rose', emoji: '🌹', distractor: 'Tulip' },
    { name: 'Tulip', emoji: '🌷', distractor: 'Rose' },
    { name: 'Sunflower', emoji: '🌻', distractor: 'Daisy' },
    { name: 'Daisy', emoji: '🌼', distractor: 'Sunflower' },
    { name: 'Mountain', emoji: '⛰️', distractor: 'Hill' },
    { name: 'Hill', emoji: '🌄', distractor: 'Mountain' },
    { name: 'River', emoji: ' ríos', distractor: 'Ocean' },
    { name: 'Ocean', emoji: '🌊', distractor: 'River' },
    { name: 'Sea', emoji: '🌊', distractor: 'Lake' },
    { name: 'Lake', emoji: '🏞️', distractor: 'Sea' },
    { name: 'Island', emoji: '🏝️', distractor: 'Beach' },
    { name: 'Beach', emoji: '🏖️', distractor: 'Desert' },
    { name: 'Desert', emoji: '🏜️', distractor: 'Forest' },
    { name: 'Forest', emoji: '🌲', distractor: 'Jungle' },
    { name: 'Jungle', emoji: '🌴', distractor: 'Forest' },
    { name: 'Volcano', emoji: '🌋', distractor: 'Mountain' },
    { name: 'Cave', emoji: '🕳️', distractor: 'Mountain' },
    { name: 'Waterfall', emoji: '🌊', distractor: 'River' },
    { name: 'Leaf', emoji: '🍃', distractor: 'Branch' },
    { name: 'Branch', emoji: '🪵', distractor: 'Leaf' },
    { name: 'Root', emoji: '🌱', distractor: 'Seed' },
    { name: 'Seed', emoji: '🌱', distractor: 'Plant' },
    { name: 'Plant', emoji: '🪴', distractor: 'Tree' },
    { name: 'Cactus', emoji: '🌵', distractor: 'Tree' },
    { name: 'Fire', emoji: '🔥', distractor: 'Water' },
    { name: 'Water', emoji: '💧', distractor: 'Fire' },
    { name: 'Earth', emoji: '🌍', distractor: 'Mars' },
    { name: 'Mars', emoji: '🔴', distractor: 'Earth' },
    { name: 'Planet', emoji: '🪐', distractor: 'Star' },
    { name: 'Galaxy', emoji: '🌌', distractor: 'Universe' },
    { name: 'Comet', emoji: '☄️', distractor: 'Meteor' },
    { name: 'Meteor', emoji: '🌠', distractor: 'Comet' },
    { name: 'Lightning', emoji: '⚡', distractor: 'Thunder' },
    { name: 'Thunder', emoji: '🌩️', distractor: 'Lightning' },
    { name: 'Wind', emoji: '💨', distractor: 'Air' },
    { name: 'Tornado', emoji: '🌪️', distractor: 'Storm' },
    { name: 'Storm', emoji: '⛈️', distractor: 'Rain' },
    { name: 'Wave', emoji: '🌊', distractor: 'Ripple' },
    { name: 'Shell', emoji: '🐚', distractor: 'Coral' },
    { name: 'Coral', emoji: '🪸', distractor: 'Shell' },
    { name: 'Rock', emoji: '🪨', distractor: 'Stone' }
  ],
  'الطقس والمواسم والسماء': [
    { name: 'Spring', emoji: '🌸', distractor: 'Summer' },
    { name: 'Summer', emoji: '☀️', distractor: 'Autumn' },
    { name: 'Autumn', emoji: '🍂', distractor: 'Winter' },
    { name: 'Winter', emoji: '⛄', distractor: 'Spring' },
    { name: 'Sunny', emoji: '☀️', distractor: 'Rainy' },
    { name: 'Rainy', emoji: '🌧️', distractor: 'Sunny' },
    { name: 'Cloudy', emoji: '⛅', distractor: 'Windy' },
    { name: 'Windy', emoji: '🌬️', distractor: 'Snowy' },
    { name: 'Snowy', emoji: '🌨️', distractor: 'Rainy' },
    { name: 'Foggy', emoji: '🌫️', distractor: 'Cloudy' },
    { name: 'Stormy', emoji: '⛈️', distractor: 'Sunny' },
    { name: 'Hot', emoji: '🥵', distractor: 'Cold' },
    { name: 'Cold', emoji: '🥶', distractor: 'Hot' },
    { name: 'Warm', emoji: '🌤️', distractor: 'Cool' },
    { name: 'Cool', emoji: '🍃', distractor: 'Warm' },
    { name: 'Day', emoji: '☀️', distractor: 'Night' },
    { name: 'Night', emoji: '🌙', distractor: 'Day' },
    { name: 'Morning', emoji: '🌅', distractor: 'Evening' },
    { name: 'Evening', emoji: '🌇', distractor: 'Morning' },
    { name: 'Sky', emoji: '🌌', distractor: 'Space' },
    { name: 'Space', emoji: '🚀', distractor: 'Sky' },
    { name: 'Thermometer', emoji: '🌡️', distractor: 'Clock' },
    { name: 'Umbrella', emoji: '☂️', distractor: 'Hat' },
    { name: 'Rainbow', emoji: '🌈', distractor: 'Cloud' },
    { name: 'Snowman', emoji: '⛄', distractor: 'Ice' },
    { name: 'Ice', emoji: '🧊', distractor: 'Water' },
    { name: 'Puddle', emoji: '💦', distractor: 'Rain' },
    { name: 'Eclipse', emoji: '🌒', distractor: 'Moon' },
    { name: 'Meteor', emoji: '🌠', distractor: 'Star' },
    { name: 'Sunrise', emoji: '🌅', distractor: 'Sunset' },
    { name: 'Sunset', emoji: '🌇', distractor: 'Sunrise' },
    { name: 'Breeze', emoji: '🍃', distractor: 'Wind' },
    { name: 'Frost', emoji: '❄️', distractor: 'Snow' },
    { name: 'Dew', emoji: '💧', distractor: 'Rain' },
    { name: 'Hail', emoji: '⚪', distractor: 'Snow' },
    { name: 'Climate', emoji: '🌍', distractor: 'Weather' },
    { name: 'Forecast', emoji: '📺', distractor: 'News' },
    { name: 'Atmosphere', emoji: '🌐', distractor: 'Sky' },
    { name: 'Ozone', emoji: '🛡️', distractor: 'Air' },
    { name: 'Gravity', emoji: '🍎', distractor: 'Space' },
    { name: 'Orbit', emoji: '🪐', distractor: 'Circle' },
    { name: 'Satellite', emoji: '🛰️', distractor: 'Rocket' },
    { name: 'Astronaut', emoji: '👨‍🚀', distractor: 'Pilot' },
    { name: 'Telescope', emoji: '🔭', distractor: 'Camera' },
    { name: 'Observatory', emoji: '🏛️', distractor: 'School' },
    { name: 'Radar', emoji: '📡', distractor: 'Antenna' },
    { name: 'Compass', emoji: '🧭', distractor: 'Map' },
    { name: 'Globe', emoji: '🌍', distractor: 'Earth' },
    { name: 'Horizon', emoji: '🌅', distractor: 'Sky' },
    { name: 'Starlight', emoji: '✨', distractor: 'Sunshine' }
  ],
  'الطيور والمخلوقات البحرية': [
    { name: 'Fish', emoji: '🐟', distractor: 'Shark' },
    { name: 'Shark', emoji: '🦈', distractor: 'Whale' },
    { name: 'Whale', emoji: '🐋', distractor: 'Dolphin' },
    { name: 'Dolphin', emoji: '🐬', distractor: 'Seal' },
    { name: 'Seal', emoji: '🦭', distractor: 'Walrus' },
    { name: 'Octopus', emoji: '🐙', distractor: 'Squid' },
    { name: 'Crab', emoji: '🦀', distractor: 'Lobster' },
    { name: 'Lobster', emoji: '🦞', distractor: 'Crab' },
    { name: 'Jellyfish', emoji: '🪼', distractor: 'Starfish' },
    { name: 'Starfish', emoji: '⭐', distractor: 'Jellyfish' },
    { name: 'Seahorse', emoji: '🦐', distractor: 'Fish' },
    { name: 'Turtle', emoji: '🐢', distractor: 'Frog' },
    { name: 'Penguin', emoji: '🐧', distractor: 'Duck' },
    { name: 'Swan', emoji: '🦢', distractor: 'Duck' },
    { name: 'Flamingo', emoji: '🦩', distractor: 'Stork' },
    { name: 'Stork', emoji: '🦅', distractor: 'Flamingo' },
    { name: 'Pelican', emoji: '🐦', distractor: 'Seagull' },
    { name: 'Seagull', emoji: '🕊️', distractor: 'Pelican' },
    { name: 'Owl', emoji: '🦉', distractor: 'Eagle' },
    { name: 'Eagle', emoji: '🦅', distractor: 'Hawk' },
    { name: 'Parrot', emoji: '🦜', distractor: 'Pigeon' },
    { name: 'Peacock', emoji: '🦚', distractor: 'Turkey' },
    { name: 'Ostrich', emoji: '🐦', distractor: 'Emus' },
    { name: 'Woodpecker', emoji: '🐦', distractor: 'Sparrow' },
    { name: 'Sparrow', emoji: '🐦', distractor: 'Robin' },
    { name: 'Pigeon', emoji: '🕊️', distractor: 'Dove' },
    { name: 'Dove', emoji: '🕊️', distractor: 'Pigeon' },
    { name: 'Crow', emoji: '🐦‍⬛', distractor: 'Raven' },
    { name: 'Raven', emoji: '🐦‍⬛', distractor: 'Crow' },
    { name: 'Bat', emoji: '🦇', distractor: 'Owl' },
    { name: 'Clownfish', emoji: '🐠', distractor: 'Goldfish' },
    { name: 'Goldfish', emoji: '🐠', distractor: 'Clownfish' },
    { name: 'Stingray', emoji: '🐟', distractor: 'Manta' },
    { name: 'Eel', emoji: '🐍', distractor: 'Snake' },
    { name: 'Clam', emoji: '🦪', distractor: 'Oyster' },
    { name: 'Oyster', emoji: '🦪', distractor: 'Clam' },
    { name: 'Coral', emoji: '🪸', distractor: 'Plant' },
    { name: 'Anemone', emoji: '🌸', distractor: 'Coral' },
    { name: 'Pelican', emoji: '🐦', distractor: 'Duck' },
    { name: 'Albatross', emoji: '🦅', distractor: 'Seagull' },
    { name: 'Puffin', emoji: '🐧', distractor: 'Penguin' },
    { name: 'Swan', emoji: '🦢', distractor: 'Goose' },
    { name: 'Goose', emoji: '🪿', distractor: 'Duck' },
    { name: 'Quail', emoji: '🐦', distractor: 'Chicken' },
    { name: 'Canary', emoji: '🐤', distractor: 'Parrot' },
    { name: 'Hummingbird', emoji: '🐦', distractor: 'Bee' },
    { name: 'Vulture', emoji: '🦅', distractor: 'Eagle' },
    { name: 'Falcon', emoji: '🦅', distractor: 'Hawk' },
    { name: 'Cormorant', emoji: '🦆', distractor: 'Pelican' },
    { name: 'Otter', emoji: '🦦', distractor: 'Beaver' }
  ],
  'أدوات البيت والمطبخ': [
    { name: 'Pot', emoji: '🍲', distractor: 'Pan' },
    { name: 'Pan', emoji: '🍳', distractor: 'Pot' },
    { name: 'Spoon', emoji: '🥄', distractor: 'Fork' },
    { name: 'Fork', emoji: '🍴', distractor: 'Knife' },
    { name: 'Knife', emoji: '🔪', distractor: 'Spoon' },
    { name: 'Plate', emoji: '🍽️', distractor: 'Bowl' },
    { name: 'Bowl', emoji: '🥣', distractor: 'Cup' },
    { name: 'Cup', emoji: '☕', distractor: 'Glass' },
    { name: 'Glass', emoji: '🥛', distractor: 'Cup' },
    { name: 'Fridge', emoji: '🎛️', distractor: 'Oven' },
    { name: 'Oven', emoji: '🔥', distractor: 'Microwave' },
    { name: 'Microwave', emoji: '📦', distractor: 'Oven' },
    { name: 'Blender', emoji: '🌪️', distractor: 'Mixer' },
    { name: 'Toaster', emoji: '🍞', distractor: 'Oven' },
    { name: 'Kettle', emoji: '🫖', distractor: 'Pot' },
    { name: 'Teapot', emoji: '🫖', distractor: 'Kettle' },
    { name: 'Sink', emoji: '🚰', distractor: 'Tub' },
    { name: 'Faucet', emoji: '🚰', distractor: 'Pipe' },
    { name: 'Trash Can', emoji: '🗑️', distractor: 'Box' },
    { name: 'Washing Machine', emoji: '🌀', distractor: 'Dryer' },
    { name: 'Dryer', emoji: '♨️', distractor: 'Washing Machine' },
    { name: 'Iron', emoji: '🪨', distractor: 'Board' },
    { name: 'Vacuum', emoji: '🧹', distractor: 'Broom' },
    { name: 'Lamp', emoji: '🛋️', distractor: 'Bulb' },
    { name: 'Bulb', emoji: '💡', distractor: 'Lamp' },
    { name: 'Battery', emoji: '🔋', distractor: 'Plug' },
    { name: 'Plug', emoji: '🔌', distractor: 'Socket' },
    { name: 'Socket', emoji: '🔌', distractor: 'Switch' },
    { name: 'Switch', emoji: '🔘', distractor: 'Button' },
    { name: 'Fan', emoji: '🪭', distractor: 'AC' },
    { name: 'AC', emoji: '❄️', distractor: 'Heater' },
    { name: 'Heater', emoji: '🔥', distractor: 'AC' },
    { name: 'Clock', emoji: '⏰', distractor: 'Timer' },
    { name: 'Timer', emoji: '⏱️', distractor: 'Clock' },
    { name: 'Scale', emoji: '⚖️', distractor: 'Ruler' },
    { name: 'Napkin', emoji: '🧻', distractor: 'Towel' },
    { name: 'Towel', emoji: '🧻', distractor: 'Napkin' },
    { name: 'Sponge', emoji: '🧽', distractor: 'Brush' },
    { name: 'Brush', emoji: '🖌️', distractor: 'Sponge' },
    { name: 'Soap', emoji: '🧼', distractor: 'Shampoo' },
    { name: 'Shampoo', emoji: '🧴', distractor: 'Soap' },
    { name: 'Toothpaste', emoji: '🪥', distractor: 'Toothbrush' },
    { name: 'Comb', emoji: '💇', distractor: 'Brush' },
    { name: 'Tissue', emoji: '🧻', distractor: 'Napkin' },
    { name: 'Basket', emoji: '🧺', distractor: 'Box' },
    { name: 'Box', emoji: '📦', distractor: 'Basket' },
    { name: 'Cabinet', emoji: '🗄️', distractor: 'Shelf' },
    { name: 'Shelf', emoji: '🪵', distractor: 'Cabinet' },
    { name: 'Mat', emoji: '🧶', distractor: 'Rug' },
    { name: 'Stool', emoji: '🪑', distractor: 'Chair' }
  ],
  'المهن والأدوات المجتمعية': [
    { name: 'Doctor', emoji: '👨‍⚕️', distractor: 'Nurse' },
    { name: 'Nurse', emoji: '👩‍⚕️', distractor: 'Doctor' },
    { name: 'Teacher', emoji: '👩‍🏫', distractor: 'Student' },
    { name: 'Police', emoji: '👮', distractor: 'Firefighter' },
    { name: 'Firefighter', emoji: '👨‍🚒', distractor: 'Police' },
    { name: 'Chef', emoji: '👨‍🍳', distractor: 'Baker' },
    { name: 'Baker', emoji: '🧑‍🍳', distractor: 'Chef' },
    { name: 'Pilot', emoji: '👨‍✈️', distractor: 'Driver' },
    { name: 'Driver', emoji: '🚌', distractor: 'Pilot' },
    { name: 'Farmer', emoji: '👨‍🌾', distractor: 'Gardener' },
    { name: 'Gardener', emoji: '🧑‍🌾', distractor: 'Farmer' },
    { name: 'Artist', emoji: '👩‍🎨', distractor: 'Musician' },
    { name: 'Musician', emoji: '🎵', distractor: 'Artist' },
    { name: 'Scientist', emoji: '👨‍🔬', distractor: 'Doctor' },
    { name: 'Engineer', emoji: '👷', distractor: 'Architect' },
    { name: 'Architect', emoji: '🏛️', distractor: 'Engineer' },
    { name: 'Builder', emoji: '👷‍♂️', distractor: 'Engineer' },
    { name: 'Mechanic', emoji: '👨‍🔧', distractor: 'Plumber' },
    { name: 'Plumber', emoji: '🚰', distractor: 'Mechanic' },
    { name: 'Electrician', emoji: '⚡', distractor: 'Mechanic' },
    { name: 'Astronaut', emoji: '👨‍🚀', distractor: 'Pilot' },
    { name: 'Astronomy', emoji: '🔭', distractor: 'Science' },
    { name: 'Dentist', emoji: '🦷', distractor: 'Doctor' },
    { name: 'Veterinarian', emoji: '🐶', distractor: 'Doctor' },
    { name: 'Postman', emoji: '📬', distractor: 'Driver' },
    { name: 'Waiter', emoji: '🍽️', distractor: 'Chef' },
    { name: 'Barber', emoji: '💇', distractor: 'Doctor' },
    { name: 'Tailor', emoji: '🧵', distractor: 'Artist' },
    { name: 'Photographer', emoji: '📷', distractor: 'Artist' },
    { name: 'Journalist', emoji: '📰', distractor: 'Writer' },
    { name: 'Writer', emoji: '✍️', distractor: 'Journalist' },
    { name: 'Actor', emoji: '🎭', distractor: 'Singer' },
    { name: 'Singer', emoji: '🎤', distractor: 'Actor' },
    { name: 'Dancer', emoji: '💃', distractor: 'Singer' },
    { name: 'Athlete', emoji: '🏃', distractor: 'Coach' },
    { name: 'Coach', emoji: '⚽', distractor: 'Athlete' },
    { name: 'Lifeguard', emoji: '🏊', distractor: 'Swimmer' },
    { name: 'Soldier', emoji: '🪖', distractor: 'Police' },
    { name: 'Sailor', emoji: '⛵', distractor: 'Captain' },
    { name: 'Captain', emoji: '⚓', distractor: 'Sailor' },
    { name: 'Judge', emoji: '⚖️', distractor: 'Lawyer' },
    { name: 'Lawyer', emoji: '💼', distractor: 'Judge' },
    { name: 'Banker', emoji: '💳', distractor: 'Merchant' },
    { name: 'Merchant', emoji: '🛒', distractor: 'Banker' },
    { name: 'Librarian', emoji: '📚', distractor: 'Teacher' },
    { name: 'Pharmacist', emoji: '💊', distractor: 'Doctor' },
    { name: 'Cleaner', emoji: '🧹', distractor: 'Farmer' },
    { name: 'Security', emoji: '🛡️', distractor: 'Police' },
    { name: 'Delivery', emoji: '📦', distractor: 'Postman' },
    { name: 'Manager', emoji: '💼', distractor: 'Worker' }
  ]
};

export const WORD_IMAGE_BANK: Record<string, QuizQuestion[]> = {};

WORD_IMAGE_TITLES.forEach((title) => {
  const pool = itemsPools[title] || itemsPools['فواكه مشكلة وكلماتها'];
  const questions: QuizQuestion[] = [];
  for (let i = 0; i < 50; i++) {
    const item = pool[i % pool.length];
    // Ensure 2 options: correct and distractor
    const options = [item.name, item.distractor].sort(() => Math.random() - 0.5);
    questions.push({
      id: i + 1,
      question: `ما هذه الصورة؟ (What is this?)`,
      image: item.emoji,
      options: options,
      correctAnswer: item.name,
      explanation: `الصورة تمثل (${item.name}) باللغة الإنجليزية.`
    });
  }
  WORD_IMAGE_BANK[title] = questions;
});
